import type { Lesson } from './types';

export const m0: Lesson = {
  intro: "Before you write any code, you need a few everyday tools and ideas: where programs run, typing commands, saving your work online, how apps talk to each other, and a safe Python setup. This module teaches them from zero and gets everything installed on your computer. The last lesson is optional: it helps you skip anything you already know.",
  glossary: {
    'editor': 'A program for writing code, like a word processor for code. VS Code is the most popular free one.',
    'homebrew': 'A free installer for developer tools on a Mac: brew install git installs Git.',
    'wsl': 'Windows Subsystem for Linux: a real Linux system running inside Windows, so you get the same commands as Mac and servers.',
    'environment variable': 'A named setting handed to a program from outside its code, e.g. DATABASE_URL. Used for config and secrets.',
    'ci/cd': 'Continuous Integration / Continuous Delivery: robots that test your code on every change and ship it if the tests pass.',
    'process': 'A program that is currently running. n8n, a Python script and your browser are each a process while they run.',
    'server': 'A computer whose job is to run programs that wait for requests, usually 24/7 and without a screen.',
    'localhost': 'The address meaning “this same computer”. Nobody else can reach your localhost.',
    'cloud': 'Renting computers in someone else’s data centre (AWS, Google Cloud, Hetzner…) instead of owning them.',
    'terminal': 'A window where you control the computer by typing commands instead of clicking.',
    'path': 'The address of a file or folder, e.g. /Users/ana/projects/lead-bot/main.py.',
    'git': 'A tool that saves snapshots of a project folder over time, so you can see and undo changes.',
    'github': 'A website that stores Git projects online, for backup, sharing and collaboration.',
    'repository': 'A project folder tracked by Git, including its full history. Short name: repo.',
    'commit': 'One saved snapshot of your project in Git, with a message saying what changed.',
    'push': 'Uploading your new commits from your computer to GitHub.',
    'monorepo': 'One repository holding several related projects or parts, each in its own folder.',
    'api': 'Application Programming Interface: the set of requests one program agrees to accept from other programs.',
    'http': 'The language of the web. Each call is a request (method, URL, headers, body) and a response with a status code.',
    'curl': 'A terminal tool that sends an HTTP request and prints the response.',
    'package': 'Code someone else wrote that you install and reuse, e.g. httpx for calling APIs. Also called a library.',
    'virtual environment': 'A private, per-project copy of Python with its own installed packages, usually in a folder called .venv.',
    'pip': 'Python’s package installer: pip install httpx.',
    'lock file': 'A file recording the exact version of every package installed, including the ones your packages need.',
    'pytest': 'The most popular Python testing tool. It finds and runs your test functions.',
    'secret': 'Anything that grants access: API keys, tokens, passwords. It must never be in your code or Git.',
    '.env': 'A text file of NAME=value lines holding local settings and secrets. Never committed to Git.',
    'database': 'A program that stores data in an organised, permanent way and lets you search it. Postgres is a popular one.',
    'docker': 'A tool that packages a program with everything it needs, so it runs the same on any computer.',
  },
  sections: [
    {
      title: 'Where software runs: your computer, servers and the cloud',
      minutes: 5,
      body: [
        "**The problem.** You build an n8n workflow on your laptop with a Webhook trigger. It works. Then you close the lid, and the webhook stops answering. Why? A program only runs while the computer running it is on and awake.",
        "A program is a set of instructions saved as files. When you start it, the computer loads it and runs it; a running program is called a [[process]]. n8n, a Python script and your browser are all programs.",
        "A [[server]] is just a computer whose job is to run programs that wait for requests, all day, every day. It usually has no screen; you control it remotely. There’s nothing magic about it. Your laptop can act as a server too, until it sleeps.",
        "**The analogy.** Your laptop is your home kitchen: fine for testing recipes, closed when you go to bed. A server is a restaurant kitchen: open all hours, ready for orders.",
        "Two terms you’ll see constantly:",
        "- [[Localhost]] means “this same computer”. `http://localhost:5678` is n8n running on *your* machine. Nobody else on the internet can reach that address.\n- The [[cloud]] means renting computers in someone else’s data centre instead of owning them: AWS, Google Cloud, Azure, Hetzner, DigitalOcean. n8n Cloud means the n8n company runs the server for you. Self-hosting means you run it yourself, on a laptop or a rented server.",
        "Same workflow, three places to run it:",
        "- **Your laptop:** only you can reach it (localhost) · stops when it sleeps.\n- **A rented server:** anyone can reach it, if you open it up · runs 24/7.\n- **n8n Cloud:** anyone with the URL · runs 24/7, and n8n looks after the server.",
        "**Why this matters.** Many automation bugs are really about *where* something runs: a webhook pointing at localhost, a script that only works on your laptop because the key is saved there, a job that stops when the machine restarts. When something works in one place and not another, ask: “which computer is this running on, and what does it have access to?”",
      ],
      interview: "I separate where code is developed from where it runs: locally for building and testing, then an always-on server or managed service for production. Most “works on my machine” bugs are environment differences: config, secrets, installed versions, or a localhost address that only makes sense on one machine.",
      check: [
        {
          id: 'm0-s0-1', kind: 'choice',
          prompt: 'You paste `http://localhost:5678/webhook/new-lead` into Typeform as the webhook URL. Form submissions never arrive. Why?',
          options: [
            { text: 'On Typeform’s servers, localhost means Typeform’s own machine, not your laptop', why: 'Right. Localhost always means “this machine”, so Typeform is sending the submission to itself.' },
            { text: 'Typeform only calls standard web ports like 80 or 443, and 5678 isn’t one', why: 'The port isn’t the problem: even on port 443, localhost would still point Typeform at its own machine.' },
            { text: 'Your laptop’s firewall is blocking Typeform; allow port 5678 in your settings', why: 'A firewall rule can’t help. Typeform never tries to reach your laptop at all, because localhost points it at itself.' },
            { text: 'The path should end in .json so Typeform knows to send the data as JSON', why: 'Webhook paths don’t need a file extension; the sender decides the data format, not the URL.' },
          ],
          answer: 0,
          explain: 'An outside service needs a public address for your machine or server. Localhost is only reachable from the same computer.',
        },
        {
          id: 'm0-s0-2', kind: 'choice',
          prompt: 'Your self-hosted n8n runs on your laptop. A workflow scheduled for 3am didn’t run last night. What’s the most likely cause?',
          options: [
            { text: 'The laptop was asleep at 3am, so n8n wasn’t running to start the workflow', why: 'Yes. A program can only run while its computer is awake, and a sleeping laptop runs nothing.' },
            { text: 'Schedule triggers only fire in n8n Cloud; self-hosted n8n needs cron instead', why: 'Self-hosted n8n has the same Schedule trigger. It just needs the n8n process to be running at that time.' },
            { text: 'Schedules only run while the n8n editor is open in a browser tab', why: 'The n8n program runs schedules, not the browser tab. Closing the tab is fine as long as n8n itself keeps running.' },
            { text: 'It ran, but n8n only keeps the history of manual runs, not scheduled ones', why: 'n8n records scheduled executions too. A missing execution means it never ran.' },
          ],
          answer: 0,
          explain: 'Anything that must run unattended belongs on an always-on server or a managed service.',
        },
      ],
    },
    {
      title: 'The terminal: a few commands that go a long way',
      minutes: 5,
      body: [
        "**The problem.** Most developer tools have no buttons. Git, Python, Docker and rented servers are controlled by typing commands. The [[terminal]] is a window where you type an instruction, press Enter and read the answer.",
        "On your phone, just read the commands; you’ll type them at a computer in Build.",
        "On a Mac, open the **Terminal** app. On Windows, you’ll use the Ubuntu terminal that the next lesson installs, so you get the same commands as Mac and Linux servers. In examples, `$` is the prompt; you don’t type it, and lines starting with `#` are comments for you to read.",
        "The terminal always has a **current folder**, and commands act on it unless you say otherwise. A [[path]] is the address of a file or folder, like `/Users/ana/projects/lead-bot`. `~` is short for your home folder.",
        "- `pwd`: show which folder you’re in.\n- `ls`: list what’s in it. `ls -a` also shows hidden files, whose names start with a dot, like `.env`.\n- `cd projects`: move into a folder. `cd ..` goes up one level; `cd ~` goes home.\n- `mkdir lead-bot`: make a new folder.\n- `cat notes.txt`: print a file’s contents.\n- `python3 main.py`: run a program.",
        "Three habits that save hours: **Tab** auto-completes names, the **up arrow** brings back your last command, and **Ctrl+C** stops a program that’s running or stuck.",
        "**Reading the reply matters more than typing.** “command not found” means the tool isn’t installed, or the terminal can’t find it. “No such file or directory” almost always means you’re in the wrong folder: run `pwd` and check.",
      ],
      example: {
        caption: 'A short session, with comments',
        code: '# where am I?\n$ pwd\n/Users/ana\n# make the folder (and its parent)\n$ mkdir -p projects/lead-bot\n# move into it\n$ cd projects/lead-bot\n# list everything, including hidden files\n$ ls -a\n.  ..\n# try to run a script that isn’t there yet\n$ python3 main.py\npython3: can\'t open file \'/Users/ana/projects/lead-bot/main.py\':\n[Errno 2] No such file or directory',
      },
      interview: "I’m comfortable in a Unix shell: navigating the filesystem, running scripts, reading errors and stopping processes. Most setup problems I hit are working-directory or PATH issues, so I check `pwd` and `which python3` before changing anything.",
      check: [
        {
          id: 'm0-s1-1', kind: 'choice',
          prompt: 'You run `python3 main.py` and get “No such file or directory”, but you can see `main.py` in Finder. What do you do first?',
          options: [
            { text: 'Run `pwd` to check the current folder, then `cd` to where main.py is', why: 'Yes. The terminal looks for the file in its current folder, which probably isn’t the one Finder is showing.' },
            { text: 'Reinstall Python, since the error means python3 can’t find its own files', why: 'Python started fine: the error names main.py, the file you asked it to open, not Python’s own files.' },
            { text: 'Run `python3 /main.py` so the terminal searches the whole disk for it', why: 'A leading `/` means the top-level folder of the disk, not “search everywhere”. The file isn’t there either.' },
            { text: 'Open a fresh terminal window so it picks up the file Finder just showed', why: 'The terminal sees the same files as Finder. A new window starts in your home folder, which is still the wrong folder.' },
          ],
          answer: 0,
          explain: '“No such file or directory” is almost always a wrong-folder problem.',
        },
        {
          id: 'm0-s1-2', kind: 'choice',
          prompt: 'A script is stuck, printing the same line over and over. How do you stop it?',
          options: [
            { text: 'Press Ctrl+C in the terminal window where the script is running', why: 'Right. Ctrl+C stops the program running in that terminal.' },
            { text: 'Close the VS Code tab that has the script’s file open in it', why: 'Closing the file in the editor doesn’t touch the running program; it keeps printing.' },
            { text: 'Type `exit` and press Enter while the lines are scrolling past', why: 'The terminal is busy with the script, so your typing goes to the script, not to the shell. It won’t stop it.' },
            { text: 'Press Ctrl+Z, the undo shortcut, to cancel the last command', why: 'In a terminal Ctrl+Z pauses the program in the background. It’s still alive, not stopped or undone.' },
          ],
          answer: 0,
          explain: 'Ctrl+C is the universal “stop this” in a terminal.',
        },
        {
          id: 'm0-s1-3', kind: 'choice',
          prompt: 'You run `ls` in your project and don’t see the `.env` file you created. Is it gone?',
          options: [
            { text: 'Probably not: names starting with a dot are hidden; try `ls -a`', why: 'Yes. Plain `ls` skips hidden files; `ls -a` shows them.' },
            { text: 'It’s there, but `ls` only lists files with a normal extension like .txt', why: '`ls` lists files whatever their extension. The only ones it skips by default are names starting with a dot.' },
            { text: 'Yes: VS Code deletes empty files when you close them, so add a line first', why: 'Editors don’t delete empty files. The file is there; it’s just hidden from plain `ls`.' },
            { text: 'It exists, but only Finder can see it, so check there instead', why: 'Finder and the terminal show the same files, and Finder hides dot-files by default too.' },
          ],
          answer: 0,
          explain: 'Dot-files like .env and .gitignore are hidden by default. `ls -a` shows them.',
        },
      ],
    },
    {
      title: 'Install your toolkit (one-time, about 30 minutes)',
      minutes: 7,
      body: [
        "**The problem.** You can’t practise without the tools on your computer, and you need somewhere to write code. This is a one-time setup at a computer. On your phone, just read it through.",
        "A code [[editor]] is a word processor for code: it colours the text, spots typos and has a terminal built in. Use **VS Code**, free from code.visualstudio.com.",
        "**On a Mac:**",
        "1. Install VS Code and drag it into Applications.\n2. Install [[Homebrew]], an installer for developer tools: copy the install command from brew.sh into Terminal and press Enter. When it asks for your Mac password, nothing appears as you type; that’s normal. At the end, run the “Next steps” commands it prints.\n3. Run `brew install git python gh` to get Git, Python and the GitHub tool.\n4. Install **Docker Desktop** from docker.com and open it once.",
        "**On Windows:**",
        "1. Open PowerShell as administrator, run `wsl --install`, then restart. This sets up [[WSL]] with Ubuntu, a Linux system inside Windows. Open **Ubuntu** from the Start menu: that’s your terminal from now on.\n2. Install VS Code and its **WSL** extension. In Ubuntu, `code .` opens the current folder in VS Code.\n3. In Ubuntu, run `sudo apt update`, then `sudo apt install -y git python3 python3-venv python3-pip gh`.\n4. Install **Docker Desktop** for Windows. It connects to WSL by default.",
        "**Your first file.** In VS Code, choose **File → Open Folder** and pick your project folder; its files appear in the sidebar. **File → New File**, type `print(\"hello\")` and save it as `main.py`. **Terminal → New Terminal** opens a terminal already in that folder: run `python3 main.py`.",
        "Finally, run the check below. Each line should print a version number. “command not found” means that install didn’t finish: open a new terminal window and try again.",
      ],
      example: {
        caption: 'Check your toolkit',
        code: '# each one should print a version number\n$ git --version\n$ python3 --version\n$ docker --version',
      },
      interview: "My setup is VS Code, Git, Python in per-project virtual environments, and Docker for anything with services like databases. On Windows I work inside WSL so my commands match the Linux servers I deploy to.",
      check: [
        {
          id: 'm0-s2-1', kind: 'choice',
          prompt: 'On a Mac, Homebrew’s installer finished, but typing `brew` says “command not found”. What do you do?',
          options: [
            { text: 'Run the “Next steps” commands Homebrew printed, then open a new terminal', why: 'Yes. Those commands tell the terminal where Homebrew lives, and a new window picks them up.' },
            { text: 'Run the installer again with `sudo`, because the first run lacked admin rights', why: 'The install worked; it already asked for your password. The terminal just doesn’t know where brew is yet.' },
            { text: 'Use `pip install brew` instead, since Python’s installer can add it too', why: 'pip installs Python packages, not Homebrew. The real install already worked.' },
            { text: 'Restart the Mac, since new commands only show up after a reboot', why: 'A reboot doesn’t tell the terminal where Homebrew is. The “Next steps” commands do that.' },
          ],
          answer: 0,
          explain: '“command not found” right after an install usually means the terminal doesn’t know where the new tool is yet. Finish the setup steps and open a new window.',
        },
        {
          id: 'm0-s2-2', kind: 'choice',
          prompt: 'You saved `main.py` in VS Code, but `python3 main.py` in the terminal says “No such file or directory”. Most likely cause?',
          options: [
            { text: 'The terminal’s current folder isn’t the project folder; `cd` there first', why: 'Right. The terminal looks for main.py in its current folder. VS Code’s Terminal → New Terminal starts in the right one.' },
            { text: 'Python isn’t installed yet, so it can’t open any .py file you give it', why: 'Then you’d get “command not found” for python3. This error came from Python itself, looking for the file.' },
            { text: 'VS Code hasn’t finished saving; files take a minute to appear on disk', why: 'Saving is instant. The file is on disk, just not in the folder the terminal is looking in.' },
            { text: 'The file must be made executable with `chmod +x` before Python can read it', why: '`python3 main.py` only reads the file. Execute permission matters only for running it directly as `./main.py`.' },
          ],
          answer: 0,
          explain: 'Open the project folder in VS Code and use its built-in terminal: it starts in the right place.',
        },
        {
          id: 'm0-s2-3', kind: 'choice',
          prompt: 'You’re on Windows with WSL installed. Where do you type this course’s commands?',
          options: [
            { text: 'In the Ubuntu terminal, opened from the Start menu', why: 'Yes. That gives you the same commands as Mac and Linux servers.' },
            { text: 'In PowerShell, since it’s the newer Windows terminal', why: 'PowerShell is still Windows: commands like `source` and `apt` don’t work there.' },
            { text: 'In Command Prompt, run as administrator for installs', why: 'Command Prompt uses different commands; `ls`, `source` and `apt` don’t exist there.' },
            { text: 'In Git Bash, which came with Git for Windows', why: 'It looks similar but isn’t the Ubuntu system you installed tools into, so `apt` and those tools aren’t there.' },
          ],
          answer: 0,
          explain: 'On Windows, Ubuntu (WSL) is your terminal for the whole course.',
        },
      ],
    },
    {
      title: 'Saving your work: Git and GitHub',
      minutes: 6,
      body: [
        "**The problem.** You change a working script, it breaks, and you can’t remember what it looked like before. Or a client asks what changed last Tuesday. Files named `final_v2_REAL.py` don’t scale.",
        "[[Git]] records snapshots of a project folder over time, like save points in a video game: you can always go back. [[GitHub]] stores a copy online, so your work is backed up, shareable and visible to employers.",
        "- [[Repository]] (repo): a project folder Git is tracking, with its full history.\n- [[Commit]]: one saved snapshot, with a message describing what changed.\n- [[Push]]: upload your new commits to GitHub. (*Pull* downloads other people’s.)\n- `.gitignore`: a file listing things Git must never save, such as `.env` and `.venv/`.",
        "The everyday loop is `git add` (choose what goes in the snapshot), `git commit` (take it) and `git push` (upload it). `git status` shows what’s changed at any moment; run it often.",
        "**One repo for the whole course.** Keep everything in one repository with a folder per kind of thing: `services/` for Python code, `workflows/` for exported n8n JSON, `infra/` for Docker and deployment files, `tests/`, and `docs/` for decisions and notes. A repo holding several parts like this is a [[monorepo]].",
        "**Your repo is your evidence.** Small commits with clear messages, tests, diagrams, READMEs and notes on failures you caused and fixed show an interviewer how you work. That counts for more than certificates.",
        "**First push.** Create an empty repository on github.com, then run the last three commands below, once. `main` is the name of your project’s main line of history, and `origin` is the nickname for your GitHub copy. GitHub won’t accept your account password from the terminal: run `gh auth login` (the GitHub tool you installed) and follow the prompts.",
      ],
      example: {
        caption: 'Starting a repo and pushing it to GitHub',
        code: '# start tracking this folder\ngit init\n# what’s new or changed?\ngit status\n# stage everything (except what .gitignore lists)\ngit add .\ngit commit -m "Add lead sync script"\n\n# once, after creating an empty repo on github.com:\n# call the main line of history “main”\ngit branch -M main\n# “origin” = the nickname for your GitHub copy\ngit remote add origin https://github.com/you/automation-portfolio.git\n# upload; afterwards, just: git push\ngit push -u origin main',
      },
      interview: "I work in Git with small, descriptive commits, so every change is reviewable and reversible. Secrets and local environments are excluded with .gitignore, and the repo is organised so someone else can clone it, read the README and run it.",
      check: [
        {
          id: 'm0-s3-1', kind: 'choice',
          prompt: 'You ran `git add .` and `git commit -m "Fix dedupe"`, but your change isn’t on GitHub. What’s missing?',
          options: [
            { text: '`git push`, because the commit only exists on your computer so far', why: 'Right. Commit saves the snapshot locally; push uploads it to GitHub.' },
            { text: '`git sync`, which uploads commits and downloads others’ in one step', why: 'Git has no `sync` command (some apps have a Sync button). The command line uses `git push`.' },
            { text: 'A second `git commit`, since the first one only staged the changes', why: '`git add` staged them; `git commit` already took the snapshot. It just hasn’t been uploaded.' },
            { text: 'Nothing: GitHub picks up local commits within a few minutes on its own', why: 'GitHub can’t see your computer. Nothing reaches it until you push.' },
          ],
          answer: 0,
          explain: 'add → commit → push. Commits are local until you push them.',
        },
        {
          id: 'm0-s3-2', kind: 'choice',
          prompt: 'Which of these files should be listed in `.gitignore`?',
          options: [
            { text: '`.env`, the file holding the API keys and passwords your scripts read', why: 'Yes. Secrets must never be committed.' },
            { text: '`requirements.txt`, since anyone can regenerate it with pip', why: 'Others can’t regenerate it without your environment. It’s the list they install from, so commit it.' },
            { text: '`workflows/lead-intake.json`, since n8n already stores your workflows', why: 'Exported workflows are exactly what the repo is for (with secrets removed). n8n’s copy isn’t a backup or history.' },
            { text: '`.gitignore` itself, because it’s only a setting for your computer', why: 'Commit it, so everyone who clones the repo gets the same ignore rules and nobody commits .env by accident.' },
          ],
          answer: 0,
          explain: 'Ignore secrets and anything your computer can regenerate, like .venv/. Commit everything someone needs to understand and run the project.',
        },
      ],
    },
    {
      title: 'APIs and JSON: how programs talk to each other',
      minutes: 6,
      body: [
        "**The problem.** Your form tool, CRM and Slack are separate programs on separate servers. To move a lead from one to another, one program has to ask another to do something. An [[API]] is the set of requests a program agrees to accept from other programs.",
        "**The analogy.** A restaurant menu. You don’t walk into the kitchen; you order from the menu and the kitchen sends back a dish. The API documentation is the menu.",
        "Most web APIs use [[HTTP]], the same language your browser uses. Every call is a **request** and a **response**:",
        "- The request says *what* (a method: `GET` reads, `POST` creates), *where* (a URL), and sometimes carries data.\n- The response comes back with a [[status code]]: **2xx** it worked, **4xx** you sent something wrong, **5xx** their server had a problem.",
        "The data almost always travels as [[JSON]]: named fields in curly braces `{}` and lists in square brackets `[]`. Values are text in quotes, numbers, `true`/`false`, or `null` (empty). You’ve already met it: every n8n item is JSON.",
        "Two ways to hear about changes. **Polling**: you ask every few minutes, “anything new?” A [[webhook]]: the other system calls *your* URL the moment something happens. In n8n, a Schedule trigger polls; a Webhook trigger waits.",
        "You don’t need n8n to make a request. [[curl]] sends one from the terminal and prints the reply; Postman does the same with buttons. The APIs & webhooks module goes much deeper: authentication, errors, retries and pagination.",
      ],
      example: {
        caption: 'A real request with curl (reply trimmed; comments added, real JSON can’t contain them)',
        code: '$ curl https://api.github.com/users/octocat\n{\n  "login": "octocat",        # text\n  "id": 583231,              # number\n  "name": "The Octocat",\n  "site_admin": false,       # true/false\n  ...\n}',
      },
      interview: "An API is a contract: which endpoints exist, what they accept and what they return. Over HTTP I think in method, URL, headers, body and status code, with JSON payloads. For change notifications I prefer webhooks when the provider supports them, and keep polling as a backstop to catch anything missed.",
      check: [
        {
          id: 'm0-s4-1', kind: 'choice',
          prompt: 'In this JSON, what is `tags`?',
          code: '{\n  "lead": {\n    "email": "ana@example.com",\n    "tags": ["vip", "au"]\n  },\n  "score": null\n}',
          options: [
            { text: 'A list of two text values, stored inside the lead object’s braces', why: 'Yes. Square brackets mean a list, and it sits inside the curly braces of "lead".' },
            { text: 'One text value, "vip, au", that’s split into parts only when shown', why: 'Each value has its own quotes, inside square brackets: that’s a list of two items, not one string.' },
            { text: 'An object with two named fields, one called vip and one called au', why: 'Objects use curly braces with name: value pairs. These are square brackets with values only.' },
            { text: 'A list at the top level, sitting alongside lead and score', why: 'It’s inside lead’s curly braces, so it belongs to lead. Only lead and score are at the top level.' },
          ],
          answer: 0,
          explain: '`{}` = object with named fields, `[]` = list, `null` = empty.',
        },
        {
          id: 'm0-s4-2', kind: 'choice',
          prompt: 'Your workflow calls a CRM and gets status **503**. Whose problem is it, most likely?',
          options: [
            { text: 'The CRM’s: 5xx means their server failed, often only briefly', why: 'Right. Waiting and trying again later is usually sensible.' },
            { text: 'Yours: 503 means your API key lacks permission for that endpoint', why: 'Permission problems are 4xx: 401 for a bad or missing key, 403 for a key that isn’t allowed.' },
            { text: 'Yours: your data was badly formatted, so the CRM rejected it', why: 'Rejected data comes back as a 4xx, usually 400 or 422.' },
            { text: 'Your network’s: the request never actually reached the CRM', why: 'If nothing was reached, you’d get a connection error with no status code. A 503 is the CRM’s server answering.' },
          ],
          answer: 0,
          explain: '2xx worked, 4xx your request was wrong, 5xx their server had a problem.',
        },
        {
          id: 'm0-s4-3', kind: 'choice',
          prompt: 'You need to react within seconds when a payment succeeds. The payment provider supports webhooks. Which approach?',
          options: [
            { text: 'Register a webhook so the provider calls your URL as it happens', why: 'Yes. Webhooks deliver changes the moment they happen.' },
            { text: 'Poll the provider every second, which is just as fast and simpler', why: 'It still lags, wastes thousands of requests an hour and will hit the provider’s request limits.' },
            { text: 'Poll every hour; payments rarely change after they succeed anyway', why: 'You’d be up to an hour late, and the requirement is seconds.' },
            { text: 'Have the checkout page email you, and start the workflow from that email', why: 'Email is slow and unreliable, and the customer may close the page first. The provider’s webhook is the reliable signal.' },
          ],
          answer: 0,
          explain: 'Webhook = they tell you. Polling = you keep asking. Use webhooks when speed matters and they’re available.',
        },
      ],
    },
    {
      title: 'Python setup: virtual environments and packages',
      minutes: 6,
      body: [
        "**The problem.** Python code relies on [[package|packages]]: code other people wrote, such as `httpx` for calling APIs. Project A needs one version, project B needs another. Install everything into one shared Python and they clash. On a Mac with Homebrew, and on recent Ubuntu, `pip install` outside a project may refuse outright with `externally-managed-environment`.",
        "A [[virtual environment]] is a private Python for one project, with its own packages. It lives in a folder, usually `.venv`, and is never shared or committed. Think of each project getting its own toolbox instead of everyone grabbing from one messy drawer.",
        "1. `python3 -m venv .venv` creates it (once per project).\n2. `source .venv/bin/activate` switches it on (same on Mac and WSL). `source` runs a file’s commands in your current terminal. Your prompt now starts with `(.venv)`.\n3. `pip install httpx` installs into this project only. [[pip]] is Python’s package installer.\n4. `pip freeze > requirements.txt` records the exact versions. `>` sends a command’s output into a file, replacing what’s there; `>>` adds to the end instead. Anyone can recreate them with `pip install -r requirements.txt`.",
        "Activation lasts for that terminal window only. Open a new one and you must activate again. The classic symptom of forgetting: `ModuleNotFoundError: No module named 'httpx'`, even though you installed it. `which python` prints which Python would run; if the path isn’t inside `.venv`, it isn’t switched on.",
        "**Pinning.** `httpx==0.27.2` means exactly that version, so what worked today installs the same next month, and on the server.",
        "Two more tools you’ll use all course: [[pytest]] runs your tests, and **Ruff** tidies your code’s layout and flags likely mistakes (`ruff format .` and `ruff check .`).",
      ],
      example: {
        caption: 'Setting up a project’s Python, once',
        code: '$ cd ~/projects/automation-portfolio\n# create the private Python\n$ python3 -m venv .venv\n# switch it on\n$ source .venv/bin/activate\n(.venv) $ pip install httpx pytest ruff\n# record exact versions\n(.venv) $ pip freeze > requirements.txt\n# which Python is running?\n(.venv) $ which python\n/Users/ana/projects/automation-portfolio/.venv/bin/python\n# add .venv/ to .gitignore: never commit it\n(.venv) $ echo ".venv/" >> .gitignore',
      },
      interview: "Every project gets its own virtual environment, so dependencies are isolated and reproducible. I pin versions, ideally with a lock file, so CI and production install exactly what I tested. When an import fails, my first check is which interpreter is actually running.",
      check: [
        {
          id: 'm0-s5-1', kind: 'choice',
          prompt: 'Yesterday you installed httpx and your script worked. Today, in a new terminal window, it fails with `ModuleNotFoundError: No module named \'httpx\'`. What’s the fix?',
          options: [
            { text: 'Activate the project’s .venv in this new window, then run it again', why: 'Yes. Without activation you’re using the system Python, which doesn’t have httpx.' },
            { text: 'Run `pip install httpx` again; installs reset when the terminal closes', why: 'Installs don’t reset. httpx is still in .venv; this window just isn’t using it yet.' },
            { text: 'Upgrade Python, since httpx needs a newer version than the system has', why: 'The version isn’t the problem: a Python without httpx is running, because .venv isn’t switched on.' },
            { text: 'Delete .venv and recreate it, because it got corrupted overnight', why: 'Nothing is corrupted. You’d lose your packages and still need to activate it.' },
          ],
          answer: 0,
          explain: 'New terminal = activate again. `which python` shows which Python is running.',
        },
        {
          id: 'm0-s5-2', kind: 'choice',
          prompt: 'How should a teammate get the same packages as you?',
          options: [
            { text: 'Commit requirements.txt; they make their own .venv and install from it', why: 'Right. Share the list of versions, not the installed folder.' },
            { text: 'Commit your .venv folder so they get exactly the files you have', why: 'It’s large and tied to your computer’s paths and system; it often breaks on other machines.' },
            { text: 'Tell them to `pip install` the latest version of each package you use', why: 'Latest today may behave differently from what you tested, so their setup won’t match yours.' },
            { text: 'Commit requirements.txt, and have them install it globally without a .venv', why: 'Global installs clash between projects, and recent Macs and Ubuntu refuse them. Each project needs its own .venv.' },
          ],
          answer: 0,
          explain: 'Commit the recipe (requirements.txt or a lock file), not the kitchen (.venv).',
        },
      ],
    },
    {
      title: 'Environment variables and secrets',
      minutes: 5,
      body: [
        "**The problem.** Your script needs a HubSpot API key. The quick way is to paste it into the code. Then you push to GitHub, and anyone who reads the repo can use your key. Automated bots scan public repositories for exactly this.",
        "The fix: keep [[secret|secrets]] and settings **outside the code**. An [[environment variable]] is a named value the computer hands your program when it starts, like `HUBSPOT_TOKEN=pat-abc123`. The code only knows the *name*; the value lives elsewhere.",
        "On your laptop, that elsewhere is a [[.env]] file in the project folder: one `NAME=value` per line. The `python-dotenv` package loads it for you. On a server or in [[ci/cd|CI]] (automatic testing), the platform supplies the same names from its own secret store. Same code, different values: that’s how dev and production use different databases.",
        "The rules:",
        "- Add `.env` to `.gitignore` before your first commit.\n- Commit a `.env.example` with the same names and fake values, so others know what to set.\n- Never print or log a secret. Log *that* a key loaded, not the key.\n- If a key ever reaches GitHub, **revoke it and create a new one** at the provider. Deleting the file isn’t enough: old commits still contain it.",
        "Don’t worry about reading every line of the Python below; Python is taught in the Python module. The point here is: the real key lives only in `.env`, and the code asks for it by name. If the name is missing, `os.environ[...]` stops with a `KeyError` (Python’s “that name isn’t there” error). That’s good: better to stop at startup than run half-configured.",
      ],
      example: {
        caption: 'Keeping secrets out of the code',
        code: '# .env  (in .gitignore, never committed)\nHUBSPOT_TOKEN=pat-na1-real-secret\nDATABASE_URL=postgresql://postgres:devpass@localhost:5432/postgres\n\n# .env.example  (committed: same names, fake values)\nHUBSPOT_TOKEN=replace-me\nDATABASE_URL=postgresql://user:password@localhost:5432/dbname\n\n# main.py  (needs: pip install python-dotenv)\nimport os\nfrom dotenv import load_dotenv\n\n# read .env into the environment\nload_dotenv()\n# KeyError if missing: fail fast\ntoken = os.environ["HUBSPOT_TOKEN"]\n# never print(token)\nprint("HubSpot token loaded")',
      },
      interview: "Configuration and secrets come from environment variables, so the same code runs in every environment. Locally they live in a gitignored .env with a committed .env.example; in production they come from the platform’s secret store. If a credential leaks, I rotate it immediately, because Git history keeps it.",
      check: [
        {
          id: 'm0-s6-1', kind: 'choice',
          prompt: 'You accidentally pushed `.env` with a Stripe key. You delete the file and push again. Are you safe?',
          options: [
            { text: 'No: revoke the key in Stripe and make a new one; history still has it', why: 'Right. Git keeps history, and the key may already have been copied.' },
            { text: 'Yes, as long as you also add .env to .gitignore before the next push', why: 'That stops future commits, but the earlier commit still holds the key for anyone to read.' },
            { text: 'Yes, if the repo is new and nobody has starred or visited it yet', why: 'Bots scan new public commits within minutes. You can’t know who has already copied it.' },
            { text: 'Mostly: delete that old commit from GitHub too, and then the key is gone', why: 'Copies, forks and bots may already have it. Rewriting history doesn’t un-leak a key; rotating it does.' },
          ],
          answer: 0,
          explain: 'A leaked key is a compromised key. Rotate first, clean up second.',
        },
        {
          id: 'm0-s6-2', kind: 'choice',
          prompt: 'A teammate clones your repo and the script immediately fails with `KeyError: \'HUBSPOT_TOKEN\'`. What’s wrong?',
          options: [
            { text: 'They have no .env yet; copy .env.example to .env and fill in values', why: 'Yes. .env is never committed, so each person creates their own.' },
            { text: 'They haven’t activated .venv, so Python can’t see the .env file', why: 'Activation affects which packages load, not which files can be read. A missing package gives ModuleNotFoundError.' },
            { text: 'python-dotenv isn’t installed, so the token can’t be read from the file', why: 'Then the import would fail with ModuleNotFoundError before the script ever reached the token.' },
            { text: 'Their HubSpot account lacks API access, so HubSpot refused to return the token', why: 'The script failed before calling HubSpot. A refused token would come back from HubSpot as a 401.' },
          ],
          answer: 0,
          explain: 'The KeyError is the code telling you, early and clearly, that a required setting isn’t there.',
        },
      ],
    },
    {
      title: 'Optional: skip what you already know',
      minutes: 4,
      body: [
        "**This lesson is optional.** The course assumes nothing, but you may already know some of it. This module’s exercises in Build double as a **diagnostic**: try each one *before* studying. If you can build it from a blank file and explain why it works, tick it off and move on. If you only recognise the words, leave it open: that’s where your time should go.",
        "Some exercises touch topics taught later. If they’re new, skip them for now:",
        "- HTTP, webhooks, OAuth and [[idempotent|idempotency]]: the APIs & webhooks module.\n- [[Database|Databases]] (Postgres) and transactions: the SQL module.\n- [[Docker]] and Compose: the Docker module.",
        "**Leave evidence.** For each exercise you finish, save something in your repo: a command and its output, a passing test, or a note on a failure you caused on purpose. In interviews, “here’s the repo” beats “I know Docker”.",
        "**Use AI as a teacher, not as proof.** Let it explain and quiz you, but every module ends with a checkpoint done with AI closed.",
        "Don’t worry about reading every line below; Docker and Python are taught in their own modules. The point here is: one command starts a database, and a few lines of Python prove you can reach it.",
      ],
      example: {
        caption: 'Diagnostic exercise: run Postgres locally and connect from Python',
        code: '# Start Postgres in Docker (throwaway password, local practice only)\ndocker run --name pg -e POSTGRES_PASSWORD=devpass -p 5432:5432 -d postgres:16\n# check it’s running\ndocker ps\n\n# check_db.py  (needs: pip install "psycopg[binary]" python-dotenv)\nimport os\nimport psycopg\nfrom dotenv import load_dotenv\n\n# DATABASE_URL comes from .env\nload_dotenv()\nwith psycopg.connect(os.environ["DATABASE_URL"]) as conn:\n    # prints the version: proves it connected\n    print(conn.execute("SELECT version()").fetchone())',
      },
      interview: "When I pick up a system, I start from evidence: I map an existing workflow’s trigger, transformations, external calls and writes, and for each boundary I say what can fail and how I’d detect it. I keep small, runnable proofs in a repo rather than relying on familiarity with tool names.",
      check: [
        {
          id: 'm0-s7-1', kind: 'choice',
          prompt: 'You recognise the phrase “OAuth refresh token” but couldn’t explain what happens when one is revoked. What should you do with that diagnostic item?',
          options: [
            { text: 'Leave it open and study it until you can explain and build it', why: 'Yes. Recognising words isn’t the same as being able to explain or build it.' },
            { text: 'Mark it done, since recognising the term shows you’ve covered it', why: 'Familiarity isn’t mastery. Interviews will find the gap.' },
            { text: 'Mark it done once an AI writes you a clear explanation of it', why: 'That proves the AI knows it, not you.' },
            { text: 'Leave the whole module open, since one gap means restudying all of it', why: 'The rule is per item: keep only this item open and skip the ones you can prove.' },
          ],
          answer: 0,
          explain: 'Skip-first rule: if you can build it from a blank file and explain why it works, mark it complete. Otherwise, it stays open.',
        },
        {
          id: 'm0-s7-2', kind: 'choice',
          prompt: 'Which is the strongest evidence that you can run a Docker Compose stack?',
          options: [
            { text: 'A compose.yaml in your repo plus a note that data survived a restart', why: 'Yes. Something runnable, with proof of behaviour you actually tested.' },
            { text: 'A certificate from a Docker course, showing your final exam score', why: 'It shows you studied, not that you can run and debug a stack.' },
            { text: 'A CV line listing Docker, Compose and the versions you’ve used', why: 'A claim, not evidence.' },
            { text: 'A screenshot of `docker compose up` printing that both containers started', why: 'It shows one start, not that the stack works or keeps its data, and there’s nothing anyone can run.' },
          ],
          answer: 0,
          explain: 'Your repo is your evidence trail: commits, tests, diagrams, READMEs and failure notes.',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'm0-q1', kind: 'order',
      prompt: 'Put the everyday Git steps in order, from editing a file to seeing it on GitHub.',
      items: ['Edit and save the file', '`git add` the change', '`git commit -m "…"`', '`git push`'],
      explain: 'Change → stage → snapshot → upload. `git status` at any point shows where you are.',
    },
    {
      id: 'm0-q2', kind: 'choice',
      prompt: 'Read the terminal session. Why did `cd` fail?',
      code: '$ pwd\n/Users/ana\n$ ls\nDesktop  Documents  projects\n$ cd lead-bot\ncd: no such file or directory: lead-bot',
      options: [
        { text: 'lead-bot isn’t in /Users/ana; try `cd projects/lead-bot`', why: 'Yes. `ls` shows only Desktop, Documents and projects in the current folder.' },
        { text: '`cd` needs a full path, like /Users/ana/lead-bot, to work', why: '`cd` accepts paths relative to the current folder, and that full path doesn’t exist either.' },
        { text: 'Names with a dash must be quoted, as in `cd "lead-bot"`', why: 'Dashes are fine unquoted; only spaces and special characters need quotes.' },
        { text: 'lead-bot is hidden, so `cd` can’t find it without the -a flag', why: 'Only names starting with a dot are hidden, and `cd` can enter hidden folders anyway. `ls` shows no lead-bot here.' },
      ],
      answer: 0,
      explain: '`pwd` and `ls` tell you where you are and what’s there. Check them before assuming something is broken.',
    },
    {
      id: 'm0-q3', kind: 'choice',
      prompt: 'Your workflow must run every 15 minutes, 24/7, for a client. Where should it run?',
      options: [
        { text: 'On an always-on server, such as a rented VPS or n8n Cloud', why: 'Yes. It needs a computer that never sleeps.' },
        { text: 'On your laptop, kept plugged in with sleep turned off', why: 'Laptops still restart for updates, lose Wi-Fi and travel with you. Not reliable for a client.' },
        { text: 'In the GitHub repo, which runs it from the exported JSON', why: 'GitHub stores your code; it doesn’t run n8n workflows.' },
        { text: 'On localhost, which keeps it private and always reachable', why: 'Localhost just means “this computer”. It doesn’t make anything always-on.' },
      ],
      answer: 0,
      explain: 'Develop locally, run production somewhere that’s always on.',
    },
    {
      id: 'm0-q4', kind: 'order',
      prompt: 'Order the steps to set up Python for a new project.',
      items: ['`python3 -m venv .venv`', '`source .venv/bin/activate`', '`pip install httpx`', '`pip freeze > requirements.txt`'],
      explain: 'Create, activate, install, record. And add .venv/ to .gitignore.',
    },
    {
      id: 'm0-q5', kind: 'choice',
      prompt: 'How many contacts are in this API response?',
      code: '{\n  "contacts": [\n    { "email": "ana@example.com", "phone": null },\n    { "email": "bo@example.com", "phone": "+61 400 000 000" }\n  ],\n  "next_cursor": null\n}',
      options: [
        { text: '2: the contacts list holds two objects, one per contact', why: 'Yes. The contacts list holds two `{}` objects, one per contact.' },
        { text: '1: Ana’s phone is null, so her record doesn’t count', why: 'A null field is still part of a contact; it’s just empty.' },
        { text: '4: each field (two emails, two phones) is one entry', why: 'Fields belong to contacts. There are two contacts with two fields each.' },
        { text: '0: next_cursor is null, which means the list is empty', why: 'next_cursor is a separate field about further pages. It doesn’t empty the list.' },
      ],
      answer: 0,
      explain: 'Square brackets hold a list; each `{}` inside is one item, like one n8n item.',
    },
    {
      id: 'm0-q6', kind: 'choice',
      prompt: 'Your script works on your laptop but crashes on the server with `ModuleNotFoundError: No module named \'httpx\'`. What’s the most likely fix?',
      options: [
        { text: 'List httpx in requirements.txt and install it in the server’s .venv', why: 'Yes. The server only has the packages you tell it to install.' },
        { text: 'Copy your laptop’s .venv folder to the server so the packages match', why: 'Virtual environments are tied to the machine that made them; recreate it from requirements.txt instead.' },
        { text: 'Install a newer Python on the server, since httpx needs 3.12 or later', why: 'The error says httpx is missing, not that Python is too old.' },
        { text: 'Add the httpx folder to the server’s PATH variable so Python can find it', why: 'PATH is for finding commands. Packages must be installed into the Python environment that runs the script.' },
      ],
      answer: 0,
      explain: 'Recorded dependencies make any machine reproducible: same list, same versions.',
    },
    {
      id: 'm0-q7', kind: 'choice',
      prompt: 'Which belongs in a committed `.env.example`?',
      options: [
        { text: '`OPENAI_API_KEY=replace-me`, a fake value in place of the key', why: 'Yes. The name tells people what to set; the value is a harmless placeholder.' },
        { text: '`OPENAI_API_KEY=` followed by a real but low-limit test key', why: 'A test key is still a working secret in Git, and anyone can spend from it.' },
        { text: 'A copy of your real .env, since the repo is private', why: 'That’s real secrets in Git. Private repos get shared, forked and made public.' },
        { text: 'Only comments describing settings, with no NAME= lines', why: 'People copy this file to .env, so it needs the exact names to fill in.' },
      ],
      answer: 0,
      explain: 'Names and placeholders in .env.example (committed); real values in .env (ignored).',
    },
    {
      id: 'm0-q8', kind: 'choice',
      prompt: 'You send a request and get **400 Bad Request**. What should you do?',
      options: [
        { text: 'Check the fields and format you sent, fix them, then resend', why: 'Yes. 4xx means the request itself was wrong.' },
        { text: 'Retry with a short delay; their server is briefly overloaded', why: 'Overload comes back as 503 or 429. The same bad request will get the same 400.' },
        { text: 'Log in again, because 400 means your token has expired', why: 'An expired or missing token gives 401, not 400.' },
        { text: 'Wait an hour and retry, since 4xx codes mean their side had a problem', why: 'Their-side problems are 5xx. 4xx means fix what you sent.' },
      ],
      answer: 0,
      explain: '4xx: fix what you sent. 5xx: their problem, often temporary.',
    },
    {
      id: 'm0-q9', kind: 'choice',
      prompt: 'A CRM has no webhooks. Your client wants new deals copied to a sheet within an hour. What do you build?',
      options: [
        { text: 'A Schedule trigger that polls the CRM for new deals every 15 min', why: 'Yes. Without webhooks, polling on a schedule is the way.' },
        { text: 'A Webhook trigger in n8n, with its URL pasted into the CRM settings', why: 'The CRM doesn’t support webhooks, so nothing would ever call it.' },
        { text: 'Poll every few seconds so nothing is ever more than a moment late', why: 'Far more than the hour needs, and likely to hit the CRM’s request limits.' },
        { text: 'A one-off bulk import now, then re-run it by hand once a month', why: 'That misses the within-an-hour requirement and isn’t automated.' },
      ],
      answer: 0,
      explain: 'Webhooks when available; polling on a sensible schedule when not.',
    },
    {
      id: 'm0-q10', kind: 'choice',
      prompt: 'Why does `os.environ["DATABASE_URL"]` crashing at startup count as good behaviour?',
      options: [
        { text: 'It stops at startup with a clear error, not half-configured later', why: 'Yes. A missing setting should stop the program at the door.' },
        { text: 'It shows the database password is wrong before trying to connect', why: 'A KeyError means the name isn’t set at all. No password has been checked yet.' },
        { text: 'It keeps the secret out of the logs, since the value is never printed', why: 'It’s about missing config, not hiding values.' },
        { text: 'It makes Python retry until the variable has been set by the server', why: 'Nothing retries. The program stops once, with an error.' },
      ],
      answer: 0,
      explain: 'Fail fast on required config. Use `os.getenv` only for settings that are genuinely optional.',
    },
    {
      id: 'm0-q11', kind: 'choice',
      prompt: 'You can explain [[idempotent|idempotency]] but have never built anything with it. According to the skip-first rule, can you skip it?',
      options: [
        { text: 'Not yet: the rule asks you to build it from a blank file too', why: 'Right. The rule asks for both: build it and explain it.' },
        { text: 'Yes: being able to explain it shows you understand it well enough', why: 'The rule asks you to build it as well.' },
        { text: 'Yes, once an AI quizzes you and confirms that your answers are right', why: 'AI is a teacher here, not proof.' },
        { text: 'No: items can only be ticked off after you’ve studied the lesson', why: 'Skipping is the point of the diagnostic, once you can build and explain it.' },
      ],
      answer: 0,
      explain: 'Build it and explain it, then skip it. Recognising it isn’t enough.',
    },
    {
      id: 'm0-q12', kind: 'choice',
      prompt: 'You export an n8n workflow to your repo. What must you check before committing it?',
      options: [
        { text: 'That it contains no API keys, tokens or real client data', why: 'Yes. Values typed into nodes end up in the export; check and remove them.' },
        { text: 'Nothing: n8n strips every secret from exported workflows', why: 'Saved credentials are left out, but a key typed directly into a node, like a header, is exported.' },
        { text: 'That it’s converted to YAML so Git can show the changes', why: 'Git shows changes to JSON fine. Keep it as .json so it can be imported again.' },
        { text: 'That it’s deactivated first, or importing it will start it running', why: 'Active status doesn’t matter for the repo; n8n imports workflows inactive. Secrets are what to check.' },
      ],
      answer: 0,
      explain: 'Treat every file you commit as public: no secrets, no real client data.',
    },
    {
      id: 'm0-q13', kind: 'choice',
      prompt: '`docker --version` prints a version, but `docker ps` says “Cannot connect to the Docker daemon”. What’s the likely fix?',
      options: [
        { text: 'Start Docker Desktop and wait until it says the engine is running', why: 'Yes. The docker command is installed, but the background engine it talks to isn’t running.' },
        { text: 'Reinstall Docker, since a version printing but ps failing means a broken install', why: 'The command works fine; it just has no running engine to talk to.' },
        { text: 'Run `sudo docker ps`, since listing containers needs admin rights', why: 'With Docker Desktop, permissions aren’t the issue. The engine isn’t running, with or without sudo.' },
        { text: 'Run `docker compose up` first, because ps only works inside a project', why: '`docker ps` lists containers from anywhere. Compose would fail the same way without the engine.' },
      ],
      answer: 0,
      explain: 'The `docker` command is only the remote control; Docker Desktop runs the engine it talks to.',
    },
  ],
  tasks: [
    { device: 'phone', plain: 'Try explaining these out loud: how an HTTP request and response work, JSON, webhooks vs polling, OAuth refresh tokens, idempotency, database transactions and Docker. It’s fine to say “don’t know yet”; this shows you what to study.', done: 'A voice note or written answer for each. Every “don’t know yet” goes on your list of topics to study, and this stays open until you can explain them all.' },
    { device: 'computer', plain: 'Create one GitHub repository for the whole course, with folders: services, workflows, infra, tests and docs.', done: 'Steps: 1) On github.com, click New repository, name it (e.g. automation-portfolio), tick “Add a README file” and create it. 2) In your terminal, go to your projects folder and run gh repo clone your-username/automation-portfolio (or git clone with the repo’s URL), then cd into it. 3) Run mkdir services workflows infra tests docs. Git doesn’t save empty folders, so add a one-line README.md inside each. 4) Create a .gitignore listing .env and .venv/. 5) git add ., git commit -m "Set up folders", git push. Done when GitHub shows the folders, README and .gitignore.' },
    { device: 'computer', plain: 'Set up Python in the repo: a virtual environment, Ruff for formatting/checking, pytest, and a .env file for settings.', done: 'pytest and ruff check . both run, requirements.txt is committed, and .env.example is committed but .env is not.' },
    { device: 'computer', plain: 'Diagnostic (optional): run Postgres on your computer and connect to it from Python. If you can’t do this yet, skip it; it’s taught in the SQL module.', done: 'Steps: 1) Open Docker Desktop. 2) Run docker run --name pg -e POSTGRES_PASSWORD=devpass -p 5432:5432 -d postgres:16 3) Run docker ps and check “pg” is listed. 4) In .env, add DATABASE_URL=postgresql://postgres:devpass@localhost:5432/postgres 5) Run check_db.py from the “Optional: skip what you already know” lesson. Done when it prints the Postgres version.' },
    { device: 'computer', plain: 'Diagnostic (optional): run a Docker Compose setup with two services (n8n and Postgres) and a named volume. If you can’t do this yet, skip it; it’s taught in the Docker module.', done: 'Steps: 1) Copy the compose.yaml from the Docker module’s Compose lesson into your infra folder. 2) Next to it, create a .env file containing DB_PASSWORD=pick-something 3) In that folder, run docker compose up -d and open localhost:5678. 4) Create a test workflow, then run docker compose down and docker compose up -d again. Done when your test workflow is still there.' },
    { device: 'computer', plain: 'Use curl or Postman to send GET, POST, PATCH and DELETE requests, and trigger 400, 401, 404 and 429 responses on purpose (httpbin.org/status/429 always replies with a 429; change the number for other codes).', done: 'Saved commands with their responses, and one line per error code saying what you’d do about it.' },
    { device: 'computer', plain: 'Export one n8n workflow you already use into the repo’s workflows folder, and document it.', done: 'The JSON (with secrets removed) plus a short note: what triggers it, what it writes, and how it can fail.' },
    { device: 'phone', plain: 'Record a 3-minute explanation of your current automation setup, with no screen and no notes.', done: 'A recording you’ve listened back to, with a list of anything you stumbled on.' },
  ],
};
