import type { Lesson } from './types';

export const m0: Lesson = {
  intro: "This is where the course starts. Everything later assumes a few basics: where software actually runs, how to type commands into a terminal, how to save your work with Git, what an API is, and how to set up Python and keep passwords out of your code. This module teaches those from zero. It also includes a diagnostic: a set of exercises you try first, so you can skip anything you can already prove you know.",
  glossary: {
    'process': 'A program that is currently running. n8n, a Python script and your browser are each a process while they run.',
    'server': 'A computer whose job is to run programs that wait for requests, usually 24/7 and without a screen.',
    'localhost': 'The address meaning “this same computer”. Nobody else can reach your localhost.',
    'cloud': 'Renting computers in someone else’s data centre (AWS, Google Cloud, Hetzner…) instead of owning them.',
    'terminal': 'A window where you control the computer by typing commands instead of clicking.',
    'path': 'The address of a file or folder, e.g. /Users/ana/projects/lead-bot/main.py.',
    'git': 'A tool that saves snapshots of a project folder over time, so you can see and undo changes.',
    'github': 'A website that stores Git projects online, for backup, sharing and collaboration.',
    'repository': 'A project folder tracked by Git, including its full history. Short name: repo.',
    'commit': 'One saved snapshot of your project in Git, with a message saying what changed.',
    'push': 'Uploading your new commits from your computer to GitHub.',
    'monorepo': 'One repository holding several related projects or parts, each in its own folder.',
    'api': 'Application Programming Interface: the set of requests one program agrees to accept from other programs.',
    'http': 'The language of the web. Each call is a request (method, URL, headers, body) and a response with a status code.',
    'curl': 'A terminal tool that sends an HTTP request and prints the response.',
    'package': 'Code someone else wrote that you install and reuse, e.g. httpx for calling APIs. Also called a library.',
    'virtual environment': 'A private, per-project copy of Python with its own installed packages, usually in a folder called .venv.',
    'pip': 'Python’s package installer: pip install httpx.',
    'lock file': 'A file recording the exact version of every package installed, including the ones your packages need.',
    'pytest': 'The most popular Python testing tool. It finds and runs your test functions.',
    'secret': 'Anything that grants access: API keys, tokens, passwords. It must never be in your code or Git.',
    '.env': 'A text file of NAME=value lines holding local settings and secrets. Never committed to Git.',
    'database': 'A program that stores data in an organised, permanent way and lets you search it. Postgres is a popular one.',
    'docker': 'A tool that packages a program with everything it needs, so it runs the same on any computer.',
  },
  sections: [
    {
      title: 'Where software runs: your computer, servers and the cloud',
      minutes: 5,
      body: [
        "**The problem.** You build an n8n workflow on your laptop with a Webhook trigger. It works. Then you close the lid, and the webhook stops answering. Why? A program only runs while the computer running it is on and awake.",
        "A program is a set of instructions saved as files. When you start it, the computer loads it and runs it; a running program is called a [[process]]. n8n, a Python script and your browser are all programs.",
        "A [[server]] is just a computer whose job is to run programs that wait for requests, all day, every day. It usually has no screen; you control it remotely. There’s nothing magic about it. Your laptop can act as a server too, until it sleeps.",
        "**The analogy.** Your laptop is your home kitchen: fine for testing recipes, closed when you go to bed. A server is a restaurant kitchen: open all hours, ready for orders.",
        "Two terms you’ll see constantly:",
        "- [[Localhost]] means “this same computer”. `http://localhost:5678` is n8n running on *your* machine. Nobody else on the internet can reach that address.\n- The [[cloud]] means renting computers in someone else’s data centre instead of owning them: AWS, Google Cloud, Azure, Hetzner, DigitalOcean. n8n Cloud means the n8n company runs the server for you. Self-hosting means you run it yourself, on a laptop or a rented server.",
        "**Why this matters.** Many automation bugs are really about *where* something runs: a webhook pointing at localhost, a script that only works on your laptop because the key is saved there, a job that stops when the machine restarts. When something works in one place and not another, ask: “which computer is this running on, and what does it have access to?”",
      ],
      example: {
        caption: 'Same workflow, three places to run it',
        code: 'Where it runs         Who can reach it            Runs while you sleep?\nYour laptop           Only you (localhost)        No\nRented server (VPS)   Anyone, if you open it up   Yes\nn8n Cloud             Anyone with the URL         Yes (n8n runs the server)',
      },
      interview: "I separate where code is developed from where it runs: locally for building and testing, then an always-on server or managed service for production. Most “works on my machine” bugs are environment differences: config, secrets, installed versions, or a localhost address that only makes sense on one machine.",
      check: [
        {
          id: 'm0-s0-1', kind: 'choice',
          prompt: 'You paste `http://localhost:5678/webhook/new-lead` into Typeform as the webhook URL. Form submissions never arrive. Why?',
          options: [
            { text: 'To Typeform’s servers, localhost means their own computer, not yours', why: 'Right. Localhost always means “this machine”, so Typeform is calling itself.' },
            { text: 'Typeform doesn’t support webhooks', why: 'It does. The address is the problem.' },
            { text: 'Port 5678 is too high a number', why: 'Port numbers aren’t the issue; any outside service would fail with a localhost address.' },
            { text: 'The webhook path needs to end in .json', why: 'Webhook paths don’t need a file extension.' },
          ],
          answer: 0,
          explain: 'An outside service needs a public address for your machine or server. Localhost is only reachable from the same computer.',
        },
        {
          id: 'm0-s0-2', kind: 'choice',
          prompt: 'Your self-hosted n8n runs on your laptop. A workflow scheduled for 3am didn’t run last night. What’s the most likely cause?',
          options: [
            { text: 'The laptop was asleep, so n8n wasn’t running', why: 'Yes. A program can only run while its computer is awake.' },
            { text: 'Schedule triggers only work in n8n Cloud', why: 'Self-hosted n8n has schedule triggers too; it just needs to be running.' },
            { text: '3am is outside n8n’s allowed hours', why: 'n8n has no allowed hours.' },
            { text: 'The workflow ran but n8n hid the result', why: 'A missing execution usually means it never ran, not that it was hidden.' },
          ],
          answer: 0,
          explain: 'Anything that must run unattended belongs on an always-on server or a managed service.',
        },
      ],
    },
    {
      title: 'The terminal: a few commands that go a long way',
      minutes: 6,
      body: [
        "**The problem.** Most developer tools have no buttons. Git, Python, Docker and rented servers are controlled by typing commands. The [[terminal]] is a window where you type an instruction, press Enter and read the answer.",
        "On a Mac, open the **Terminal** app. On Windows, install **WSL** (Windows Subsystem for Linux) so you get the same commands as Mac and Linux servers. This course assumes those commands. In examples, `$` is the prompt; you don’t type it.",
        "The terminal always has a **current folder**, and commands act on it unless you say otherwise. A [[path]] is the address of a file or folder, like `/Users/ana/projects/lead-bot`. `~` is short for your home folder.",
        "- `pwd`: show which folder you’re in.\n- `ls`: list what’s in it. `ls -a` also shows hidden files, whose names start with a dot, like `.env`.\n- `cd projects`: move into a folder. `cd ..` goes up one level; `cd ~` goes home.\n- `mkdir lead-bot`: make a new folder.\n- `cat notes.txt`: print a file’s contents.\n- `python3 main.py`: run a program.",
        "Three habits that save hours: **Tab** auto-completes names, the **up arrow** brings back your last command, and **Ctrl+C** stops a program that’s running or stuck.",
        "**Reading the reply matters more than typing.** “command not found” means the tool isn’t installed, or the terminal can’t find it. “No such file or directory” almost always means you’re in the wrong folder: run `pwd` and check.",
      ],
      example: {
        caption: 'A short session, with comments',
        code: '$ pwd                          # where am I?\n/Users/ana\n$ mkdir -p projects/lead-bot   # make the folder (and its parent)\n$ cd projects/lead-bot         # move into it\n$ ls -a                        # list everything, including hidden files\n.  ..\n$ python3 main.py              # try to run a script that isn’t there yet\npython3: can\'t open file \'/Users/ana/projects/lead-bot/main.py\': [Errno 2] No such file or directory',
      },
      interview: "I’m comfortable in a Unix shell: navigating the filesystem, running scripts, reading errors and stopping processes. Most setup problems I hit are working-directory or PATH issues, so I check `pwd` and `which python3` before changing anything.",
      check: [
        {
          id: 'm0-s1-1', kind: 'choice',
          prompt: 'You run `python3 main.py` and get “No such file or directory”, but you can see `main.py` in Finder. What do you do first?',
          options: [
            { text: 'Run `pwd` to check which folder you’re in, then `cd` to the right one', why: 'Yes. The terminal looks in its current folder, which is probably not where the file is.' },
            { text: 'Reinstall Python', why: 'Python ran fine; it just couldn’t find the file.' },
            { text: 'Rename the file to main.txt', why: 'That would make it harder to run, not easier.' },
            { text: 'Restart the computer', why: 'The current folder would still be wrong afterwards.' },
          ],
          answer: 0,
          explain: '“No such file or directory” is almost always a wrong-folder problem.',
        },
        {
          id: 'm0-s1-2', kind: 'choice',
          prompt: 'A script is stuck, printing the same line over and over. How do you stop it?',
          options: [
            { text: 'Press Ctrl+C in that terminal', why: 'Right. Ctrl+C stops the running program.' },
            { text: 'Type `cd ..`', why: 'The terminal is busy with the script; it won’t take new commands until the script stops.' },
            { text: 'Press the up arrow', why: 'That recalls previous commands; it doesn’t stop anything.' },
            { text: 'Type `ls`', why: 'Listing files doesn’t stop a running program.' },
          ],
          answer: 0,
          explain: 'Ctrl+C is the universal “stop this” in a terminal.',
        },
        {
          id: 'm0-s1-3', kind: 'choice',
          prompt: 'You run `ls` in your project and don’t see the `.env` file you created. Is it gone?',
          options: [
            { text: 'Probably not: files starting with a dot are hidden; use `ls -a`', why: 'Yes. Plain `ls` skips hidden files.' },
            { text: 'Yes, the terminal deleted it', why: 'Listing files never deletes them.' },
            { text: 'Yes, .env files expire after a day', why: 'Files don’t expire.' },
            { text: 'It only exists in Finder, not in the terminal', why: 'Finder and the terminal show the same files; Finder hides dot-files too by default.' },
          ],
          answer: 0,
          explain: 'Dot-files like .env and .gitignore are hidden by default. `ls -a` shows them.',
        },
      ],
    },
    {
      title: 'Saving your work: Git and GitHub',
      minutes: 7,
      body: [
        "**The problem.** You change a working script, it breaks, and you can’t remember what it looked like before. Or a client asks what changed last Tuesday. Files named `final_v2_REAL.py` don’t scale.",
        "[[Git]] records snapshots of a project folder over time, like save points in a video game: you can always go back. [[GitHub]] stores a copy online, so your work is backed up, shareable and visible to employers.",
        "- [[Repository]] (repo): a project folder Git is tracking, with its full history.\n- [[Commit]]: one saved snapshot, with a message describing what changed.\n- [[Push]]: upload your new commits to GitHub. (*Pull* downloads other people’s.)\n- `.gitignore`: a file listing things Git must never save, such as `.env` and `.venv/`.",
        "The everyday loop is `git add` (choose what goes in the snapshot), `git commit` (take it) and `git push` (upload it). `git status` shows what’s changed at any moment; run it often.",
        "**One repo for the whole course.** Keep everything in one repository with a folder per kind of thing: `services/` for Python code, `workflows/` for exported n8n JSON, `infra/` for Docker and deployment files, `tests/`, and `docs/` for decisions and notes. A repo holding several parts like this is a [[monorepo]].",
        "**Your repo is your evidence.** Small commits with clear messages, tests, diagrams, READMEs and notes on failures you caused and fixed show an interviewer how you work. That counts for more than certificates.",
        "First push: GitHub doesn’t accept your account password from the terminal. The simplest fix is GitHub’s own tool: install the GitHub CLI and run `gh auth login`.",
      ],
      example: {
        caption: 'Starting a repo and pushing it to GitHub',
        code: 'git init                     # start tracking this folder\ngit status                   # what’s new or changed?\ngit add .                    # stage everything (except what .gitignore lists)\ngit commit -m "Add lead sync script"\n\n# create an empty repo on github.com, then once:\ngit branch -M main           # name the main branch “main”\ngit remote add origin https://github.com/you/automation-portfolio.git\ngit push -u origin main      # afterwards, just: git push',
      },
      interview: "I work in Git with small, descriptive commits, so every change is reviewable and reversible. Secrets and local environments are excluded with .gitignore, and the repo is organised so someone else can clone it, read the README and run it.",
      check: [
        {
          id: 'm0-s2-1', kind: 'choice',
          prompt: 'You ran `git add .` and `git commit -m "Fix dedupe"`, but your change isn’t on GitHub. What’s missing?',
          options: [
            { text: '`git push`: the commit only exists on your computer so far', why: 'Right. Commit saves locally; push uploads.' },
            { text: 'Another `git add .`', why: 'The files are already in the commit.' },
            { text: '`git init`', why: 'That starts a new repo; yours already exists.' },
            { text: 'Waiting a few minutes for GitHub to sync', why: 'GitHub doesn’t pull from your computer. You have to push.' },
          ],
          answer: 0,
          explain: 'add → commit → push. Commits are local until you push them.',
        },
        {
          id: 'm0-s2-2', kind: 'choice',
          prompt: 'Which of these files should be listed in `.gitignore`?',
          options: [
            { text: '`.env`, which holds your API keys', why: 'Yes. Secrets must never be committed.' },
            { text: '`README.md`', why: 'The README is how people understand your project. Commit it.' },
            { text: '`requirements.txt`', why: 'This tells others which packages to install. Commit it.' },
            { text: '`workflows/lead-intake.json`', why: 'Exported workflows are exactly what the repo is for (with credentials removed).' },
          ],
          answer: 0,
          explain: 'Ignore secrets and anything your computer can regenerate, like .venv/. Commit everything someone needs to understand and run the project.',
        },
      ],
    },
    {
      title: 'APIs and JSON: how programs talk to each other',
      minutes: 6,
      body: [
        "**The problem.** Your form tool, CRM and Slack are separate programs on separate servers. To move a lead from one to another, one program has to ask another to do something. An [[API]] is the set of requests a program agrees to accept from other programs.",
        "**The analogy.** A restaurant menu. You don’t walk into the kitchen; you order from the menu and the kitchen sends back a dish. The API documentation is the menu.",
        "Most web APIs use [[HTTP]], the same language your browser uses. Every call is a **request** and a **response**:",
        "- The request says *what* (a method: `GET` reads, `POST` creates), *where* (a URL), and sometimes carries data.\n- The response comes back with a [[status code]]: **2xx** it worked, **4xx** you sent something wrong, **5xx** their server had a problem.",
        "The data almost always travels as [[JSON]]: named fields in curly braces `{}` and lists in square brackets `[]`. Values are text in quotes, numbers, `true`/`false`, or `null` (empty). You’ve already met it: every n8n item is JSON.",
        "Two ways to hear about changes. **Polling**: you ask every few minutes, “anything new?” A [[webhook]]: the other system calls *your* URL the moment something happens. In n8n, a Schedule trigger polls; a Webhook trigger waits.",
        "You don’t need n8n to make a request. [[curl]] sends one from the terminal and prints the reply; Postman does the same with buttons. Module 2 goes much deeper: authentication, errors, retries and pagination.",
      ],
      example: {
        caption: 'A real request with curl (reply trimmed; comments added, real JSON can’t contain them)',
        code: '$ curl https://api.github.com/users/octocat\n{\n  "login": "octocat",        # text\n  "id": 583231,              # number\n  "name": "The Octocat",\n  "site_admin": false,       # true/false\n  ...\n}',
      },
      interview: "An API is a contract: which endpoints exist, what they accept and what they return. Over HTTP I think in method, URL, headers, body and status code, with JSON payloads. For change notifications I prefer webhooks when the provider supports them, and keep polling as a backstop to catch anything missed.",
      check: [
        {
          id: 'm0-s3-1', kind: 'choice',
          prompt: 'In this JSON, what is `tags`?',
          code: '{\n  "lead": { "email": "ana@example.com", "tags": ["vip", "au"] },\n  "score": null\n}',
          options: [
            { text: 'A list of two text values, inside the lead object', why: 'Yes. Square brackets mean a list; it sits inside the curly braces of "lead".' },
            { text: 'A single text value "vip, au"', why: 'The square brackets and separate quotes make it two items, not one string.' },
            { text: 'Empty, because score is null', why: 'Each field is independent. Only score is empty.' },
            { text: 'Another object with named fields', why: 'Objects use curly braces with names; this uses square brackets.' },
          ],
          answer: 0,
          explain: '`{}` = object with named fields, `[]` = list, `null` = empty.',
        },
        {
          id: 'm0-s3-2', kind: 'choice',
          prompt: 'Your workflow calls a CRM and gets status **503**. Whose problem is it, most likely?',
          options: [
            { text: 'The CRM’s server: 5xx means a problem on their side, often temporary', why: 'Right. Waiting and trying again later is usually sensible.' },
            { text: 'Yours: you sent badly formatted data', why: 'That would be a 4xx code.' },
            { text: 'Nobody’s: 5xx means success', why: 'Success is 2xx.' },
            { text: 'Your laptop’s Wi-Fi', why: 'If your connection failed, you wouldn’t get a status code back at all.' },
          ],
          answer: 0,
          explain: '2xx worked, 4xx your request was wrong, 5xx their server had a problem.',
        },
        {
          id: 'm0-s3-3', kind: 'choice',
          prompt: 'You need to react within seconds when a payment succeeds. The payment provider supports webhooks. Which approach?',
          options: [
            { text: 'Register a webhook so the provider calls your URL immediately', why: 'Yes. Webhooks deliver changes as they happen.' },
            { text: 'Poll the provider every hour', why: 'You’d be up to an hour late.' },
            { text: 'Poll every second', why: 'Wasteful, and likely to hit the provider’s request limits.' },
            { text: 'Ask the customer to email you', why: 'Not an automation.' },
          ],
          answer: 0,
          explain: 'Webhook = they tell you. Polling = you keep asking. Use webhooks when speed matters and they’re available.',
        },
      ],
    },
    {
      title: 'Python setup: virtual environments and packages',
      minutes: 7,
      body: [
        "**The problem.** Python code relies on [[package|packages]]: code other people wrote, such as `httpx` for calling APIs. Project A needs one version, project B needs another. Install everything into one shared Python and they clash. On a Mac with Homebrew Python, `pip install` outside a project may refuse outright with `externally-managed-environment`.",
        "A [[virtual environment]] is a private Python for one project, with its own packages. It lives in a folder, usually `.venv`, and is never shared or committed. Think of each project getting its own toolbox instead of everyone grabbing from one messy drawer.",
        "1. `python3 -m venv .venv` creates it (once per project).\n2. `source .venv/bin/activate` switches it on (Windows: `.venv\\Scripts\\activate`). Your prompt now starts with `(.venv)`.\n3. `pip install httpx` installs into this project only. [[pip]] is Python’s package installer.\n4. `pip freeze > requirements.txt` records the exact versions, so anyone can recreate them with `pip install -r requirements.txt`.",
        "Activation lasts for that terminal window only. Open a new one and you must activate again. The classic symptom of forgetting: `ModuleNotFoundError: No module named 'httpx'`, even though you installed it.",
        "**Pinning.** `httpx==0.27.2` means exactly that version. Pinned versions mean what worked today installs the same next month, and on the server. Tools like uv and Poetry go further with a [[lock file]] that also pins the packages your packages depend on.",
        "Set up two more tools now; you’ll use them all course. [[pytest]] runs your tests. **Ruff** tidies and checks your code: `ruff format .` and `ruff check .`.",
      ],
      example: {
        caption: 'Setting up a project’s Python, once',
        code: '$ cd ~/projects/automation-portfolio\n$ python3 -m venv .venv               # create the private Python\n$ source .venv/bin/activate           # switch it on\n(.venv) $ pip install httpx pytest ruff\n(.venv) $ pip freeze > requirements.txt   # record exact versions\n(.venv) $ which python                # which Python is running?\n/Users/ana/projects/automation-portfolio/.venv/bin/python\n(.venv) $ echo ".venv/" >> .gitignore  # never commit the environment',
      },
      interview: "Every project gets its own virtual environment, so dependencies are isolated and reproducible. I pin versions, ideally with a lock file, so CI and production install exactly what I tested. When an import fails, my first check is which interpreter is actually running.",
      check: [
        {
          id: 'm0-s4-1', kind: 'choice',
          prompt: 'Yesterday you installed httpx and your script worked. Today, in a new terminal window, it fails with `ModuleNotFoundError: No module named \'httpx\'`. What’s the fix?',
          options: [
            { text: 'Activate the project’s virtual environment, then run it again', why: 'Yes. Without activation you’re using the system Python, which doesn’t have httpx.' },
            { text: 'Reinstall httpx every morning', why: 'It’s still installed, just in the .venv you haven’t switched on.' },
            { text: 'Delete the .venv folder', why: 'That deletes the packages you installed.' },
            { text: 'Upgrade to a newer Python', why: 'The version isn’t the problem; the wrong Python is running.' },
          ],
          answer: 0,
          explain: 'New terminal = activate again. `which python` shows which Python is running.',
        },
        {
          id: 'm0-s4-2', kind: 'choice',
          prompt: 'How should a teammate get the same packages as you?',
          options: [
            { text: 'You commit requirements.txt; they create their own .venv and run `pip install -r requirements.txt`', why: 'Right. Share the list of versions, not the installed folder.' },
            { text: 'You commit your .venv folder', why: 'It’s large, tied to your computer, and often breaks on other machines.' },
            { text: 'You email them each package name', why: 'Easy to get wrong, and versions won’t match.' },
            { text: 'They install the latest version of everything', why: 'Latest today may behave differently from what you tested.' },
          ],
          answer: 0,
          explain: 'Commit the recipe (requirements.txt or a lock file), not the kitchen (.venv).',
        },
      ],
    },
    {
      title: 'Environment variables and secrets',
      minutes: 6,
      body: [
        "**The problem.** Your script needs a HubSpot API key. The quick way is to paste it into the code. Then you push to GitHub, and anyone who reads the repo can use your key. Automated bots scan public repositories for exactly this.",
        "The fix: keep [[secret|secrets]] and settings **outside the code**. An [[environment variable]] is a named value the computer hands your program when it starts, like `HUBSPOT_TOKEN=pat-abc123`. The code only knows the *name*; the value lives elsewhere.",
        "On your laptop, that elsewhere is a [[.env]] file in the project folder: one `NAME=value` per line. The `python-dotenv` package loads it for you. On a server or in CI, the platform supplies the same names from its own secret store. Same code, different values: that’s how dev and production use different databases.",
        "The rules:",
        "- Add `.env` to `.gitignore` before your first commit.\n- Commit a `.env.example` with the same names and fake values, so others know what to set.\n- Never print or log a secret. Log *that* a key loaded, not the key.\n- If a key ever reaches GitHub, **revoke it and create a new one** at the provider. Deleting the file isn’t enough: old commits still contain it.",
        "`os.environ['HUBSPOT_TOKEN']` fails loudly with a `KeyError` if the variable is missing. That’s good: better to stop at startup than run half-configured. `os.getenv('HUBSPOT_TOKEN')` quietly returns `None` instead.",
      ],
      example: {
        caption: 'Keeping secrets out of the code',
        code: '# .env  (in .gitignore, never committed)\nHUBSPOT_TOKEN=pat-na1-real-secret\nDATABASE_URL=postgresql://postgres:devpass@localhost:5432/postgres\n\n# .env.example  (committed: same names, fake values)\nHUBSPOT_TOKEN=replace-me\nDATABASE_URL=postgresql://user:password@localhost:5432/dbname\n\n# main.py\nimport os\nfrom dotenv import load_dotenv        # pip install python-dotenv\n\nload_dotenv()                         # read .env into the environment\ntoken = os.environ["HUBSPOT_TOKEN"]   # KeyError if missing: fail fast\nprint("HubSpot token loaded")         # never print(token)',
      },
      interview: "Configuration and secrets come from environment variables, so the same code runs in every environment. Locally they live in a gitignored .env with a committed .env.example; in production they come from the platform’s secret store. If a credential leaks, I rotate it immediately, because Git history keeps it.",
      check: [
        {
          id: 'm0-s5-1', kind: 'choice',
          prompt: 'You accidentally pushed `.env` with a Stripe key. You delete the file and push again. Are you safe?',
          options: [
            { text: 'No: revoke the key in Stripe and create a new one, because the old commit still contains it', why: 'Right. Git keeps history, and the key may already have been copied.' },
            { text: 'Yes: the file is gone from GitHub', why: 'It’s gone from the latest version, but anyone can view the earlier commit.' },
            { text: 'Yes, if the repo has few visitors', why: 'Bots find leaked keys quickly; visitor numbers don’t matter.' },
            { text: 'Only if you also rename the repo', why: 'Renaming doesn’t remove history.' },
          ],
          answer: 0,
          explain: 'A leaked key is a compromised key. Rotate first, clean up second.',
        },
        {
          id: 'm0-s5-2', kind: 'choice',
          prompt: 'A teammate clones your repo and the script immediately fails with `KeyError: \'HUBSPOT_TOKEN\'`. What’s wrong?',
          options: [
            { text: 'They have no .env yet; they should copy .env.example to .env and fill in real values', why: 'Yes. .env is never committed, so each person creates their own.' },
            { text: 'The code has a typo and must be rewritten', why: 'It works for you, so the code is fine. The setting is missing.' },
            { text: 'You should commit your .env so it works for everyone', why: 'That puts your secrets in Git.' },
            { text: 'HubSpot is down', why: 'The script failed before it called HubSpot.' },
          ],
          answer: 0,
          explain: 'The KeyError is the code telling you, early and clearly, that a required setting isn’t there.',
        },
      ],
    },
    {
      title: 'The diagnostic: skip what you know, prove what you can',
      minutes: 6,
      body: [
        "This course assumes nothing, but you may already know some of it. The **diagnostic** is this module’s task list. Try each exercise *before* studying. If you can build it from a blank file and explain why it works, mark it done and skip ahead. If you only recognise the words, leave it open: that’s where your time should go.",
        "Some exercises touch topics later modules teach properly. Don’t worry if they’re unfamiliar:",
        "- HTTP, webhooks, OAuth and idempotency: Module 2.\n- [[Database|Databases]] and transactions: Module 4. A database stores data in an organised, permanent way; you’ll use Postgres.\n- [[Docker]] and Compose: Module 7. Docker packages a program with everything it needs, so it runs the same anywhere.",
        "**Start from something real.** Export one n8n workflow you already run into `workflows/` in your repo. Write down what triggers it, what it reads and writes, and where it could fail: an API down, a bad record, a duplicate webhook. For each, how would you notice?",
        "**Leave evidence.** For each exercise, save something: a command and its output, a passing test, a screenshot, or a note on a failure you caused on purpose and what happened. In interviews, “here’s the repo” beats “I know Docker”.",
        "**Use AI as a teacher, not as proof.** Ask it to explain, quiz you and review your code. But every module ends with a checkpoint done with AI closed. This one: rebuild a small API → transform → database automation without help, and explain every moving part.",
      ],
      example: {
        caption: 'Diagnostic exercise: run Postgres locally and connect from Python',
        code: '# Start Postgres in Docker (a throwaway password for local practice only)\ndocker run --name pg -e POSTGRES_PASSWORD=devpass -p 5432:5432 -d postgres:16\n\n# check_db.py  (pip install "psycopg[binary]" python-dotenv)\nimport os\nimport psycopg\nfrom dotenv import load_dotenv\n\nload_dotenv()                                   # DATABASE_URL comes from .env\nwith psycopg.connect(os.environ["DATABASE_URL"]) as conn:\n    print(conn.execute("SELECT version()").fetchone())   # proves it connected',
      },
      interview: "When I pick up a system, I start from evidence: I map an existing workflow’s trigger, transformations, external calls and writes, and for each boundary I say what can fail and how I’d detect it. I keep small, runnable proofs in a repo rather than relying on familiarity with tool names.",
      check: [
        {
          id: 'm0-s6-1', kind: 'choice',
          prompt: 'You recognise the phrase “OAuth refresh token” but couldn’t explain what happens when one is revoked. What should you do with that diagnostic item?',
          options: [
            { text: 'Leave it open and study it', why: 'Yes. Recognising words isn’t the same as being able to explain or build it.' },
            { text: 'Mark it done, since you’ve heard of it', why: 'Familiarity isn’t mastery. Interviews will find the gap.' },
            { text: 'Ask an AI to write the answer and mark it done', why: 'That proves the AI knows it, not you.' },
            { text: 'Skip the whole module', why: 'The rule is per item: skip only what you can prove.' },
          ],
          answer: 0,
          explain: 'Skip-first rule: if you can build it from a blank file and explain why it works, mark it complete. Otherwise, it stays open.',
        },
        {
          id: 'm0-s6-2', kind: 'choice',
          prompt: 'Which is the strongest evidence that you can run a Docker Compose stack?',
          options: [
            { text: 'A compose.yaml in your repo plus a note showing the data survived a restart', why: 'Yes. Something runnable, with proof of behaviour you tested.' },
            { text: 'A certificate from a short online course', why: 'It shows you studied, not that you can do it.' },
            { text: 'Saying “I’ve used Docker” on your CV', why: 'A claim, not evidence.' },
            { text: 'A screenshot of the Docker website', why: 'That shows nothing about your skills.' },
          ],
          answer: 0,
          explain: 'Your repo is your evidence trail: commits, tests, diagrams, READMEs and failure notes.',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'm0-q1', kind: 'order',
      prompt: 'Put the everyday Git steps in order, from editing a file to seeing it on GitHub.',
      items: ['Edit and save the file', '`git add` the change', '`git commit -m "…"`', '`git push`'],
      explain: 'Change → stage → snapshot → upload. `git status` at any point shows where you are.',
    },
    {
      id: 'm0-q2', kind: 'choice',
      prompt: 'Read the terminal session. Why did `cd` fail?',
      code: '$ pwd\n/Users/ana\n$ ls\nDesktop  Documents  projects\n$ cd lead-bot\ncd: no such file or directory: lead-bot',
      options: [
        { text: 'lead-bot isn’t in /Users/ana; it’s inside projects, so use `cd projects/lead-bot`', why: 'Yes. `ls` shows only Desktop, Documents and projects in the current folder.' },
        { text: 'The lead-bot folder has been deleted', why: 'It may well exist; it just isn’t in the current folder.' },
        { text: '`cd` only works with full paths', why: '`cd` accepts paths relative to the current folder too.' },
        { text: 'You need to run Python first', why: 'Moving between folders has nothing to do with Python.' },
      ],
      answer: 0,
      explain: '`pwd` and `ls` tell you where you are and what’s there. Check them before assuming something is broken.',
    },
    {
      id: 'm0-q3', kind: 'choice',
      prompt: 'Your workflow must run every 15 minutes, 24/7, for a client. Where should it run?',
      options: [
        { text: 'On an always-on server: a rented VPS or a managed service like n8n Cloud', why: 'Yes. It needs a computer that never sleeps.' },
        { text: 'On your laptop, kept plugged in', why: 'Laptops sleep, restart for updates and travel with you.' },
        { text: 'On localhost, so it’s private', why: 'Localhost just means “this computer”; it doesn’t make it always-on.' },
        { text: 'In your GitHub repo', why: 'GitHub stores your code; it doesn’t run your n8n workflows.' },
      ],
      answer: 0,
      explain: 'Develop locally, run production somewhere that’s always on.',
    },
    {
      id: 'm0-q4', kind: 'order',
      prompt: 'Order the steps to set up Python for a new project.',
      items: ['`python3 -m venv .venv`', '`source .venv/bin/activate`', '`pip install httpx`', '`pip freeze > requirements.txt`'],
      explain: 'Create, activate, install, record. And add .venv/ to .gitignore.',
    },
    {
      id: 'm0-q5', kind: 'choice',
      prompt: 'How many contacts are in this API response?',
      code: '{\n  "contacts": [\n    { "email": "ana@example.com", "phone": null },\n    { "email": "bo@example.com", "phone": "+61 400 000 000" }\n  ],\n  "next_cursor": null\n}',
      options: [
        { text: '2', why: 'Yes. The contacts list holds two objects.' },
        { text: '1, because Ana’s phone is null', why: 'A null field is still part of a contact; it’s just empty.' },
        { text: '4, counting every field', why: 'Fields belong to contacts; there are two contacts with two fields each.' },
        { text: '0, because next_cursor is null', why: 'next_cursor is a separate field. It doesn’t empty the list.' },
      ],
      answer: 0,
      explain: 'Square brackets hold a list; each `{}` inside is one item, like one n8n item.',
    },
    {
      id: 'm0-q6', kind: 'choice',
      prompt: 'Your script works on your laptop but crashes on the server with `ModuleNotFoundError: No module named \'httpx\'`. What’s the most likely fix?',
      options: [
        { text: 'Make sure requirements.txt lists httpx, then run `pip install -r requirements.txt` in the server’s virtual environment', why: 'Yes. The server only has the packages you tell it to install.' },
        { text: 'Copy your laptop’s .venv folder to the server', why: 'Virtual environments are tied to the machine that made them; recreate it instead.' },
        { text: 'Rewrite the script without httpx', why: 'The package is fine; it’s just not installed there.' },
        { text: 'Restart the server', why: 'Restarting doesn’t install packages.' },
      ],
      answer: 0,
      explain: 'Recorded dependencies make any machine reproducible: same list, same versions.',
    },
    {
      id: 'm0-q7', kind: 'choice',
      prompt: 'Which belongs in a committed `.env.example`?',
      options: [
        { text: '`OPENAI_API_KEY=replace-me`', why: 'Yes. The name tells people what to set; the value is a harmless placeholder.' },
        { text: '`OPENAI_API_KEY=sk-` followed by your real key', why: 'That’s a real secret in Git.' },
        { text: 'Nothing; the file should be empty', why: 'Then nobody knows which settings the app needs.' },
        { text: 'Your .venv folder', why: 'That’s not a settings file, and it shouldn’t be committed.' },
      ],
      answer: 0,
      explain: 'Names and placeholders in .env.example (committed); real values in .env (ignored).',
    },
    {
      id: 'm0-q8', kind: 'choice',
      prompt: 'You send a request and get **400 Bad Request**. What should you do?',
      options: [
        { text: 'Check what you sent: a missing field or wrong format, then fix the request', why: 'Yes. 4xx means the request itself was wrong.' },
        { text: 'Retry the same request until it works', why: 'The same bad request will get the same 400.' },
        { text: 'Wait for their server to recover', why: 'That’s the 5xx family.' },
        { text: 'Nothing; 400 means success', why: 'Success is 2xx.' },
      ],
      answer: 0,
      explain: '4xx: fix what you sent. 5xx: their problem, often temporary.',
    },
    {
      id: 'm0-q9', kind: 'choice',
      prompt: 'A CRM has no webhooks. Your client wants new deals copied to a sheet within an hour. What do you build?',
      options: [
        { text: 'A scheduled workflow that polls the CRM for new deals, e.g. every 15 minutes', why: 'Yes. Without webhooks, polling on a schedule is the way.' },
        { text: 'A Webhook trigger and wait', why: 'The CRM can’t call it; it doesn’t support webhooks.' },
        { text: 'Poll every second to be safe', why: 'Far more than the hour needs, and likely to hit request limits.' },
        { text: 'Ask the sales team to paste deals in manually', why: 'That’s not automation.' },
      ],
      answer: 0,
      explain: 'Webhooks when available; polling on a sensible schedule when not.',
    },
    {
      id: 'm0-q10', kind: 'choice',
      prompt: 'Why does `os.environ["DATABASE_URL"]` crashing at startup count as good behaviour?',
      options: [
        { text: 'It fails early and clearly, instead of running half-configured and failing somewhere confusing later', why: 'Yes. A missing setting should stop the program at the door.' },
        { text: 'Crashes are always good', why: 'Only crashes that surface a real problem early are useful.' },
        { text: 'It means the database password is wrong', why: 'It means the variable isn’t set at all.' },
        { text: 'It hides the secret from the logs', why: 'It’s about missing config, not hiding values.' },
      ],
      answer: 0,
      explain: 'Fail fast on required config. Use `os.getenv` only for settings that are genuinely optional.',
    },
    {
      id: 'm0-q11', kind: 'choice',
      prompt: 'You can explain idempotency but have never built anything with it. According to the skip-first rule, can you skip it?',
      options: [
        { text: 'Not yet: you need to build it from a blank file and explain it', why: 'Right. The rule asks for both.' },
        { text: 'Yes: explaining is enough', why: 'The rule asks you to build it as well.' },
        { text: 'Yes, if an AI agrees you understand it', why: 'AI is a teacher here, not proof.' },
        { text: 'No: nobody can skip anything', why: 'Skipping is the point of the diagnostic, once you can prove it.' },
      ],
      answer: 0,
      explain: 'Build it and explain it, then skip it. Recognising it isn’t enough.',
    },
    {
      id: 'm0-q12', kind: 'choice',
      prompt: 'You export an n8n workflow to your repo. What must you check before committing it?',
      options: [
        { text: 'That it contains no API keys, tokens or client data', why: 'Yes. Exported workflows can contain hard-coded values; check and remove them.' },
        { text: 'That the file is under 1 KB', why: 'Size doesn’t matter; secrets do.' },
        { text: 'That it’s renamed to .txt', why: 'Keep it as .json so it can be imported again.' },
        { text: 'Nothing; n8n files are always safe', why: 'Anything typed directly into a node, like a key in a header, ends up in the export.' },
      ],
      answer: 0,
      explain: 'Treat every file you commit as public: no secrets, no real client data.',
    },
  ],
  tasks: [
    { device: 'phone', plain: 'Without notes, explain: how an HTTP request and response work, JSON, webhooks vs polling, OAuth refresh tokens, idempotency, database transactions and Docker.', done: 'A voice note or written answer for each. Mark any you can only half-explain as “study”, and leave them open.' },
    { device: 'computer', plain: 'Create one GitHub repository for the whole course, with folders: services, workflows, infra, tests and docs.', done: 'The repo is on GitHub with those folders, a README and a .gitignore that lists .env and .venv/.' },
    { device: 'computer', plain: 'Set up Python in the repo: a virtual environment, Ruff for formatting/checking, pytest, and a .env file for settings.', done: '`pytest` and `ruff check .` both run, requirements.txt is committed, and .env.example is committed but .env is not.' },
    { device: 'computer', plain: 'Run Postgres on your computer (Docker is easiest) and connect to it from a Python script.', done: 'Your script prints the Postgres version, reading the connection details from .env.' },
    { device: 'computer', plain: 'Run a Docker Compose setup with two services (e.g. n8n and Postgres) and a named volume for the data.', done: 'Both start with `docker compose up -d`, and your data is still there after `docker compose down` and `up` again.' },
    { device: 'computer', plain: 'Use curl or Postman to send GET, POST, PATCH and DELETE requests, and trigger 400, 401, 404 and 429 responses on purpose (httpbin.org/status/429 always replies with a 429; change the number for other codes).', done: 'Saved commands with their responses, and one line per error code saying what you’d do about it.' },
    { device: 'computer', plain: 'Export one n8n workflow you already use into the repo’s workflows folder, and document it.', done: 'The JSON (with secrets removed) plus a short note: what triggers it, what it writes, and how it can fail.' },
    { device: 'phone', plain: 'Record a 3-minute explanation of your current automation setup, with no screen and no notes.', done: 'A recording you’ve listened back to, with a list of anything you stumbled on.' },
  ],
};
