import type { Lesson } from './types';

export const m1: Lesson = {
  intro: "Almost every automation job is really an integration job: getting two systems that were never designed to work together to pass data reliably. Pre-built n8n or Zapier nodes hide how that works, until something breaks at 2am. This module teaches what is underneath those nodes, so you can connect any API from its docs and explain exactly what happens when it fails. These topics come up in nearly every AI automation interview.",
  sections: [
    {
      title: 'How systems talk: HTTP in plain English',
      minutes: 6,
      body: [
        "Every API call is a letter and a reply. Your automation sends a **request**; the other system sends back a **response**.",
        "A request has four parts:",
        "- **Method**: what you want to do. `GET` reads, `POST` creates, `PUT`/`PATCH` update, `DELETE` removes.\n- **URL**: where it goes, at a specific [[endpoint]], plus optional [[query parameters]] like `?page=2`.\n- **Headers**: labels on the envelope, such as who you are (`Authorization`) and what format you're sending (`Content-Type: application/json`).\n- **Body**: the actual data, usually [[JSON]]. GET requests normally don't have one.",
        "The response comes back with a [[status code]], a three-digit number saying what happened. You don't need to memorise them all, just the families:",
        "- **2xx: it worked.** 200 OK, 201 Created, 204 No Content.\n- **4xx: you did something wrong.** 400 bad data, 401 not logged in, 403 logged in but not allowed, 404 not found, 429 slow down.\n- **5xx: their server had a problem.** Often temporary, so often worth retrying.",
        "One thing beginners skip: [[timeout|timeouts]]. Without one, a request can hang for minutes and freeze your workflow. Always set one; 10–30 seconds is typical.",
        "Now the sneaky part. **A timeout doesn't mean “it failed”. It means “I don't know.”** The other system may have received your POST and created the record; the reply just never made it back. Remember this, because it's the reason the last lesson of this module exists.",
      ],
      example: {
        caption: 'A real request in curl, with a timeout',
        code: 'curl -X POST https://api.example.com/v1/contacts \\\n  -H "Authorization: Bearer $API_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"email": "ana@example.com"}\' \\\n  --max-time 20',
      },
      interview: "I think about HTTP errors in families. 4xx means the request is wrong, so I fix it rather than retry it, except 429, which means back off and try later. 5xx and network errors are usually temporary and retryable with backoff. I always set explicit timeouts, and I treat a timeout on a write as an unknown outcome, not a failure.",
      check: [
        {
          id: 'm1-s0-1', kind: 'choice',
          prompt: 'Your workflow calls a CRM with a valid token and gets back **403 Forbidden**. What does that mean?',
          options: [
            { text: 'The CRM knows who you are, but your token isn’t allowed to do this action', why: 'Right. 403 means you’re authenticated but not authorised. Usually a missing scope or role.' },
            { text: 'Your token is missing or invalid; you need to log in', why: 'That’s 401 Unauthorized. 403 means the CRM recognised you.' },
            { text: 'The CRM’s server crashed', why: 'Server problems are 5xx codes, not 4xx.' },
            { text: 'You sent too many requests', why: 'That’s 429 Too Many Requests.' },
          ],
          answer: 0,
          explain: '401 = “who are you?” 403 = “I know who you are, and the answer is no.” Fix 403 by granting the right permission or scope, not by retrying.',
        },
        {
          id: 'm1-s0-2', kind: 'choice',
          prompt: 'Which of these errors is usually worth retrying automatically?',
          options: [
            { text: '503 Service Unavailable', why: 'Yes. Their server is temporarily overloaded or restarting. A retry a little later often works.' },
            { text: '400 Bad Request', why: 'Retrying sends the same bad data and gets the same error.' },
            { text: '404 Not Found', why: 'The thing doesn’t exist. Asking again won’t create it.' },
            { text: '401 Unauthorized', why: 'You need a new or valid token. Repeating the same request won’t fix it.' },
          ],
          answer: 0,
          explain: '5xx (and timeouts, connection errors and 429) are temporary. Most other 4xx errors need you to change something first.',
        },
        {
          id: 'm1-s0-3', kind: 'choice',
          prompt: 'A `POST /invoices` request **times out** after 20 seconds. What do you know for certain?',
          options: [
            { text: 'Nothing. The invoice may or may not have been created', why: 'Correct. The request may have arrived and succeeded; only the reply was lost.' },
            { text: 'The invoice was not created', why: 'Not necessarily. The server might have finished the work after your client gave up waiting.' },
            { text: 'The invoice was created', why: 'Not necessarily. The request may never have arrived.' },
            { text: 'The API is down', why: 'A single timeout doesn’t tell you that; it could be a slow request or a network blip.' },
          ],
          answer: 0,
          explain: 'This “unknown outcome” is why blindly retrying writes can create duplicates. Lesson 6 (idempotency) is the fix.',
        },
      ],
    },
    {
      title: 'Reading API docs and paging through data',
      minutes: 7,
      body: [
        "Before building with a new API, read five parts of its docs: **authentication**, **the endpoint you need**, **pagination**, **rate limits** and **errors**. That's about 15 minutes, and it saves hours of guessing.",
        "[[Pagination]]: APIs never send you 50,000 records at once. They send a page, and you ask for the next one. There are two common styles:",
        "- **Offset / page number**: `?page=3&limit=100` or `?offset=200`. Simple, but if records are added or deleted while you're paging, everything shifts, and you can skip or duplicate records.\n- **Cursor**: each response includes a bookmark, like `next_cursor: \"abc123\"`, and you send it back to get the next page. This is more reliable for big or changing data. Stripe, Slack and HubSpot all work this way.",
        "You stop when the API says there's nothing more: `has_more: false`, no next cursor, or an empty page.",
        "[[Checkpoint|Checkpoints]]: imagine a 100,000-record sync crashes at record 63,284. Without a checkpoint, you start over. With one, you've saved “last finished cursor = X” in your database, and the next run resumes from there.",
        "The golden rule: **save the checkpoint only after that page's records are safely stored.** If you move the bookmark first and then crash, those records are skipped forever, because the next run thinks they're done.",
      ],
      example: {
        caption: 'Cursor pagination with a safe checkpoint (Python)',
        code: 'cursor = load_checkpoint()            # None on the first run\nwhile True:\n    page = client.get("/contacts", params={"limit": 100, "cursor": cursor}).json()\n    upsert_contacts(page["results"])  # 1. store the data first\n    cursor = page.get("next_cursor")\n    save_checkpoint(cursor)           # 2. THEN move the bookmark\n    if not cursor:\n        break',
      },
      interview: "I prefer cursor pagination for large or changing datasets, because offset pagination can skip or duplicate rows when the data shifts underneath you. I save a checkpoint only after each page is committed, so a crash resumes from the last durable position. And because the writes are upserts, replaying one page is harmless.",
      check: [
        {
          id: 'm1-s1-1', kind: 'order',
          prompt: 'Put the steps for processing **one page** of a sync in the safe order.',
          items: ['Request the page using the saved cursor', 'Store the page’s records', 'Save the new cursor as the checkpoint', 'Stop if there is no next cursor'],
          explain: 'Data first, bookmark second. If you crash between the two, you re-process one page (harmless if writes are upserts) instead of losing it.',
        },
        {
          id: 'm1-s1-2', kind: 'choice',
          prompt: 'You’re paging with `?offset=` through a contact list while a teammate deletes contacts on page 1. What can go wrong?',
          options: [
            { text: 'You skip some contacts, because everything after the deletions shifts up', why: 'Right. Record #101 moves to position #100, which you already “read”.' },
            { text: 'Nothing; offsets are fixed', why: 'Offsets are positions, not identities. When rows disappear, positions change.' },
            { text: 'The API returns a 409 Conflict', why: 'APIs don’t usually detect this. It fails silently, which is what makes it dangerous.' },
            { text: 'You get duplicate pages forever', why: 'Deletions cause skips; insertions near the top cause duplicates. It doesn’t loop forever.' },
          ],
          answer: 0,
          explain: 'Cursor pagination avoids this because the bookmark points at a specific record, not a position.',
        },
        {
          id: 'm1-s1-3', kind: 'choice',
          prompt: 'A sync saves the checkpoint, **then** writes the records, and crashes in between. What happens on the next run?',
          options: [
            { text: 'Those records are skipped permanently', why: 'Correct. The bookmark already says they’re done.' },
            { text: 'Those records are written twice', why: 'That’s the opposite mistake. Here they’re never written at all.' },
            { text: 'The sync starts from the beginning', why: 'No. It trusts the checkpoint and starts after it.' },
            { text: 'The API rejects the stale cursor', why: 'The cursor is fine; the problem is in your ordering.' },
          ],
          answer: 0,
          explain: 'Silent data loss is the worst failure because nothing alerts you. Store first, checkpoint second.',
        },
      ],
    },
    {
      title: 'Logging in: API keys, tokens and OAuth',
      minutes: 8,
      body: [
        "APIs need to know who's calling. There are three common ways:",
        "- **API key**: a long secret string sent in a header. Simple, but anyone who has it *is* you, so it lives on the server: in n8n credentials or environment variables, never in front-end code, a screenshot or a GitHub repo.\n- **Bearer token**: `Authorization: Bearer <token>`. Same idea; “bearer” means whoever holds it gets in.\n- **[[OAuth]] 2.0**: used when your app acts *on behalf of a user* inside their account (their Gmail, their HubSpot). The user never gives you their password.",
        "How OAuth works, using a hotel as the analogy:",
        "1. You send the user to the provider's login page, asking for specific [[scopes]] (permissions), such as “read contacts”.\n2. The user logs in and clicks **Allow**.\n3. The provider sends them back to your app with a short-lived **authorization code**, like a claim ticket.\n4. Your server swaps that code for tokens.\n5. You receive an [[access token]], the room key card that works for about an hour, and a [[refresh token]], which gets you a new key card without bothering the user again.",
        "[[PKCE]] (pronounced “pixie”) adds a lock to steps 3–4. Your app makes up a random secret at the start and proves it during the swap, so a stolen claim ticket is useless. It's now recommended for every OAuth app.",
        "What actually breaks in real life:",
        "- **Access token expired**: normal. Use the refresh token.\n- **Refresh token revoked** (the user disconnected your app, an admin removed access, a password change, or the token went unused too long): retrying will never work. Stop the job and ask the user to reconnect.\n- **Two jobs refresh at the same moment**: some providers issue a new refresh token on every refresh and kill the old one, so one job ends up holding a dead token. Make sure only one process refreshes at a time.",
      ],
      interview: "For user-delegated access I use the OAuth authorization-code flow with PKCE, request the minimum scopes, and store tokens server-side, encrypted. I refresh before expiry and make sure only one process refreshes at a time, because some providers rotate refresh tokens. An `invalid_grant` on refresh is terminal: I pause the affected jobs and surface a reconnect action instead of retrying.",
      check: [
        {
          id: 'm1-s2-1', kind: 'choice',
          prompt: 'In the hotel analogy, what does the **refresh token** do?',
          options: [
            { text: 'Gets a new access token without the user logging in again', why: 'Exactly. It’s how automations keep working for months.' },
            { text: 'Proves the user typed the right password', why: 'Your app never sees the password; that happens on the provider’s page.' },
            { text: 'Is sent with every API call', why: 'That’s the access token. The refresh token only goes to the token endpoint.' },
            { text: 'Decides which scopes you get', why: 'Scopes are chosen at the start and approved by the user.' },
          ],
          answer: 0,
          explain: 'Access token = short-lived key card for API calls. Refresh token = long-lived way to get new key cards.',
        },
        {
          id: 'm1-s2-2', kind: 'choice',
          prompt: 'Your token refresh call returns `400 {"error": "invalid_grant"}`. What’s the best response?',
          options: [
            { text: 'Stop the affected jobs and alert the user to reconnect the account', why: 'Right. The grant is dead, and only the user can create a new one.' },
            { text: 'Retry the refresh with exponential backoff', why: 'invalid_grant won’t fix itself. You’d just retry forever.' },
            { text: 'Switch to the user’s password instead', why: 'You should never have it, and many providers don’t allow password logins for APIs.' },
            { text: 'Ignore it; the next scheduled run will work', why: 'It won’t, and meanwhile data silently stops syncing.' },
          ],
          answer: 0,
          explain: 'Classify errors before retrying. Revoked access is a “needs a human” error, so make it visible.',
        },
        {
          id: 'm1-s2-3', kind: 'choice',
          prompt: 'Where should an API key for your n8n or Python automation live?',
          options: [
            { text: 'In n8n credentials or server environment variables', why: 'Yes. They’re kept out of code, out of logs and out of the browser.' },
            { text: 'Hard-coded in the workflow JSON you commit to GitHub', why: 'Bots scan GitHub for keys within minutes of a push.' },
            { text: 'In the LLM prompt, so the agent can call the API', why: 'Never put secrets in prompts. Tools should hold credentials on the server.' },
            { text: 'In front-end JavaScript', why: 'Anyone can open DevTools and read it.' },
          ],
          answer: 0,
          explain: 'Rule of thumb: if a human or a model can see it, assume it will leak.',
        },
      ],
    },
    {
      title: 'Webhooks: when the other system calls you',
      minutes: 8,
      body: [
        "**Polling** means you ask “anything new?” every 5 minutes. A [[webhook]] means the provider calls *your* URL the moment something happens. Webhooks are faster and cheaper, but you're now running a public URL that anyone on the internet can hit.",
        "Four facts about webhooks that every provider documents somewhere:",
        "1. **They can arrive more than once.** If you don't reply with a 2xx quickly, the provider assumes you missed it and sends it again.\n2. **They can arrive out of order.** “Subscription updated” can land before “subscription created”.\n3. **They can arrive late**, sometimes hours late, after an outage.\n4. **Anyone can fake one**, unless you check the [[signature]].",
        "**How signatures work.** You and the provider share a secret. With each webhook, the provider sends a fingerprint of the request body made with that secret (an [[HMAC]]). You calculate the same fingerprint yourself; if they match, the webhook is genuine and unmodified.",
        "Calculate it from the **raw body exactly as received**. If your framework parses the JSON and re-formats it first, even a changed space breaks the match.",
        "Many signatures include a timestamp. Reject old ones (for example, older than 5 minutes), so an attacker can't record a real webhook and send it again later. That's a [[replay attack]].",
        "The safe recipe:",
        "1. Verify the signature.\n2. Save the raw event in your database, keyed by the provider's event ID.\n3. Reply 200 immediately.\n4. Do the real work afterwards, in a background [[worker]].",
        "If the same event ID shows up again, a [[unique constraint]] in the database rejects it and you just reply 200 again, so nothing happens twice. For out-of-order events, don't trust arrival order: compare each object's updated time or version, or fetch the latest state from the API.",
      ],
      interview: "My webhook receiver verifies the HMAC against the raw body, checks the signed timestamp within a tolerance window, inserts the event under a unique key of provider, account and event ID, returns 2xx, and hands processing to a worker. Duplicates hit the constraint and are acknowledged without side effects. I don't rely on delivery order: I compare object versions or refetch current state.",
      check: [
        {
          id: 'm1-s3-1', kind: 'choice',
          prompt: 'Why reply 200 **before** doing the slow work (like an LLM call)?',
          options: [
            { text: 'If you’re too slow, the provider times out and sends the webhook again, causing duplicates', why: 'Right. Slow handlers cause duplicate deliveries.' },
            { text: 'Because 200 is required by the HTTP standard', why: 'Any 2xx works. The point is replying quickly.' },
            { text: 'So the provider sends the next event faster', why: 'Speed isn’t the main issue; duplicate deliveries and the provider disabling your endpoint are.' },
            { text: 'It isn’t necessary if you check the signature', why: 'Signatures prove authenticity; they don’t stop retries.' },
          ],
          answer: 0,
          explain: 'Many providers wait only a few seconds, and some disable endpoints that keep failing. Acknowledge fast, process later.',
        },
        {
          id: 'm1-s3-2', kind: 'choice',
          prompt: 'Your signature check fails on every webhook, even though the secret is definitely correct. Most likely cause?',
          options: [
            { text: 'The body was parsed and re-serialised before you computed the HMAC', why: 'Yes. You must sign the raw bytes, not your re-formatted JSON.' },
            { text: 'The provider is under attack', why: 'Possible in theory, but “every webhook fails” points to your code.' },
            { text: 'You need to retry the verification', why: 'The same input will always produce the same result.' },
            { text: 'HTTPS is stripping the header', why: 'HTTPS doesn’t remove headers.' },
          ],
          answer: 0,
          explain: 'In n8n, turn on the Webhook node’s raw body option. In FastAPI, read `await request.body()` before parsing.',
        },
        {
          id: 'm1-s3-3', kind: 'order',
          prompt: 'Put the webhook receiver steps in order.',
          items: ['Verify the signature', 'Save the raw event by its event ID', 'Reply with 2xx', 'Process it in a background worker'],
          explain: 'Verify → persist → acknowledge → process. Persisting before acknowledging means a crash never loses an event you said you received.',
        },
      ],
    },
    {
      title: 'Rate limits and retrying the right way',
      minutes: 7,
      body: [
        "Every API limits how fast you can call it (a [[rate limit]]). Go over it and you get **429 Too Many Requests**. The response often includes a `Retry-After` header saying exactly how many seconds to wait. Always obey it.",
        "When a call fails, ask one question: **will trying again help?**",
        "- **Yes, retry:** 429, 500, 502, 503, 504, timeouts, dropped connections. These are usually temporary.\n- **No, don't retry:** 400, 404, 422. Your data is wrong and will be wrong next time too. Send it to a review queue (a [[dead-letter queue]]).\n- **Retrying won't help, and it needs fixing:** 401/403. Re-authenticate or fix permissions.",
        "How to retry well:",
        "- [[Exponential backoff]]: wait 1s, then 2s, 4s, 8s… so you don't hammer a struggling server.\n- [[Jitter]]: add randomness. If 500 jobs all failed at the same moment and all retry at exactly 4 seconds, they knock the server over again together (the [[thundering herd]]).\n- **A maximum**: for example, 5 attempts. After that, mark the job failed and alert someone. Endless retries hide problems and burn through your rate limit.",
        "Prevention beats cure: use batch endpoints where the API offers them (one call for 100 records), and cap how many requests run at once ([[concurrency]]).",
      ],
      example: {
        caption: 'Backoff with “full jitter” (Python)',
        code: 'import random, time\n\nfor attempt in range(5):\n    response = client.post(url, json=payload, timeout=20)\n    if response.status_code not in (429, 500, 502, 503, 504):\n        break\n    wait = float(response.headers.get("Retry-After", 0)) or random.uniform(0, min(60, 2 ** attempt))\n    time.sleep(wait)\nelse:\n    mark_failed_and_alert(payload)  # ran out of attempts',
      },
      interview: "I classify errors before retrying. 429, 5xx and network timeouts are retryable with capped exponential backoff and jitter, honouring Retry-After. Validation errors fail fast to a dead-letter queue. Auth errors trigger re-authentication. Retries are bounded and end in a visible failed state, and they're only safe because the operations are idempotent.",
      check: [
        {
          id: 'm1-s4-1', kind: 'choice',
          prompt: 'You get `429` with the header `Retry-After: 30`. What do you do?',
          options: [
            { text: 'Wait at least 30 seconds before calling again', why: 'Yes. The API told you exactly what it needs.' },
            { text: 'Retry immediately; 429s are random', why: 'They’re not random. You’re over the limit, and hammering it can get you blocked.' },
            { text: 'Mark the job as failed', why: '429 is temporary; failing it permanently loses work for no reason.' },
            { text: 'Switch to a different API key to get around the limit', why: 'This usually breaks the provider’s terms and can get the account banned.' },
          ],
          answer: 0,
          explain: 'Retry-After beats your own backoff calculation, because the server knows its own limits.',
        },
        {
          id: 'm1-s4-2', kind: 'choice',
          prompt: 'Why add **jitter** (randomness) to retry delays?',
          options: [
            { text: 'So many clients that failed together don’t all retry at the same instant', why: 'Exactly. It spreads the load out.' },
            { text: 'To make retries faster on average', why: 'Speed isn’t the goal; spreading the load is.' },
            { text: 'Because APIs block predictable retry patterns', why: 'That’s not the reason; the issue is synchronised load spikes.' },
            { text: 'To make debugging easier', why: 'It actually makes timings less predictable. It’s worth it for the load spreading.' },
          ],
          answer: 0,
          explain: 'Without jitter, failures that happened together retry together, and fail together again.',
        },
        {
          id: 'm1-s4-3', kind: 'choice',
          prompt: 'In a 500-record sync, one record gets `400 Bad Request: "email is invalid"`. Best handling?',
          options: [
            { text: 'Send that record to a review queue with the error, and continue with the rest', why: 'Yes. One bad record shouldn’t block 499 good ones, and it isn’t silently lost.' },
            { text: 'Retry it 5 times with backoff', why: 'The email will still be invalid on attempt 5.' },
            { text: 'Stop the whole sync', why: 'Sometimes right for critical data, but usually too disruptive for one bad record.' },
            { text: 'Skip it and move on', why: 'Silently dropping data is the worst choice, because nobody knows it’s missing.' },
          ],
          answer: 0,
          explain: 'Bad data needs a person or a fix, not another attempt. Make it visible and keep going.',
        },
      ],
    },
    {
      title: 'Idempotency: making it safe to run twice',
      minutes: 8,
      body: [
        "[[Idempotent]] means **doing something twice has the same effect as doing it once.** It's the single most important word in this module, and interviewers love it.",
        "Why it matters: retries, duplicate webhooks and crashed-then-restarted jobs mean **your code will sometimes run twice.** The only question is whether that creates two invoices, two CRM contacts or two emails to a customer.",
        "Three tools that make actions safe to repeat:",
        "1. [[Upsert]] **by a stable ID**: instead of “create contact”, do “create or update the contact whose external ID is `cus_123`”. Running it twice just updates the same record. In SQL this is `INSERT … ON CONFLICT`; many CRMs have a “create or update” endpoint.\n2. [[Idempotency key|Idempotency keys]]: some APIs (Stripe is the famous one) accept a header like `Idempotency-Key: order-981-charge`. If they see the same key again, they return the original result instead of charging twice. The key must stay **the same on every retry**, so build it from your data (the order ID), not a fresh random value each attempt.\n3. **A unique constraint in your own database**, so even if two workers grab the same event at the same moment, only one wins.",
        "Why “check whether it exists, then create” isn't enough: two workers can both check at the same millisecond, both see “not there”, and both create. That's a [[race condition]]. A database unique constraint is the only reliable referee.",
        "Remember the timeout from the first lesson? This is the answer. When a create times out and you don't know whether it worked, an idempotent retry is safe: either it creates the record, or it harmlessly finds the one that already exists.",
      ],
      example: {
        caption: 'An upsert in Postgres: run it 10 times, still one row',
        code: "INSERT INTO contacts (external_id, email, name)\nVALUES ('cus_123', 'ana@example.com', 'Ana')\nON CONFLICT (external_id)\nDO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name;",
      },
      interview: "I design every side effect to be idempotent: upserts keyed on a stable external ID, provider idempotency keys derived from the business operation, and unique constraints as the final referee against races. That turns at-least-once delivery into effectively-once outcomes, and it's what makes retries and replays safe.",
      check: [
        {
          id: 'm1-s5-1', kind: 'choice',
          prompt: 'A Stripe charge request timed out. Which retry is safe?',
          options: [
            { text: 'Retry with the same Idempotency-Key as the first attempt', why: 'Yes. If the first one went through, Stripe returns that result instead of charging again.' },
            { text: 'Retry with a new random Idempotency-Key', why: 'A new key looks like a new charge, so the customer may pay twice.' },
            { text: 'Retry with no key; Stripe detects duplicates automatically', why: 'Without a key, Stripe can’t tell a retry from a new charge.' },
            { text: 'Don’t retry; tell the customer it failed', why: 'It may have succeeded. Telling them it failed causes confusion and double payments.' },
          ],
          answer: 0,
          explain: 'Build the key from the business operation (e.g. `order-981-charge`), so every retry of that operation uses the same key.',
        },
        {
          id: 'm1-s5-2', kind: 'choice',
          prompt: 'Why isn’t “check if the contact exists, and create it if not” enough to prevent duplicates?',
          options: [
            { text: 'Two workers can both check before either one creates', why: 'Right. That’s a race condition, and only a unique constraint closes the gap.' },
            { text: 'Checking is too slow', why: 'Speed isn’t the problem; the gap between check and create is.' },
            { text: 'APIs don’t support searching', why: 'Most do. The issue is concurrency, not capability.' },
            { text: 'It is enough, if the code is correct', why: 'Correct code still races when two copies run at once.' },
          ],
          answer: 0,
          explain: 'Concurrency bugs don’t show up in testing with one worker; they show up in production at scale.',
        },
        {
          id: 'm1-s5-3', kind: 'choice',
          prompt: 'Which of these actions is naturally **idempotent**?',
          options: [
            { text: 'Set the contact’s status to “customer”', why: 'Yes. Doing it twice leaves the same result.' },
            { text: 'Add 1 to the contact’s login count', why: 'Twice = +2. Not idempotent.' },
            { text: 'Send the welcome email', why: 'Twice = two emails. You’d need to record that it was sent.' },
            { text: 'Append a note to the deal', why: 'Twice = two notes.' },
          ],
          answer: 0,
          explain: '“Set to X” is idempotent; “add”, “append” and “send” are not, unless you track that they already happened.',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'm1-q1', kind: 'choice',
      prompt: 'An integration worked for months. Today every call fails. Read the log. What happened?',
      code: '02:00:01  POST /oauth/token  grant_type=refresh_token\n          → 400 {"error":"invalid_grant"}\n02:00:02  GET /v3/contacts?limit=100\n          → 401 Unauthorized\n02:05:02  GET /v3/contacts?limit=100\n          → 401 Unauthorized',
      options: [
        { text: 'The refresh token was revoked or expired, so no new access token could be issued', why: 'Yes. invalid_grant on refresh is the root cause; the 401s are the symptom.' },
        { text: 'The contacts API is down', why: 'An outage would be 5xx. These are auth failures.' },
        { text: 'The access token is missing a scope', why: 'That would be 403 on the contacts call, and the refresh would have succeeded.' },
        { text: 'The rate limit was exceeded', why: 'That would be 429.' },
      ],
      answer: 0,
      explain: 'Read logs from the first error, not the loudest one. Next steps: ask the account owner to reconnect, then alert on invalid_grant so you hear about it before the client does.',
    },
    {
      id: 'm1-q2', kind: 'order',
      prompt: 'Put the OAuth authorization-code flow (with PKCE) in order.',
      items: [
        'Send the user to the provider with the requested scopes and a PKCE challenge',
        'The user logs in and approves access',
        'The provider redirects back to your app with an authorization code',
        'Your server exchanges the code and the PKCE verifier for tokens',
        'Call the API with the access token, and refresh it when it expires',
      ],
      explain: 'The code is a claim ticket; the PKCE verifier proves that you are the one who asked for it.',
    },
    {
      id: 'm1-q3', kind: 'choice',
      prompt: 'What happens with this code when the server returns **429**?',
      code: 'for attempt in range(5):\n    r = requests.post(url, json=invoice, timeout=20)\n    if r.status_code < 500:\n        break\n    time.sleep(2 ** attempt)',
      options: [
        { text: 'It exits the loop as if it succeeded, so the invoice is silently never sent', why: 'Right. 429 is less than 500, so the code breaks out and treats it as done.' },
        { text: 'It retries with exponential backoff', why: 'Only 5xx codes reach the sleep. 429 hits the break.' },
        { text: 'It waits for the Retry-After header', why: 'Nothing in this code reads Retry-After.' },
        { text: 'requests raises an exception', why: 'requests doesn’t raise on error status codes unless you call raise_for_status().' },
      ],
      answer: 0,
      explain: 'Bugs like this pass happy-path testing. Check for success explicitly, and list the retryable codes (429, 500, 502, 503, 504) explicitly.',
    },
    {
      id: 'm1-q4', kind: 'choice',
      prompt: 'A provider delivers the same webhook **four times**. How do you guarantee only one business action?',
      options: [
        { text: 'Insert each event under a unique event ID before processing, and acknowledge duplicates without acting', why: 'Yes. The database constraint is the referee, and duplicates are harmless.' },
        { text: 'Look up the event ID in a Google Sheet first', why: 'Check-then-act races, and Sheets has no unique constraints.' },
        { text: 'Process faster so the provider never retries', why: 'You can’t control network blips or provider bugs. Duplicates will still happen.' },
        { text: 'Turn off retries in the provider’s dashboard', why: 'Then you lose events whenever your server hiccups.' },
      ],
      answer: 0,
      explain: 'Assume at-least-once delivery, and make the effect happen once through idempotency.',
    },
    {
      id: 'm1-q5', kind: 'choice',
      prompt: 'You need to sync **2 million** orders from a table that receives new orders every second. Which pagination?',
      options: [
        { text: 'Cursor-based, with a checkpoint after each committed page', why: 'Yes. It stays stable while data changes, and it can resume after a crash.' },
        { text: 'Offset-based; it’s simpler', why: 'New rows shift the offsets, so you’d skip or duplicate orders.' },
        { text: 'Request all 2 million in one call', why: 'APIs cap page sizes, and one failure would lose everything.' },
        { text: 'Poll page 1 every minute', why: 'You’d never reach the older records.' },
      ],
      answer: 0,
      explain: 'Big + changing + must not miss anything = cursor + checkpoint + idempotent writes.',
    },
    {
      id: 'm1-q6', kind: 'choice',
      prompt: 'A webhook arrives with a **valid** signature, but its signed timestamp is **2 hours old**. What should you do?',
      options: [
        { text: 'Reject it; it could be a recorded webhook being replayed', why: 'Yes. A valid signature only proves it was genuine at some point.' },
        { text: 'Accept it; the signature is valid', why: 'Replay attacks use valid signatures. The timestamp check is what stops them.' },
        { text: 'Accept it, but process it later', why: 'Delaying doesn’t make a replayed event safe.' },
        { text: 'Retry the verification', why: 'It will give the same result.' },
      ],
      answer: 0,
      explain: 'Providers like Stripe sign each delivery attempt when they send it, so a legitimate retry carries a fresh timestamp. Your duplicate check by event ID covers the rest.',
    },
    {
      id: 'm1-q7', kind: 'choice',
      prompt: 'An API allows **100 requests/minute** and has a batch endpoint that takes 100 records per call. You need to update 6,000 contacts. Best plan?',
      options: [
        { text: 'Use the batch endpoint: about 60 calls, done in about a minute', why: 'Yes. Batching turns a 1-hour job into a 1-minute job, within the limit.' },
        { text: '6,000 single calls as fast as possible, retrying 429s', why: 'This hits the limit constantly and takes over an hour.' },
        { text: '6,000 single calls spread over 60 minutes', why: 'It works, but it’s 60× slower than it needs to be.' },
        { text: 'Run 10 workers in parallel', why: 'The rate limit is per account. More workers just means more 429s.' },
      ],
      answer: 0,
      explain: 'Read the docs for batch endpoints first. They’re the cheapest way to avoid rate limits.',
    },
    {
      id: 'm1-q8', kind: 'choice',
      prompt: 'Look at the timestamps. What’s the fix?',
      code: '10:00:00.002  worker-1  GET /orders → 503\n10:00:00.004  worker-2  GET /orders → 503\n10:00:00.005  worker-3  GET /orders → 503\n10:00:04.001  worker-1  retry → 503\n10:00:04.002  worker-2  retry → 503\n10:00:04.004  worker-3  retry → 503',
      options: [
        { text: 'Add jitter so the workers’ retries spread out', why: 'Yes. They’re retrying in lockstep, hitting the recovering server together.' },
        { text: 'Retry faster', why: 'That makes the stampede worse.' },
        { text: 'Stop retrying 503s', why: '503s are temporary. Retrying is right; the timing is the problem.' },
        { text: 'Add more workers', why: 'More synchronised retries means more load.' },
      ],
      answer: 0,
      explain: 'This is the thundering herd: identical backoff means identical timing.',
    },
    {
      id: 'm1-q9', kind: 'choice',
      prompt: 'In n8n you switch on **Retry On Fail** for an HTTP node that **creates** a HubSpot contact. What must also be true for this to be safe?',
      options: [
        { text: 'The step is idempotent (e.g. upsert by email or external ID), because a retry after a timeout could create a duplicate', why: 'Yes. Retries are only safe on idempotent actions.' },
        { text: 'Nothing; n8n handles duplicates automatically', why: 'n8n just re-sends the request. It doesn’t know if the first one worked.' },
        { text: 'The wait between tries is at least 5 seconds', why: 'The wait time doesn’t prevent duplicates.' },
        { text: 'The workflow uses the error workflow feature', why: 'Error workflows alert you; they don’t make creates safe to repeat.' },
      ],
      answer: 0,
      explain: 'Whenever you add a retry, ask: “If the first attempt actually worked, what does the second one do?”',
    },
    {
      id: 'm1-q10', kind: 'choice',
      prompt: 'Which **idempotency key** is best for charging order #981?',
      options: [
        { text: '`order-981-charge`', why: 'Yes. It’s the same on every retry and unique to this operation.' },
        { text: 'A new `uuid4()` on each attempt', why: 'A new key each attempt defeats the whole point.' },
        { text: 'The current timestamp', why: 'It changes between retries, so it gives no protection.' },
        { text: '`charge`', why: 'It’s the same for every order, so the second order would be treated as a duplicate.' },
      ],
      answer: 0,
      explain: 'A good key is stable across retries and unique per business operation.',
    },
    {
      id: 'm1-q11', kind: 'choice',
      prompt: 'A client wants an automation that **reads** incoming Gmail to triage support emails. Which OAuth scopes do you request?',
      options: [
        { text: 'Read-only access to mail', why: 'Yes. Least privilege: ask only for what the job needs.' },
        { text: 'Full mail access, in case you need to send replies later', why: 'Ask for more when you need it. Extra scopes add risk and reduce user trust.' },
        { text: 'Full Google account access', why: 'This is far beyond the task, and Google reviews sensitive scopes strictly.' },
        { text: 'No scopes; use an API key', why: 'Reading a user’s private mail requires their OAuth consent.' },
      ],
      answer: 0,
      explain: 'Least privilege limits the damage if a token leaks, or if an AI agent is tricked into misusing it.',
    },
    {
      id: 'm1-q12', kind: 'choice',
      prompt: 'Your token works for reading contacts, but `DELETE /contacts/42` returns **403**. Most likely?',
      options: [
        { text: 'The token lacks the scope or role for deleting', why: 'Yes. You’re authenticated (reads work) but not authorised for this action.' },
        { text: 'The token expired', why: 'An expired token would fail every call with 401, including reads.' },
        { text: 'Contact 42 doesn’t exist', why: 'That would normally be 404.' },
        { text: 'The API is rate-limiting you', why: 'That’s 429.' },
      ],
      answer: 0,
      explain: 'Fix it by adding the scope (the user must re-consent) or asking an admin for the role.',
    },
    {
      id: 'm1-q13', kind: 'choice',
      prompt: 'Two `subscription.updated` webhooks: *plan=basic* (sent at 10:00) arrives **after** *plan=pro* (sent at 10:01). Your database now says “basic”. The fix?',
      options: [
        { text: 'Only apply an event if it’s newer than what you’ve stored, or refetch the current subscription from the API', why: 'Yes. Never trust arrival order.' },
        { text: 'Process webhooks one at a time', why: 'The provider delivered them out of order; processing order can’t fix that.' },
        { text: 'Ask the provider to deliver in order', why: 'Most providers explicitly don’t guarantee order.' },
        { text: 'Ignore update events and only use created events', why: 'You’d miss every real change.' },
      ],
      answer: 0,
      explain: 'Store an `updated_at` or version per record and skip stale updates, or treat the webhook as a “something changed, go look” signal.',
    },
    {
      id: 'm1-q14', kind: 'choice',
      prompt: 'This runs **twice** (`external_id` has a UNIQUE constraint). What’s in the table afterwards?',
      code: "INSERT INTO contacts (external_id, email, name)\nVALUES ('cus_123', 'ana@example.com', 'Ana')\nON CONFLICT (external_id)\nDO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name;",
      options: [
        { text: 'One row for cus_123, with the latest values', why: 'Yes. The second run hits the conflict and updates instead of inserting.' },
        { text: 'Two rows for cus_123', why: 'The unique constraint makes that impossible.' },
        { text: 'An error on the second run', why: 'ON CONFLICT turns the error into an update.' },
        { text: 'Zero rows', why: 'Nothing here deletes anything.' },
      ],
      answer: 0,
      explain: '`EXCLUDED` refers to the row you tried to insert. This is the SQL version of “create or update”.',
    },
    {
      id: 'm1-q15', kind: 'choice',
      prompt: 'Your webhook handler calls an LLM (about 20 seconds) **before** replying. The provider times out at 10 seconds. What will you see?',
      options: [
        { text: 'Duplicate deliveries, and the provider may eventually disable your endpoint', why: 'Yes. Every slow reply looks like a failure to the provider.' },
        { text: 'Nothing; the LLM result is still saved', why: 'It might be saved several times, once per redelivery.' },
        { text: 'A 504 error in your logs only', why: 'The bigger effect is on the provider side: retries and endpoint health.' },
        { text: 'Faster processing next time', why: 'Nothing gets faster here.' },
      ],
      answer: 0,
      explain: 'This is the classic AI-automation mistake: putting the slow model call in the request path. Persist, acknowledge, then process in a worker.',
    },
  ],
  tasks: [
    { device: 'phone', plain: 'Learn the parts of an HTTP request and response well enough to explain them to a friend who doesn’t code.', done: 'You can explain methods, status code families, headers and timeouts without notes, and you’ve passed the Lesson 1 check.' },
    { device: 'computer', plain: 'Pick an API you’ve never used (Airtable, Notion, Trello…). Using only its docs, make a working request in curl, then rebuild it in n8n’s HTTP Request node, without the pre-built app node.', done: 'Your curl command and exported n8n workflow are saved in your repo, with a note on how authentication works for that API.' },
    { device: 'computer', plain: 'Write a sync that pages through an API and saves a checkpoint, so you can stop it halfway and it continues where it left off.', done: 'Kill it mid-run, restart it, and show that no records were skipped or duplicated.' },
    { device: 'phone', plain: 'Learn API keys, bearer tokens and the OAuth flow, including PKCE and refresh tokens.', done: 'You can draw the OAuth flow from memory, and you’ve passed the Lesson 3 check.' },
    { device: 'computer', plain: 'Connect one OAuth app (e.g. Google Sheets or HubSpot with your own OAuth client), then revoke its access from the provider’s settings page. Watch what breaks.', done: 'Notes on the exact error you got, and how your workflow should react (stop, then ask to reconnect).' },
    { device: 'phone', plain: 'Learn how webhooks behave: duplicates, wrong order, late delivery, signatures and replay attacks.', done: 'You can explain the verify → save → reply → process recipe, and you’ve passed the Lesson 4 check.' },
    { device: 'computer', plain: 'Build a small webhook receiver (n8n Webhook node or FastAPI) that checks the signature, saves the raw event, replies straight away, and processes it afterwards.', done: 'Send the same event twice and show it’s processed once. Send a tampered event and show it’s rejected.' },
    { device: 'phone', plain: 'Learn rate limits, Retry-After, exponential backoff, jitter, and which errors should never be retried.', done: 'You can sort any status code into “retry”, “don’t retry” or “needs fixing”, and you’ve passed the Lesson 5 check.' },
    { device: 'computer', plain: 'Make your sync safe to run twice, using a stable external ID (upsert) or an idempotency key.', done: 'Run it twice back to back. Record counts don’t change, and no duplicate side effects happen.' },
    { device: 'computer', plain: 'Break things on purpose: timeout, 429, 500, malformed JSON, duplicate webhook, expired token. Tip: `https://httpbin.org/status/429` returns any status code you ask for.', done: 'A table of each failure → what happened → whether that was the right behaviour.' },
    { device: 'phone', plain: 'Practise out loud: “An integration worked for months and suddenly returns 401. Walk me through your diagnosis.”', done: 'Record a 2–3 minute answer on your phone, then compare it with quiz question 1’s explanation.' },
  ],
};
