import type { Lesson } from './types';

export const m1: Lesson = {
  intro: "Most automation work is really integration: getting two systems that were never designed to work together to pass data reliably. Pre-built n8n nodes hide how that works until something breaks. This module shows what’s underneath, so you can connect any service from its documentation and know what to do when it fails.",
  sections: [
    {
      title: 'How systems talk: HTTP in plain English',
      minutes: 6,
      body: [
        "Every API call is a letter and a reply. Your automation sends a **request**; the other system sends back a **response**.",
        "A request has four parts:",
        "- **Method**: what you want to do. `GET` reads, `POST` creates, `PUT`/`PATCH` update, `DELETE` removes.\n- **URL**: where it goes, at a specific [[endpoint]], plus optional [[query parameters]] like `?page=2`.\n- **Headers**: labels on the envelope, such as who you are (`Authorization`) and what format you're sending (`Content-Type: application/json`).\n- **Body**: the actual data, usually [[JSON]]. GET requests normally don't have one.",
        "The response comes back with a [[status code]], a three-digit number saying what happened. You don't need to memorise them all, just the families:",
        "- **2xx: it worked.** 200 OK, 201 Created, 204 No Content.\n- **4xx: you did something wrong.** 400 bad data, 401 not logged in, 403 logged in but not allowed, 404 not found, 429 slow down.\n- **5xx: their server had a problem.** Often temporary, so often worth retrying.",
        "One thing beginners skip: [[timeout|timeouts]]. Without one, a request can hang for minutes and freeze your workflow. Always set one; 10–30 seconds is typical.",
        "Now the sneaky part. **A timeout doesn't mean “it failed”. It means “I don't know.”** The other system may have received your POST and created the record; the reply just never made it back. Remember this, because it's the reason the last lesson of this module exists.",
        "Reading the example below: `-X` sets the method, `-H` adds a header, `-d` is the body, `\\` continues the command on the next line, `$API_TOKEN` reads a saved variable, and `--max-time 20` gives up after 20 seconds. `Bearer` means “whoever holds this token”; lesson 3 covers it.",
      ],
      example: {
        caption: 'A real request in curl, with a timeout',
        code: 'curl -X POST https://api.example.com/v1/contacts \\\n  -H "Authorization: Bearer $API_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d \'{"email": "ana@example.com"}\' \\\n  --max-time 20',
      },
      interview: "I think about HTTP errors in families. 4xx means the request is wrong, so I fix it rather than retry it, except 429, which means back off and try later. 5xx and network errors are usually temporary and retryable with backoff. I always set explicit timeouts, and I treat a timeout on a write as an unknown outcome, not a failure.",
      check: [
        {
          id: 'm1-s0-1', kind: 'choice',
          prompt: 'Your workflow calls a CRM with a valid token and gets back **403 Forbidden**. What does that mean?',
          options: [
            { text: "Your token is valid, but it lacks the scope or role for this action", why: "Right. 403 means you’re authenticated but not authorised, usually a missing scope or role. Retrying won’t help." },
            { text: "Your token has expired, so the CRM wants you to log in again", why: "An expired or invalid token gives 401 Unauthorized. 403 means the CRM recognised you." },
            { text: "The CRM is blocking you for a while, so a retry later should work", why: "Temporary blocks are 429 (rate limit) or 503. 403 is a permissions decision that won’t change on retry." },
            { text: "The record you asked for doesn’t exist in the CRM at all", why: "A missing record is 404 Not Found. 403 is about what you’re allowed to do." },
          ],
          answer: 0,
          explain: '401 = “who are you?” 403 = “I know who you are, and the answer is no.” Fix 403 by granting the right permission or scope, not by retrying.',
        },
        {
          id: 'm1-s0-2', kind: 'choice',
          prompt: 'Which of these errors is usually worth retrying automatically?',
          options: [
            { text: "503 Service Unavailable, from a server that’s overloaded", why: "Yes. Their server is temporarily overloaded or restarting, so a retry a little later often works." },
            { text: "401 Unauthorized, since tokens sometimes fail to load at first", why: "Repeating the same request with the same token gets the same 401. You need a new or valid token." },
            { text: "400 Bad Request, since the body may have been garbled in transit", why: "The network protects the bytes in transit; 400 means the data itself is wrong, so a retry gets the same error." },
            { text: "404 Not Found, since the endpoint may be briefly unavailable", why: "An unavailable server returns 5xx. 404 means the URL or record doesn’t exist, and asking again won’t create it." },
          ],
          answer: 0,
          explain: '5xx (and timeouts, connection errors and 429) are temporary. Most other 4xx errors need you to change something first.',
        },
        {
          id: 'm1-s0-3', kind: 'choice',
          prompt: 'A `POST /invoices` request **times out** after 20 seconds. What do you know for certain?',
          options: [
            { text: "Nothing for certain: the invoice may or may not exist", why: "Correct. The request may have arrived and succeeded; only the reply was lost." },
            { text: "The invoice wasn’t created, since no reply ever came back", why: "Not necessarily. The server may have finished the work after your client gave up waiting." },
            { text: "The invoice was created, but the API was too slow to confirm", why: "Not necessarily. The request may never have reached the server." },
            { text: "It failed, so it’s safe to retry the POST without any checks", why: "A timeout is an unknown outcome, not a failure. A blind retry can create a second invoice." },
          ],
          answer: 0,
          explain: 'This “unknown outcome” is why blindly retrying writes can create duplicates. Lesson 6 (idempotency) is the fix.',
        },
      ],
    },
    {
      title: 'Reading API docs and paging through data',
      minutes: 7,
      body: [
        "Before building with a new API, read five parts of its docs: **authentication**, **the endpoint you need**, **pagination**, **rate limits** and **errors**. That's about 15 minutes, and it saves hours of guessing.",
        "[[Pagination]]: APIs never send you 50,000 records at once. They send a page, and you ask for the next one. There are two common styles:",
        "- **Offset / page number**: `?page=3&limit=100` or `?offset=200`. Simple, but if records are added or deleted while you're paging, everything shifts, and you can skip or duplicate records.\n- **Cursor**: each response includes a bookmark, like `next_cursor: \"abc123\"`, and you send it back to get the next page. This is more reliable for big or changing data. Stripe, Slack and HubSpot all work this way.",
        "You stop when the API says there's nothing more: `has_more: false`, no next cursor, or an empty page.",
        "[[Checkpoint|Checkpoints]]: imagine a 100,000-record sync crashes at record 63,284. Without a checkpoint, you start over. With one, you've saved “last finished cursor = X” in your database, and the next run resumes from there.",
        "The golden rule: **save the checkpoint only after that page's records are safely stored.** If you move the bookmark first and then crash, those records are skipped forever, because the next run thinks they're done.",
        "Don’t worry about reading every line of the Python below; it’s taught in the Python module. The point here is the order: store the page, *then* save the bookmark. `upsert_contacts` stores each record with an [[upsert]] (update it if it exists, insert it if not), so re-processing a page is harmless.",
      ],
      example: {
        caption: 'Cursor pagination with a safe checkpoint (Python)',
        code: '# None on the first run\ncursor = load_checkpoint()\n# keep going until we break out\nwhile True:\n    params = {"limit": 100, "cursor": cursor}\n    page = client.get("/contacts", params=params).json()\n    # 1. store the data first\n    upsert_contacts(page["results"])\n    cursor = page.get("next_cursor")\n    # 2. THEN move the bookmark\n    save_checkpoint(cursor)\n    # no next cursor: we’re done\n    if not cursor:\n        break',
      },
      interview: "I prefer cursor pagination for large or changing datasets, because offset pagination can skip or duplicate rows when the data shifts underneath you. I save a checkpoint only after each page is committed, so a crash resumes from the last durable position. And because the writes are upserts, replaying one page is harmless.",
      check: [
        {
          id: 'm1-s1-1', kind: 'order',
          prompt: 'Put the steps for processing **one page** of a sync in the safe order.',
          items: ['Request the page using the saved cursor', 'Store the page’s records', 'Save the new cursor as the checkpoint', 'Stop if there is no next cursor'],
          explain: 'Data first, bookmark second. If you crash between the two, you re-process one page (harmless if writes are upserts) instead of losing it.',
        },
        {
          id: 'm1-s1-2', kind: 'choice',
          prompt: 'You’re paging with `?offset=` through a contact list while a teammate deletes contacts on page 1. What can go wrong?',
          options: [
            { text: "Some contacts get skipped, as later rows shift into pages you’ve read", why: "Right. Record #101 moves to position #100, which you already “read”, so it’s never fetched." },
            { text: "Nothing changes, since each offset points at one specific contact", why: "Offsets are positions, not identities. When rows disappear, positions change." },
            { text: "The API returns 409 Conflict because the list changed mid-paging", why: "APIs don’t usually detect this. It fails silently, which is what makes it dangerous." },
            { text: "Some contacts appear twice, as deleted rows leave gaps to refill", why: "Deletions shift rows up, causing skips. Duplicates come from rows inserted near the top." },
          ],
          answer: 0,
          explain: 'Cursor pagination avoids this because the bookmark points at a specific record, not a position.',
        },
        {
          id: 'm1-s1-3', kind: 'choice',
          prompt: 'A sync saves the checkpoint, **then** writes the records, and crashes in between. What happens on the next run?',
          options: [
            { text: "Those records are skipped for good, as the checkpoint says they’re done", why: "Correct. The bookmark already points past them, so nothing ever writes them." },
            { text: "Those records are written twice, since the page is fetched again", why: "That’s the opposite mistake. The checkpoint has already moved past that page, so it isn’t fetched again." },
            { text: "The sync starts again from the beginning, as the last run didn’t finish", why: "No. The next run trusts the saved checkpoint and starts after it." },
            { text: "The API rejects the stale cursor, so the next run fails with an error", why: "The cursor is valid. The problem is your ordering, and it fails silently rather than with an error." },
          ],
          answer: 0,
          explain: 'Silent data loss is the worst failure because nothing alerts you. Store first, checkpoint second.',
        },
      ],
    },
    {
      title: 'Logging in: API keys, tokens and OAuth',
      minutes: 8,
      body: [
        "APIs need to know who's calling. There are three common ways:",
        "- **API key**: a long secret string sent in a header. Simple, but anyone who has it *is* you, so it lives on the server: in n8n credentials or environment variables, never in code that runs in a visitor’s browser, a screenshot or a GitHub repo.\n- **Bearer token**: `Authorization: Bearer <token>`. Same idea; “bearer” means whoever holds it gets in.\n- **[[OAuth]] 2.0**: used when your app acts *on behalf of a user* inside their account (their Gmail, their HubSpot). The user never gives you their password.",
        "How OAuth works, using a hotel as the analogy:",
        "1. You send the user to the provider's login page, asking for specific [[scopes]] (permissions), such as “read contacts”.\n2. The user logs in and clicks **Allow**.\n3. The provider sends them back to your app with a short-lived **authorization code**, like a claim ticket.\n4. Your server swaps that code for tokens.\n5. You receive an [[access token]], the room key card that works for about an hour, and a [[refresh token]], which gets you a new key card without bothering the user again.",
        "[[PKCE]] (pronounced “pixie”) adds a lock to steps 3–4. Your app makes up a random secret at the start and proves it during the swap, so a stolen claim ticket is useless. It's now recommended for every OAuth app.",
        "What actually breaks in real life:",
        "- **Access token expired**: normal. Use the refresh token.\n- **Refresh token revoked** (the user disconnected your app, an admin removed access, a password change, or the token went unused too long): retrying will never work. Stop the job and ask the user to reconnect.\n- **Two jobs refresh at the same moment**: some providers issue a new refresh token on every refresh and kill the old one, so one job ends up holding a dead token. Make sure only one process refreshes at a time.",
      ],
      interview: "For user-delegated access I use the OAuth authorization-code flow with PKCE, request the minimum scopes, and store tokens server-side, encrypted. I refresh before expiry and make sure only one process refreshes at a time, because some providers rotate refresh tokens. An `invalid_grant` on refresh is terminal: I pause the affected jobs and surface a reconnect action instead of retrying.",
      check: [
        {
          id: 'm1-s2-1', kind: 'choice',
          prompt: 'In the hotel analogy, what does the **refresh token** do?',
          options: [
            { text: "Gets a new access token without the user logging in again", why: "Exactly. It’s how automations keep working for months." },
            { text: "Goes in the Authorization header on every API call you make", why: "That’s the access token. The refresh token is only sent to the provider when asking for a new access token." },
            { text: "Proves to the provider that the user typed the right password", why: "Your app never sees the password; the user types it on the provider’s own page." },
            { text: "Lists which scopes the user approved, so you can add more later", why: "Scopes are approved at consent time. Getting more needs the user to consent again, not the refresh token." },
          ],
          answer: 0,
          explain: 'Access token = short-lived key card for API calls. Refresh token = long-lived way to get new key cards.',
        },
        {
          id: 'm1-s2-2', kind: 'choice',
          prompt: 'Your token refresh call returns `400 {"error": "invalid_grant"}`. What’s the best response?',
          options: [
            { text: "Pause the affected jobs and ask the user to reconnect the account", why: "Right. The grant is dead, and only the user can create a new one." },
            { text: "Retry the refresh with exponential backoff until the provider recovers", why: "invalid_grant isn’t an outage; the grant has been revoked or expired. You’d retry forever." },
            { text: "Keep using the last access token, since it may still have time left", why: "That only delays the failure by minutes, and the access token is often revoked along with the grant." },
            { text: "Ignore it for now, since the next scheduled run will refresh again", why: "It won’t work next time either, and meanwhile data silently stops syncing." },
          ],
          answer: 0,
          explain: 'Classify errors before retrying. Revoked access is a “needs a human” error, so make it visible.',
        },
        {
          id: 'm1-s2-3', kind: 'choice',
          prompt: 'Where should an API key for your n8n or Python automation live?',
          options: [
            { text: "In n8n credentials or server-side environment variables", why: "Yes. They’re kept out of code, out of logs and out of the browser." },
            { text: "In the workflow JSON, in a private repo only your team can see", why: "Private repos get cloned, shared and occasionally made public, and the key stays in git history forever." },
            { text: "In the agent’s system prompt, so it can call the API itself", why: "Never put secrets in prompts; models can be tricked into revealing them. Tools should hold credentials on the server." },
            { text: "In the site’s JavaScript, minified so visitors can’t read it", why: "Minifying isn’t hiding. Anyone can read code that runs in their own browser." },
          ],
          answer: 0,
          explain: 'Rule of thumb: if a human or a model can see it, assume it will leak.',
        },
      ],
    },
    {
      title: 'Webhooks: when the other system calls you',
      minutes: 8,
      body: [
        "**Polling** means you ask “anything new?” every 5 minutes. A [[webhook]] means the provider calls *your* URL the moment something happens. Webhooks are faster and cheaper, but you're now running a public URL that anyone on the internet can hit.",
        "Four facts about webhooks that every provider documents somewhere:",
        "1. **They can arrive more than once.** If you don't reply with a 2xx quickly, the provider assumes you missed it and sends it again.\n2. **They can arrive out of order.** “Subscription updated” can land before “subscription created”.\n3. **They can arrive late**, sometimes hours late, after an outage.\n4. **Anyone can fake one**, unless you check the [[signature]].",
        "**How signatures work.** You and the provider share a secret. With each webhook, the provider sends a fingerprint of the request body made with that secret (an [[HMAC]]). You calculate the same fingerprint yourself; if they match, the webhook is genuine and unmodified.",
        "Calculate it from the **raw body exactly as received**. If your framework parses the JSON and re-formats it first, even a changed space breaks the match.",
        "Many signatures include a timestamp. Reject old ones (for example, older than 5 minutes), so an attacker can't record a real webhook and send it again later. That's a [[replay attack]].",
        "The safe recipe:",
        "1. Verify the signature.\n2. Save the raw event in your database, keyed by the provider's event ID.\n3. Reply 200 immediately.\n4. Do the real work afterwards, in a background [[worker]].",
        "If the same event ID shows up again, a [[unique constraint]] in the database rejects it and you just reply 200 again, so nothing happens twice. For out-of-order events, don't trust arrival order: compare each object's updated time or version, or fetch the latest state from the API.",
      ],
      interview: "My webhook receiver verifies the HMAC against the raw body, checks the signed timestamp within a tolerance window, inserts the event under a unique key of provider, account and event ID, returns 2xx, and hands processing to a worker. Duplicates hit the constraint and are acknowledged without side effects. I don't rely on delivery order: I compare object versions or refetch current state.",
      check: [
        {
          id: 'm1-s3-1', kind: 'choice',
          prompt: 'Why reply 200 **before** doing the slow work (like an LLM call)?',
          options: [
            { text: "A slow reply looks like a failure, so the provider resends it", why: "Right. Slow handlers cause duplicate deliveries, and some providers disable endpoints that keep failing." },
            { text: "The provider needs exactly 200; other 2xx codes count as failures", why: "Any 2xx works. The point is replying quickly." },
            { text: "Replying early lets the provider send you the next event sooner", why: "Speed of the next event isn’t the issue; duplicate deliveries and the provider disabling your endpoint are." },
            { text: "It isn’t needed once you verify the signature, which blocks resends", why: "Signatures prove authenticity; they don’t stop the provider retrying a slow delivery." },
          ],
          answer: 0,
          explain: 'Many providers wait only a few seconds, and some disable endpoints that keep failing. Acknowledge fast, process later.',
        },
        {
          id: 'm1-s3-2', kind: 'choice',
          prompt: 'Your signature check fails on every webhook, even though the secret is definitely correct. Most likely cause?',
          options: [
            { text: "The body was parsed and re-serialised before you computed the HMAC", why: "Yes. You must sign the raw bytes, not your re-formatted JSON." },
            { text: "The webhooks are replays, so their signatures no longer match", why: "A replayed webhook still has a valid signature; that’s why you also check the timestamp. And “every webhook” points to your code." },
            { text: "HTTPS encrypts the body, so you must decrypt it before verifying", why: "Your server or proxy has already decrypted TLS. Your code sees the plain body." },
            { text: "The provider rotates the secret on every delivery for safety", why: "Secrets stay the same until someone rotates them. Changing per delivery would make verification impossible." },
          ],
          answer: 0,
          explain: 'In n8n, turn on the Webhook node’s raw body option. In FastAPI, read `await request.body()` before parsing.',
        },
        {
          id: 'm1-s3-3', kind: 'order',
          prompt: 'Put the webhook receiver steps in order.',
          items: ['Verify the signature', 'Save the raw event by its event ID', 'Reply with 2xx', 'Process it in a background worker'],
          explain: 'Verify → persist → acknowledge → process. Persisting before acknowledging means a crash never loses an event you said you received.',
        },
      ],
    },
    {
      title: 'Rate limits and retrying the right way',
      minutes: 7,
      body: [
        "Every API limits how fast you can call it (a [[rate limit]]). Go over it and you get **429 Too Many Requests**. The response often includes a `Retry-After` header saying exactly how many seconds to wait. Always obey it.",
        "When a call fails, ask one question: **will trying again help?**",
        "- **Yes, retry:** 429, 500, 502, 503, 504, timeouts, dropped connections. These are usually temporary.\n- **No, don't retry:** 400, 404, 422. Your data is wrong and will be wrong next time too. Send it to a review queue (a [[dead-letter queue]]).\n- **Retrying won't help, and it needs fixing:** 401/403. Re-authenticate or fix permissions.",
        "How to retry well:",
        "- [[Exponential backoff]]: wait 1s, then 2s, 4s, 8s… so you don't hammer a struggling server.\n- [[Jitter]]: add randomness. If 500 jobs all failed at the same moment and all retry at exactly 4 seconds, they knock the server over again together (the [[thundering herd]]).\n- **A maximum**: for example, 5 attempts. After that, mark the job failed and alert someone. Endless retries hide problems and burn through your rate limit.",
        "Prevention beats cure: use batch endpoints where the API offers them (one call for 100 records), and cap how many requests run at once ([[concurrency]]).",
        "Don’t worry about reading every line of the Python below; it’s taught in the Python module. The point here is: retry only the temporary errors, wait longer (with randomness) each time, obey `Retry-After`, and give up loudly after 5 attempts.",
      ],
      example: {
        caption: 'Backoff with “full jitter” (Python)',
        code: 'import random, time\n\nRETRYABLE = (429, 500, 502, 503, 504)\nfor attempt in range(5):\n    response = client.post(url, json=payload, timeout=20)\n    if response.status_code not in RETRYABLE:\n        break\n    # obey Retry-After if given, else a random wait up to 1, 2, 4, 8… s\n    retry_after = float(response.headers.get("Retry-After", 0))\n    backoff = random.uniform(0, min(60, 2 ** attempt))\n    time.sleep(retry_after or backoff)\nelse:\n    # ran out of attempts\n    mark_failed_and_alert(payload)',
      },
      interview: "I classify errors before retrying. 429, 5xx and network timeouts are retryable with capped exponential backoff and jitter, honouring Retry-After. Validation errors fail fast to a dead-letter queue. Auth errors trigger re-authentication. Retries are bounded and end in a visible failed state, and they're only safe because the operations are idempotent.",
      check: [
        {
          id: 'm1-s4-1', kind: 'choice',
          prompt: 'You get `429` with the header `Retry-After: 30`. What do you do?',
          options: [
            { text: "Wait at least 30 seconds, then retry the same request", why: "Yes. The API told you exactly what it needs." },
            { text: "Retry now with exponential backoff, starting at 1 second", why: "That ignores what the server told you. Early retries just collect more 429s and can get you blocked." },
            { text: "Mark the job failed, since 4xx means the request was wrong", why: "429 is the 4xx exception: it’s temporary. Failing it permanently loses work for no reason." },
            { text: "Rotate to a second API key so the work isn’t held up", why: "This usually breaks the provider’s terms, limits are often per account, and it can get the account banned." },
          ],
          answer: 0,
          explain: 'Retry-After beats your own backoff calculation, because the server knows its own limits.',
        },
        {
          id: 'm1-s4-2', kind: 'choice',
          prompt: 'Why add **jitter** (randomness) to retry delays?',
          options: [
            { text: "So clients that failed together don’t all retry at the same instant", why: "Exactly. It spreads the load out." },
            { text: "So retries finish faster on average than with a fixed schedule", why: "Speed isn’t the goal, and jitter can make an individual wait shorter or longer. Spreading the load is the point." },
            { text: "So the API can’t spot and block your automated retry pattern", why: "APIs don’t block predictable timing. The issue is synchronised load spikes." },
            { text: "So each retry picks a new connection instead of a stuck one", why: "Jitter only changes when you retry, not how you connect." },
          ],
          answer: 0,
          explain: 'Without jitter, failures that happened together retry together, and fail together again.',
        },
        {
          id: 'm1-s4-3', kind: 'choice',
          prompt: 'In a 500-record sync, one record gets `400 Bad Request: "email is invalid"`. Best handling?',
          options: [
            { text: "Send it to a review queue with the error, then carry on", why: "Yes. One bad record shouldn’t block 499 good ones, and it isn’t silently lost." },
            { text: "Retry it a few times with backoff in case the API glitched", why: "400 isn’t a glitch. The email will still be invalid on attempt 5." },
            { text: "Stop the whole sync so no partial data reaches the CRM", why: "Sometimes right for critical data, but usually too disruptive: 499 good records wait for one bad one." },
            { text: "Log a warning and skip it, since one record won’t matter", why: "A log line nobody reads is still silent data loss. Nobody will know it’s missing." },
          ],
          answer: 0,
          explain: 'Bad data needs a person or a fix, not another attempt. Make it visible and keep going.',
        },
      ],
    },
    {
      title: 'Idempotency: making it safe to run twice',
      minutes: 8,
      body: [
        "[[Idempotent]] means **doing something twice has the same effect as doing it once.** It's the single most important word in this module, and interviewers love it.",
        "Why it matters: retries, duplicate webhooks and crashed-then-restarted jobs mean **your code will sometimes run twice.** The only question is whether that creates two invoices, two CRM contacts or two emails to a customer.",
        "Three tools that make actions safe to repeat:",
        "1. [[Upsert]] **by a stable ID**: instead of “create contact”, do “create or update the contact whose external ID is `cus_123`”. Running it twice just updates the same record. In SQL this is `INSERT … ON CONFLICT`; many CRMs have a “create or update” endpoint.\n2. [[Idempotency key|Idempotency keys]]: some APIs (Stripe is the famous one) accept a header like `Idempotency-Key: order-981-charge`. If they see the same key again, they return the original result instead of charging twice. The key must stay **the same on every retry**, so build it from your data (the order ID), not a fresh random value each attempt.\n3. **A unique constraint in your own database**, so even if two workers grab the same event at the same moment, only one wins.",
        "Why “check whether it exists, then create” isn't enough: two workers can both check at the same millisecond, both see “not there”, and both create. That's a [[race condition]]. A database unique constraint is the only reliable referee.",
        "Remember the timeout from the first lesson? This is the answer. When a create times out and you don't know whether it worked, an idempotent retry is safe: either it creates the record, or it harmlessly finds the one that already exists.",
        "The example below is SQL, which the SQL module teaches. The point here: it says “insert this contact, but if `cus_123` already exists, update it instead”.",
      ],
      example: {
        caption: 'An upsert in Postgres: run it 10 times, still one row',
        code: "INSERT INTO contacts (external_id, email, name)\nVALUES ('cus_123', 'ana@example.com', 'Ana')\nON CONFLICT (external_id)\nDO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name;",
      },
      interview: "I design every side effect to be idempotent: upserts keyed on a stable external ID, provider idempotency keys derived from the business operation, and unique constraints as the final referee against races. That turns at-least-once delivery into effectively-once outcomes, and it's what makes retries and replays safe.",
      check: [
        {
          id: 'm1-s5-1', kind: 'choice',
          prompt: 'A Stripe charge request timed out. Which retry is safe?',
          options: [
            { text: "Retry with the same Idempotency-Key as the first attempt", why: "Yes. If the first one went through, Stripe returns that result instead of charging again." },
            { text: "Retry with a new Idempotency-Key, since the first attempt failed", why: "It may not have failed. A new key looks like a new charge, so the customer may pay twice." },
            { text: "Retry with no key, since Stripe spots identical charges itself", why: "Without a key, Stripe can’t tell a retry from a genuine second charge." },
            { text: "Don’t retry; tell the customer the payment failed and to pay again", why: "It may have succeeded. Telling them it failed can lead to a double payment." },
          ],
          answer: 0,
          explain: 'Build the key from the business operation (e.g. `order-981-charge`), so every retry of that operation uses the same key.',
        },
        {
          id: 'm1-s5-2', kind: 'choice',
          prompt: 'Why isn’t “check if the contact exists, and create it if not” enough to prevent duplicates?',
          options: [
            { text: "Two workers can both check before either one has created it", why: "Right. That’s a race condition, and only a unique constraint closes the gap." },
            { text: "The existence check is too slow once the contact list is large", why: "Speed isn’t the problem; the gap between check and create is." },
            { text: "Most APIs don’t support search, so the check can’t be trusted", why: "Most do. The issue is concurrency, not capability." },
            { text: "It is enough, as long as the check matches the exact email", why: "Exact matching doesn’t help when two copies run at the same moment." },
          ],
          answer: 0,
          explain: 'Concurrency bugs don’t show up in testing with one worker; they show up in production at scale.',
        },
        {
          id: 'm1-s5-3', kind: 'choice',
          prompt: 'Which of these actions is naturally **idempotent**?',
          options: [
            { text: "Set the contact’s status to “customer”", why: "Yes. Doing it twice leaves the same result." },
            { text: "Add 1 to the contact’s login count", why: "Twice = +2. Not idempotent." },
            { text: "Send the contact their welcome email", why: "Twice = two emails. You’d need to record that it was sent." },
            { text: "Append a “synced by bot” note to the deal", why: "Twice = two notes." },
          ],
          answer: 0,
          explain: '“Set to X” is idempotent; “add”, “append” and “send” are not, unless you track that they already happened.',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'm1-q1', kind: 'choice',
      prompt: 'An integration worked for months. Today every call fails. Read the log. What happened?',
      code: '02:00:01  POST /oauth/token  grant_type=refresh_token\n          → 400 {"error":"invalid_grant"}\n02:00:02  GET /v3/contacts?limit=100\n          → 401 Unauthorized\n02:05:02  GET /v3/contacts?limit=100\n          → 401 Unauthorized',
      options: [
        { text: "The refresh token was revoked, so no new access token could be issued", why: "Yes. invalid_grant on refresh is the root cause; the 401s are the symptom." },
        { text: "The contacts API is down, so every call after 02:00 fails with 401", why: "An outage would be 5xx, and the first error is on the token endpoint." },
        { text: "The token lost a scope, so it can no longer read the contacts endpoint", why: "A missing scope gives 403 on the contacts call, and the refresh itself would have succeeded." },
        { text: "The token endpoint is rate-limiting you, so the refresh was refused", why: "Rate limiting is 429. invalid_grant means the grant itself is no longer valid." },
      ],
      answer: 0,
      explain: 'Read logs from the first error, not the loudest one. Next steps: ask the account owner to reconnect, then alert on invalid_grant so you hear about it before the client does.',
    },
    {
      id: 'm1-q2', kind: 'order',
      prompt: 'Put the OAuth authorization-code flow (with PKCE) in order.',
      items: [
        'Send the user to the provider with the requested scopes and a PKCE challenge',
        'The user logs in and approves access',
        'The provider redirects back to your app with an authorization code',
        'Your server exchanges the code and the PKCE verifier for tokens',
        'Call the API with the access token, and refresh it when it expires',
      ],
      explain: 'The code is a claim ticket; the PKCE verifier proves that you are the one who asked for it.',
    },
    {
      id: 'm1-q3', kind: 'choice',
      prompt: 'What happens with this code when the server returns **429**?',
      code: 'for attempt in range(5):\n    r = requests.post(url, json=invoice, timeout=20)\n    if r.status_code < 500:\n        break\n    time.sleep(2 ** attempt)',
      options: [
        { text: "It breaks out as if it succeeded, so the invoice is silently lost", why: "Right. 429 is less than 500, so the code breaks out and treats it as done." },
        { text: "It retries with exponential backoff, waiting 1, 2, 4 and 8 seconds", why: "Only codes of 500 and above reach the sleep. 429 hits the break." },
        { text: "It waits for the Retry-After period, then sends the invoice again", why: "Nothing in this code reads Retry-After." },
        { text: "requests raises an HTTPError, which stops the run with a traceback", why: "requests doesn’t raise on error status codes unless you call raise_for_status()." },
      ],
      answer: 0,
      explain: 'Bugs like this pass happy-path testing. Check for success explicitly, and list the retryable codes (429, 500, 502, 503, 504) explicitly.',
    },
    {
      id: 'm1-q4', kind: 'choice',
      prompt: 'A provider delivers the same webhook **four times**. How do you guarantee only one business action?',
      options: [
        { text: "Store each event under a unique event ID; ack duplicates without acting", why: "Yes. The database constraint is the referee, and duplicates are harmless." },
        { text: "Check a Google Sheet for the event ID and skip it if it’s already there", why: "Check-then-act races when deliveries overlap, and Sheets has no unique constraints." },
        { text: "Reply within a second, so the provider never needs to resend the event", why: "Fast replies reduce duplicates but can’t stop them; network blips and provider bugs still cause resends." },
        { text: "Turn off retries in the provider’s dashboard so each event comes once", why: "Then you lose events whenever your server hiccups." },
      ],
      answer: 0,
      explain: 'Assume at-least-once delivery, and make the effect happen once through idempotency.',
    },
    {
      id: 'm1-q5', kind: 'choice',
      prompt: 'You need to sync **2 million** orders from a table that receives new orders every second. Which pagination?',
      options: [
        { text: "Cursor-based, saving a checkpoint after each committed page", why: "Yes. It stays stable while data changes, and it can resume after a crash." },
        { text: "Offset-based with a big page size, to finish before data shifts", why: "New orders arrive every second, so offsets shift during the sync and you skip or duplicate orders." },
        { text: "One request for all 2 million rows, so nothing changes mid-sync", why: "APIs cap page sizes, and one failure would lose everything." },
        { text: "Offset-based, newest first, so new orders always land on page 1", why: "Each new order pushes every row down a position, so you re-read rows and the sync never settles." },
      ],
      answer: 0,
      explain: 'Big + changing + must not miss anything = cursor + checkpoint + idempotent writes.',
    },
    {
      id: 'm1-q6', kind: 'choice',
      prompt: 'A webhook arrives with a **valid** signature, but its signed timestamp is **2 hours old**. What should you do?',
      options: [
        { text: "Reject it, since it could be a recorded webhook being replayed", why: "Yes. A valid signature only proves it was genuine at some point." },
        { text: "Accept it, since a valid signature proves the event is legitimate", why: "Replay attacks use valid signatures. The timestamp check is what stops them." },
        { text: "Accept it, since providers often retry deliveries hours after outages", why: "Providers like Stripe re-sign each retry with a fresh timestamp, so a 2-hour-old signature isn’t a normal retry." },
        { text: "Accept it but queue it, so it’s processed after newer events", why: "Delaying doesn’t make a replayed event safe." },
      ],
      answer: 0,
      explain: 'Providers like Stripe sign each delivery attempt when they send it, so a legitimate retry carries a fresh timestamp. Your duplicate check by event ID covers the rest.',
    },
    {
      id: 'm1-q7', kind: 'choice',
      prompt: 'An API allows **100 requests/minute** and has a batch endpoint that takes 100 records per call. You need to update 6,000 contacts. Best plan?',
      options: [
        { text: "Use the batch endpoint: about 60 calls, done in around a minute", why: "Yes. Batching turns a 1-hour job into a 1-minute job, within the limit." },
        { text: "Make 6,000 single calls as fast as possible and retry any 429s", why: "This hits the limit constantly and still takes over an hour." },
        { text: "Make 6,000 single calls, paced evenly across about an hour", why: "It works, but it’s 60× slower than it needs to be." },
        { text: "Spread single calls over 10 parallel workers to go 10× faster", why: "The rate limit is per account. More workers just means more 429s." },
      ],
      answer: 0,
      explain: 'Read the docs for batch endpoints first. They’re the cheapest way to avoid rate limits.',
    },
    {
      id: 'm1-q8', kind: 'choice',
      prompt: 'Look at the timestamps. What’s the fix?',
      code: '10:00:00.002  worker-1  GET /orders → 503\n10:00:00.004  worker-2  GET /orders → 503\n10:00:00.005  worker-3  GET /orders → 503\n10:00:04.001  worker-1  retry → 503\n10:00:04.002  worker-2  retry → 503\n10:00:04.004  worker-3  retry → 503',
      options: [
        { text: "Add random jitter so the workers’ retries spread out over time", why: "Yes. They’re retrying in lockstep, hitting the recovering server together." },
        { text: "Retry sooner, so requests land before the server gets busy again", why: "That makes the stampede worse and gives the server less time to recover." },
        { text: "Stop retrying 503s, since the server is clearly refusing them", why: "503s are temporary. Retrying is right; the timing is the problem." },
        { text: "Use a longer fixed backoff, such as 30 seconds for every worker", why: "Every worker still retries at the same instant, just later. The herd stays together." },
      ],
      answer: 0,
      explain: 'This is the thundering herd: identical backoff means identical timing.',
    },
    {
      id: 'm1-q9', kind: 'choice',
      prompt: 'In n8n you switch on **Retry On Fail** for an HTTP node that **creates** a HubSpot contact. What must also be true for this to be safe?',
      options: [
        { text: "The create is idempotent, e.g. an upsert by email or external ID", why: "Yes. If a timed-out first attempt actually worked, the retry updates instead of duplicating." },
        { text: "Nothing; n8n skips the retry if the first request reached HubSpot", why: "n8n just re-sends the request. It can’t know if a timed-out attempt worked." },
        { text: "The wait between tries is long enough for HubSpot to finish saving", why: "The wait time doesn’t prevent duplicates; the retry still creates a second contact." },
        { text: "An error workflow is set up to catch failures after the last retry", why: "Error workflows alert you; they don’t make creates safe to repeat." },
      ],
      answer: 0,
      explain: 'Whenever you add a retry, ask: “If the first attempt actually worked, what does the second one do?”',
    },
    {
      id: 'm1-q10', kind: 'choice',
      prompt: 'Which **idempotency key** is best for charging order #981?',
      options: [
        { text: "`order-981-charge`, built from the order", why: "Yes. It’s the same on every retry and unique to this operation." },
        { text: "A fresh `uuid4()` generated on each attempt", why: "A new key each attempt defeats the whole point." },
        { text: "The current timestamp in milliseconds", why: "It changes between retries, so it gives no protection." },
        { text: "`charge`, the same for every payment", why: "It’s the same for every order, so order #982 would be treated as a duplicate of #981." },
      ],
      answer: 0,
      explain: 'A good key is stable across retries and unique per business operation.',
    },
    {
      id: 'm1-q11', kind: 'choice',
      prompt: 'A client wants an automation that **reads** incoming Gmail to triage support emails. Which OAuth scopes do you request?',
      options: [
        { text: "Read-only mail access, the least the triage job needs", why: "Yes. Least privilege: ask only for what the job needs." },
        { text: "Full mail access, so you can add auto-replies later", why: "Ask for more when you need it. Extra scopes add risk and reduce user trust." },
        { text: "Full account access, so one consent screen covers all", why: "This is far beyond the task, and Google reviews sensitive scopes strictly." },
        { text: "No scopes; a Google API key can read the inbox", why: "API keys identify your project, not a user. Reading someone’s private mail requires their OAuth consent." },
      ],
      answer: 0,
      explain: 'Least privilege limits the damage if a token leaks, or if an AI agent is tricked into misusing it.',
    },
    {
      id: 'm1-q12', kind: 'choice',
      prompt: 'Your token works for reading contacts, but `DELETE /contacts/42` returns **403**. Most likely?',
      options: [
        { text: "The token lacks the scope or role needed to delete contacts", why: "Yes. You’re authenticated (reads work) but not authorised for this action." },
        { text: "The token expired between the read and the delete request", why: "An expired token gives 401, not 403." },
        { text: "Contact 42 was already deleted, so there’s nothing to remove", why: "A missing record would normally be 404." },
        { text: "Deletes are rate-limited more strictly than reads on this API", why: "Rate limiting is 429, not 403." },
      ],
      answer: 0,
      explain: 'Fix it by adding the scope (the user must re-consent) or asking an admin for the role.',
    },
    {
      id: 'm1-q13', kind: 'choice',
      prompt: 'Two `subscription.updated` webhooks: *plan=basic* (sent at 10:00) arrives **after** *plan=pro* (sent at 10:01). Your database now says “basic”. The fix?',
      options: [
        { text: "Apply an event only if it’s newer than what’s stored, or refetch", why: "Yes. Never trust arrival order; compare versions or ask the API for the current state." },
        { text: "Process webhooks one at a time through a single-worker queue", why: "The provider delivered them out of order; processing them one by one keeps the wrong order." },
        { text: "Ask the provider to guarantee in-order delivery to your endpoint", why: "Most providers explicitly don’t guarantee order." },
        { text: "Use arrival time as updated_at, so the latest arrival always wins", why: "That’s exactly the bug: the latest arrival here is the oldest event." },
      ],
      answer: 0,
      explain: 'Store an `updated_at` or version per record and skip stale updates, or treat the webhook as a “something changed, go look” signal.',
    },
    {
      id: 'm1-q14', kind: 'choice',
      prompt: 'This runs **twice** (`external_id` has a UNIQUE constraint). What’s in the table afterwards?',
      code: "INSERT INTO contacts (external_id, email, name)\nVALUES ('cus_123', 'ana@example.com', 'Ana')\nON CONFLICT (external_id)\nDO UPDATE SET email = EXCLUDED.email, name = EXCLUDED.name;",
      options: [
        { text: "One row for cus_123, holding the values from the latest run", why: "Yes. The second run hits the conflict and updates instead of inserting." },
        { text: "Two rows, since UNIQUE only blocks duplicates within one statement", why: "A unique constraint applies to the whole table, across every statement. Two rows can never exist." },
        { text: "One row, and the second run fails with a unique-violation error", why: "A plain INSERT would. ON CONFLICT turns the conflict into an update." },
        { text: "Zero rows, as the conflict rolls back the first insert as well", why: "The first run was already committed, and nothing here deletes anything." },
      ],
      answer: 0,
      explain: '`EXCLUDED` refers to the row you tried to insert. This is the SQL version of “create or update”.',
    },
    {
      id: 'm1-q15', kind: 'choice',
      prompt: 'Your webhook handler calls an LLM (about 20 seconds) **before** replying. The provider times out at 10 seconds. What will you see?',
      options: [
        { text: "Duplicate deliveries, and the provider may disable your endpoint", why: "Yes. Every slow reply looks like a failure to the provider, so it resends." },
        { text: "Nothing visible; the provider waits until your handler finishes", why: "It gives up at 10 seconds and treats the delivery as failed." },
        { text: "One 504 in your logs, and that event is simply lost for good", why: "The provider retries failed deliveries, so the event isn’t lost; it arrives again, and may be processed several times." },
        { text: "The provider marks it failed once and never sends it again", why: "Providers retry failed deliveries, usually several times with backoff." },
      ],
      answer: 0,
      explain: 'This is the classic AI-automation mistake: putting the slow model call in the request path. Persist, acknowledge, then process in a worker.',
    },
  ],
  tasks: [
    { device: 'phone', plain: 'Learn the parts of an HTTP request and response well enough to explain them to a friend who doesn’t code.', done: 'You can explain methods, status code families, headers and timeouts without notes, and you’ve passed the Lesson 1 check.' },
    { device: 'computer', plain: 'Pick an API you’ve never used (Airtable, Notion, Trello…). Using only its docs, make a working request in curl, then rebuild it in n8n’s HTTP Request node, without the pre-built app node.', done: 'Your curl command and exported n8n workflow are saved in your repo, with a note on how authentication works for that API.' },
    { device: 'computer', plain: 'Write a sync that pages through an API and saves a checkpoint, so you can stop it halfway and it continues where it left off.', done: 'Kill it mid-run, restart it, and show that no records were skipped or duplicated.' },
    { device: 'phone', plain: 'Learn API keys, bearer tokens and the OAuth flow, including PKCE and refresh tokens.', done: 'You can draw the OAuth flow from memory, and you’ve passed the Lesson 3 check.' },
    { device: 'computer', plain: 'Connect one OAuth app (e.g. Google Sheets or HubSpot with your own OAuth client), then revoke its access from the provider’s settings page. Watch what breaks.', done: 'Notes on the exact error you got, and how your workflow should react (stop, then ask to reconnect).' },
    { device: 'phone', plain: 'Learn how webhooks behave: duplicates, wrong order, late delivery, signatures and replay attacks.', done: 'You can explain the verify → save → reply → process recipe, and you’ve passed the Lesson 4 check.' },
    { device: 'computer', plain: 'Build a small webhook receiver (n8n Webhook node or FastAPI) that checks the signature, saves the raw event, replies straight away, and processes it afterwards.', done: 'Send the same event twice and show it’s processed once. Send a tampered event and show it’s rejected.' },
    { device: 'phone', plain: 'Learn rate limits, Retry-After, exponential backoff, jitter, and which errors should never be retried.', done: 'You can sort any status code into “retry”, “don’t retry” or “needs fixing”, and you’ve passed the Lesson 5 check.' },
    { device: 'computer', plain: 'Make your sync safe to run twice, using a stable external ID (upsert) or an idempotency key.', done: 'Run it twice back to back. Record counts don’t change, and no duplicate side effects happen.' },
    { device: 'computer', plain: 'Break things on purpose: timeout, 429, 500, malformed JSON, duplicate webhook, expired token. Tip: `https://httpbin.org/status/429` returns any status code you ask for.', done: 'A table of each failure → what happened → whether that was the right behaviour.' },
    { device: 'phone', plain: 'Practise out loud: “An integration worked for months and suddenly returns 401. Walk me through your diagnosis.”', done: 'Record a 2–3 minute answer on your phone, then compare it with quiz question 1’s explanation.' },
  ],
};
