import type { Lesson } from './types';

export const m14: Lesson = {
  intro: "Being able to build isn’t enough if you can’t explain it under pressure. Interviewers want to hear how you think: how you handle a vague request, design for failure, debug from evidence and admit what you don’t know. This module turns the systems you built in earlier modules into clear interview answers, with a repeatable structure for each type of question.",
  glossary: {
    'recruiter screen': 'A short first call with a recruiter, usually 15–30 minutes, checking basic fit, salary range and availability. Not technical.',
    'take-home': 'A small project you build in your own time and submit, often followed by a call where you walk through it.',
    'system design': 'Planning how the pieces of a system fit together: what triggers it, where data lives, and what happens when things fail.',
    'behavioural interview': 'Questions about how you acted in past situations, e.g. “Tell me about a time something broke.”',
    'star': 'Situation, Task, Action, Result: the common name for a structured story about your past work.',
    'source of truth': 'The one system whose copy of the data wins when systems disagree.',
    'happy path': 'What happens when everything works as expected, with no errors.',
    'hypothesis': 'Your best guess at the cause of a problem, stated so that evidence can prove or disprove it.',
    'edge case': 'An unusual input that often breaks code: an empty list, a missing field, a duplicate.',
    'group by': 'SQL that bundles rows sharing a value, so you can count or sum per group, e.g. leads per source.',
    'failure log': 'Your own list of interview questions you answered badly, with what you missed, the fix and a date to retest.',
  },
  sections: [
    {
      title: 'What AI automation interviews actually look like',
      minutes: 5,
      body: [
        "**The problem.** You’ve built real automations, but an interview is a different skill: explaining your work clearly to strangers, on a clock. Knowing what each stage tests lets you prepare for the right thing instead of everything.",
        "Most hiring processes for these roles use some mix of these stages. Not every company uses all of them, and the order varies.",
        "- **[[Recruiter screen]]** (15–30 min): are you a plausible fit? Expect your intro, why this role, salary expectations and availability.\n- **Technical screen** (45–60 min): an engineer asks rapid questions (webhooks, OAuth, n8n, SQL, LLMs) or sets a short coding task. Tests whether your knowledge is real.\n- **[[Take-home]]**: build something small in a few hours, then walk through it. Tests whether you finish, test and explain.\n- **[[System design]]**: “Design a lead intake system.” Tests how you handle a vague request and plan for failure.\n- **[[Behavioural interview|Behavioural]]**: “Tell me about a time…” Tests ownership, communication and how you handle problems and people.\n- **Demo**: some companies ask you to show a project. Have a 90-second and a 6-minute version ready.",
        "**What they reward.** Clear trade-off thinking and calm debugging beat jargon. The strongest evidence sounds like: **here’s what I built, here’s what broke, here’s how I measured it, here’s what I changed.**",
        "**Take-home tips.** Ask how long they expect it to take and stay close to that. Include a README with setup steps, the assumptions you made and what you’d do with more time. A small, tested, working solution beats a big unfinished one.",
        "**Your study material is your own work.** Your project READMEs, incident reports and failure tests from earlier modules are what you’ll draw on at every stage.",
      ],
      interview: "Early in a process I ask what each round focuses on, so I can prepare properly. In a take-home I keep to the requested scope, state my assumptions in the README, and list what I’d add with more time, such as extra failure tests or monitoring.",
      check: [
        {
          id: 'm14-s0-1', kind: 'choice',
          prompt: 'A take-home brief says “expected time: about 3 hours”. You have ideas for three extra features. What’s the strongest submission?',
          options: [
            { text: 'A small working solution with tests, plus a README listing assumptions and what you’d add next', why: 'Yes. It shows you finish, test and communicate, which is what a take-home measures.' },
            { text: 'All three extra features, even if it takes three days', why: 'Ignoring the time box suggests poor scoping, and extra features rarely make up for that.' },
            { text: 'The core feature only, with no README', why: 'Without a README the reviewer can’t run it or see your reasoning.' },
            { text: 'A half-finished version of all the features', why: 'Unfinished work is weaker than a small complete one.' },
          ],
          answer: 0,
          explain: 'Scope it, finish it, test it, explain it. “With more time I’d…” is a strength, not an admission.',
        },
        {
          id: 'm14-s0-2', kind: 'choice',
          prompt: 'Which stage is mainly testing how you handle a vague request and plan for failures?',
          options: [
            { text: 'System design', why: 'Right. The request is deliberately vague, and failure handling is where strong answers stand out.' },
            { text: 'Recruiter screen', why: 'That checks basic fit, salary and availability.' },
            { text: 'Behavioural', why: 'That’s about how you acted in past situations.' },
            { text: 'Live coding', why: 'That tests a small, well-defined task.' },
          ],
          answer: 0,
          explain: 'Know what each stage measures and prepare for that, not for everything at once.',
        },
      ],
    },
    {
      title: 'Your 90-second intro and stories about your work',
      minutes: 6,
      body: [
        "**The problem.** “Tell me about yourself” and “Tell me about a time…” come up in almost every interview. Without a plan, people ramble through their whole CV or give vague answers with no result.",
        "**The 90-second intro** has four parts, about 20 seconds each:",
        "1. **Now:** what you do today, in automation terms.\n2. **Proof:** one or two systems you built and owned, with a result you can back up.\n3. **Growth:** the technical step you’ve taken recently (Python, Postgres, deployment, evals).\n4. **Why here:** why this role is the logical next step.",
        "**Stories about your work.** Interviewers often call this [[STAR]]. Use four beats: **problem → what you owned → result → what you learned.** Say “I” for the parts you did, not “we”. Keep each story to about two minutes.",
        "Prepare five: a production failure, a difficult integration, an ambiguous request, a disagreement with a stakeholder, and learning something fast. One story can often be adapted to several questions.",
        "**Only use results you can support.** “The ops team says manual entry dropped from about two hours a day to a few minutes” is fine if they said it. If nobody measured, describe scope honestly: “it handles every inbound lead for a six-person sales team”. Never invent a number; the follow-up question will expose it.",
      ],
      example: {
        caption: 'A worked story: a production failure (swap in your own)',
        code: "PROBLEM   Our lead webhook sometimes created the same HubSpot contact\n          twice. Sales called people twice; CRM reports were wrong.\nOWNED     I owned the n8n workflow. In the execution history I found the\n          form tool retried when we replied slowly, so we got duplicates.\n          I made it reply immediately and process afterwards, and changed\n          “create contact” to an upsert keyed on email.\nRESULT    No duplicates in the next month (I checked weekly with a query).\n          Sales stopped reporting double calls.\nLEARNED   Webhooks can arrive more than once. Now I make every write\n          safe to repeat before anything goes live.",
      },
      interview: "I keep stories short and specific: the problem and its impact, exactly what I owned, the result and how I know it, and what I changed in how I work. I say “we” for the team and “I” for my own decisions, so the interviewer can see my contribution.",
      check: [
        {
          id: 'm14-s1-1', kind: 'choice',
          prompt: 'You never measured how much time your workflow saved. Which result line is strongest?',
          options: [
            { text: '“It now handles all inbound leads for the sales team, so nobody types them in by hand any more.”', why: 'Yes. Honest scope and a concrete change you can defend.' },
            { text: '“It saved the company about 40% of admin time.”', why: 'An invented figure. “How did you measure that?” ends the story badly.' },
            { text: '“It was a big success and everyone loved it.”', why: 'Vague. There’s nothing the interviewer can assess.' },
            { text: '“We built an amazing system together.”', why: 'Vague, and “we” hides what you actually did.' },
          ],
          answer: 0,
          explain: 'No measurement? Use scope, volume or a concrete before-and-after. Never a made-up percentage.',
        },
        {
          id: 'm14-s1-2', kind: 'order',
          prompt: 'Put the beats of a work story in order.',
          items: ['The problem and its impact', 'What you owned and did', 'The result, and how you know it', 'What you learned or now do differently'],
          explain: 'Problem → owned → result → learned. The last beat is what makes it sound like growth, not luck.',
        },
      ],
    },
    {
      title: 'A repeatable checklist for system design answers',
      minutes: 7,
      body: [
        "**The problem.** “Design a system that handles inbound leads” is deliberately vague. Weak answers jump straight to tools (“I’d use n8n and HubSpot”). Strong answers ask questions first, then walk through the **same checklist every time**, so nothing is forgotten under pressure.",
        "**The checklist.** Say each step out loud:",
        "1. **Requirements:** who uses it, how much traffic, how fast it must be, what loss is acceptable, which actions are risky.\n2. **Data flow:** trigger → steps → where results land. Name the [[source of truth]].\n3. **Data model:** the main tables and their unique keys.\n4. **[[Happy path]]:** one record, start to finish.\n5. **Duplicates and retries:** what if the event arrives twice, or a call times out?\n6. **Auth and security:** who can call it, where secrets live, what personal data you keep.\n7. **Scale:** what breaks at 10× the traffic. Usually [[rate limit|rate limits]] and slow steps.\n8. **Monitoring:** how you’ll know it’s broken before the client does.\n9. **Cost:** LLM calls, API plans, hosting, and where you’d save.",
        "**State assumptions** instead of inventing requirements: “I’ll assume about 1,000 leads a day; tell me if it’s much more.” Then spend most of your time on **failures and recovery**, not boxes and arrows.",
        "Practise the checklist on ten systems: lead intake, ticket triage, document extraction, a RAG assistant, reporting, a two-way sync, an agent, a bulk migration, a webhook platform and a multi-tenant SaaS.",
      ],
      example: {
        caption: 'The checklist applied to lead intake',
        code: "REQUIREMENTS  Form leads → CRM within 5 min. ~1,000/day (assumed).\n              No lead lost. Risky action: auto-emailing the lead.\nDATA FLOW     Webhook → verify signature → save event → reply 200\n              → queue → worker: enrich, LLM score, rules → CRM upsert\n              Source of truth for leads: the CRM. For events: our DB.\nDATA MODEL    events(tenant_id, event_id, payload, status, attempts)\n                unique on (tenant_id, event_id)\n              leads(email unique, score, crm_id)\nHAPPY PATH    One lead: saved, enriched, scored, upserted, Slack ping\nRETRIES       Same webhook twice → unique key rejects the copy\n              CRM 429 → backoff + jitter, max 5 tries, then\n              dead-letter queue + alert\nSECURITY      Verify signature; secrets in env vars; no lead data in logs\nSCALE         Add workers, but the CRM rate limit caps throughput\nMONITORING    Success rate, oldest job in queue, dead-letter count,\n              heartbeat for the scheduled clean-up job\nCOST          Rules first; LLM only for unclear leads; cheaper model\n              by default",
      },
      interview: "I clarify requirements and state assumptions, then sketch the data flow and name the source of truth. Most of my time goes on failure modes: idempotent intake on a unique event key, bounded retries with backoff and jitter, a dead-letter queue, and the metrics and alerts that show it’s healthy. I finish with scaling limits and cost trade-offs.",
      check: [
        {
          id: 'm14-s2-1', kind: 'choice',
          prompt: 'The interviewer says: “Design a support-ticket triage system.” What’s your strongest first move?',
          options: [
            { text: 'Ask about volume, speed, which actions are risky and what loss is acceptable, then state your assumptions', why: 'Yes. Requirements first; everything else depends on them.' },
            { text: 'Name the tools: n8n, OpenAI and Zendesk', why: 'Tools before requirements means you might design the wrong system.' },
            { text: 'Explain how it would scale to millions of tickets', why: 'You don’t know the volume yet. That might be irrelevant.' },
            { text: 'Draw the full architecture in silence', why: 'The interviewer can’t score reasoning they can’t hear, and you skipped requirements.' },
          ],
          answer: 0,
          explain: 'Clarify, assume out loud, then design. Interviewers often hold back details to see whether you ask.',
        },
        {
          id: 'm14-s2-2', kind: 'choice',
          prompt: 'A candidate’s whole design is: “Form → n8n → LLM scores it → create HubSpot contact → Slack.” Which checklist item is the biggest gap?',
          options: [
            { text: 'Duplicates and retries: nothing stops a repeated webhook creating two contacts', why: 'Right. Webhooks can arrive more than once, and “create” isn’t safe to repeat.' },
            { text: 'Cost: the LLM might be expensive', why: 'Worth a mention later, but duplicate contacts break the business first.' },
            { text: 'The choice of HubSpot over another CRM', why: 'Tool choice isn’t what’s missing; failure handling is.' },
            { text: 'It needs more Slack notifications', why: 'More notifications don’t fix the reliability gap.' },
          ],
          answer: 0,
          explain: 'A happy-path-only answer is the most common weak design. Always say what happens when things repeat or fail.',
        },
        {
          id: 'm14-s2-3', kind: 'choice',
          prompt: 'You add more workers to the lead system, but leads per minute don’t go up. What’s the most likely limit?',
          options: [
            { text: 'The CRM’s rate limit', why: 'Yes. More workers can’t make the provider accept more requests.' },
            { text: 'Not enough workers yet', why: 'If adding workers didn’t help, the bottleneck is somewhere else.' },
            { text: 'The webhook signature check', why: 'That’s a fast, local check.' },
            { text: 'The size of the events table', why: 'A modest table with the right index won’t cap throughput like this.' },
          ],
          answer: 0,
          explain: 'In automation, the slowest external API usually sets the speed limit. Say so in your scale step.',
        },
      ],
    },
    {
      title: 'Debugging out loud from logs',
      minutes: 6,
      body: [
        "**The problem.** In a debugging question you get a symptom (“leads stopped reaching the CRM”) and sometimes some logs. Many candidates go quiet, then guess: “Maybe restart the server?” The interviewer can’t score thinking they can’t hear.",
        "**The loop. Say each step out loud:**",
        "1. **Symptom:** restate exactly what’s wrong, and since when.\n2. **Last good state:** where did a record last look correct? Follow one record’s ID through each system.\n3. **[[Hypothesis]]:** “I think the token expired, because…”\n4. **Evidence:** what would prove or disprove it? Which log, which query?\n5. **Smallest safe test:** change one thing, ideally not in production first.\n6. **Fix and prevent:** fix it, then add the check or alert that would have caught it sooner.",
        "**Change one thing at a time.** If you change three settings and it starts working, you don’t know which one fixed it, or whether the others broke something else.",
        "**Reading the example log.** The webhook arrived and was saved, so intake is fine. The CRM call fails with `401`: the credentials were rejected. A 401 isn’t temporary, so retrying won’t help, and jobs pile up behind it. Hypothesis: the CRM token expired or was revoked. Evidence: when was the credential last refreshed, and did anyone change the CRM app’s permissions? Prevention: alert on the first 401 and show a “reconnect” action instead of retrying.",
      ],
      example: {
        caption: 'A log you might be shown',
        code: "10:02:11 lead L-311 webhook received, signature ok\n10:02:11 lead L-311 saved, queued\n10:02:14 lead L-311 crm.upsert → 401 Unauthorized\n10:02:44 lead L-311 retry 1 → 401 Unauthorized\n10:03:44 lead L-311 retry 2 → 401 Unauthorized\n10:03:45 queue depth: 214 (rising)",
      },
      interview: "I start from the symptom and the last known good state, then trace one correlation ID across the system boundaries. I state a hypothesis and the evidence that would confirm it, run the smallest safe test, and change one variable at a time. Once it’s fixed, I add the alert or check that would have caught it earlier.",
      check: [
        {
          id: 'm14-s3-1', kind: 'choice',
          prompt: 'In the example log, what’s the strongest next step?',
          options: [
            { text: 'Stop retrying, check whether the CRM token expired or was revoked, then reconnect', why: 'Yes. 401 means the credentials were rejected; retries can’t fix that.' },
            { text: 'Increase the retry count to 10', why: 'Every retry will get the same 401, and the queue keeps growing.' },
            { text: 'Treat it as a rate limit and slow down', why: 'A rate limit returns 429, not 401.' },
            { text: 'Fix the webhook signature check', why: 'The log shows the signature passed and the lead was saved.' },
          ],
          answer: 0,
          explain: 'Read where it last worked (saved, queued) and where it first failed (CRM 401). The gap tells you where to look.',
        },
        {
          id: 'm14-s3-2', kind: 'choice',
          prompt: 'You change the timeout, the retry count and the node version at once, and the workflow starts working. What’s the problem?',
          options: [
            { text: 'You don’t know which change fixed it, or whether another one caused a new issue', why: 'Right. Change one thing at a time so you learn the cause.' },
            { text: 'Nothing; it works now', why: 'Without knowing the cause, it may come back, and you can’t explain it.' },
            { text: 'You should have restarted the server too', why: 'That would add a fourth unknown.' },
            { text: 'Node versions can’t affect workflows', why: 'They can. That’s one reason to test changes one by one.' },
          ],
          answer: 0,
          explain: 'In an interview, “I’d change one thing and check” is a strong signal of a calm debugger.',
        },
        {
          id: 'm14-s3-3', kind: 'choice',
          prompt: 'The Monday report didn’t arrive and no error alert fired. What do you check first?',
          options: [
            { text: 'Whether the workflow ran at all: the scheduler and the execution history', why: 'Yes. No error often means it never started.' },
            { text: 'The email template’s formatting', why: 'That matters only if it ran and sent something.' },
            { text: 'Switching to a better LLM', why: 'Nothing points to the model.' },
            { text: 'Adding more error alerts', why: 'A job that never starts produces no error to alert on.' },
          ],
          answer: 0,
          explain: 'Then prevent it with a heartbeat check that expects a success signal on schedule.',
        },
      ],
    },
    {
      title: 'Live coding: small Python and SQL tasks',
      minutes: 7,
      body: [
        "**The problem.** Live coding feels scary because someone is watching. For automation roles the tasks are usually small and practical: clean a list, remove duplicates, group and count, page through an API, write a JOIN. They’re watching **how you approach it** more than perfect syntax.",
        "**A routine for every task:**",
        "1. **Restate it** and ask about inputs: “Can emails have different capitals? Can the list be empty?”\n2. **Write one example** input and the output you expect.\n3. **Simplest working version first.** No classes, no frameworks.\n4. **Talk while you type:** “I’m using a set because checking if something’s in it is fast.”\n5. **Test an [[edge case]]:** empty input, a missing field, a duplicate.\n6. **Say what you’d improve** with more time.",
        "**The Python example** removes duplicate leads by email and keeps the first one. Notice the cleaning step: `' Ana@X.com'` and `'ana@x.com'` are the same person.",
        "**For SQL**, practise JOINs, [[group by|GROUP BY]], CTEs (`WITH` blocks that name a step), window functions and upserts on your own event data. A typical question: “Which source sent the most leads last week?”",
        "**Practise without an AI assistant**, with a timer. Aim for about 20 Python and 20 SQL exercises. If you get stuck, say what you’re stuck on. Silence is worse than a wrong first attempt.",
      ],
      example: {
        caption: 'Python: dedupe leads by email. SQL: leads per source',
        code: "def dedupe_leads(leads):\n    seen = set()                 # emails we've already kept\n    result = []\n    for lead in leads:\n        email = (lead.get('email') or '').strip().lower()  # clean; missing → ''\n        if not email or email in seen:\n            continue                 # skip blanks and repeats\n        seen.add(email)\n        result.append(lead)          # keep the first one we see\n    return result\n\n-- SQL (Postgres): leads per source in the last 7 days\nSELECT source, COUNT(*) AS leads\nFROM leads\nWHERE created_at >= NOW() - INTERVAL '7 days'\nGROUP BY source\nORDER BY leads DESC;",
      },
      interview: "I restate the problem, confirm what counts as a duplicate, and write a small example before coding. I start with the simplest correct version, for example a set of seen keys for a single linear pass, test it on empty and duplicate input, then discuss improvements like streaming a large file or enforcing uniqueness in the database.",
      check: [
        {
          id: 'm14-s4-1', kind: 'choice',
          prompt: 'How many leads does `dedupe_leads` return for these emails: `" Ana@x.com"`, `"ana@X.com"`, `None`, `"bo@y.com"`?',
          options: [
            { text: '2', why: 'Yes. The two Ana emails clean to the same value, and the missing email is skipped.' },
            { text: '3', why: 'The None email is skipped because it cleans to an empty string.' },
            { text: '4', why: 'The cleaning step makes the two Ana emails identical.' },
            { text: 'It crashes on None', why: '`lead.get(\'email\') or \'\'` turns None into an empty string first.' },
          ],
          answer: 0,
          explain: 'Cleaning (strip + lowercase) before comparing, and handling missing values, are the two edge cases interviewers look for.',
        },
        {
          id: 'm14-s4-2', kind: 'choice',
          prompt: 'Postgres rejects this query. Why?',
          code: "SELECT source, COUNT(*)\nFROM leads;",
          options: [
            { text: 'It needs `GROUP BY source` to count per source', why: 'Right. Mixing a plain column with COUNT needs a GROUP BY.' },
            { text: 'COUNT(*) only works on one column', why: 'COUNT(*) counts rows; it doesn’t take a column list.' },
            { text: 'It needs a WHERE clause', why: 'WHERE is optional.' },
            { text: 'The table name must be in quotes', why: 'Plain lowercase table names don’t need quotes.' },
          ],
          answer: 0,
          explain: 'Every column in SELECT that isn’t inside an aggregate like COUNT or SUM must be in GROUP BY.',
        },
        {
          id: 'm14-s4-3', kind: 'choice',
          prompt: 'You’re asked to “remove duplicate leads”. What do you do first?',
          options: [
            { text: 'Ask what counts as a duplicate: same email? Different capitals? Missing emails?', why: 'Yes. The definition changes the code, and asking shows good judgement.' },
            { text: 'Start writing a Lead class with methods', why: 'Too much structure for a small task, before you understand it.' },
            { text: 'Say it’s easy and type in silence', why: 'They can’t follow your thinking, and you may solve the wrong problem.' },
            { text: 'Ask if you can use an AI assistant', why: 'The point of the exercise is to see your own reasoning.' },
          ],
          answer: 0,
          explain: 'Restate, clarify, example, simple version, edge case, improvements.',
        },
      ],
    },
    {
      title: '“I don’t know”, demos and mock interviews',
      minutes: 6,
      body: [
        "**Saying “I don’t know”.** You will get questions you can’t answer. Bluffing is the worst option: the interviewer usually knows the answer and will ask a follow-up. A strong reply has three parts: **be honest, share what you know that’s nearby, and say how you’d find out.**",
        "For example: “I haven’t used Kafka. I have used a Redis-backed queue, so I know the at-least-once delivery idea. I’d read how Kafka handles retries and crashed consumers, then test a crash mid-job.”",
        "**Demos.** Prepare each capstone two ways. **90 seconds:** the problem, one live run, one sentence on reliability. **6 minutes:** add the architecture, a failure and how it recovers, and a measured result. Rehearse with a timer; demos always run long.",
        "**Rapid questions.** Technical screens often fire short questions across APIs and OAuth, n8n, Python, Postgres, Docker, LLMs, evals, RAG, agents, MCP and security. Keep a list of about 50 and answer each in two or three sentences.",
        "**Mocks and the failure log.** Do at least five mock interviews: with a friend, a mentor, or by recording yourself answering. After each one, add every weak answer to your [[failure log]]: the question, what you missed, which module covers it, and a date to retest.",
        "**Don’t memorise scripts.** Interviewers change the scenario (“now there are 50 clients”). Retest each topic with a changed version until you can reason through it, not recite it.",
      ],
      example: {
        caption: 'One failure-log entry',
        code: "QUESTION  “What if the worker crashes after the CRM call succeeds?”\nMISSED    Didn’t say the job gets redelivered and could duplicate\nMODULE    Queues (Module 7), idempotency (Module 2)\nFIX       Store an operation key + result; check before repeating\nRETEST    Next Tuesday, changed scenario: an email instead of a CRM write",
      },
      interview: "“I haven’t used that directly. The closest thing I’ve done is X, which works like this. To find out, I’d check the docs for Y and run a small test of Z.” That answer shows honesty, related knowledge and a plan, which is what the question is really testing.",
      check: [
        {
          id: 'm14-s5-1', kind: 'choice',
          prompt: 'You’re asked how you’d use a vector database you’ve never touched. What’s the strongest answer?',
          options: [
            { text: 'Say you haven’t used it, explain the retrieval idea you do know, and how you’d test it', why: 'Yes. Honest, connected to real knowledge, with a plan.' },
            { text: 'Describe it confidently from what you’ve heard', why: 'A follow-up question will expose the bluff, and trust is hard to win back.' },
            { text: 'Just say “I don’t know” and stop', why: 'Honest, but it misses the chance to show related knowledge and how you learn.' },
            { text: 'Change the subject to a tool you know', why: 'Interviewers notice dodging.' },
          ],
          answer: 0,
          explain: 'Honest → nearby knowledge → how you’d find out.',
        },
        {
          id: 'm14-s5-2', kind: 'choice',
          prompt: 'You recite a perfect memorised answer about retries. The interviewer changes one detail and you freeze. What does that tell you?',
          options: [
            { text: 'You memorised the wording, not the reasoning; retest the topic with changed scenarios', why: 'Right. The goal is handling a changed scenario.' },
            { text: 'You need to memorise more variations', why: 'There are endless variations. Understanding scales; scripts don’t.' },
            { text: 'The interviewer was being unfair', why: 'Changing the scenario is a normal way to test understanding.' },
            { text: 'Nothing; one freeze doesn’t matter', why: 'It’s exactly the kind of weak answer that belongs in your failure log.' },
          ],
          answer: 0,
          explain: 'Add it to the failure log with a changed-scenario retest.',
        },
        {
          id: 'm14-s5-3', kind: 'choice',
          prompt: 'What belongs in a **90-second** demo of a capstone?',
          options: [
            { text: 'The problem, one live run, and one sentence on reliability', why: 'Yes. Short, concrete, and it hints at depth.' },
            { text: 'A full walkthrough of every node and the code', why: 'That’s the long version, if they ask.' },
            { text: 'The architecture diagram only', why: 'Without the problem and a run, it’s hard to see why it matters.' },
            { text: 'A list of every tool you used', why: 'A tool list isn’t a demo.' },
          ],
          answer: 0,
          explain: 'The 6-minute version adds architecture, a failure and its recovery, and a measured result.',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'm14-q1', kind: 'choice',
      prompt: 'Recruiter screen: “Why are you interested in this role?” Which answer is stronger?',
      options: [
        { text: '“I’ve built n8n and Python automations for lead intake. Your ad focuses on CRM integrations and LLM steps, which is exactly the work I want to do more of.”', why: 'Yes. Specific evidence linked to what the role asks for.' },
        { text: '“I’m passionate about AI and I want to grow.”', why: 'True of almost everyone; it gives them nothing to go on.' },
        { text: '“I need a change from my current job.”', why: 'Honest, but it’s about leaving, not about this role.' },
        { text: '“I’ll do whatever you need.”', why: 'Sounds flexible, but shows you haven’t read the ad.' },
      ],
      answer: 0,
      explain: 'Match one piece of your evidence to one thing in their ad.',
    },
    {
      id: 'm14-q2', kind: 'choice',
      prompt: '“Tell me about a time something broke in production.” Which answer is stronger?',
      options: [
        { text: 'A specific incident, what you personally did, how you confirmed the fix, and what you now do differently', why: 'Yes. Problem → owned → result → learned.' },
        { text: '“We had some issues, but the team sorted them out quickly.”', why: 'Vague, and your own role is invisible.' },
        { text: '“Nothing I build really breaks.”', why: 'Not believable, and it suggests you don’t monitor.' },
        { text: 'A detailed walk through every node in the workflow', why: 'Too much detail and no result or lesson.' },
      ],
      answer: 0,
      explain: 'Interviewers trust people who can describe a failure honestly and show what changed.',
    },
    {
      id: 'm14-q3', kind: 'choice',
      prompt: 'Which is the stronger opening to a 90-second intro?',
      options: [
        { text: '“I build automations that move leads and documents between business tools, mostly n8n, and more recently Python and Postgres.”', why: 'Yes. What you do now, in their language, and the direction you’re growing.' },
        { text: '“I was born in…, studied…, then my first job was…”', why: 'A life story uses up the 90 seconds before you reach anything relevant.' },
        { text: '“I’m a fast learner and a team player.”', why: 'Claims with no evidence.' },
        { text: '“I don’t have an engineering background, sorry.”', why: 'Opening with an apology hides what you can do.' },
      ],
      answer: 0,
      explain: 'Now → proof → growth → why here.',
    },
    {
      id: 'm14-q4', kind: 'choice',
      prompt: '“Design a system that extracts data from supplier invoices.” Which opening is stronger?',
      options: [
        { text: '“How many invoices a day, which fields matter, and what happens if a total is wrong? I’ll assume a few hundred a day and that payments need a human check.”', why: 'Yes. Clarifies requirements and states assumptions before designing.' },
        { text: '“I’d use GPT and n8n.”', why: 'Tools before requirements.' },
        { text: '“I’d build a microservices architecture on Kubernetes.”', why: 'Heavy infrastructure before knowing the volume or risks.' },
        { text: '“That’s easy, it’s just OCR.”', why: 'Skips validation, review and failure handling, which are the hard parts.' },
      ],
      answer: 0,
      explain: 'Requirements, then data flow, model, happy path, failures, security, scale, monitoring and cost.',
    },
    {
      id: 'm14-q5', kind: 'choice',
      prompt: '“A provider delivers the same webhook four times. How do you make sure only one contact is created?” Which answer is stronger?',
      options: [
        { text: 'Store the event ID under a unique constraint, skip events already processed but still reply success, and make the CRM write an upsert', why: 'Yes. Duplicate-safe intake plus a write that’s safe to repeat.' },
        { text: 'Check if the contact exists, then create it', why: 'Two workers can both check, find nothing and both create. The database must enforce it.' },
        { text: 'Ask the provider to send it only once', why: 'Providers deliberately retry. You can’t control that.' },
        { text: 'Return an error for duplicates so the provider stops', why: 'An error usually makes the provider retry more.' },
      ],
      answer: 0,
      explain: 'Unique key + upsert + success for already-processed events.',
    },
    {
      id: 'm14-q6', kind: 'choice',
      prompt: '“A 100,000-record sync crashes at record 63,284. How do you resume?” Which answer is stronger?',
      options: [
        { text: 'Process in batches, save a checkpoint after each batch is safely written, make writes idempotent, and resume from the last checkpoint', why: 'Yes. No restart from zero, and any overlap is harmless.' },
        { text: 'Restart from record 1', why: 'Slow, and without idempotent writes it creates duplicates.' },
        { text: 'Restart from exactly 63,284', why: 'You don’t know which records near the crash were actually saved.' },
        { text: 'Run it on a bigger server so it doesn’t crash', why: 'Crashes have many causes. You still need a way to resume.' },
      ],
      answer: 0,
      explain: 'Checkpoint only after the batch is stored, and make repeats safe.',
    },
    {
      id: 'm14-q7', kind: 'choice',
      prompt: 'Read the log. Which explanation is stronger?',
      code: "11:00:01 crm.upsert → 429 Too Many Requests (Retry-After: 30)\n11:00:01 crm.upsert → 429 Too Many Requests (Retry-After: 30)\n11:00:02 crm.upsert → 429 Too Many Requests (Retry-After: 30)",
      options: [
        { text: 'We’re hitting the CRM’s rate limit. I’d wait as Retry-After says, add backoff with jitter, and lower concurrency', why: 'Yes. Reads the code correctly and gives a measured fix.' },
        { text: 'The CRM credentials are wrong', why: 'That would be 401 or 403, not 429.' },
        { text: 'The CRM is down', why: 'A down service usually gives 5xx errors or timeouts.' },
        { text: 'Add more workers to get through the backlog', why: 'More workers means even more requests over the limit.' },
      ],
      answer: 0,
      explain: '429 = slow down. Respect Retry-After, back off with jitter, and cap concurrency.',
    },
    {
      id: 'm14-q8', kind: 'choice',
      prompt: '“The model returns valid JSON but the decision is wrong.” Which answer is stronger?',
      options: [
        { text: 'Valid JSON only proves the shape. I’d test against labelled examples, find the error pattern, change the prompt, model or rules, and rerun the tests', why: 'Yes. Separates shape from correctness and fixes with evidence.' },
        { text: 'Make the JSON schema stricter', why: 'A stricter schema still can’t tell whether the decision is right.' },
        { text: 'Ask the model to double-check itself', why: 'Might help occasionally, but there’s no measurement.' },
        { text: 'Switch to the most expensive model', why: 'Maybe, but without an evaluation you can’t tell if it helped.' },
      ],
      answer: 0,
      explain: 'Shape check, then meaning check against labelled data. Risky or unclear cases go to a human.',
    },
    {
      id: 'm14-q9', kind: 'choice',
      prompt: '“Model A costs 8× more and improves accuracy from 92% to 96%. Which do you use?” Which answer is stronger?',
      options: [
        { text: 'It depends on what a wrong answer costs and the volume. I might use the cheaper model by default and send hard cases to A', why: 'Yes. Ties the choice to error cost and traffic, and offers a middle path.' },
        { text: 'Always A, because accuracy matters most', why: 'Not if errors are cheap and volume is huge.' },
        { text: 'Always the cheaper one; 92% is fine', why: 'Not if a wrong decision is expensive.' },
        { text: 'Whichever is newer', why: 'Newness isn’t a reason.' },
      ],
      answer: 0,
      explain: 'Trade-off questions want reasoning about cost of errors, volume, latency and spend.',
    },
    {
      id: 'm14-q10', kind: 'choice',
      prompt: '“When would you not use an agent?” Which answer is stronger?',
      options: [
        { text: 'When the steps are known and fixed. A plain workflow is cheaper, faster, easier to test and easier to secure', why: 'Yes. Shows you choose the simplest tool that works.' },
        { text: 'Never; agents are always better', why: 'They add cost, unpredictability and risk where none is needed.' },
        { text: 'When the model is too small', why: 'Model size isn’t the main reason.' },
        { text: 'Only when there’s no internet connection', why: 'Not the real trade-off.' },
      ],
      answer: 0,
      explain: 'Use an agent only when the next step genuinely depends on what it finds.',
    },
    {
      id: 'm14-q11', kind: 'choice',
      prompt: 'During live coding you’re stuck on how to page through an API. What’s the stronger move?',
      options: [
        { text: 'Say what you’re stuck on, write the simple version (one page at a time until there’s no next page), and test it', why: 'Yes. Keeps your reasoning visible and moves forward.' },
        { text: 'Go silent until you remember the perfect answer', why: 'Silence gives them nothing to score.' },
        { text: 'Write a large generic API client first', why: 'Over-building wastes the time you have.' },
        { text: 'Say you’d just use an n8n node instead', why: 'They asked to see you code it.' },
      ],
      answer: 0,
      explain: 'Talking through a simple working version beats a silent attempt at a perfect one.',
    },
    {
      id: 'm14-q12', kind: 'order',
      prompt: 'Put the debugging-out-loud loop in order.',
      items: ['Restate the symptom', 'Find the last good state', 'State a hypothesis', 'Name the evidence that would prove it', 'Run the smallest safe test', 'Fix it and add prevention'],
      explain: 'Symptom → last good → hypothesis → evidence → small test → fix and prevent. One change at a time.',
    },
  ],
  tasks: [
    { device: 'phone', plain: 'Write a 90-second intro in four parts: what you do now, proof you built and owned, how you’ve grown technically, and why this role.', done: 'A voice recording under 90 seconds, said without reading it.' },
    { device: 'phone', plain: 'Write five work stories: a production failure, a difficult integration, an ambiguous request, a stakeholder disagreement and learning something fast.', done: 'Each follows problem → owned → result → learned, takes about two minutes out loud, and uses only results you can back up.' },
    { device: 'phone', plain: 'Sketch ten systems on paper: lead intake, ticket triage, document extraction, RAG, reporting, sync, agent, bulk migration, webhook platform and multi-tenant SaaS.', done: 'Ten one-page sketches, each showing the data flow and the source of truth.' },
    { device: 'phone', plain: 'Go through the full checklist for every sketch: requirements, data model, happy path, duplicates and retries, auth, scale, monitoring, security and cost.', done: 'Every sketch has a note for all nine items, including what happens when each external call fails.' },
    { device: 'computer', plain: 'Do 20 small Python exercises: parsing, grouping, removing duplicates, paging through an API, retries and reshaping data.', done: '20 solved files, each with at least one edge-case test, written without an AI assistant.' },
    { device: 'computer', plain: 'Do 20 SQL exercises: JOIN, GROUP BY, CTEs, window functions, upserts and table design.', done: '20 working queries run against your own data, each with a one-line comment on what it answers.' },
    { device: 'phone', plain: 'Write and answer 50 rapid questions across APIs/OAuth, n8n, Python, Postgres, Docker, LLMs, evals, RAG, agents, MCP and security.', done: 'A list of 50 with two-to-three-sentence answers, and you can answer 10 random ones out loud.' },
    { device: 'phone', plain: 'Practise debugging aloud: talk through log scenarios using symptom, last good state, hypothesis, evidence, smallest test, fix and prevent.', done: 'Recordings of yourself working through three different logs without guessing.' },
    { device: 'computer', plain: 'Demo each capstone twice: once in under 6 minutes and once in under 90 seconds.', done: 'Two timed recordings per capstone, both within the limit.' },
    { device: 'phone', plain: 'Practise saying “I don’t know, here’s how I’d find out” instead of bluffing.', done: 'Five unfamiliar-topic questions answered out loud with: honest, nearby knowledge, how you’d find out.' },
    { device: 'phone', plain: 'Run at least five mock interviews and log every weak answer.', done: 'Five dated mocks and a failure log with question, what you missed, module and retest date for each weak answer.' },
    { device: 'phone', plain: 'Retest every failure-log topic with a changed scenario until you can reason through it instead of reciting a script.', done: 'Every failure-log item retested and passed, with no major weak category left.' },
  ],
};
