import type { Lesson } from './types';

// Question IDs are stable so saved progress stays attached to the right question.
// "The Australian market" was added later, so its checks use m15-s6-* even though it sits at index 4.
export const m15: Lesson = {
  intro: "Start applying once your case study project is finished, around week 6–7 of the fast track, not at the end of the course. Interviews tell you which of the deeper engineering modules to prioritise, so the job search runs alongside them. This module covers the practical side of getting hired in Australia: which titles to target, how to make your case study the centrepiece, where to find roles, how to reach people, and how to track your search in the Career tracker so you know what to change.",
  glossary: {
    'ats': 'Applicant Tracking System: the software companies use to receive, store and search job applications.',
    'readme': 'The front-page document of a code repository (README.md), shown automatically on GitHub.',
    'pinned repositories': 'Projects you choose to show at the top of your GitHub profile (up to six).',
    'case study': 'A short write-up of one project: the problem, what you built, how it handles failure and what happened.',
    'boolean search': 'Combining search terms with AND, OR, NOT and quotes for exact phrases, to cut irrelevant results.',
    'hiring manager': 'The person you would report to, who usually makes the final hiring decision.',
    'referral': 'An employee at the company recommending you for a specific role.',
    'funnel': 'The stages your applications move through, with fewer at each stage: applied → screen → interview → offer.',
    'conversion rate': 'The share that moves on to the next stage, e.g. 3 recruiter screens from 30 applications is 10%.',
    'power platform': 'Microsoft’s low-code tools, including Power Automate (workflows) and Copilot Studio (AI agents), widely used where organisations run Microsoft 365.',
    'workflow json': 'The export file of an n8n workflow: every node and setting as text, which can be imported elsewhere.',
  },
  sections: [
    {
      title: 'Which jobs to target, and when to start',
      minutes: 5,
      body: [
        "**The problem.** The same work goes by many names, and similar-sounding titles can mean different jobs. Search one title and you miss most roles. Apply to everything and you waste time on roles you can’t win yet.",
        "**The titles you’ll see.** Meanings vary by company, so always read the job description:",
        "- **Automation Specialist / AI Automation Specialist:** builds and maintains workflows in n8n, Make, Zapier or Power Automate that connect business tools. Closest to your current skills.\n- **AI Automation Engineer / AI Workflow Engineer:** the same work with more code: Python, APIs, databases, deployment, LLM steps.\n- **AI Implementation Specialist:** sets up AI tools and workflows for clients or internal teams. Lots of contact with the people using them.\n- **Solutions Engineer (AI):** technical but close to sales: demos, proofs of concept, helping customers connect the product.\n- **GenAI Automation / Agentic AI Developer:** heavier on LLMs, RAG and agents. Usually expects stronger Python.",
        "**When to start.** Once your case study project is finished, around week 6–7. Don’t wait for the deeper engineering modules: interviews show you which of them matter most.",
        "**Start closest to your strengths, then widen.** Apply first to automation and implementation roles where n8n, integrations and LLM steps are the main ask. Add engineering titles as later projects become evidence.",
        "**One master CV, three variants.** Keep a long master CV with everything you’ve done. From it, make three versions: Automation Specialist, AI Automation Engineer, and AI Implementation/Solutions. Each puts different projects and skills first, but the case study leads in all three.",
      ],
      interview: "When a recruiter asks what I’m looking for, I answer in their words: “AI automation roles where I build and own integrations, webhooks and LLM steps, including the reliability work around them.” Then I link my case study to each of the role’s main requirements.",
      check: [
        {
          id: 'm15-s0-1', kind: 'choice',
          prompt: 'An ad titled “Solutions Engineer – AI” mentions demos to prospects, proofs of concept and working with the sales team. What is this role mainly?',
          options: [
            { text: 'A technical role close to sales: demos and fitting the product to customers', why: 'Yes. Demos and proofs of concept for prospects are the giveaway.' },
            { text: 'A back-end engineering role building the product’s core features, APIs and integrations', why: 'The ad is about prospects and sales, not building the core product.' },
            { text: 'A sales role where all the technical work is handled by a separate team', why: 'Proofs of concept are technical work the role does itself.' },
            { text: 'An internal automation role improving the company’s own sales workflows', why: 'The demos are for prospects, so the work faces customers, not internal teams.' },
          ],
          answer: 0,
          explain: 'Read the duties, not just the title. The same title can mean different jobs at different companies.',
        },
        {
          id: 'm15-s0-2', kind: 'choice',
          prompt: 'You’ve just finished the case study project: strong n8n, LLM steps, little code so far. What should you do now?',
          options: [
            { text: 'Start applying to automation and implementation roles that match that evidence', why: 'Yes. Your case study is evidence for exactly these roles, and interviews will guide what you study next.' },
            { text: 'Finish the deeper engineering modules first, so your CV looks complete', why: 'You’d lose weeks of feedback about what employers actually ask for.' },
            { text: 'Apply to senior AI engineer roles, since a stretch application costs nothing', why: 'Each one costs tailoring time, and the hit rate without production code evidence is very low.' },
            { text: 'Apply to every ad with “AI” in the title, to maximise your volume', why: 'Untargeted volume wastes time and teaches you little.' },
          ],
          answer: 0,
          explain: 'Case study done → start applying, closest roles first, widening as evidence grows.',
        },
      ],
    },
    {
      title: 'CV bullets that show real evidence',
      minutes: 6,
      body: [
        "**The problem.** Most CV bullets list duties: “Responsible for automations.” That tells a reader nothing about what you built or whether it worked. Recruiters skim fast, so each bullet has to carry evidence.",
        "**The formula:** **problem → system you owned → scale → result**, plus a reliability or technical detail if there’s room.",
        "**Results must be true.** Use a number only if you measured it or someone gave it to you, and say where it came from if it’s an estimate. No number? Use honest scale or scope instead: how many records, users, systems or runs. Interviewers ask “how did you measure that?”, and an invented figure falls apart on the spot.",
        "**Tailor the top third.** For every application, rewrite the summary and first few bullets to match the ad’s main requirements, using its exact words where they’re true (“n8n”, “webhooks”, “HubSpot”, “Power Automate”). Many companies use an [[ATS]] that recruiters search by keyword, so exact titles and tool names help. Don’t add tools you can’t discuss.",
        "**The case study is the centrepiece.** Put it in a Projects section near the top, written with the same formula, with a link to the write-up and demo.",
      ],
      example: {
        caption: 'Before and after (no invented numbers)',
        code: "BEFORE  Responsible for building automations in n8n.\nAFTER   Built and maintain the n8n workflow that routes every inbound\n        web lead to HubSpot and Slack for a 6-person sales team; added\n        duplicate protection and failure alerts after a double-contact bug.\n\nBEFORE  Used AI to process invoices.\nAFTER   Built an invoice-extraction workflow (n8n + LLM) that reads\n        supplier PDFs, checks totals against line items and sends\n        unclear invoices to a person for review.\n\nBEFORE  Saved the company 50% of admin time.     ← only if measured\nAFTER   Replaced a daily manual CRM export with a scheduled sync; the\n        ops lead estimates it saves about an hour a day.",
      },
      interview: "For any bullet, I can explain the problem, my part, how it was built and how I know the result. Where I don’t have a measured outcome, I talk about scope and reliability instead: the volume it handles, and how failures are detected and replayed.",
      check: [
        {
          id: 'm15-s1-1', kind: 'choice',
          prompt: 'Which bullet best follows problem → system → scale → result, honestly?',
          options: [
            { text: 'Built the n8n + Postgres sync that keeps 3 client CRMs in step overnight; added retries and a failed-records table', why: 'Yes. Clear system, scale, ownership and a reliability detail, with no invented figure.' },
            { text: 'Responsible for CRM integrations and workflow automation across the business, working closely with sales and operations', why: 'A duty description: it says what area you worked in, not what you built or how it went.' },
            { text: 'Delivered AI automations that increased revenue by 30% and cut admin costs significantly for a growing team', why: 'A big unsupported claim that will be questioned immediately.' },
            { text: 'Skilled in n8n, Python, LangGraph, RAG, Docker, Kubernetes and MCP, with a passion for reliable automation', why: 'A keyword list with no proof of any of it.' },
          ],
          answer: 0,
          explain: 'Specific systems and honest scale are more convincing than big numbers.',
        },
        {
          id: 'm15-s1-2', kind: 'choice',
          prompt: 'You never measured how much time your workflow saved. What’s the best approach?',
          options: [
            { text: 'Describe the scope honestly, or ask the team for an estimate and credit it to them', why: 'Yes. True, specific and defensible in an interview.' },
            { text: 'Estimate a modest percentage, since a conservative figure is unlikely to be questioned', why: 'Still an invented metric, and you can’t explain how it was measured.' },
            { text: 'Leave the project off the CV until you can come back and measure it properly', why: 'Real work is evidence even without a number.' },
            { text: 'Write “significant time savings”, which is true without committing to a number', why: 'Vague claims add nothing and invite the same question.' },
          ],
          answer: 0,
          explain: 'Every number on your CV needs a source you can name.',
        },
      ],
    },
    {
      title: 'GitHub, portfolio and workflow exports',
      minutes: 7,
      body: [
        "**The problem.** Two different people look at your projects. A **recruiter** spends a minute or two and wants to know: what problem, does it work, can I see it? An **engineer** wants architecture, setup, tests and trade-offs. Your write-up has to serve both.",
        "**Lead with the case study.** Pin it first in your [[pinned repositories]], and add later projects as you build them. Each [[README]] opens with the recruiter part, then goes deeper for engineers, as in the example.",
        "**A one-page portfolio** ties it together. For each project: **What I built / Why / Architecture / Reliability / Results / Demo.** The case study goes first, plus links to your CV, GitHub and LinkedIn. A simple one-page site is enough.",
        "**Workflow exports.** Some employers ask for your most complex [[workflow JSON]]. Keep a cleaned export of the case study ready, with a one-paragraph note on what to look at.",
        "**Before publishing anything**, get the client’s permission, remove secrets, hard-coded keys, client names and real customer data, and use synthetic data. Check the Git history too: deleting a key in a new commit doesn’t remove it from older ones. If a key was ever committed, revoke it and make a new one.",
        "**Write about it.** Turn one real build a week into a short [[case study]] or post: the problem, a decision you made, something that broke and how you fixed it. It shows steady progress and gives recruiters something to find.",
      ],
      example: {
        caption: 'README layout for your case study repo',
        code: "# Lead Intake for a Physio Clinic (case study)\nSends web-form leads to the CRM within minutes, with no duplicates.\n[2-min demo video]  [screenshot]        ← a recruiter can stop here\n\n## Architecture          diagram + three sentences\n## How it handles failure duplicates, 429s, expired tokens, replay\n## Results               measured timings, test runs, error behaviour\n## Run it                import workflow.json, add credentials\n## Tests                 test inputs and expected outputs\n## Trade-offs            what I chose, what I'd do with more time",
      },
      interview: "My case study repo opens with the problem, a short demo and a screenshot, then documents architecture, failure handling, setup, tests and trade-offs. Data is synthetic, the workflow export has no secrets or client details, and results are measured rather than claimed.",
      check: [
        {
          id: 'm15-s2-1', kind: 'choice',
          prompt: 'A recruiter opens your repo and the README starts with 40 lines of install commands. What’s the fix?',
          options: [
            { text: 'Open with one line on the problem, a demo link and a screenshot; move setup lower', why: 'Yes. The recruiter gets the point in seconds; engineers still find the setup.' },
            { text: 'Delete the install steps entirely; anyone technical can work out the setup from the code', why: 'Engineers need them. Just move them down.' },
            { text: 'Add badges and a table of contents at the top so it looks more professional', why: 'Badges don’t explain what the project does or show that it works.' },
            { text: 'Keep it; install steps first is the standard layout and shows you’re thorough', why: 'The recruiter leaves before finding out what the project is.' },
          ],
          answer: 0,
          explain: 'Recruiter part first, engineer part below.',
        },
        {
          id: 'm15-s2-2', kind: 'choice',
          prompt: 'You notice an API key in an old commit, so you delete it in a new commit. Is the key safe now?',
          options: [
            { text: 'No. It’s still in the Git history; revoke the key and create a new one', why: 'Right. Anyone can browse old commits on a public repo.' },
            { text: 'Yes. Once the latest commit removes it, the key is no longer visible anywhere', why: 'Older commits still contain it, and anyone can open them.' },
            { text: 'Mostly. Make the repo private now, and the old commits will be hidden from everyone', why: 'Automated scanners may already have copied it while it was public. Treat it as leaked.' },
            { text: 'Only after you also rewrite the history to remove it from the older commits', why: 'Cleaning history is good, but the key may already be copied. Revoke it first.' },
          ],
          answer: 0,
          explain: 'A leaked key is compromised. Revoke first, then clean up.',
        },
        {
          id: 'm15-s2-3', kind: 'choice',
          prompt: 'An employer asks you to send your most complex n8n workflow JSON. What do you send?',
          options: [
            { text: 'The case study export, checked for keys and client details, with a short note on what to look at', why: 'Yes. Your strongest work, safe to share, with the hard parts pointed out.' },
            { text: 'The biggest workflow you have, unedited, since more nodes looks more impressive', why: 'Size isn’t complexity, and an unchecked export may contain keys or client data.' },
            { text: 'A screenshot of the canvas instead, since a JSON file could expose too much', why: 'They asked for the JSON to see the details; a cleaned export solves the exposure problem.' },
            { text: 'A template from the n8n library, tidied up so it looks like your own work', why: 'Passing off a template as yours falls apart as soon as they ask about it.' },
          ],
          answer: 0,
          explain: 'Clean it, then point them to error handling, deduplication and the LLM step.',
        },
      ],
    },
    {
      title: 'LinkedIn and finding the roles',
      minutes: 6,
      body: [
        "**The problem.** Recruiters search LinkedIn by job title and skills. If your profile says “Operations Coordinator, passionate about tech”, you won’t show up for “AI Automation Specialist”. And job boards are noisy: without saved searches you scroll the same irrelevant ads every day.",
        "**Headline:** the title you want, plus proof. For example: `AI Automation Specialist | n8n, APIs, LLM workflows | Built a lead-intake system for a local clinic`. Only list tools you can discuss in an interview.",
        "**About:** three short paragraphs. What you do and the problems you solve. Your case study and anything else you’ve built, with honest results. The kind of role you want, and a link to your portfolio.",
        "**Skills:** add the exact terms from ads you genuinely match: n8n, REST APIs, webhooks, HubSpot, LLMs, Power Automate. Use the ads’ wording, but don’t stuff in tools you can’t talk about.",
        "**Saved searches.** Make one per exact title and turn on job alerts: “AI Automation Specialist”, “Automation Engineer n8n”, “AI Implementation Specialist”, “AI Workflow Engineer”, “GenAI Automation”, “Agentic AI Developer”, “Solutions Engineer AI”. Quotes around a phrase match it exactly. [[Boolean search]] with OR and NOT combines or excludes terms.",
        "**Read the ad, not the title.** Job ads are often wish lists. If you match the core must-haves and can show evidence for them, apply.",
      ],
      example: {
        caption: 'Search strings, one per saved search',
        code: '"AI Automation Specialist"\n"n8n" AND ("automation engineer" OR "workflow engineer")\n"AI Implementation Specialist"\n"Solutions Engineer" AND ("AI" OR "LLM") NOT "senior"',
      },
      interview: "When asked how I’d describe myself: “I’m an AI automation specialist. I build n8n integrations with LLM steps, and I focus on making them reliable: duplicate-safe intake, retries and monitoring.” It matches my headline and CV, so the story is consistent wherever they look.",
      check: [
        {
          id: 'm15-s3-1', kind: 'choice',
          prompt: 'Which LinkedIn headline is strongest for your target roles?',
          options: [
            { text: 'AI Automation Specialist | n8n, APIs, LLM workflows | Built a lead-intake case study', why: 'Yes. The searched-for title, true skills and proof.' },
            { text: 'Operations Coordinator at Acme | Passionate about AI, automation and solving problems', why: 'Accurate, but recruiters searching for automation titles won’t find it.' },
            { text: 'AI | ML | LLM | RAG | Agents | MCP | Kubernetes | Python | n8n | Make | Zapier', why: 'Keyword stuffing, and you’ll be asked about every one.' },
            { text: 'Aspiring automation professional open to new opportunities in AI and tech', why: 'No searchable title and no proof; “aspiring” undersells built work.' },
          ],
          answer: 0,
          explain: 'Target title + real skills + evidence.',
        },
        {
          id: 'm15-s3-2', kind: 'choice',
          prompt: 'Searching “AI automation” returns hundreds of irrelevant ads. What’s the best fix?',
          options: [
            { text: 'Save a separate search for each exact title in quotes, with alerts switched on', why: 'Yes. Exact phrases cut noise and alerts bring new roles to you.' },
            { text: 'Search “AI automation” daily and scroll further until the ads become relevant', why: 'Slow, and new relevant roles still get buried.' },
            { text: 'Search just “AI” with a salary filter, so only better-paid roles come through', why: 'Even broader, and many ads don’t list salary, so the filter hides good roles.' },
            { text: 'Stop using job boards and rely on outreach and referrals for every single application', why: 'Boards are still a major source of roles; just search them better.' },
          ],
          answer: 0,
          explain: 'One saved search per exact title is the simplest way to keep the feed relevant.',
        },
      ],
    },
    {
      title: 'The Australian market',
      minutes: 5,
      body: [
        "**The problem.** Most job-search advice online is written for the US. Here’s where to look in Australia, and who is most likely to hire someone switching careers.",
        "**Where to search.** On **SEEK** and **LinkedIn**, save a search for each exact title with alerts on, such as “Automation Specialist”, “AI Automation”, “Power Platform Developer” and “n8n”. Also watch the n8n community forum and similar tool communities and boards, where businesses post paid automation work.",
        "**Who hires career-switchers.** Automation agencies, consultancies and small-to-medium businesses often care more about what you can show than your job history. They’re good targets for your outreach messages.",
        "**Enterprise and government.** Large organisations and government agencies often run Microsoft 365, so their ads ask for [[Power Platform]]: Power Automate and Copilot Studio. If those roles appeal, rebuild part of your case study in Power Automate so you can show both. Microsoft has a free developer plan you can practise in.",
        "**Freelance first.** A paid project is income and portfolio evidence at once. Two routes: a small, fixed-scope job on Upwork, or one local small business (an accountant, a clinic, a trades business) with a manual process you can automate. With permission, it becomes your second case study.",
        "**Salary research.** Look up each exact title and city on SEEK’s salary insights, and note the ranges printed in similar ads. Check whether a range is base salary or includes super. Don’t quote figures from blogs or forum threads you can’t check.",
        "**Your weekly target** still applies: 10 tailored applications and 10 outreach messages, mixing ads, agencies and small businesses.",
      ],
      interview: "If asked why I’m applying to an agency: “You work across many clients and tools, which is how I learned: my case study was a real small-business process. I can learn your stack quickly, and I’ve already rebuilt part of it in Power Automate.” Only say the last part if it’s true.",
      check: [
        {
          id: 'm15-s6-1', kind: 'choice',
          prompt: 'Government and enterprise ads you like keep asking for Power Automate and Copilot Studio. You only know n8n. What’s the best move?',
          options: [
            { text: 'Rebuild part of your case study in Power Automate, then apply with both', why: 'Yes. Quick, real evidence in the tool they name, on top of the n8n work.' },
            { text: 'Apply anyway and say n8n is basically the same thing, so the tool doesn’t matter', why: 'The concepts transfer, but ads naming a tool want evidence in it.' },
            { text: 'List Power Automate as a skill now, since you’ll learn it on the job', why: 'A skill you can’t discuss will come out in the first technical question.' },
            { text: 'Skip those roles until you’ve finished a formal Microsoft certification', why: 'A small built example gets you applying sooner; a certificate can come later if you want one.' },
          ],
          answer: 0,
          explain: 'Concepts transfer between tools, but evidence in the named tool is what gets you through the screen.',
        },
        {
          id: 'm15-s6-2', kind: 'choice',
          prompt: 'You want income and a second piece of evidence while you apply. What’s the strongest freelance-first move?',
          options: [
            { text: 'One small fixed-scope job, or one local business’s manual process, written up with permission', why: 'Yes. Small enough to finish well, real enough to count as evidence.' },
            { text: 'Free automations for as many businesses as possible, to build a long client list quickly', why: 'Spreading thin means little finished, well-documented work, and no income.' },
            { text: 'Bid on large, complex Upwork projects, so the portfolio looks impressive', why: 'Big projects are hard to win and finish without a track record.' },
            { text: 'Wait until you have a full-time role before taking any paid client work', why: 'You miss the easiest way to get real, paid evidence now.' },
          ],
          answer: 0,
          explain: 'A small, finished, paid project beats a big, half-done one.',
        },
        {
          id: 'm15-s6-3', kind: 'choice',
          prompt: 'A recruiter asks your salary expectations for an Automation Specialist role in Melbourne. Where should your range come from?',
          options: [
            { text: 'SEEK’s salary insights for that title and city, plus ranges in similar ads', why: 'Yes. Local, current and checkable, and you can say where it came from.' },
            { text: 'A US salary survey for the same title, converted to Australian dollars', why: 'Different market, different pay structures; converting the currency doesn’t fix that.' },
            { text: 'What a friend in software engineering earns, since it’s also a tech job', why: 'One person in a different role isn’t a market range for this title.' },
            { text: 'A forum thread where people in automation share what they’re paid', why: 'You can’t check who posted or when, so it’s not a reliable basis.' },
          ],
          answer: 0,
          explain: 'Research by exact title and city, and say whether the range includes super.',
        },
      ],
    },
    {
      title: 'Outreach, follow-ups and referrals',
      minutes: 6,
      body: [
        "**The problem.** Applying through a job board alone can be slow. A short, relevant message to the right person can get your application read. But generic messages (“Hi, I’m looking for opportunities, can you help?”) get ignored.",
        "**Who to message:** the recruiter for the role, or the [[hiring manager]], often the head of automation, operations or engineering. At agencies and small businesses, often the founder. Aim for **10 short, specific messages a week**.",
        "**What makes it work:** one specific role, your case study (or another relevant project), one easy ask. Keep it short enough to read on a phone. No attachments in the first message.",
        "**Follow up once**, after 4–7 days, if there’s no reply. Add something useful if you can, like a demo link or a recent post. Then stop chasing and log it in the Career tracker.",
        "**Referrals.** Ask only when you can point to a specific role and a relevant project. Make it easy: send the job link, two sentences on why you fit and your portfolio link, so they can forward it. A [[referral]] from someone who has never heard of you carries little weight, so build the connection first.",
      ],
      example: {
        caption: 'A short outreach message',
        code: "Hi Sam, I saw the AI Automation Specialist role at Acme.\n\nI recently built a lead-intake system in n8n for a local clinic\n(my case study): it verifies webhooks, prevents duplicate CRM\ncontacts and alerts on failures (2-min demo: [link]). It looks\nclose to the HubSpot work in your ad.\n\nI’ve applied. Would you be open to a 15-minute chat about the team?\n\nThanks, [your name]\n\n— Follow-up, 5 days later —\nHi Sam, a quick follow-up: I’ve added a short write-up on how\nit recovers from CRM outages ([link]). Happy to chat if useful.",
      },
      interview: "When outreach turns into a call, I open with the same project from my message: what it does, what broke and how I fixed it. Then I ask what the team’s biggest automation problem is right now, so the rest of the conversation is about their needs.",
      check: [
        {
          id: 'm15-s4-1', kind: 'choice',
          prompt: 'Which first message to a hiring manager is strongest?',
          options: [
            { text: 'Names the role, links your case study with a demo, and asks for a 15-minute chat', why: 'Yes. Specific, evidence-backed, easy to say yes to.' },
            { text: 'Introduces you, attaches your CV, and lists every project so they can pick what’s relevant', why: 'Too much to read, and attachments from strangers are often ignored.' },
            { text: 'Asks whether they have any openings in AI, keeping it short so it’s easy to reply to', why: 'Short, but no role and no evidence, so there’s nothing to respond to.' },
            { text: 'Asks them to refer you for the role, with your CV link so they can forward it', why: 'A cold referral request gives them no reason to vouch for you.' },
          ],
          answer: 0,
          explain: 'One role, one project, one easy ask.',
        },
        {
          id: 'm15-s4-2', kind: 'choice',
          prompt: 'Five days after a good outreach message, there’s no reply. What do you do?',
          options: [
            { text: 'Send one short follow-up with something useful, then log it and move on', why: 'Yes. One polite nudge, then let it go.' },
            { text: 'Message every day until they answer; persistence shows you really want it', why: 'Repeated chasing annoys people and damages your reputation.' },
            { text: 'Don’t follow up; if they were interested they would already have replied', why: 'People are busy. One follow-up often gets a reply.' },
            { text: 'Message several other people at the same company that day to get noticed', why: 'Looks like spam and can backfire on your application.' },
          ],
          answer: 0,
          explain: 'Follow up once after 4–7 days, then set the outcome in the Career tracker.',
        },
      ],
    },
    {
      title: 'Tracking the funnel and learning from rejections',
      minutes: 6,
      body: [
        "**The problem.** Without tracking, a job search feels random: you apply, hear nothing and don’t know what to change. Tracking turns it into a system you can debug, just like an automation.",
        "**Use the Career tracker.** Add every application and move it through the stages: **Applied → Recruiter screen → Technical → Take-home → Final round → Offer / Rejected**. Record the company, title, CV variant and source (job board, outreach, referral, agency), and set a follow-up reminder.",
        "**Read the drop-off.** The stage with the worst [[conversion rate]] in your [[funnel]] tells you what to fix:",
        "- **Few replies to applications:** targeting or positioning. Check the roles really match, the top third of your CV and your headline.\n- **Screens but no technical rounds:** your intro or stories don’t yet match the role.\n- **Failing technical rounds:** a skill or explanation gap. Check your failure log.\n- **Final rounds but no offers:** often behavioural answers or team fit. Ask for feedback.",
        "**Rejections are study input.** After every rejection or interview, write down the exact question or missing skill straight away, then add it to your study backlog with the module that covers it. This is how you choose what to study in the deeper engineering modules.",
        "**Weekly rhythm:** **10 tailored applications and 10 outreach messages**, plus one short post about something you built. Review once a week and change **one** thing at a time, so you can tell what helped.",
      ],
      example: {
        caption: 'A weekly review',
        code: "WEEK 3     applied 10 · outreach 10 · screens 2 · technical 1\nBY SOURCE  job board 7 → 0 screens | outreach 3 → 2 screens\nGAP        technical screen: couldn’t explain OAuth refresh tokens\nACTION     redo the OAuth lesson (the APIs & webhooks module); retest Friday\nCHANGE     next week: more agency outreach, same CV (one change only)",
      },
      interview: "If asked what I’ve been working on: “A recent interview showed a gap in OAuth refresh tokens, so I redid that material, rebuilt the flow in a test workflow and added it to my notes.” It shows I treat feedback as input and close gaps quickly.",
      check: [
        {
          id: 'm15-s5-1', kind: 'choice',
          prompt: 'You’ve sent 40 applications and had one reply. What does that most likely point to?',
          options: [
            { text: 'Targeting or positioning: the roles you pick, the top of your CV or your headline', why: 'Yes. Almost nobody is reaching the interview stage, so the problem is before it.' },
            { text: 'Your technical skills: employers can tell from the CV that you lack engineering depth', why: 'If so, that’s still a positioning problem: the CV and role choice are what they’re reacting to.' },
            { text: 'Bad luck: the market is slow, so keep sending the same applications at the same pace', why: 'Repeating what isn’t working wastes another 40 applications.' },
            { text: 'Your interview answers, which you should rehearse more before applying anywhere', why: 'You’ve barely reached interviews, so they can’t be the main cause.' },
          ],
          answer: 0,
          explain: 'Where the funnel drops tells you what to fix.',
        },
        {
          id: 'm15-s5-2', kind: 'choice',
          prompt: 'You fail a technical screen on a question about OAuth refresh tokens. What’s the best next step?',
          options: [
            { text: 'Note the exact question, add it to your backlog with a retest date, keep applying', why: 'Yes. The rejection becomes a targeted study item.' },
            { text: 'Pause all applications until you’ve redone every module that mentions authentication', why: 'One gap doesn’t need a pause. Study it alongside applying.' },
            { text: 'Filter out roles that mention OAuth until the deeper engineering modules are done', why: 'OAuth comes up in most integration roles, so that rules out too much.' },
            { text: 'Ask the interviewer to send the full answer, then memorise it for next time', why: 'Memorised answers break when the scenario changes; understand it instead.' },
          ],
          answer: 0,
          explain: 'Capture the exact question immediately, while you still remember it.',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'm15-q1', kind: 'choice',
      prompt: 'An ad asks for production LangGraph agents, RAG evaluation and several years of Python. You’re strong in n8n with little code. What’s the best call?',
      options: [
        { text: 'Note it as a later target; focus on roles where your n8n and integration work covers the must-haves', why: 'Yes. Start close to your strengths and widen as evidence grows.' },
        { text: 'Apply and describe LangGraph as a strength, since you can learn it before any technical round', why: 'An interview will expose it quickly, and it damages trust in the rest of your CV.' },
        { text: 'Apply mainly to roles like this one, since aiming high gets you noticed faster by recruiters', why: 'Your hit rate would be very low right now, and each one costs tailoring time.' },
        { text: 'Rule out AI roles for now and look for general admin roles that use some automation tools as well', why: 'Many AI automation roles fit your current skills; there’s no need to step back.' },
      ],
      answer: 0,
      explain: 'Closest roles first, engineering-heavy roles as your projects prove the skills.',
    },
    {
      id: 'm15-q2', kind: 'choice',
      prompt: 'Which CV bullet is strongest?',
      options: [
        { text: 'Built the n8n workflow that triages every support ticket for a 10-person team into 5 queues, with human review for unclear cases', why: 'Yes. Problem, system, scale and a reliability detail.' },
        { text: 'Worked on support ticket automation across email and live chat, helping the team respond faster and keep customers much happier overall', why: 'Describes an area and a vague benefit, not what you built.' },
        { text: 'Improved customer satisfaction by 85% by introducing AI-powered ticket triage for the support team', why: 'An unsupported number that will be questioned.' },
        { text: 'Hard-working, detail-oriented automation professional with strong n8n, LLM and customer-support experience', why: 'Adjectives, not evidence.' },
      ],
      answer: 0,
      explain: 'Problem → system → scale → result, with only numbers you can source.',
    },
    {
      id: 'm15-q3', kind: 'choice',
      prompt: 'An interviewer asks how you measured the “40% faster” on your CV. You guessed it. What’s the lesson?',
      options: [
        { text: 'Only use numbers you measured or can credit to a named source, such as the team lead', why: 'Yes. An invented figure undermines everything else you’ve said.' },
        { text: 'Use a smaller, more believable figure next time, like 15%, so it’s less likely to be questioned', why: 'Still invented. The question would be the same.' },
        { text: 'Say the measurement method is confidential, which is common for client work', why: 'That sounds evasive and won’t be believed.' },
        { text: 'Remove the projects from your CV and focus on your work history instead', why: 'Projects are your evidence; just describe them honestly.' },
      ],
      answer: 0,
      explain: 'Honest scope beats an unsupported percentage.',
    },
    {
      id: 'm15-q4', kind: 'choice',
      prompt: 'You’ve found a role you really want. What should you customise?',
      options: [
        { text: 'The top third of your CV and your opening paragraph, matched to the ad’s main requirements', why: 'Yes. That’s what gets read first.' },
        { text: 'Nothing; a strong master CV works everywhere and saves time for more applications', why: 'Untailored CVs miss the ad’s keywords and priorities, which costs you the roles you want most.' },
        { text: 'The whole CV rewritten from scratch, so that every single line is written for this one role', why: 'Too slow to sustain 10 a week. The top third does most of the work.' },
        { text: 'Every keyword from the ad added to your skills list, so the ATS ranks you higher', why: 'Untrue skills will be found out in the first technical conversation.' },
      ],
      answer: 0,
      explain: 'Start from a variant, then tailor the top third for each application.',
    },
    {
      id: 'm15-q5', kind: 'choice',
      prompt: 'An engineer reviewing your case study repo wants to judge your skill. Which sections matter most to them?',
      options: [
        { text: 'Architecture, failure handling, setup, tests and trade-offs', why: 'Yes. That’s how they judge whether you can build real systems.' },
        { text: 'A detailed list of every tool and integration used in the project', why: 'A list doesn’t show how you used them or how well it works.' },
        { text: 'The demo video, a screenshot gallery and a short summary', why: 'That’s the recruiter part. Engineers look past it to how it’s built.' },
        { text: 'The commit history and how often you pushed changes during the build', why: 'Commit count says little about quality.' },
      ],
      answer: 0,
      explain: 'Recruiter part at the top (problem, demo); engineer part below.',
    },
    {
      id: 'm15-q6', kind: 'choice',
      prompt: 'You want to publish your case study, built on a real client’s workflow. What must you do first?',
      options: [
        { text: 'Get the client’s permission, swap in synthetic data and remove all secrets', why: 'Yes. Publishing client data without that could break confidentiality and privacy rules.' },
        { text: 'Make the repo private, then share the link with any reviewers who ask', why: 'Reviewers often can’t open private repos, and the data problem remains.' },
        { text: 'Publish it as is, as long as the client was happy with the finished work', why: 'Being happy with the work isn’t permission to publish their data.' },
        { text: 'Blur the customer details in every screenshot and in the README before publishing', why: 'The data would still be in the workflow export and the history.' },
      ],
      answer: 0,
      explain: 'Permission, synthetic data, no secrets, no client names.',
    },
    {
      id: 'm15-q7', kind: 'choice',
      prompt: 'Which LinkedIn skills approach is best?',
      options: [
        { text: 'Exact terms from ads you genuinely match, such as n8n, webhooks and HubSpot', why: 'Yes. Searchable and defensible.' },
        { text: 'Every AI and automation term you’ve come across, to appear in more searches', why: 'You’ll be asked about them, and it looks unfocused.' },
        { text: 'Mainly soft skills, since technical skills are already shown in your projects', why: 'Recruiters search for technical keywords for these roles.' },
        { text: 'Only the tools listed in the one ad you most want, in the order they appear', why: 'Your profile serves every search, not one ad; tailor the CV for that.' },
      ],
      answer: 0,
      explain: 'Match the market’s words, but only for skills you can discuss.',
    },
    {
      id: 'm15-q8', kind: 'choice',
      prompt: 'Someone you met at a meetup works at a company you like. When should you ask for a referral?',
      options: [
        { text: 'When there’s an open role that fits and you can link a relevant project', why: 'Yes. Makes it easy and credible for them to forward.' },
        { text: 'Straight away, asking them to put you forward for any suitable role', why: 'Too vague to act on, and too soon.' },
        { text: 'Once you’ve applied and been rejected, so they can ask the team to reconsider', why: 'A referral helps most before or as you apply, not after a decision.' },
        { text: 'After a few months of regular contact, whether or not there’s a role you fit', why: 'Without a specific role there’s nothing for them to refer you to.' },
      ],
      answer: 0,
      explain: 'Role + relevant project + easy-to-forward message.',
    },
    {
      id: 'm15-q9', kind: 'choice',
      prompt: 'You get plenty of recruiter screens, but keep failing technical screens. What does the funnel say?',
      options: [
        { text: 'Positioning works; study the skill or explanation gaps in your failure log', why: 'Yes. The drop is at the technical stage.' },
        { text: 'Your CV oversells you, so rewrite it to lower expectations before the technical round', why: 'The CV is doing its job; the gap is in the technical answers.' },
        { text: 'Apply to more roles, since technical rounds are partly luck and volume evens it out', why: 'More volume repeats the same technical failure.' },
        { text: 'Change your target titles, since the roles you’re reaching must be the wrong fit', why: 'Recruiters agree you fit; the drop is in the technical answers.' },
      ],
      answer: 0,
      explain: 'Find the stage with the worst drop-off and fix that.',
    },
    {
      id: 'm15-q10', kind: 'choice',
      prompt: 'Your plan: “I’ll start applying once I finish the whole course.” What’s the better approach?',
      options: [
        { text: 'Start once the case study project is done, around week 6–7, and let interviews guide what you study', why: 'Yes. Your case study is enough to start, and interviews show what to learn next.' },
        { text: 'Finish every module first, including the deeper engineering ones, so you’re fully ready for anything', why: 'That feeling rarely arrives, and you lose months of feedback.' },
        { text: 'Start in week one with as many applications as possible, since volume matters more than fit', why: 'Without the case study you have little evidence, and untargeted volume teaches little.' },
        { text: 'Wait until you hold a certificate, since employers screen these roles on qualifications first', why: 'For these roles, interviews probe what you’ve built; a certificate alone doesn’t show that.' },
      ],
      answer: 0,
      explain: 'Case study done → apply, and keep studying alongside.',
    },
    {
      id: 'm15-q11', kind: 'choice',
      prompt: 'This week you changed your CV, your headline and your outreach template, and replies went up. What’s the problem?',
      options: [
        { text: 'You can’t tell which of the three changes caused the improvement', why: 'Right. Change one thing at a time so you learn what works.' },
        { text: 'Nothing; more replies is the goal, so keep all three and move on', why: 'Next time replies drop, you won’t know what to undo.' },
        { text: 'You should change even more next week, while the momentum is still good', why: 'That makes it even harder to learn what works.' },
        { text: 'Replies don’t count; only offers show whether any of the changes worked', why: 'Replies are an early stage that feeds offers, so they’re worth tracking.' },
      ],
      answer: 0,
      explain: 'Treat your search like debugging: one variable at a time.',
    },
    {
      id: 'm15-q12', kind: 'order',
      prompt: 'Put the Career tracker stages in order.',
      items: ['Applied', 'Recruiter screen', 'Technical (and any take-home)', 'Final round', 'Offer'],
      explain: 'Track each stage so you can see where things drop off.',
    },
  ],
  tasks: [
    { device: 'computer', plain: 'Make one master CV, then three targeted versions: Automation Specialist, AI Automation Engineer, and AI Implementation/Solutions, each leading with your case study.', done: 'Four CV files, each variant putting different projects and skills first, with the case study near the top.' },
    { device: 'phone', plain: 'Rewrite every experience bullet as problem → system you owned → scale → result, plus a reliability or technical detail.', done: 'No duty-only bullets left, and you can name the source of every number.' },
    { device: 'computer', plain: 'Publish your case study repo (and later projects as you build them) with screenshots, an architecture diagram, setup steps, tests, a demo and a cleaned workflow export.', done: 'A recruiter can see the problem and demo at the top of the README; an engineer can import and run the workflow.' },
    { device: 'computer', plain: 'Build a one-page portfolio with What I built / Why / Architecture / Reliability / Results / Demo, case study first.', done: 'A live page linking your case study, your CV, GitHub and LinkedIn.' },
    { device: 'phone', plain: 'Update your LinkedIn headline, About section and skills to use the exact job-title words, without stuffing in tools you can’t discuss.', done: 'Headline has your target title and proof; About has three short paragraphs with a portfolio link.' },
    { device: 'phone', plain: 'Create saved searches with alerts on SEEK and LinkedIn for: AI Automation Specialist, Automation Engineer n8n, AI Implementation Specialist, AI Workflow Engineer, GenAI Automation, Agentic AI Developer, Solutions Engineer AI (add Power Platform Developer if you’re targeting enterprise or government).', done: 'Saved searches with alerts switched on for each title, on both sites.' },
    { device: 'computer', plain: 'From the week your case study is done, send 10 tailored applications a week, rewriting the top third of the CV and the opening paragraph for each.', done: 'The Career tracker shows about 10 applications a week, each with the CV variant and source.' },
    { device: 'phone', plain: 'Send 10 short, specific messages a week to recruiters, hiring managers, agencies or small-business owners, each naming a role or problem and your case study.', done: 'Your tracker logs about 10 outreach messages a week, with who, which role and which project.' },
    { device: 'phone', plain: 'Follow up once, 4–7 days later, where it makes sense, then stop and record the outcome.', done: 'Every outreach and application in the Career tracker has a follow-up reminder and an outcome.' },
    { device: 'phone', plain: 'After every rejection or interview, write down the missing skill or exact question and add it to your study backlog.', done: 'Each interview in your tracker links to backlog items with the module that covers them.' },
    { device: 'phone', plain: 'Publish one short case study or post a week about something you really built.', done: 'A post each week covering the problem, a decision you made and something that broke.' },
    { device: 'phone', plain: 'Ask for referrals only when you can point to a specific role and a relevant project.', done: 'Each referral request in your tracker names the role and includes the job link and project link.' },
    { device: 'phone', plain: 'Review your funnel weekly in the Career tracker: Applied → Recruiter screen → Technical → Take-home → Final round → Offer / Rejected.', done: 'A weekly review with counts per stage, the biggest drop-off and one change for next week.' },
    { device: 'phone', plain: 'Keep applying while you work through the deeper engineering modules; interviews tell you what to study next.', done: 'The Career tracker shows applications in every week since you finished the case study project.' },
  ],
};
