import type { Lesson } from './types';

export const m15: Lesson = {
  intro: "You don’t need to feel finished to start applying. Interviews tell you what to study next, so the job search runs alongside the course, not after it. This module covers the practical side of getting hired: which job titles to target, how to show real evidence without exaggerating, how to find roles and reach people, and how to track your search so you know what to change.",
  glossary: {
    'ats': 'Applicant Tracking System: the software companies use to receive, store and search job applications.',
    'readme': 'The front-page document of a code repository (README.md), shown automatically on GitHub.',
    'pinned repositories': 'Projects you choose to show at the top of your GitHub profile (up to six).',
    'case study': 'A short write-up of one project: the problem, what you built, how it handles failure and what happened.',
    'boolean search': 'Combining search terms with AND, OR, NOT and quotes for exact phrases, to cut irrelevant results.',
    'hiring manager': 'The person you would report to, who usually makes the final hiring decision.',
    'referral': 'An employee at the company recommending you for a specific role.',
    'funnel': 'The stages your applications move through, with fewer at each stage: applied → screen → interview → offer.',
    'conversion rate': 'The share that moves on to the next stage, e.g. 3 recruiter screens from 30 applications is 10%.',
  },
  sections: [
    {
      title: 'Which jobs to target, and what the titles mean',
      minutes: 5,
      body: [
        "**The problem.** The same work goes by many names, and similar-sounding titles can mean different jobs. Search one title and you miss most roles. Apply to everything and you waste time on roles you can’t win yet.",
        "**The titles you’ll see.** Meanings vary by company, so always read the job description:",
        "- **Automation Specialist / AI Automation Specialist:** builds and maintains workflows in n8n, Make or Zapier that connect business tools. Closest to your current skills.\n- **AI Automation Engineer / AI Workflow Engineer:** the same work with more code: Python, APIs, databases, deployment, LLM steps.\n- **AI Implementation Specialist:** sets up AI tools and workflows for clients or internal teams. Lots of contact with the people using them.\n- **Solutions Engineer (AI):** technical but close to sales: demos, proofs of concept, helping customers connect the product.\n- **GenAI Automation / Agentic AI Developer:** heavier on LLMs, RAG and agents. Usually expects stronger Python.",
        "**Start closest to your strengths, then widen.** Apply now to automation and implementation roles where n8n and integration work are the main ask. As your Python, RAG and agent projects become real evidence, add the engineering titles.",
        "**One master CV, three variants.** Keep a long master CV with everything you’ve done. From it, make three versions: Automation Specialist, AI Automation Engineer, and AI Implementation/Solutions. Each puts different projects and skills first.",
        "**Apply while you learn.** Don’t wait until you feel ready. Every interview shows you what the market actually asks for, so treat applying as part of the curriculum.",
      ],
      interview: "When a recruiter asks what I’m looking for, I answer in their words: “AI automation roles where I build and own integrations, webhooks and LLM steps, including the reliability work around them.” Then I link one project to each of the role’s main requirements.",
      check: [
        {
          id: 'm15-s0-1', kind: 'choice',
          prompt: 'An ad titled “Solutions Engineer – AI” mentions demos to prospects, proofs of concept and working with the sales team. What is this role mainly?',
          options: [
            { text: 'A technical role close to sales: showing and fitting the product for customers', why: 'Yes. Demos and proofs of concept for prospects are the giveaway.' },
            { text: 'A back-end engineering role with no customer contact', why: 'The ad clearly mentions prospects and sales.' },
            { text: 'A pure sales role with no technical work', why: 'Proofs of concept are technical work.' },
            { text: 'A data science research role', why: 'Nothing in the ad mentions research or modelling.' },
          ],
          answer: 0,
          explain: 'Read the duties, not just the title. The same title can mean different jobs at different companies.',
        },
        {
          id: 'm15-s0-2', kind: 'choice',
          prompt: 'You’re halfway through the course: strong n8n, growing Python. Where should most applications go right now?',
          options: [
            { text: 'Automation and implementation roles where n8n and integrations are the main requirements', why: 'Yes. That’s where your evidence is strongest today.' },
            { text: 'Nowhere until you finish every module', why: 'You’d lose months of feedback about what the market asks for.' },
            { text: 'Only senior agentic AI roles asking for years of production Python', why: 'Add those as your evidence grows; for now your hit rate would be very low.' },
            { text: 'Every job with “AI” in the title', why: 'Untargeted volume wastes time and teaches you little.' },
          ],
          answer: 0,
          explain: 'Closest roles first, then widen as projects become evidence.',
        },
      ],
    },
    {
      title: 'CV bullets that show real evidence',
      minutes: 6,
      body: [
        "**The problem.** Most CV bullets list duties: “Responsible for automations.” That tells a reader nothing about what you built or whether it worked. Recruiters skim fast, so each bullet has to carry evidence.",
        "**The formula:** **problem → system you owned → scale → result**, plus a reliability or technical detail if there’s room.",
        "**Results must be true.** Use a number only if you measured it or someone gave it to you, and say where it came from if it’s an estimate. No number? Use honest scale or scope instead: how many records, users, systems or runs. Interviewers ask “how did you measure that?”, and an invented figure falls apart on the spot.",
        "**Tailor the top third.** For roles you really want, rewrite the summary and first few bullets to match the ad’s main requirements, using its exact words where they’re true (“n8n”, “webhooks”, “Python”). Many companies use an [[ATS]] that recruiters search by keyword, so exact job titles and tool names help. Don’t add tools you can’t discuss.",
        "**Projects count.** If your best evidence is a capstone, give it a Projects section near the top, written with the same formula.",
      ],
      example: {
        caption: 'Before and after (no invented numbers)',
        code: "BEFORE  Responsible for building automations in n8n.\nAFTER   Built and maintain the n8n workflow that routes every inbound\n        web lead to HubSpot and Slack for a 6-person sales team; added\n        duplicate protection and failure alerts after a double-contact bug.\n\nBEFORE  Used AI to process invoices.\nAFTER   Built an invoice-extraction pipeline (n8n, Python, Postgres) that\n        reads supplier PDFs, checks totals against line items and sends\n        unclear invoices to a person for review.\n\nBEFORE  Saved the company 50% of admin time.     ← only if measured\nAFTER   Replaced a daily manual CRM export with a scheduled sync; the\n        ops lead estimates it saves about an hour a day.",
      },
      interview: "For any bullet, I can explain the problem, my part, how it was built and how I know the result. Where I don’t have a measured outcome, I talk about scope and reliability instead: the volume it handles, and how failures are detected and replayed.",
      check: [
        {
          id: 'm15-s1-1', kind: 'choice',
          prompt: 'Which bullet best follows problem → system → scale → result, honestly?',
          options: [
            { text: 'Built the n8n + Postgres sync that keeps 3 client CRMs in step overnight; added retries and a failed-records table after missed updates', why: 'Yes. Clear system, scale, ownership and a reliability detail, with no invented figure.' },
            { text: 'Responsible for CRM integrations', why: 'A duty, not evidence.' },
            { text: 'Increased revenue by 300% using AI automation', why: 'A huge unsupported claim that will be questioned immediately.' },
            { text: 'Expert in n8n, Python, LangGraph, RAG, Docker, Kubernetes and MCP', why: 'A keyword list with no proof of any of it.' },
          ],
          answer: 0,
          explain: 'Specific systems and honest scale are more convincing than big numbers.',
        },
        {
          id: 'm15-s1-2', kind: 'choice',
          prompt: 'You never measured how much time your workflow saved. What’s the best approach?',
          options: [
            { text: 'Describe the scope honestly, or ask the team for an estimate and say it’s theirs', why: 'Yes. True, specific and defensible in an interview.' },
            { text: 'Estimate a percentage that sounds reasonable', why: 'That’s an invented metric. You can’t explain how it was measured.' },
            { text: 'Leave the project off your CV', why: 'Real work is evidence even without a number.' },
            { text: 'Write “significant time savings”', why: 'Vague claims add nothing and invite the same question.' },
          ],
          answer: 0,
          explain: 'Every number on your CV needs a source you can name.',
        },
      ],
    },
    {
      title: 'GitHub and a one-page portfolio',
      minutes: 7,
      body: [
        "**The problem.** Two different people look at your projects. A **recruiter** spends a minute or two and wants to know: what problem, does it work, can I see it? An **engineer** wants architecture, setup, tests and trade-offs. Your repository has to serve both.",
        "**Pin three flagship repos**, your capstones. [[Pinned repositories]] show first on your profile. Each [[README]] opens with the recruiter part, then goes deeper for engineers, as in the example.",
        "**A profile README** is a short intro shown at the top of your GitHub profile. You create a public repository with exactly the same name as your username and add a `README.md` to it.",
        "**A one-page portfolio** ties it together. For each capstone: **What I built / Why / Architecture / Reliability / Results / Demo.** Three projects, plus links to your CV, GitHub and LinkedIn. A simple one-page site is enough.",
        "**Before publishing**, remove secrets, API keys, client names and real customer data; use synthetic data. Check the Git history too: deleting a key in a new commit doesn’t remove it from older ones. If a key was ever committed, revoke it and make a new one.",
        "**Write about it.** Turn one real build a week into a short [[case study]] or post: the problem, a decision you made, something that broke and how you fixed it. It shows steady progress and gives recruiters something to find.",
      ],
      example: {
        caption: 'README layout for one flagship repo',
        code: "# Lead Intake Pipeline\nSends web-form leads to HubSpot within minutes, with no duplicates.\n[2-min demo video]  [screenshot]        ← a recruiter can stop here\n\n## Architecture          diagram + three sentences\n## How it handles failure duplicates, 429s, expired tokens, replay\n## Results               measured timings, test runs, error behaviour\n## Run it locally        docker compose up -d, with .env.example\n## Tests                 what they cover, how to run them\n## Trade-offs            what I chose, what I'd do with more time",
      },
      interview: "Each flagship repo opens with the problem, a short demo and a screenshot, then documents architecture, failure handling, setup, tests and trade-offs. Data is synthetic, secrets come from environment variables with an example file, and results are measured rather than claimed.",
      check: [
        {
          id: 'm15-s2-1', kind: 'choice',
          prompt: 'A recruiter opens your repo and the README starts with 40 lines of install commands. What’s the fix?',
          options: [
            { text: 'Start with one line on the problem, a demo link and a screenshot; move setup further down', why: 'Yes. The recruiter gets the point in seconds; engineers still find the setup.' },
            { text: 'Delete the install steps', why: 'Engineers need them. Just move them down.' },
            { text: 'Add more badges at the top', why: 'Badges don’t explain what the project does.' },
            { text: 'Nothing; recruiters should read the code', why: 'Most recruiters won’t, and don’t need to.' },
          ],
          answer: 0,
          explain: 'Recruiter part first, engineer part below.',
        },
        {
          id: 'm15-s2-2', kind: 'choice',
          prompt: 'You notice an API key in an old commit, so you delete it in a new commit. Is the key safe now?',
          options: [
            { text: 'No. It’s still in the Git history; revoke the key and create a new one', why: 'Right. Anyone can browse old commits on a public repo.' },
            { text: 'Yes, deleting it in the latest commit removes it', why: 'Older commits still contain it.' },
            { text: 'Yes, as long as the repo has few stars', why: 'Automated scanners look for leaked keys on public repos regardless of popularity.' },
            { text: 'Only if you also rename the file', why: 'Renaming doesn’t change history either.' },
          ],
          answer: 0,
          explain: 'A leaked key is compromised. Revoke first, then clean up.',
        },
      ],
    },
    {
      title: 'LinkedIn and finding the roles',
      minutes: 6,
      body: [
        "**The problem.** Recruiters search LinkedIn by job title and skills. If your profile says “Operations Coordinator, passionate about tech”, you won’t show up for “AI Automation Specialist”. And job boards are noisy: without saved searches you scroll the same irrelevant ads every day.",
        "**Headline:** the title you want, plus proof. For example: `AI Automation Specialist | n8n, Python, APIs, LLM workflows | Built lead-intake and invoice-extraction systems`. Only list tools you can discuss in an interview.",
        "**About:** three short paragraphs. What you do and the problems you solve. Two or three things you’ve built, with honest results. The kind of role you want, and a link to your portfolio.",
        "**Skills:** add the exact terms from ads you genuinely match: n8n, Python, REST APIs, webhooks, PostgreSQL, Docker, RAG. Use the ads’ wording, but don’t stuff in tools you can’t talk about.",
        "**Saved searches.** Make one per exact title and turn on job alerts: “AI Automation Specialist”, “Automation Engineer n8n”, “AI Implementation Specialist”, “AI Workflow Engineer”, “GenAI Automation”, “Agentic AI Developer”, “Solutions Engineer AI”. Quotes around a phrase match it exactly. [[Boolean search]] with OR and NOT combines or excludes terms.",
        "**Read the ad, not the title.** Job ads are often wish lists. If you match the core must-haves and can show evidence for them, apply.",
      ],
      example: {
        caption: 'Search strings, one per saved search',
        code: '"AI Automation Specialist"\n"n8n" AND ("automation engineer" OR "workflow engineer")\n"AI Implementation Specialist"\n"Solutions Engineer" AND ("AI" OR "LLM") NOT "senior"',
      },
      interview: "When asked how I’d describe myself: “I’m an AI automation specialist. I build n8n and Python integrations with LLM steps, and I focus on making them reliable: duplicate-safe intake, retries and monitoring.” It matches my headline and CV, so the story is consistent wherever they look.",
      check: [
        {
          id: 'm15-s3-1', kind: 'choice',
          prompt: 'Which LinkedIn headline is strongest for your target roles?',
          options: [
            { text: 'AI Automation Specialist | n8n, Python, APIs | Built lead-intake and invoice systems', why: 'Yes. The searched-for title, true skills and proof.' },
            { text: 'Passionate tech enthusiast open to opportunities', why: 'Contains nothing a recruiter would search for.' },
            { text: 'AI | ML | LLM | RAG | Agents | MCP | Kubernetes | Rust | Web3', why: 'Keyword stuffing, and you’ll be asked about every one.' },
            { text: 'Operations Coordinator at Acme', why: 'Accurate, but it hides the role you’re targeting.' },
          ],
          answer: 0,
          explain: 'Target title + real skills + evidence.',
        },
        {
          id: 'm15-s3-2', kind: 'choice',
          prompt: 'Searching “AI automation” returns hundreds of irrelevant ads. What’s the best fix?',
          options: [
            { text: 'Save separate searches for each exact title in quotes, with alerts on', why: 'Yes. Exact phrases cut noise and alerts bring new roles to you.' },
            { text: 'Scroll further each day', why: 'Slow, and you’ll miss new roles.' },
            { text: 'Only search “AI”', why: 'Even broader, so even noisier.' },
            { text: 'Stop using job boards', why: 'They’re still a major source of roles; just search them better.' },
          ],
          answer: 0,
          explain: 'One saved search per exact title is the simplest way to keep the feed relevant.',
        },
      ],
    },
    {
      title: 'Outreach, follow-ups and referrals',
      minutes: 6,
      body: [
        "**The problem.** Applying through a job board alone can be slow. A short, relevant message to the right person can get your application read. But generic messages (“Hi, I’m looking for opportunities, can you help?”) get ignored.",
        "**Who to message:** the recruiter for the role, or the [[hiring manager]], often the head of automation, operations or engineering. About three concise messages per weekday is a sustainable pace.",
        "**What makes it work:** one specific role, one relevant project you shipped, one easy ask. Keep it short enough to read on a phone. No attachments in the first message.",
        "**Follow up once**, after 4–7 days, if there’s no reply. Add something useful if you can, like a demo link or a recent post. Then stop chasing and log it in your tracker.",
        "**Referrals.** Ask only when you can point to a specific role and a relevant project. Make it easy: send the job link, two sentences on why you fit and your portfolio link, so they can forward it. A [[referral]] from someone who has never heard of you carries little weight, so build the connection first.",
      ],
      example: {
        caption: 'A short outreach message',
        code: "Hi Sam, I saw the AI Automation Specialist role at Acme.\n\nI recently built a lead-intake pipeline in n8n and Python that\nverifies webhooks, prevents duplicate CRM contacts and alerts on\nfailures (2-min demo: [link]). It looks close to the HubSpot work\nin your ad.\n\nI’ve applied. Would you be open to a 15-minute chat about the team?\n\nThanks, [your name]\n\n— Follow-up, 5 days later —\nHi Sam, a quick follow-up: I’ve added a short write-up on how\nthe pipeline recovers from CRM outages ([link]). Happy to chat if useful.",
      },
      interview: "When outreach turns into a call, I open with the same project from my message: what it does, what broke and how I fixed it. Then I ask what the team’s biggest automation problem is right now, so the rest of the conversation is about their needs.",
      check: [
        {
          id: 'm15-s4-1', kind: 'choice',
          prompt: 'Which first message to a hiring manager is strongest?',
          options: [
            { text: 'Names the role, links a relevant shipped project with a demo, and asks for a short chat', why: 'Yes. Specific, evidence-backed, easy to say yes to.' },
            { text: '“Hi, I’m looking for opportunities in AI. Can you help?”', why: 'Generic, no role, no evidence, and a big vague ask.' },
            { text: 'A long message with your full CV attached and your life story', why: 'Too much to read, and attachments from strangers are often ignored.' },
            { text: '“Can you refer me?” to someone you’ve never spoken to', why: 'A cold referral request puts them on the spot with no reason to vouch for you.' },
          ],
          answer: 0,
          explain: 'One role, one project, one easy ask.',
        },
        {
          id: 'm15-s4-2', kind: 'choice',
          prompt: 'Five days after a good outreach message, there’s no reply. What do you do?',
          options: [
            { text: 'Send one short follow-up, ideally with something useful, then log it and move on', why: 'Yes. One polite nudge, then let it go.' },
            { text: 'Message them every day until they answer', why: 'Repeated chasing annoys people and damages your reputation.' },
            { text: 'Never follow up; silence means no', why: 'People are busy. One follow-up often gets a reply.' },
            { text: 'Message five other people at the same company the same day', why: 'Looks like spam and can backfire.' },
          ],
          answer: 0,
          explain: 'Follow up once after 4–7 days, then track it.',
        },
      ],
    },
    {
      title: 'Tracking the funnel and learning from rejections',
      minutes: 6,
      body: [
        "**The problem.** Without tracking, a job search feels random: you apply, hear nothing and don’t know what to change. Tracking turns it into a system you can debug, just like an automation.",
        "**Track every stage** of your [[funnel]] in a spreadsheet: applications → recruiter screens → technical screens → take-homes → final rounds → offers. For each application record the date, company, title, which CV variant you used and the source (job board, outreach, referral).",
        "**Read the drop-off.** The stage with the worst [[conversion rate]] tells you what to fix:",
        "- **Few replies to applications:** targeting or positioning. Check the roles really match, the top third of your CV and your headline.\n- **Screens but no technical rounds:** your intro or stories don’t yet match the role.\n- **Failing technical rounds:** a skill or explanation gap. Check your failure log.\n- **Final rounds but no offers:** often behavioural answers or team fit. Ask for feedback.",
        "**Rejections are study input.** After every rejection or interview, write down the exact question or missing skill straight away, then add it to your study backlog with the module that covers it. A failed interview is a diagnostic you paid for in time.",
        "**Rhythm.** This course’s target: about five well-matched applications and three outreach messages per weekday, plus one case study a week. Quality matters, but volume still matters. Review weekly and change **one** thing at a time, so you can tell what helped.",
      ],
      example: {
        caption: 'A weekly review',
        code: "WEEK 3     applied 25 · screens 2 · technical 1 · offers 0\nBY SOURCE  job board 20 → 0 screens | outreach 5 → 2 screens\nGAP        technical screen: couldn’t explain OAuth refresh tokens\nACTION     redo the OAuth lesson (Module 2); retest Friday\nCHANGE     next week: more outreach, same CV (one change only)",
      },
      interview: "If asked what I’ve been working on: “A recent interview showed a gap in SQL window functions, so I practised them on my own event data and added a query to my project.” It shows I treat feedback as input and close gaps quickly.",
      check: [
        {
          id: 'm15-s5-1', kind: 'choice',
          prompt: 'You’ve sent 60 applications and had one reply. What does that most likely point to?',
          options: [
            { text: 'Targeting or positioning: the roles, the top of your CV or your headline', why: 'Yes. Almost nobody is reaching the interview stage, so the problem is before it.' },
            { text: 'Your technical skills', why: 'You haven’t been tested technically yet.' },
            { text: 'Your salary negotiation', why: 'You haven’t reached that stage.' },
            { text: 'Bad luck; just send 60 more the same way', why: 'Repeating what isn’t working wastes another 60 applications.' },
          ],
          answer: 0,
          explain: 'Where the funnel drops tells you what to fix.',
        },
        {
          id: 'm15-s5-2', kind: 'choice',
          prompt: 'You fail a technical screen on a SQL window-function question. What’s the best next step?',
          options: [
            { text: 'Write down the exact question, add it to your study backlog with the module and a retest date, and keep applying', why: 'Yes. The rejection becomes a targeted study item.' },
            { text: 'Stop applying until you’ve redone the whole SQL module', why: 'One gap doesn’t need a pause. Study it alongside applying.' },
            { text: 'Avoid any role that mentions SQL', why: 'That rules out a big share of good roles.' },
            { text: 'Forget it and move on', why: 'You’ll likely get the same question again.' },
          ],
          answer: 0,
          explain: 'Capture the exact question immediately, while you still remember it.',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'm15-q1', kind: 'choice',
      prompt: 'An ad asks for production LangGraph agents, RAG evaluation and several years of Python. You’re strong in n8n with growing Python. What’s the best call?',
      options: [
        { text: 'Note it as a later target; focus now on roles where your n8n and integration evidence covers the must-haves', why: 'Yes. Start close to your strengths and widen as evidence grows.' },
        { text: 'Apply and claim you know LangGraph well', why: 'An interview will expose it quickly.' },
        { text: 'Give up on AI roles entirely', why: 'Many AI automation roles fit your current skills.' },
        { text: 'Apply only to roles like this one', why: 'Your success rate would be very low right now.' },
      ],
      answer: 0,
      explain: 'Closest roles first, engineering-heavy roles as your projects prove the skills.',
    },
    {
      id: 'm15-q2', kind: 'choice',
      prompt: 'Which CV bullet is strongest?',
      options: [
        { text: 'Built the n8n workflow that triages every support ticket for a 10-person team into 5 queues, with a human-review path for unclear cases', why: 'Yes. Problem, system, scale and a reliability detail.' },
        { text: 'Worked on support ticket automation', why: 'Describes an area, not what you built.' },
        { text: 'Improved customer satisfaction by 85% with AI', why: 'An unsupported number that will be questioned.' },
        { text: 'Hard-working, detail-oriented automation professional', why: 'Adjectives, not evidence.' },
      ],
      answer: 0,
      explain: 'Problem → system → scale → result, with only numbers you can source.',
    },
    {
      id: 'm15-q3', kind: 'choice',
      prompt: 'An interviewer asks how you measured the “40% faster” on your CV. You guessed it. What’s the lesson?',
      options: [
        { text: 'Only put numbers on your CV that you measured or can attribute to a source', why: 'Yes. An invented figure undermines everything else you’ve said.' },
        { text: 'Pick a smaller, more believable number next time', why: 'Still invented. The question would be the same.' },
        { text: 'Don’t put any projects on your CV', why: 'Projects are your evidence; just describe them honestly.' },
        { text: 'Say you can’t share the measurement method', why: 'That sounds evasive and won’t be believed.' },
      ],
      answer: 0,
      explain: 'Honest scope beats an unsupported percentage.',
    },
    {
      id: 'm15-q4', kind: 'choice',
      prompt: 'You find a high-priority role. What should you customise?',
      options: [
        { text: 'The top third of your CV and the first paragraph of your application, matching the ad’s main requirements', why: 'Yes. That’s what gets read first.' },
        { text: 'Nothing; send the master CV', why: 'Fine for low-priority roles, but you’ll miss easy wins on the ones you want.' },
        { text: 'Rewrite your entire CV from scratch', why: 'Too slow to sustain. The top third does most of the work.' },
        { text: 'Add every keyword from the ad, whether true or not', why: 'Keyword stuffing with untrue skills will be found out.' },
      ],
      answer: 0,
      explain: 'Use a variant, then tailor the top third for the roles you care most about.',
    },
    {
      id: 'm15-q5', kind: 'choice',
      prompt: 'An engineer reviewing your repo wants to judge your skill. Which sections matter most to them?',
      options: [
        { text: 'Architecture, failure handling, setup, tests and trade-offs', why: 'Yes. That’s how they judge whether you can build real systems.' },
        { text: 'A long list of technologies used', why: 'A list doesn’t show how you used them.' },
        { text: 'The number of commits', why: 'Commit count says little about quality.' },
        { text: 'A logo and colour scheme', why: 'Nice, but not evidence of engineering skill.' },
      ],
      answer: 0,
      explain: 'Recruiter part at the top (problem, demo); engineer part below.',
    },
    {
      id: 'm15-q6', kind: 'choice',
      prompt: 'You want to publish a capstone built from a real client workflow. What must you do first?',
      options: [
        { text: 'Replace client names and customer data with synthetic data, and remove all secrets', why: 'Yes. Publishing client data could break confidentiality and privacy rules.' },
        { text: 'Make the repo private and share the link anyway', why: 'Reviewers often can’t see private repos, and the data problem remains.' },
        { text: 'Nothing, if the client is happy with the work', why: 'Being happy with the work isn’t permission to publish their data.' },
        { text: 'Blur the data in screenshots only', why: 'The data would still be in the code and history.' },
      ],
      answer: 0,
      explain: 'Synthetic data, no secrets, no client names.',
    },
    {
      id: 'm15-q7', kind: 'choice',
      prompt: 'Which LinkedIn skills approach is best?',
      options: [
        { text: 'Exact terms from ads you genuinely match, such as n8n, Python, webhooks and PostgreSQL', why: 'Yes. Searchable and defensible.' },
        { text: 'Every AI term you’ve heard of', why: 'You’ll be asked about them, and it looks unfocused.' },
        { text: 'Soft skills only', why: 'Recruiters search for technical keywords for these roles.' },
        { text: 'Leave skills empty and rely on the headline', why: 'Skills help you appear in recruiter searches.' },
      ],
      answer: 0,
      explain: 'Match the market’s words, but only for skills you can discuss.',
    },
    {
      id: 'm15-q8', kind: 'choice',
      prompt: 'Someone you met at a meetup works at a company you like. When should you ask for a referral?',
      options: [
        { text: 'When there’s a specific open role and you can point to a relevant project, with the link and a short blurb ready', why: 'Yes. Makes it easy and credible for them to forward.' },
        { text: 'Right away, for “any role you have”', why: 'Too vague to act on.' },
        { text: 'Never; referrals are unfair', why: 'They’re a normal, common route into companies.' },
        { text: 'After you’ve already been rejected', why: 'A referral helps most before or as you apply.' },
      ],
      answer: 0,
      explain: 'Role + relevant project + easy-to-forward message.',
    },
    {
      id: 'm15-q9', kind: 'choice',
      prompt: 'You get plenty of recruiter screens, but keep failing technical screens. What does the funnel say?',
      options: [
        { text: 'Positioning works; there’s a skill or explanation gap to study using your failure log', why: 'Yes. The drop is at the technical stage.' },
        { text: 'Rewrite your CV', why: 'Your CV is already getting you screens.' },
        { text: 'Apply to more roles', why: 'More volume repeats the same technical failure.' },
        { text: 'Change your LinkedIn photo', why: 'Not related to technical rounds.' },
      ],
      answer: 0,
      explain: 'Find the stage with the worst drop-off and fix that.',
    },
    {
      id: 'm15-q10', kind: 'choice',
      prompt: 'Your plan: “I’ll start applying once I finish the course.” What’s the better approach?',
      options: [
        { text: 'Apply to well-matched roles now, and use what interviews reveal to choose what to study next', why: 'Yes. The market is part of the curriculum.' },
        { text: 'Keep studying until you feel fully ready', why: 'That feeling rarely arrives, and you lose months of feedback.' },
        { text: 'Apply to as many roles as possible without reading them', why: 'Volume without fit teaches you little.' },
        { text: 'Only apply after you get a certificate', why: 'Evidence of built systems matters more for these roles.' },
      ],
      answer: 0,
      explain: 'Learning and applying run in parallel.',
    },
    {
      id: 'm15-q11', kind: 'choice',
      prompt: 'This week you changed your CV, your headline and your outreach template, and replies went up. What’s the problem?',
      options: [
        { text: 'You can’t tell which change helped', why: 'Right. Change one thing at a time so you learn what works.' },
        { text: 'Nothing; more replies is all that matters', why: 'Next time it drops, you won’t know what to undo.' },
        { text: 'You should have changed more things', why: 'That makes it even harder to learn.' },
        { text: 'Replies don’t matter, only offers', why: 'Replies are an early stage that feeds offers.' },
      ],
      answer: 0,
      explain: 'Treat your search like debugging: one variable at a time.',
    },
    {
      id: 'm15-q12', kind: 'order',
      prompt: 'Put the job-search funnel stages in order.',
      items: ['Applications', 'Recruiter screens', 'Technical screens', 'Take-homes', 'Final rounds and offers'],
      explain: 'Track each stage so you can see where things drop off.',
    },
  ],
  tasks: [
    { device: 'computer', plain: 'Make one master CV, then three targeted versions: Automation Specialist, AI Automation Engineer, and AI Implementation/Solutions.', done: 'Four CV files, each variant putting different projects and skills first.' },
    { device: 'phone', plain: 'Rewrite every experience bullet as problem → system you owned → scale → result, plus a reliability or technical detail.', done: 'No duty-only bullets left, and you can name the source of every number.' },
    { device: 'computer', plain: 'Pin three flagship GitHub repos, each with screenshots, an architecture diagram, setup steps, tests, a demo and measured results.', done: 'A recruiter can see the problem and demo at the top of each README; an engineer can run it from the setup steps.' },
    { device: 'computer', plain: 'Build a one-page portfolio with What I built / Why / Architecture / Reliability / Results / Demo for each capstone.', done: 'A live page linking all three capstones, your CV, GitHub and LinkedIn.' },
    { device: 'phone', plain: 'Update your LinkedIn headline, About section and skills to use the exact job-title words, without stuffing in tools you can’t discuss.', done: 'Headline has your target title and proof; About has three short paragraphs with a portfolio link.' },
    { device: 'phone', plain: 'Create saved searches with alerts for: AI Automation Specialist, Automation Engineer n8n, AI Implementation Specialist, AI Workflow Engineer, GenAI Automation, Agentic AI Developer, Solutions Engineer AI.', done: 'Seven saved searches with alerts switched on.' },
    { device: 'computer', plain: 'Apply to five well-matched roles each weekday, tailoring the top third of the CV and the first paragraph for high-priority ones.', done: 'Your tracker shows about 25 applications a week, each with the CV variant used.' },
    { device: 'phone', plain: 'Send three short messages per weekday to recruiters or hiring managers, each naming a role and a relevant project you shipped.', done: 'Your tracker logs about 15 outreach messages a week, with who, which role and which project.' },
    { device: 'phone', plain: 'Follow up once, 4–7 days later, where it makes sense, then stop and track the response.', done: 'Every outreach in your tracker has a follow-up date and an outcome.' },
    { device: 'phone', plain: 'After every rejection or interview, write down the missing skill or exact question and add it to your study backlog.', done: 'Each interview in your tracker links to backlog items with the module that covers them.' },
    { device: 'phone', plain: 'Publish one short case study or post a week about something you really built.', done: 'A post each week covering the problem, a decision you made and something that broke.' },
    { device: 'phone', plain: 'Ask for referrals only when you can point to a specific role and a relevant project.', done: 'Each referral request in your tracker names the role and includes the job link and project link.' },
    { device: 'phone', plain: 'Track your funnel: applications → recruiter screens → technical screens → take-homes → final rounds → offers.', done: 'A weekly review with counts per stage, the biggest drop-off and one change for next week.' },
    { device: 'phone', plain: 'Keep applying while you study; the job market is part of the course.', done: 'Your tracker shows applications in every week since you started this module.' },
  ],
};
