import type { Lesson } from './types';

export const m16: Lesson = {
  intro: "Most automation jobs aren’t won by the cleverest workflow. They’re won by the person who finds the right process to automate, proves it’s worth the money, agrees exactly what will be built, and makes sure people actually use it. Almost every AI Automation Specialist and Implementation job ad asks for this: process discovery, process mapping, ROI and stakeholder work. This module gives you a script, a template or a worked example for each step, so you can do it with a real business this week.",
  glossary: {
    "discovery": "The early conversations where you learn how a business really works today, before you build anything.",
    "stakeholder": "Anyone affected by or with a say in the project: the owner, the people doing the work, IT, finance.",
    "process map": "A simple drawing of the steps in a piece of work: who does what, in what order, with which decisions.",
    "current state": "How the process works today, including the workarounds. Also called “as-is”.",
    "future state": "How the process will work once it’s automated. Also called “to-be”.",
    "swimlane": "A row (or column) on a process map for one person, team or system, so you can see who does each step.",
    "exception path": "What happens when a case doesn’t fit the normal flow: missing details, an angry customer, a duplicate.",
    "bpmn": "Business Process Model and Notation: a standard set of shapes for drawing processes. You only need a few of them.",
    "human review": "A step where a person checks or approves something before the automation carries on. Also called human-in-the-loop.",
    "roi": "Return on investment: what the business gets back compared with what it spends.",
    "baseline": "The measured starting point (time, volume, errors) before you change anything, so you can prove the improvement.",
    "loaded hourly cost": "What an hour of someone’s time really costs the business: wage plus super, leave and overheads.",
    "payback period": "How long it takes for the savings to cover what was spent building the automation.",
    "statement of work": "A short document that says what will be delivered, what won’t, and how everyone will know it’s done. Often shortened to SOW.",
    "acceptance test": "A specific check, agreed up front, that the automation must pass before it counts as done.",
    "scope creep": "When extra requests keep getting added to a project without changing the time, cost or deadline.",
    "sop": "Standard operating procedure: step-by-step written instructions for doing a task the same way every time.",
    "raci": "A table that shows, for each task, who is Responsible, Accountable, Consulted and Informed.",
    "go-live": "The moment the automation starts handling real work, not tests.",
    "adoption": "Whether people actually use the new process instead of going back to the old way.",
  },
  sections: [
    {
      title: "Discovery: finding the automation worth building",
      minutes: 6,
      body: [
        "**The problem.** A client says “we want to use AI”. That’s not a project. Your job in [[discovery]] is to find the one process where automation saves real time or prevents costly mistakes, and to measure it before you build.",
        "**The best target is rarely the most interesting one.** Look for work that is high volume, repetitive, rule-based and annoying, where mistakes cost money: re-typing enquiries into a CRM, chasing unpaid invoices, copying data between spreadsheets.",
        "A 30-minute discovery interview:",
        "1. **Context (5 min).** “What does your week look like? What eats your time?”\n2. **Walk-through (15 min).** “Show me the last time you did it.” Ask them to share the screen or open the inbox. Real examples beat memory.\n3. **Numbers (5 min).** How many a week? How long does each take? How often does it go wrong, and what does a mistake cost? Which cases are odd ones out?\n4. **Wrap-up (5 min).** “If this disappeared tomorrow, what would you do with the time?” Agree who you can follow up with.",
        "Write down five numbers for each process: **volume, frequency, minutes per task, error rate, and the share of exceptions**. People guess low on volume and high on speed, so ask to count last week’s real examples.",
        "**Ranking opportunities.** Score each process 1–5 on three things, then multiply:",
        "- **Value**: hours saved and errors avoided.\n- **Feasibility**: are the inputs digital, are the rules clear, do the systems have APIs?\n- **Risk**: score 5 for low risk (an internal summary) and 1 for high risk (sending money, medical advice).",
        "Practise on a real small business, or interview a friend about their job. You’ll be surprised how much is hidden in “oh, I just copy that across”.",
      ],
      example: {
        caption: "Discovery notes: ranking three processes at a plumbing business",
        code: "Process                 Vol/week  Min each  Errors       V  F  R  Score\nEnquiry → CRM + reply      60        6      ~1 in 20 lost  4  5  4   80\nQuote follow-ups           25        4      often forgot   3  4  5   60\nSupplier invoice coding    40        3      rare           2  3  3   18\n\n# V = value, F = feasibility, R = risk (5 = low risk). Score = V × F × R.\n# Pick the top one. Note the exceptions you heard: emergencies,\n# repeat customers, enquiries with photos but no address.",
      },
      interview: "I start with a structured discovery interview: walk through real recent examples, then capture volume, frequency, handling time, error rate and exception share. I rank candidate processes by value, feasibility and risk, and I baseline the winner before building, so the ROI claim is measurable.",
      check: [
        {
          id: "m16-s0-1", kind: "choice",
          prompt: "In a discovery call, the office manager says enquiries take “a minute or two each, maybe 20 a week”. What do you do next?",
          options: [
            { text: "Count and time last week’s real enquiries with them", why: "Right. People misjudge volume and time; real examples give you a baseline you can defend." },
            { text: "Write down 20 × 2 minutes as the baseline and start the ROI", why: "That’s a guess. Your ROI will rest on it, so check it against real examples." },
            { text: "Decide it’s too small and end the call", why: "Too early. The estimate may be wrong, and errors (lost leads) may matter more than time." },
            { text: "Start designing the n8n workflow", why: "You don’t yet know the volume, the exceptions or whether this is the best process to automate." },
          ],
          answer: 0,
          explain: "Ask them to show you, not tell you. Counting real examples turns a guess into a baseline.",
        },
        {
          id: "m16-s0-2", kind: "choice",
          prompt: "Which process is the **best first** automation candidate?",
          options: [
            { text: "Copying 80 web enquiries a week into the CRM", why: "High volume, repetitive, clear rules, and typos that cost leads: high value, high feasibility, low risk." },
            { text: "Approving staff pay rises once a year", why: "Very low volume and high-stakes judgement. Little to gain from automation." },
            { text: "Automatically issuing refunds of any size from customer emails", why: "Risky: money moves on the strength of free text. Not a first project." },
            { text: "The owner’s weekly strategy meeting", why: "Not a repeatable, rule-based process." },
          ],
          answer: 0,
          explain: "Value × feasibility × risk. Boring, frequent, rule-based work with costly errors usually wins.",
        },
      ],
    },
    {
      title: "Mapping the process: today and tomorrow",
      minutes: 6,
      body: [
        "**Why draw it?** In discovery, people describe the tidy version. Drawing the steps exposes the real one: the double entry, the “I check with Sam first”, the sticky note. A [[process map]] is also the fastest way to agree with a client on what you’ll build.",
        "Draw two maps:",
        "- **[[Current state]]**: how it works today, including workarounds and waiting time.\n- **[[Future state]]**: how it will work once automated.",
        "What to put on each map:",
        "- **[[Swimlane|Swimlanes]]**: one row per person or system (customer, office, CRM, automation).\n- **Trigger**: what starts it (an email arrives, a form is submitted, it’s 9am Monday).\n- **Decisions**: diamonds with yes/no questions (“Is it urgent?”).\n- **[[Exception path|Exception paths]]**: what happens when details are missing, it’s a duplicate, or it’s a complaint. This is where most of the real work hides.",
        "On the future map, **label every step**:",
        "- **[RULE]**: fixed logic, always the same (save to CRM, send a template).\n- **[AI]**: an LLM handles messy text (pull the suburb and job type out of an email).\n- **[HUMAN]**: a person checks or approves ([[human review]]), because a mistake would be costly or the AI may be unsure.",
        "Most steps should be RULE. Use AI only where the input is unstructured, and put a HUMAN step after AI wherever a wrong answer reaches a customer.",
        "**Tools.** Miro, Excalidraw or pen and paper are fine. You don’t need full [[BPMN]]; boxes for steps, diamonds for decisions, arrows and lanes are enough. A tidy text version, like the one below, also works and fits in a proposal.",
      ],
      example: {
        caption: "A future-state map in text (BPMN-lite)",
        code: "LANE Customer   : submits website form ─────────────┐\nLANE Automation : [RULE] form received (trigger)  ◄──┘\n                  [AI]   extract name, phone, suburb, job type, urgency\n                  [RULE] all required fields present?\n                     ├─ no  → [HUMAN] review queue: office calls back\n                     └─ yes → [RULE] create/update contact in CRM\nLANE Office     : [HUMAN] approve or edit draft reply (in Slack)\nLANE Automation : [RULE] send reply, log in CRM\n\n# Current state, for comparison: office reads email (2 min) → retypes\n# into CRM (3 min) → writes reply (3 min). Missed when office is busy.",
      },
      interview: "I map current and future state with swimlanes, triggers, decisions and exception paths, and I tag each future step as deterministic, AI-assisted or human review. Most steps stay deterministic; the LLM handles only unstructured input, with review gates wherever an error is customer-facing or costly.",
      check: [
        {
          id: "m16-s1-1", kind: "choice",
          prompt: "Your future-state map has an [AI] step that drafts a reply to the customer, followed directly by “send email”. What’s missing?",
          options: [
            { text: "A [HUMAN] approval step before sending", why: "Yes. A wrong AI reply reaches a customer, so a person approves it, at least until accuracy is proven." },
            { text: "A second AI step to check the first", why: "That can help, but it doesn’t replace a person approving customer-facing text early on." },
            { text: "Nothing; LLMs don’t make mistakes on short replies", why: "They do. Plan for wrong or odd answers." },
            { text: "A swimlane for the email server", why: "Lanes are for who does the work; the missing piece is the approval." },
          ],
          answer: 0,
          explain: "Put a human checkpoint after any AI step whose mistakes are costly or customer-facing.",
        },
        {
          id: "m16-s1-2", kind: "choice",
          prompt: "Which step should be labelled **[RULE]**, not [AI]?",
          options: [
            { text: "If urgency is “emergency”, alert the on-call channel", why: "Right. It’s fixed logic on a value you already have." },
            { text: "Work out the job type from a rambling customer email", why: "That’s unstructured text: a good AI step." },
            { text: "Summarise a long complaint for the owner", why: "Summarising free text is an AI step." },
            { text: "Pull an address out of a photo caption", why: "Messy, unstructured input: AI." },
          ],
          answer: 0,
          explain: "If you can write it as an if/then rule on known fields, it’s RULE. It’s cheaper, faster and never “creative”.",
        },
      ],
    },
    {
      title: "ROI and the business case",
      minutes: 7,
      body: [
        "**The question every client asks:** “Is this worth paying for?” [[ROI]] answers it with simple arithmetic, not hype.",
        "**Step 1: monthly saving** = minutes saved per run × runs per month ÷ 60 × [[loaded hourly cost]].",
        "Count only the minutes that really disappear. If someone still spends 2 minutes approving each reply, subtract that.",
        "**Step 2: running costs per month.** Hosting or platform subscription, LLM cost per run × runs, other paid tools, and a few hours of maintenance. LLM cost per run is usually small for short emails, but calculate it from your provider’s current pricing rather than assuming.",
        "**Step 3: build cost.** Your hours × your rate, plus setup fees.",
        "**Step 4: [[payback period]]** = build cost ÷ (monthly saving − monthly running cost).",
        "**Rules that keep you honest:**",
        "- **Measure the [[baseline]] before you build.** Time ten real cases with a stopwatch and count last month’s volume. Without it, you can’t prove anything afterwards.\n- **Write every assumption down**, next to the number it affects.\n- **Be conservative.** Use the lower estimate. A client who gets more than promised trusts you; one who gets less doesn’t.\n- **List benefits you can’t price separately**: faster replies, fewer lost leads. Don’t inflate the headline number with them.",
        "If payback is longer than about a year, or the saving is tiny, say so. Recommending *not* to build something is a strong look.",
      ],
      example: {
        caption: "Worked ROI example (illustrative numbers, AUD, not benchmarks)",
        code: "BASELINE (measured: 10 cases timed, last month's inbox counted)\n  Enquiries per month          300\n  Minutes each today            8\n\nAFTER (estimated)\n  Minutes each (approve reply)  2      → saves 6 min per enquiry\n  Hours saved per month         300 × 6 ÷ 60 = 30 h\n  Loaded hourly cost (assumed)  $45   → $1,350 saved per month\n\nRUNNING COSTS PER MONTH (assumed)\n  Hosting / platform            $40\n  LLM: 300 runs × ~$0.01        $3\n  Maintenance: 2 h × $90        $180\n  Total                         $223\n\nNET SAVING                      $1,350 − $223 = $1,127 per month\nBUILD COST                      30 h × $90 = $2,700\nPAYBACK                         $2,700 ÷ $1,127 ≈ 2.4 months\n\nNot counted: fewer lost leads, faster first reply.",
      },
      interview: "I baseline volume and handling time before building, then calculate monthly savings as minutes saved × volume × loaded hourly cost, minus run costs including per-execution LLM spend and maintenance, and divide build cost by the net to get payback. Every assumption is written down and conservative, and unpriced benefits are listed separately.",
      check: [
        {
          id: "m16-s2-1", kind: "choice",
          prompt: "A task takes 10 minutes, runs 120 times a month, and the automation cuts it to 2 minutes. Loaded cost is $50 an hour. What’s the monthly time saving in dollars?",
          options: [
            { text: "$800", why: "Right: 8 min × 120 = 960 min = 16 h × $50 = $800." },
            { text: "$1,000", why: "That counts all 10 minutes. Someone still spends 2 minutes, so only 8 are saved." },
            { text: "$400", why: "Check the maths: 8 × 120 ÷ 60 = 16 hours, not 8." },
            { text: "$9,600", why: "That’s 8 × 120 × 10 or similar. Convert minutes to hours before multiplying by the hourly cost." },
          ],
          answer: 0,
          explain: "Minutes saved × runs ÷ 60 × hourly cost. Only count the minutes that actually disappear.",
        },
        {
          id: "m16-s2-2", kind: "choice",
          prompt: "Three months after go-live, the client asks you to prove the time saving. You never timed the old process. What went wrong?",
          options: [
            { text: "You never measured the baseline", why: "Yes. Without a measured starting point, any “before vs after” is a guess." },
            { text: "You should have used a more accurate LLM", why: "Model accuracy doesn’t help you prove time saved." },
            { text: "You needed a longer payback period", why: "Payback is calculated from the baseline; it can’t replace it." },
            { text: "Nothing; you can estimate the old time from memory", why: "That’s exactly the unprovable claim a client or interviewer will challenge." },
          ],
          answer: 0,
          explain: "Measure first. Ten timed cases and a volume count take an hour and make every later claim defensible.",
        },
      ],
    },
    {
      title: "Scoping and stakeholders",
      minutes: 6,
      body: [
        "**The problem.** Vague projects never finish. “Automate our enquiries” can grow forever. A one-page [[statement of work]] (SOW) fixes the edges before you start.",
        "What goes on the page:",
        "- **Goal**, in business terms: “Reply to every web enquiry within 15 minutes during business hours.”\n- **In scope**: the exact process, systems and steps.\n- **Out of scope**: what you won’t do this time (phone enquiries, quoting, the old CRM data).\n- **What “done” means**: a short list of [[acceptance test|acceptance tests]], e.g. “Of 30 test enquiries, at least 27 are classified correctly; none creates a duplicate contact; every one missing a phone number goes to the review queue.”\n- **Who does what, timeline, price and assumptions** (“client provides HubSpot admin access by week 1”).",
        "**[[Stakeholder|Stakeholders]].** The owner pays, but the office manager uses it daily, and IT controls access. Talk to all three early. Show a working demo **every week**, even a rough one: problems surface while they’re still cheap.",
        "**[[Scope creep]].** New requests will come (“can it also do quotes?”). Don’t say a flat no. Say: “Good idea. I’ll add it to the phase 2 list with an estimate. Do you want it to replace something in this phase, or wait?”",
        "**Fit the client’s tools.** A Google Workspace business is a good fit for n8n, Make or Zapier. A Microsoft 365 organisation, including much of Australian enterprise and government, will often expect Power Automate or Copilot Studio. Proposing their stack makes approval easier.",
        "**When to say no to AI and agents.** If the steps are known and the inputs are structured, a fixed workflow is cheaper, faster, easier to test and easier to explain. Use an LLM for messy text, and an agent only when the steps genuinely can’t be planned in advance.",
      ],
      interview: "I scope with a one-page SOW: business goal, in and out of scope, assumptions, and measurable acceptance tests that define done. I demo weekly, log new requests into a phase 2 backlog with estimates, and default to a deterministic workflow, adding LLM steps only for unstructured input.",
      check: [
        {
          id: "m16-s3-1", kind: "choice",
          prompt: "Which is a usable **acceptance test**?",
          options: [
            { text: "At least 27 of 30 test enquiries get the right job type", why: "Specific and checkable: anyone can run it and agree whether it passed." },
            { text: "The automation handles enquiries well and the client feels it works", why: "Too vague. People will disagree on what “well” means." },
            { text: "The client is happy", why: "Important, but not something you can test on the day." },
            { text: "Uses the latest AI model", why: "That’s a design choice, not evidence the job is done." },
          ],
          answer: 0,
          explain: "Good acceptance tests have numbers and a clear pass/fail, agreed before you build.",
        },
        {
          id: "m16-s3-2", kind: "choice",
          prompt: "A client wants an “AI agent” to move form submissions into their CRM. The form has fixed fields. What do you recommend?",
          options: [
            { text: "A fixed workflow mapping form fields to CRM fields", why: "Right. Structured input and known steps: no AI needed, and it’s cheaper and more reliable." },
            { text: "An agent, because the client asked for one", why: "Your job is to recommend what works best. An agent adds cost and unpredictability here." },
            { text: "An LLM that reads each field and decides where it should go", why: "The fields are already structured; the LLM adds cost and a chance of errors." },
            { text: "Build both and let them choose later", why: "Doubles the work for no benefit." },
          ],
          answer: 0,
          explain: "Saying no to AI where a rule does the job is a sign of good judgement, not a lack of skill.",
        },
      ],
    },
    {
      title: "Handover and adoption",
      minutes: 6,
      body: [
        "**The uncomfortable truth:** an automation nobody uses has zero ROI. Staff quietly go back to the old way if they don’t trust it, don’t understand it, or don’t know who to ask when it breaks. Plan the handover from day one.",
        "**1. A one-page [[SOP]] or [[runbook]].** Plain steps for whoever runs it: what it does, how to tell it’s working, what to do with items in the review queue, what to do if it stops, and who to call. If they can’t follow it without you, rewrite it.",
        "**2. Who owns what: a [[RACI]] table.** For each task, name one person in each column:",
        "- **Responsible**: does the work.\n- **Accountable**: makes the final call; exactly one person.\n- **Consulted**: asked before changes.\n- **Informed**: told after.",
        "**3. Training.** A 30-minute live session with the people who’ll use it, using real examples, plus a 5-minute screen-recorded walkthrough they can rewatch. Show a failure and how to handle it, not just the happy path.",
        "**4. Track [[adoption]] after [[go-live]].** Check at 2 weeks and 6 weeks:",
        "- How many items went through the automation versus by hand?\n- How big is the review queue, and how long do items wait in it?\n- Is the time saved close to your ROI estimate? If not, why?",
        "Low adoption is a design problem, not a staff problem. Ask what’s getting in the way and fix it.",
      ],
      example: {
        caption: "A simple RACI for an enquiry automation",
        code: "Task                          Office mgr  Owner  You (builder)  IT\nApprove draft replies             R         A          I          -\nClear the review queue daily      R         A          I          -\nFix a failed workflow             I         A          R          C\nChange the reply templates        R         A          C          -\nRotate API keys / access          I         A          C          R",
      },
      interview: "I hand over with a one-page runbook, a RACI so ownership is explicit, a live training session and a recorded walkthrough that includes failure handling. After go-live I track adoption: share of volume going through the automation, review-queue size and age, and realised versus estimated savings.",
      check: [
        {
          id: "m16-s4-1", kind: "choice",
          prompt: "Six weeks after go-live, the automation works, but the office manager still types most enquiries in by hand. What’s the most useful next step?",
          options: [
            { text: "Find out what’s stopping them, and fix that", why: "Right. Low adoption is usually trust, training or a missing case. Find it." },
            { text: "Tell the owner the staff are the problem", why: "Blaming users rarely helps and usually hides a real design issue." },
            { text: "Add more AI features to make it more impressive", why: "More features don’t fix why people aren’t using the current ones." },
            { text: "Nothing; the workflow runs, so the project succeeded", why: "If it isn’t used, it saves nothing. ROI is zero." },
          ],
          answer: 0,
          explain: "Adoption is part of the job. Track it and treat a gap as something to fix.",
        },
        {
          id: "m16-s4-2", kind: "choice",
          prompt: "In a RACI table, how many people should be **Accountable** for a task?",
          options: [
            { text: "Exactly one", why: "Yes. One person makes the final call, so nothing falls between two chairs." },
            { text: "Everyone involved", why: "If everyone is accountable, nobody is." },
            { text: "None; it’s optional", why: "Without an accountable owner, failures go unhandled." },
            { text: "Two, for backup", why: "Have a backup for doing the work (Responsible), but keep one final owner." },
          ],
          answer: 0,
          explain: "One Accountable person per task. Several people can be Responsible, Consulted or Informed.",
        },
      ],
    },
    {
      title: "Putting it together: the 5-minute proposal",
      minutes: 5,
      body: [
        "Discovery, the map, the ROI and the scope only matter if you can explain them quickly to someone busy. This is also what interviewers test when they ask “How would you find what to automate here?”",
        "A 5-minute structure, one minute each:",
        "1. **The problem, in their words and numbers.** “Your office handles about 300 enquiries a month at 8 minutes each, and some get missed when it’s busy.”\n2. **Today’s process.** Show the current map. Point at the double entry and the gaps.\n3. **The future process.** Show the future map. Say which steps are rules, which use AI and where a person still approves.\n4. **The numbers.** Saving, running cost, payback, and the assumptions behind them.\n5. **Scope and next step.** What’s in, what’s out, how you’ll prove it’s done, and what you need from them to start.",
        "**Lead with the business result**, not the tools. Nobody approves a project because it uses n8n; they approve it because it saves 30 hours a month and stops lost leads.",
        "For an interview question about a team you don’t know, such as finance, use the same shape as a plan: “I’d interview the team and look at real examples, measure volume and time on candidates like invoice entry or reconciliations, rank them by value, feasibility and risk, map the best one, baseline it, and report savings against that baseline after go-live.”",
      ],
      interview: "I’d run discovery interviews with the finance team, walk through real recent examples, and baseline volume, handling time and error rates for candidates like invoice processing or reconciliations. I’d rank them by value, feasibility and risk, map the top one, and agree acceptance tests. After go-live I’d report realised savings and adoption against the measured baseline.",
      check: [
        {
          id: "m16-s5-1", kind: "order",
          prompt: "Put the 5-minute proposal in order.",
          items: ["The problem, with their numbers", "Today’s process map", "The future process map", "Savings, costs and payback", "Scope and next step"],
          explain: "Problem → today → tomorrow → numbers → what happens next. Business result first, tools second.",
        },
        {
          id: "m16-s5-2", kind: "choice",
          prompt: "You have one sentence to open the proposal. Which is strongest?",
          options: [
            { text: "“Your team spends about 40 hours a month retyping enquiries, and some get missed.”", why: "It’s the client’s problem in measured numbers. It earns attention for the rest." },
            { text: "“I’ll build this in n8n with an LLM and a Slack approval step.”", why: "Tools before the problem. The client can’t yet tell why this matters." },
            { text: "“AI is transforming every industry.”", why: "Generic. It says nothing about their business." },
            { text: "“This is a really interesting technical challenge.”", why: "Interesting to you, not a reason for them to pay." },
          ],
          answer: 0,
          explain: "Open with their problem and the measured cost of it.",
        },
      ],
    },
  ],
  quiz: [
    {
      id: "m16-q1", kind: "choice",
      prompt: "A dental clinic owner says: “We want AI.” What’s your first move?",
      options: [
        { text: "Run a discovery interview to find the costly, repetitive work", why: "Right. Find the problem first; the tool comes later." },
        { text: "Build a chatbot for the website, since every business needs one", why: "That’s a solution before you know the problem." },
        { text: "Send a price list for AI projects", why: "You can’t price what you haven’t scoped." },
        { text: "Recommend they hire a data scientist", why: "Premature. Most small-business wins are simple automations." },
      ],
      answer: 0,
      explain: "Discovery before design. “We want AI” is a wish, not a requirement.",
    },
    {
      id: "m16-q2", kind: "choice",
      prompt: "Read the discovery notes. Which process do you pick first?",
      code: "Process              Value  Feasibility  Risk(5=low)\nA. Recall reminders    4        5           5\nB. Clinical notes      5        2           1\nC. Supplier orders     2        4           4",
      options: [
        { text: "A: score 100", why: "4 × 5 × 5 = 100, the highest by far, with low risk." },
        { text: "B: it has the highest value", why: "High value, but hard to build and high risk: 5 × 2 × 1 = 10." },
        { text: "C: it’s the simplest", why: "2 × 4 × 4 = 32. Simple, but not much value." },
        { text: "All three at once", why: "Start with one, finish it, prove it." },
      ],
      answer: 0,
      explain: "Multiply the scores so a very low score on risk or feasibility drags the total down.",
    },
    {
      id: "m16-q3", kind: "choice",
      prompt: "During the walk-through, the receptionist mentions: “If the patient’s a child, I also have to find the parent’s details.” Where does this belong?",
      options: [
        { text: "As an exception path on the process map", why: "Yes. It’s a case that doesn’t fit the normal flow and needs its own handling." },
        { text: "Nowhere; it’s a small detail", why: "Exceptions are where automations break. Capture every one you hear." },
        { text: "In the ROI calculation only", why: "It may affect time, but first it changes the process itself." },
        { text: "In the out-of-scope list, automatically, to keep it simple", why: "You might put it out of scope later, but first record it so it’s a decision, not an accident." },
      ],
      answer: 0,
      explain: "Exceptions you don’t map turn into bugs after go-live.",
    },
    {
      id: "m16-q4", kind: "choice",
      prompt: "A client’s estimate is 200 invoices a month at 5 minutes each. Your baseline count of last month shows 90 invoices at 9 minutes. Which numbers go in the ROI?",
      options: [
        { text: "90 at 9 minutes, noting how you measured it", why: "Right. Measured beats estimated, and you say where the numbers came from." },
        { text: "200 at 5 minutes, because the client said so", why: "You have better data. Use it." },
        { text: "The average of the two", why: "Averaging a guess with a measurement makes the result worse, not better." },
        { text: "Whichever gives the bigger saving", why: "That’s inflating the case, and it will be found out." },
      ],
      answer: 0,
      explain: "Use measured numbers, say how you measured them, and note any seasonality as an assumption.",
    },
    {
      id: "m16-q5", kind: "choice",
      prompt: "Your ROI shows $300 saved a month, $200 running costs a month and a $5,000 build. What do you tell the client?",
      options: [
        { text: "Payback is about 50 months; probably not worth it as scoped", why: "$5,000 ÷ ($300 − $200) = 50 months. Being honest here builds trust." },
        { text: "It pays back in about 17 months", why: "That ignores running costs: $5,000 ÷ $300. Always subtract them." },
        { text: "It pays back in 10 months", why: "Check the maths: the net saving is $100, not $500." },
        { text: "Leave payback out and focus on the hours of time saved instead", why: "Hiding a weak number is how you lose a client’s trust." },
      ],
      answer: 0,
      explain: "Payback = build cost ÷ (saving − running cost). A long payback is a reason to rescope or say no.",
    },
    {
      id: "m16-q6", kind: "choice",
      prompt: "Your ROI table lists “LLM cost: $0”. Why will a careful reviewer question it?",
      options: [
        { text: "Every LLM call costs something per run", why: "Right. It should be cost per run × runs per month: often small, never zero, and leaving it out looks careless." },
        { text: "LLM costs are always the biggest cost", why: "For short texts they’re often small. The issue is leaving them out, not their size." },
        { text: "LLMs are billed per year, not per month", why: "API providers usually bill by usage (tokens), which you can estimate per run." },
        { text: "It shouldn’t be questioned; free tiers exist", why: "Free tiers have limits and aren’t a basis for a production cost estimate." },
      ],
      answer: 0,
      explain: "Include every running cost: platform, LLM per run, other tools and maintenance time.",
    },
    {
      id: "m16-q7", kind: "choice",
      prompt: "Week 3. The client asks: “While you’re at it, can it also send quotes?” It isn’t in the SOW. Best reply?",
      options: [
        { text: "“Good idea, I’ll estimate it as a phase 2 item.”", why: "Takes the idea seriously without silently growing the project." },
        { text: "“Sure, no problem,” and add it quietly", why: "Classic scope creep: the deadline and budget stay the same while the work grows." },
        { text: "“No, that’s not in the contract, so it’s not happening.”", why: "Correct on paper, but it damages the relationship. Offer a path." },
        { text: "Start on quotes and pause the current work", why: "You’d leave the agreed work unfinished." },
      ],
      answer: 0,
      explain: "Log it, estimate it, let the client choose. The SOW is what makes this conversation easy.",
    },
    {
      id: "m16-q8", kind: "choice",
      prompt: "A government department on Microsoft 365 asks for an enquiry-triage automation. Which platform should you lead with?",
      options: [
        { text: "Power Automate, to fit their Microsoft stack", why: "Right. It fits their licensing, identity and IT approval process. Add Copilot Studio if they need a chat assistant." },
        { text: "Whatever tool you like best", why: "Your preference matters less than what the client can approve and support." },
        { text: "A custom app written from scratch", why: "More to build and support, and harder to get approved." },
        { text: "Zapier, because it’s the easiest tool to learn and set up", why: "Possibly fine elsewhere, but a Microsoft-standardised organisation will usually prefer its own platform." },
      ],
      answer: 0,
      explain: "Fit the client’s stack. Many Australian enterprise and government roles are Microsoft-first.",
    },
    {
      id: "m16-q9", kind: "choice",
      prompt: "The process: when a Stripe payment succeeds, add a row to a spreadsheet and email a receipt. The client wants “an AI agent”. What do you say?",
      options: [
        { text: "A fixed workflow: structured input, fixed steps", why: "Yes. No judgement is needed, so AI only adds cost and risk." },
        { text: "Use an agent so it can handle anything unexpected later", why: "There’s nothing unpredictable to handle. Agents are for steps you can’t plan." },
        { text: "Use an LLM to write each receipt", why: "A template is cheaper, consistent and can’t invent an amount." },
        { text: "Refuse the project", why: "Recommend the simpler solution instead." },
      ],
      answer: 0,
      explain: "AI where the input is messy; rules everywhere else.",
    },
    {
      id: "m16-q10", kind: "choice",
      prompt: "Which line belongs in the **out of scope** section of an SOW for an email-enquiry automation?",
      options: [
        { text: "Enquiries by phone or Facebook Messenger", why: "Right. Saying so up front stops the client assuming they’re included." },
        { text: "Create or update the contact in HubSpot", why: "That’s core work: in scope." },
        { text: "At least 27 of 30 test enquiries classified correctly", why: "That’s an acceptance test." },
        { text: "Client provides HubSpot admin access by week 1", why: "That’s an assumption or dependency." },
      ],
      answer: 0,
      explain: "Out of scope names the nearby things people might expect but you’re not doing this time.",
    },
    {
      id: "m16-q11", kind: "order",
      prompt: "Order the stages of a small automation engagement.",
      items: ["Discovery interview and baseline", "Current and future process maps", "ROI and one-page scope", "Build with weekly demos", "Handover, training and adoption tracking"],
      explain: "Find it, map it, cost it, scope it, build it, then make sure it’s used.",
    },
    {
      id: "m16-q12", kind: "choice",
      prompt: "You’re leaving a client. Their automation fails on a Saturday and nobody knows what to do. What was missing from the handover?",
      options: [
        { text: "A runbook, and a RACI naming who fixes it", why: "Right. Someone needs instructions and someone needs to own it." },
        { text: "A more powerful server", why: "Failures happen on any server. The gap is ownership and instructions." },
        { text: "More AI in the workflow", why: "Unrelated to who responds when it breaks." },
        { text: "A longer statement of work with more detail on the build", why: "The SOW defines the build; the runbook and RACI cover running it." },
      ],
      answer: 0,
      explain: "Handover means someone else can run it, and everyone knows who owns what.",
    },
  ],
  tasks: [
    { device: "phone", plain: "Learn how to run a discovery conversation and rank processes by value, feasibility and risk.", done: "You can list the five numbers to capture and you’ve passed the Lesson 1 check." },
    { device: "phone", plain: "Run a 30-minute discovery interview with a small business owner (or a friend about their job) using the script in Lesson 1.", done: "Notes with volume, frequency, minutes per task, error rate and exceptions for at least two processes, ranked by score." },
    { device: "computer", plain: "Draw the current and future map for your top process in Miro, Excalidraw or on paper, labelling each future step RULE, AI or HUMAN.", done: "Two maps with swimlanes, a trigger, at least one decision and at least one exception path." },
    { device: "computer", plain: "Build an ROI table in a spreadsheet: time saved, running costs including LLM cost per run, build cost and payback period.", done: "A table where every number is marked “measured” or “assumed”, with assumptions listed underneath." },
    { device: "phone", plain: "Write a one-page statement of work for that process: goal, in scope, out of scope, acceptance tests, assumptions.", done: "One page with at least three acceptance tests that contain numbers." },
    { device: "phone", plain: "Write a one-page runbook for an automation you’ve already built, including a RACI table.", done: "Someone else reads it and can tell you what to do if it stops working and who to call." },
    { device: "phone", plain: "Answer out loud: “How would you find what to automate in our finance team, and prove it was worth it?”", done: "A recording under 2 minutes that covers discovery, baseline, ranking, mapping and measuring after go-live." },
    { device: "computer", plain: "Present discovery, process maps, ROI and scope for one process in 5 minutes, as if to a client.", done: "A recorded 5-minute presentation that opens with the business problem in numbers and ends with a clear next step." },
  ],
};
