import type { Lesson } from './types';

export const m17: Lesson = {
  intro: "Specialist roles hire on visible business results. This module walks you through one small, finished client project: discovery and ROI for a realistic small business, a working n8n flow that reads enquiries with an LLM, updates HubSpot and asks a person to approve each reply, then testing, a rebuild in Make or Power Automate, and a one-page case study. A recruiter should understand it in two minutes; an engineer should be able to open the workflow JSON and check it. Every number you publish comes from your own test runs.",
  glossary: {
    "case study": "A short write-up of one project: the problem, what you built, the measured result and what you’d do next.",
    "crm": "Customer relationship management system: the database of contacts, deals and conversations, e.g. HubSpot or Salesforce.",
    "baseline": "The measured starting point (time, volume, errors) before the automation, so you can prove the improvement.",
    "structured output": "Getting an LLM to answer in a fixed JSON shape with named fields, instead of free text.",
    "validation": "Checking data against rules (required fields, allowed values, valid email) before you use it.",
    "review queue": "A list where items the automation can’t handle safely wait for a person to check them.",
    "error workflow": "A separate n8n workflow, starting with an Error Trigger node, that runs when another workflow’s execution fails.",
    "retry on fail": "An n8n node setting that re-runs a failed node a set number of times, with a wait in between.",
    "temporary error": "A failure that may succeed if you try again shortly: a timeout, a rate limit (429) or a server error (5xx).",
    "replay": "Running the same input through the workflow again, e.g. after fixing a bug.",
    "test set": "A fixed list of realistic inputs with the answers you expect, written down before you run them.",
    "accuracy": "The share of test inputs the automation got right: correct ÷ total.",
    "architecture diagram": "A simple drawing of the parts of a system and how data flows between them.",
    "credentials": "The keys, tokens and passwords an automation uses to log in to other services.",
    "repo": "Short for repository: a project folder stored on GitHub, with its full history.",
    "readme": "The front-page document of a repo, explaining what the project is and how to run it.",
    "scenario": "Make’s name for a workflow.",
    "premium connector": "In Power Automate, a connector (such as HTTP) that needs a paid licence.",
  },
  sections: [
    {
      title: "The brief: one business, one painful process",
      minutes: 6,
      body: [
        "**Small and finished beats big and half-built.** You’re building one automation for one realistic small business, well enough that it could go live.",
        "**Pick the business.** A trades business (plumber, electrician), a clinic (physio, dental) or a small agency. If you know a real one, use it, with permission. Otherwise create a realistic one and **say clearly in the case study that it’s a simulated client**. Pretending otherwise is easy to spot and ends interviews.",
        "**Pick the process: inbound enquiries.** It’s painful everywhere: emails and web forms arrive, someone reads each one, retypes the details into a [[CRM]], decides how urgent it is and writes a reply. When they’re busy, leads go cold.",
        "**Discovery notes.** Use the script from the Business automation module. Interview the owner, or a friend who does this job, and write down volume, minutes per enquiry, error rate and the exceptions (emergencies, repeat customers, missing addresses).",
        "**Before/after map.** Draw today’s process and the future one, labelling each step RULE, AI or HUMAN.",
        "**ROI table with a measured [[baseline]].** No client staff to time? Write 10 realistic enquiries, then handle each by hand yourself: read it, enter it into HubSpot, write the reply. Time each with a stopwatch and use the median. Label it honestly: “measured on my own manual run”. Volume and hourly cost are assumptions; mark them as such.",
        "Leave the “after” column blank. You’ll fill it from your test results, not from hopes.",
      ],
      example: {
        caption: "Discovery and ROI template: fill in the blanks",
        code: "BUSINESS    ________ (e.g. 3-person electrical business, Brisbane; simulated)\nPROCESS     Inbound email and web-form enquiries\nWHO         ________ (e.g. part-time office manager)\nSTEPS TODAY read → retype into CRM → judge urgency → write reply\nEXCEPTIONS  ________ (emergencies, repeat customers, no address, spam)\n\nROI TABLE                      Value      Source\nEnquiries per week             ____       assumed (from interview)\nMinutes per enquiry, before    ____       MEASURED: median of __ manual runs\nMinutes per enquiry, after     ____       MEASURED in testing (fill in later)\nLoaded hourly cost             $____      assumed (say why)\nRunning cost per month         $____      platform + LLM per run × runs\nBuild hours                    ____       my time log\nPayback                        ____ months",
      },
      interview: "I scoped a simulated client, a small electrical business, and picked inbound enquiry handling because it was high volume and leads were lost when the office was busy. I baselined handling time by processing ten realistic enquiries manually and taking the median, and I labelled every other input in the ROI as an assumption.",
      check: [
        {
          id: "m17-s0-1", kind: "choice",
          prompt: "You have no real client. How should the case study describe the business?",
          options: [
            { text: "As a realistic simulated client, stated clearly", why: "Right. Honest framing still shows the skill, and it survives interview questions." },
            { text: "As a real client, with a made-up name", why: "An interviewer will ask follow-up questions. Being caught out ends the conversation." },
            { text: "Leave it vague and hope nobody asks", why: "Someone will ask. Say it up front." },
            { text: "Don’t do the project until you have a real client", why: "A well-built simulated project is a normal, accepted portfolio piece." },
          ],
          answer: 0,
          explain: "Simulated is fine. Misleading is not.",
        },
        {
          id: "m17-s0-2", kind: "choice",
          prompt: "Where should the “minutes per enquiry, before” number come from?",
          options: [
            { text: "Timing your own manual run of 10 enquiries", why: "It’s measured, repeatable and honestly labelled." },
            { text: "A statistic from a blog post about admin time", why: "Not your process, not your measurement." },
            { text: "A round number that makes the ROI look good", why: "That’s inventing results." },
            { text: "Leave it out; the after number is enough", why: "Without a before, the after proves nothing." },
          ],
          answer: 0,
          explain: "Measure the baseline yourself and say how you measured it.",
        },
      ],
    },
    {
      title: "Building the flow in n8n, step by step",
      minutes: 7,
      body: [
        "Build it in this order, testing each node before adding the next. The diagram below is the [[architecture diagram]] for your README.",
        "1. **Trigger.** A Gmail Trigger (or IMAP Email) node for email, or an n8n Form Trigger for a web form. Keep the sender, subject, body and the message ID.\n2. **LLM extraction and classification.** From the LLM module: ask for [[structured output]] with fixed fields: `name`, `email`, `phone`, `suburb`, `job_type`, `urgency`, `summary`. Give `job_type` and `urgency` a short list of allowed values.\n3. **[[Validation]] before use.** A Code or IF node checks: is the email present and valid? Are `job_type` and `urgency` from the allowed list? Anything that fails goes to the review queue, never to the CRM.\n4. **HubSpot upsert.** The HubSpot node, Contact → **Create or Update**. HubSpot identifies contacts by email, so a second enquiry from the same person updates their contact instead of creating a new one. Trim and lowercase the email first. HubSpot’s free CRM is enough.\n5. **Slack approval.** The Slack node’s **Send and Wait for Response** operation posts the summary and draft reply with Approve and Decline buttons, and pauses the workflow until someone clicks. The buttons link back to your n8n, so it needs a public address (n8n Cloud, or a self-hosted instance with a domain).\n6. **Reply.** If approved, send the reply (Gmail node, or HTTP Request node for other providers). If declined, send it to the review queue.",
        "Don’t let the LLM write anything you send without a person approving it. That’s what the Slack step is for.",
      ],
      example: {
        caption: "Architecture diagram (text version for your README)",
        code: "[Gmail Trigger / Form Trigger]\n      │  sender, subject, body, message id\n      ▼\n[LLM: extract + classify] → JSON {name, email, phone, suburb,\n      │                            job_type, urgency, summary}\n      ▼\n[Validate: Code / IF] ──fail──► [Review queue: sheet + Slack note]\n      │ ok\n      ▼\n[HubSpot: Contact → Create or Update (by email)]\n      ▼\n[Slack: Send and Wait for Response]\n      │ approved               │ declined\n      ▼                        ▼\n[Gmail: reply]           [Review queue]",
      },
      interview: "The flow ingests email or form submissions, uses an LLM with a constrained JSON schema for extraction and classification, and validates the output before anything downstream uses it. Contacts are upserted in HubSpot keyed on normalised email, and every outbound reply goes through a Slack send-and-wait approval.",
      check: [
        {
          id: "m17-s1-1", kind: "choice",
          prompt: "The LLM returns `\"job_type\": \"electrical-ish\"`. Your allowed values are `lighting`, `switchboard`, `power`, `other`. What should happen?",
          options: [
            { text: "It fails validation and goes to the review queue", why: "Right. The output isn’t in the allowed list, so it isn’t trusted downstream." },
            { text: "Save it to HubSpot as is", why: "Now your CRM has a value no report or rule expects." },
            { text: "Ask the LLM again until it says something valid, forever", why: "One retry can be reasonable, but it needs a limit, then the review queue." },
            { text: "Stop the whole workflow for all enquiries", why: "One bad item shouldn’t block the rest." },
          ],
          answer: 0,
          explain: "Validate LLM output before use. Anything off-list goes to a person.",
        },
        {
          id: "m17-s1-2", kind: "choice",
          prompt: "Why use HubSpot’s Contact **Create or Update** rather than **Create**?",
          options: [
            { text: "It updates the existing contact, matched by email", why: "Yes. HubSpot identifies contacts by email, so a repeat enquiry doesn’t create a duplicate. This is an upsert." },
            { text: "Create doesn’t work on the free CRM", why: "Create works fine; the problem is duplicates." },
            { text: "Create or Update is faster", why: "Speed isn’t the reason; avoiding duplicates is." },
            { text: "It lets the LLM decide which existing contact to change", why: "The match is on email, a fixed rule, not the LLM’s judgement." },
          ],
          answer: 0,
          explain: "Upsert by a stable key (email) so repeats and replays don’t create duplicates.",
        },
      ],
    },
    {
      title: "Making it reliable",
      minutes: 6,
      body: [
        "A demo that works once isn’t the goal. You want something a business could trust on a busy Monday. Four pieces:",
        "**1. An [[error workflow]].** Create a separate workflow that starts with an **Error Trigger** node and posts the failed workflow’s name, the error message and a link to the execution into Slack. In your main workflow’s **Settings**, choose it as the **Error workflow**. It fires when an automatic run fails; it doesn’t fire for manual test runs, so test it with the workflow active.",
        "**2. Retries for [[temporary error|temporary errors]] only.** Turn on **Retry On Fail** on nodes that call other services (LLM, HubSpot, Slack, Gmail): for example 3 tries, a few seconds apart. Timeouts, rate limits (429) and server errors (5xx) often succeed on the next try. Retry On Fail can’t tell error types apart, so keep the tries low: a bad email address (400) or a wrong API key (401) will fail every time.",
        "**3. A [[review queue]] for bad data.** Validation failures, declined replies and errors that won’t fix themselves go to one place: a Google Sheet (or an n8n data table) plus a Slack message, with the original text and the reason. On steps where bad data is likely, set the node’s **On Error** setting to **Continue (using error output)** and connect that output to the queue, so one bad item doesn’t stop the run.",
        "**4. Safe to [[replay]].** You’ll re-run items after fixing things. The HubSpot upsert by email already prevents duplicate contacts. For replies, record each message ID once its reply is sent, and check that record before sending, so a replay never emails a customer twice.",
      ],
      interview: "I attached an error workflow via the Error Trigger that alerts Slack with the execution link, enabled bounded retries on external calls for transient failures like 429s and 5xxs, and routed permanent failures and validation errors to a review queue through the error output. Replays are idempotent: contacts are upserted by email and replies are gated on a sent-message record.",
      check: [
        {
          id: "m17-s2-1", kind: "choice",
          prompt: "You run the workflow manually, force a failure, and your error workflow doesn’t fire. Why?",
          options: [
            { text: "Error workflows don’t fire on manual test runs", why: "Right. They fire only when an automatic run of an active workflow fails. Activate it and trigger a real failure to test." },
            { text: "The Error Trigger node is broken", why: "It’s working as designed." },
            { text: "You need Retry On Fail turned on for the failing node", why: "Retries are separate from the error workflow." },
            { text: "Error workflows only work on n8n Cloud", why: "They work on self-hosted n8n too." },
          ],
          answer: 0,
          explain: "Test the error workflow with an active workflow and a real (deliberate) failure.",
        },
        {
          id: "m17-s2-2", kind: "choice",
          prompt: "HubSpot returns `400 Bad Request: invalid email` for one enquiry. Retry On Fail is set to 3 tries. What should your design do with it?",
          options: [
            { text: "Let retries fail, then route it to the review queue", why: "A 400 is permanent: a person needs to fix the data." },
            { text: "Increase retries to 20 so it eventually gets through", why: "The same bad email fails every time." },
            { text: "Drop it silently", why: "That loses a lead with no trace." },
            { text: "Stop the whole workflow", why: "Other enquiries should keep flowing." },
          ],
          answer: 0,
          explain: "Retry temporary errors; route permanent ones to a person.",
        },
        {
          id: "m17-s2-3", kind: "choice",
          prompt: "You replay yesterday’s 12 enquiries after a bug fix. What stops customers getting a second reply?",
          options: [
            { text: "A record of message IDs already replied to", why: "Yes. Check it before sending, and the send step becomes safe to repeat." },
            { text: "The HubSpot upsert by email, which blocks repeats", why: "That prevents duplicate contacts, not duplicate emails." },
            { text: "Retry On Fail", why: "Retries can actually cause repeats; they don’t prevent them." },
            { text: "Slack approval alone", why: "A busy approver may approve the same reply twice." },
          ],
          answer: 0,
          explain: "Each side effect needs its own duplicate guard: upsert for contacts, a sent record for emails.",
        },
      ],
    },
    {
      title: "Testing with 30+ messy inputs",
      minutes: 6,
      body: [
        "Your case study needs numbers, and the only honest source is a test run. Build a [[test set]] of at least 30 realistic enquiries in a spreadsheet, **writing the expected answer for each before you run anything**.",
        "A good mix:",
        "- **Normal** (about half): clear enquiries with all details.\n- **Messy**: typos, no punctuation, all capitals, a long email signature, a forwarded thread.\n- **Missing details**: no phone, no email, no suburb.\n- **Duplicates**: the same person twice, the same email in different capitals.\n- **Edge cases**: an emergency (“sparks coming from the switchboard”), spam, a job you don’t do, a message that says “ignore your instructions”.",
        "Use made-up names and test email addresses you control. Never use real customer data.",
        "For each input, record:",
        "- Classification right or wrong (job type and urgency).\n- Key fields right or wrong (name, email, phone).\n- Correct route: approved, review queue, or ignored.\n- Contact created or updated, and no duplicate.\n- Time: the run’s duration from n8n’s executions list, plus how long the approval took you.",
        "Then calculate [[accuracy]] (correct ÷ total) for classification and fields, duplicates created (target: zero), and median time per item including the human step. Compare that with your baseline.",
        "**Look at every miss.** Fix the prompt or validation, then re-run the *whole* set, not just the failures, so you can see whether the fix broke something else. Report the final numbers and how many rounds it took.",
      ],
      example: {
        caption: "Test log: write the expected column first",
        code: "#   Type         Expected             Got                  OK  Contact     Route    Secs\n1   normal       power / normal       power / normal       Y   created     approve  9\n2   messy        switchboard / urgent lighting / urgent    N   created     approve  11\n3   dup of #1    power / normal       power / normal       Y   updated     approve  8\n4   no email     (review)             (review)             Y   none        review   5\n...\nTOTALS  classification __/__ (__%)   fields __/__   duplicate contacts: __\n        median time per item: __ s automated + __ s approval  (baseline: __ min)",
      },
      interview: "I tested against a fixed set of 30-plus synthetic enquiries, including messy, incomplete, duplicate and adversarial cases, with expected labels written beforehand. I tracked classification and field accuracy, routing, duplicate contacts and end-to-end time per item, and re-ran the full set after each change to catch regressions.",
      check: [
        {
          id: "m17-s3-1", kind: "choice",
          prompt: "Your first test set is 30 tidy enquiries, all with full details. You get 30/30. What’s the problem?",
          options: [
            { text: "It skips the messy and duplicate cases", why: "Right. A perfect score on easy inputs tells you little." },
            { text: "Nothing; 100% is the goal", why: "100% on easy data hides how it behaves on real data." },
            { text: "30 is too many", why: "30 is a reasonable minimum; the issue is variety." },
            { text: "You should have used real customer emails", why: "Never use real customer data. Write realistic fake ones." },
          ],
          answer: 0,
          explain: "Test the cases you’re afraid of, not the ones you know will pass.",
        },
        {
          id: "m17-s3-2", kind: "choice",
          prompt: "You fix the prompt so test #2 now passes. What do you re-run?",
          options: [
            { text: "The whole test set", why: "Yes. A prompt change can break cases that used to pass." },
            { text: "Only test #2", why: "You won’t see if the fix broke something else." },
            { text: "Nothing; it’s fixed", why: "You need evidence, and fresh numbers for the case study." },
            { text: "Only the tests that failed before", why: "That misses new failures among the old passes." },
          ],
          answer: 0,
          explain: "Same full set, every change. That’s how your accuracy number stays honest.",
        },
      ],
    },
    {
      title: "Rebuilding the core in Make or Power Automate",
      minutes: 6,
      body: [
        "Job ads ask for n8n **plus** Make, Zapier or Power Automate. Rebuilding the core of your flow in a second tool proves the skills transfer. Rebuild only the core: trigger → LLM extraction → validation → CRM or list update → approval. Use the same test set.",
        "**Which one?** Make if you’re aiming at agencies and small businesses. Power Automate if you’re aiming at Australian enterprise or government, which are often Microsoft-first. Both have free plans or trials you can practise on; check the current limits.",
        "**What you’ll notice in Make:**",
        "- Workflows are [[scenario|scenarios]], made of modules. You pay by how many module runs (operations) you use, so filtering early saves money.\n- You’ll likely use a Parse JSON module to turn the LLM’s answer into fields.\n- Errors are handled by attaching an error handler route to a module (such as Resume, Ignore or Break).\n- There’s no built-in pause-for-approval like n8n’s, so approval is usually a link or button that triggers a second scenario.",
        "**What you’ll notice in Power Automate:**",
        "- Workflows are cloud flows made of actions and connectors. Some connectors, including HTTP, are [[premium connector|premium]].\n- The Parse JSON action needs a schema; you can generate it from a sample.\n- “Configure run after” and Scope actions give you try/catch-style error handling, and actions have retry policies.\n- Approvals are built in (“Start and wait for an approval”, or an adaptive card in Teams). The CRM might be Dataverse, a SharePoint list or HubSpot through a connector.",
        "**Write a short comparison** for your README: what was easier, what was harder, where error handling and pricing differ, and which you’d pick for which client.",
      ],
      interview: "I rebuilt the core flow in Power Automate to compare: Parse JSON with a schema for the LLM output, Scope plus configure-run-after for error handling, and native Approvals instead of n8n’s send-and-wait. The main trade-offs were licensing for premium connectors and less flexibility in custom logic, versus tighter Microsoft 365 integration.",
      check: [
        {
          id: "m17-s4-1", kind: "choice",
          prompt: "A Microsoft-first government agency asks how you’d do the approval step on their platform. What’s the closest equivalent to n8n’s Slack send-and-wait?",
          options: [
            { text: "Power Automate’s “Start and wait for an approval”", why: "Right. It pauses the flow until someone responds. An adaptive card in Teams works too." },
            { text: "A Make error handler", why: "That handles errors, not approvals, and it’s a different platform." },
            { text: "An HTTP request to Slack", why: "A Microsoft-first agency will usually use Teams and native Approvals." },
            { text: "There’s no built-in way to add approvals in Power Automate", why: "Approvals are a built-in feature." },
          ],
          answer: 0,
          explain: "Same pattern, different tool: pause the flow until a person decides.",
        },
        {
          id: "m17-s4-2", kind: "choice",
          prompt: "Your Make scenario’s usage is climbing because every incoming email runs all 8 modules, including spam. What’s the fix?",
          options: [
            { text: "Filter out spam early, before the costly modules", why: "Yes. Make counts module runs, so stopping early saves operations." },
            { text: "Remove error handling", why: "That saves little and makes failures invisible." },
            { text: "Run the scenario less often and hope it evens out", why: "The same emails still go through every module." },
            { text: "Switch the LLM to a longer prompt", why: "Unrelated to how many modules run." },
          ],
          answer: 0,
          explain: "On per-operation pricing, filter as early as you can.",
        },
      ],
    },
    {
      title: "Packaging it: repo, demo and case study",
      minutes: 7,
      body: [
        "**1. Export the workflow JSON.** In n8n, open the workflow’s menu and choose Download. The file includes credential names and IDs but not their secret values. Still open it and search for anything private: API keys pasted into HTTP Request headers or Code nodes, real email addresses, and pinned test data. Commit it to a public GitHub [[repo]]. Some employers ask for your most complex workflow JSON, so keep it tidy: clear node names and sticky notes.",
        "**2. Write the [[README]].** In this order: the business result in one sentence, the architecture diagram, how it handles failures, test results (your table), the Make or Power Automate comparison, how to import it and which [[credentials]] to set up, and what you’d do next.",
        "**3. Record a 2-minute demo.**",
        "1. 15 s: the problem and the baseline number.\n2. 40 s: a normal enquiry, from arrival to Slack approval to reply.\n3. 30 s: a failure being handled: bad data landing in the review queue.\n4. 20 s: the contact in HubSpot, updated rather than duplicated.\n5. 15 s: your measured results and the repo link.",
        "**4. Write the one-page [[case study]]** using the template below. Business result first, technical detail second. Every number from your own test runs.",
        "**5. Publish and talk about it.** Post on LinkedIn: the result in the first line, three short lines on how, the demo video, the repo link. Link it in every application (see the job search module). In interviews, tell it in the same order: problem, what you built, measured result, one design decision you’d defend, and what you’d improve.",
      ],
      example: {
        caption: "One-page case study template: fill in only measured numbers",
        code: "TITLE     Enquiry handling for a [type of business]: __ min → __ min per enquiry\n          (simulated client)\n\nPROBLEM   About __ enquiries a week, each taking __ min by hand\n          (measured: median of __ manual runs). Leads were ________.\nSOLUTION  n8n reads each enquiry; an LLM extracts and classifies it into\n          validated JSON; HubSpot is upserted by email; a person approves\n          the reply in Slack; bad data goes to a review queue.\nRESULTS   __ test inputs (messy, missing, duplicate): __/__ classified\n          correctly (__%), __ duplicate contacts, median __ s automated\n          + __ s approval.\nROI       ~__ h/month saved at __ enquiries/week (assumed), running cost\n          $__/month, payback __ months. Assumptions: ________.\nNEXT      ________\nLINKS     Repo · 2-minute demo",
      },
      interview: "My case study leads with the measured result, then the architecture: n8n intake, schema-constrained LLM extraction with validation, HubSpot upsert by email, Slack approval and a review queue. The repo has the sanitised workflow JSON, a README with test results and a comparison with Power Automate.",
      check: [
        {
          id: "m17-s5-1", kind: "choice",
          prompt: "Before pushing the exported workflow JSON, you find `Authorization: Bearer sk-…` in an HTTP Request node’s headers. What do you do?",
          options: [
            { text: "Move it into a credential, re-export, revoke the key", why: "Right. Put the key in an n8n credential: keys typed into node fields get exported, credentials’ secret values don’t." },
            { text: "Push it; the repo is only for recruiters", why: "Public repos are scanned by bots for keys within minutes." },
            { text: "Delete the line in the JSON file and push it as it is", why: "Better than pushing it, but fix the workflow too, and revoke the key if it was ever shared." },
            { text: "Make the README say “don’t use my key”", why: "That doesn’t protect anything." },
          ],
          answer: 0,
          explain: "Secrets live in credentials, never in node fields. Check every export before publishing.",
        },
        {
          id: "m17-s5-2", kind: "choice",
          prompt: "Your test run gave 26/30 correct. A friend suggests writing “95% accuracy” because it “sounds better”. What do you write?",
          options: [
            { text: "26/30 (87%) on 30 messy test inputs, with what failed and why", why: "Honest, specific and defensible in an interview." },
            { text: "95% accuracy", why: "That’s inventing a result." },
            { text: "“Highly accurate”", why: "Vague, and it hides a number you actually have." },
            { text: "Leave accuracy out", why: "Your measured result is the strongest part of the case study." },
          ],
          answer: 0,
          explain: "Real numbers, with the test conditions. An honest 87% beats a suspicious 95%.",
        },
      ],
    },
  ],
  quiz: [
    {
      id: "m17-q1", kind: "choice",
      prompt: "Halfway through, you want to add WhatsApp, voice messages and a quoting tool. The core flow isn’t tested yet. What do you do?",
      options: [
        { text: "Finish and test the core first; list extras as next steps", why: "Small and finished beats big and half-built." },
        { text: "Add all three now", why: "More half-built parts, and still nothing to show." },
        { text: "Start a new, bigger project that includes all three from the start", why: "You’d lose the work that’s nearly ready to show." },
        { text: "Add them but skip testing", why: "Untested features can’t go in a case study with measured results." },
      ],
      answer: 0,
      explain: "Ship one finished thing. Ideas become your roadmap.",
    },
    {
      id: "m17-q2", kind: "choice",
      prompt: "The web form already has a dropdown for job type. Should the LLM classify job type?",
      options: [
        { text: "No. Use the dropdown; save the LLM for free text", why: "Right. The field is already structured, so a rule is cheaper and never wrong." },
        { text: "Yes, because LLMs are usually more accurate than dropdowns", why: "The customer already chose. An LLM can only add errors here." },
        { text: "Yes, to make the project look more advanced", why: "Interviewers value good judgement over extra AI." },
        { text: "Remove the dropdown so the LLM has more to do", why: "That makes the input worse on purpose." },
      ],
      answer: 0,
      explain: "AI for messy text, rules for structured fields.",
    },
    {
      id: "m17-q3", kind: "choice",
      prompt: "Read the LLM output. What should your validation step do?",
      code: "{\n  \"name\": \"Jo\",\n  \"email\": null,\n  \"phone\": \"0400 000 000\",\n  \"job_type\": \"power\",\n  \"urgency\": \"urgent\",\n  \"summary\": \"Power out in kitchen since this morning\"\n}",
      options: [
        { text: "Send it to the review queue: there’s no email to upsert the contact by", why: "HubSpot matches contacts by email. Without one, a person should handle it (they have a phone number)." },
        { text: "Create the HubSpot contact with a blank email", why: "That risks creating a contact you can never match again." },
        { text: "Ask the LLM to guess the email", why: "It would invent one." },
        { text: "Skip it; it’s incomplete", why: "It’s an urgent lead. Dropping it loses business." },
      ],
      answer: 0,
      explain: "Validation decides what’s safe to automate. The rest goes to a person, fast.",
    },
    {
      id: "m17-q4", kind: "choice",
      prompt: "During testing, `Sam@Example.com` and `sam@example.com ` (trailing space) are treated as two different people by your own sent-reply check. What’s the fix?",
      options: [
        { text: "Trim and lowercase emails first", why: "Right. Normalise the key once, early, and use it everywhere." },
        { text: "Ask customers to type more carefully", why: "You can’t control input. Clean it." },
        { text: "Let the LLM decide if they’re the same person", why: "A simple rule is cheaper and consistent." },
        { text: "Turn off the duplicate check", why: "Then customers get duplicate replies." },
      ],
      answer: 0,
      explain: "Normalise matching keys (email) before upserts and duplicate checks.",
    },
    {
      id: "m17-q5", kind: "choice",
      prompt: "Where should the Slack approval sit in the flow?",
      options: [
        { text: "After the CRM update, before the reply", why: "The contact is safely recorded, and nothing reaches the customer without approval." },
        { text: "Before the LLM step", why: "There’s nothing to approve yet." },
        { text: "After the reply is sent", why: "Too late: approval must happen before the customer sees it." },
        { text: "Nowhere; the LLM is good enough for short replies", why: "Customer-facing AI text needs a person’s approval, at least until accuracy is proven over time." },
      ],
      answer: 0,
      explain: "Approve right before the step a mistake would be visible or costly.",
    },
    {
      id: "m17-q6", kind: "choice",
      prompt: "Read the error. Which setup handles it best?",
      code: "Node: HubSpot (Create or Update)\nError: 429 Too Many Requests\nAttempt 1 of 3",
      options: [
        { text: "Retry On Fail with a short wait, then alert", why: "A 429 is temporary. Wait, retry, and let the error workflow alert only if all tries fail." },
        { text: "Send it straight to the review queue for a person", why: "It’ll probably succeed in a few seconds; a person doesn’t need to look." },
        { text: "Retry instantly 50 times", why: "Hammering a rate-limited API makes it worse." },
        { text: "Ignore the error and continue", why: "The contact silently never gets saved." },
      ],
      answer: 0,
      explain: "Temporary errors: bounded retries with a wait. Permanent errors: review queue.",
    },
    {
      id: "m17-q7", kind: "choice",
      prompt: "Your main workflow fails at 2am. Nobody notices until a customer complains. What was missing?",
      options: [
        { text: "An error workflow that alerts Slack", why: "Right. An Error Trigger workflow, chosen in the main workflow’s settings, makes failures announce themselves." },
        { text: "More retries on every node that calls an API", why: "Retries help with temporary errors, but someone still needs to know when they run out." },
        { text: "A bigger LLM", why: "Unrelated to being alerted about failures." },
        { text: "A longer README", why: "Documentation doesn’t alert anyone at 2am." },
      ],
      answer: 0,
      explain: "Every production workflow gets an error workflow.",
    },
    {
      id: "m17-q8", kind: "order",
      prompt: "Order the 2-minute demo.",
      items: ["The problem and the baseline number", "A normal enquiry, from arrival to approved reply", "A failure being handled: bad data in the review queue", "The contact in HubSpot, updated not duplicated", "Measured results and the repo link"],
      explain: "Problem, happy path, failure, proof in the CRM, results. Business first, detail second.",
    },
    {
      id: "m17-q9", kind: "choice",
      prompt: "Which test set gives you the most trustworthy accuracy number?",
      options: [
        { text: "35 inputs, a mix of normal, messy, missing-detail, duplicate and edge cases, with expected answers written first", why: "Varied, realistic and judged against answers fixed in advance." },
        { text: "100 copies of the same clean enquiry", why: "Large, but it tests one case 100 times." },
        { text: "10 inputs you picked after seeing which ones worked", why: "Choosing tests after the fact inflates the score." },
        { text: "Whatever came in, judged afterwards by how the output looks", why: "Without expected answers written first, you’ll be too generous." },
      ],
      answer: 0,
      explain: "Variety plus expected answers written before the run.",
    },
    {
      id: "m17-q10", kind: "choice",
      prompt: "An interviewer asks: “What would you do differently?” Which answer is strongest?",
      options: [
        { text: "“Misclassified urgent jobs were my biggest error type, so I’d add an urgent-keyword rule before the LLM and measure again.”", why: "Specific, based on your own test results, with a plan to measure." },
        { text: "“Nothing, it works well.”", why: "Sounds like you haven’t looked closely." },
        { text: "“I’d use a better AI model.”", why: "Vague, and not tied to any evidence." },
        { text: "“I’d rebuild it all from scratch in Python.”", why: "No reason given, and it ignores what you learned." },
      ],
      answer: 0,
      explain: "Point at a measured weakness and a concrete, testable fix.",
    },
    {
      id: "m17-q11", kind: "choice",
      prompt: "You’re applying for an Australian government role that lists Power Automate. How do you present this project?",
      options: [
        { text: "Lead with the business result, then mention your Power Automate rebuild and what you learned comparing it with n8n", why: "It matches their stack and shows the skill transfers." },
        { text: "Only mention n8n; it’s the main build", why: "You’d hide the most relevant evidence for this role." },
        { text: "Claim you built it in Power Automate first", why: "Not true, and easy to disprove from your repo." },
        { text: "Leave the project out because it uses n8n", why: "The process, ROI and testing transfer to any platform." },
      ],
      answer: 0,
      explain: "Tailor what you emphasise, never what happened.",
    },
  ],
  tasks: [
    { device: "phone", plain: "Pick a realistic small business (a trades business, clinic or agency) and write discovery notes for its enquiry handling.", done: "Notes with volume, minutes per enquiry, error rate and at least three exceptions, and a line saying whether the client is real or simulated." },
    { device: "computer", plain: "Draw the before and after process maps, and fill in the ROI table with a baseline you measured by handling 10 enquiries by hand.", done: "Two maps with RULE / AI / HUMAN labels, and an ROI table where each number is marked measured or assumed." },
    { device: "computer", plain: "Build the n8n flow: email or form trigger → LLM extraction and classification with structured output → validation → HubSpot Create or Update → Slack approval → reply.", done: "One test enquiry goes all the way through: a contact appears in HubSpot and a reply is sent only after you click Approve." },
    { device: "computer", plain: "Add an error workflow, Retry On Fail on nodes that call other services, and a review queue for bad data.", done: "With the workflow active, a forced failure posts a Slack alert, and an enquiry with no email lands in the review queue." },
    { device: "computer", plain: "Run 30+ realistic test inputs, including messy and duplicate ones, and record accuracy and time per item.", done: "A filled-in test log with expected answers, accuracy, duplicate count and median time per item." },
    { device: "computer", plain: "Rebuild the core of the flow in Make or Power Automate and note what changed.", done: "A working rebuild run against some of your test inputs, plus a short comparison covering error handling, approvals and pricing." },
    { device: "computer", plain: "Export the n8n workflow JSON, check it for secrets and private data, and publish it to a public GitHub repo with a README.", done: "A public repo with the workflow JSON (no keys or real data), architecture diagram, test results and setup steps." },
    { device: "computer", plain: "Record a 2-minute demo video: a normal case, a failure being handled, and the result in the CRM.", done: "A video under 2 minutes 15 seconds, linked from the README." },
    { device: "phone", plain: "Write a one-page case study using the template: problem, solution, ROI and what you’d do next.", done: "One page where every number comes from your own test runs or is clearly marked as an assumption." },
    { device: "phone", plain: "Publish the case study as a LinkedIn post or portfolio page and link it in every application.", done: "A public link to the case study, added to your CV and application tracker." },
  ],
};
