import type { Lesson } from './types';

export const m2: Lesson = {
  intro: "n8n gets you far, but the hard parts of an automation (messy data, unreliable services, retries, testing) are easier to handle in code. This module teaches Python from zero: not puzzles, but dependable automation code you can write, test and explain without an AI writing it for you.",
  glossary: {
    'variable': 'A name that points at a value, e.g. email = "ana@example.com".',
    'list': 'An ordered collection in square brackets: ["vip", "au"]. The first item is number 0.',
    'dict': 'Dictionary: named fields in curly braces, {"email": "ana@example.com"}. The Python version of a JSON object.',
    'comprehension': 'A one-line way to build a list from another: [x for x in items if condition].',
    'type hint': 'A label saying what type a value should be, e.g. score: int. Python doesn’t enforce it; tools use it to catch mistakes.',
    'function': 'A named, reusable block of code with inputs and an output. Defined with def.',
    'module': 'Any .py file. Other files can import functions from it.',
    'library': 'Code someone else wrote that you install and reuse, e.g. httpx. Also called a package.',
    'httpx': 'A popular Python library for making HTTP requests, with both normal and async versions.',
    'exception': 'Python’s way of signalling that something went wrong. If nothing catches it, the program stops.',
    'traceback': 'The error report Python prints when an exception isn’t caught: the chain of calls, with the actual error on the last line.',
    'utc': 'Coordinated Universal Time: the one clock with no time zone and no daylight saving. Store times in it.',
    'iso 8601': 'The standard text format for dates and times, e.g. 2026-10-07T09:00:00+11:00.',
    'dst': 'Daylight saving time: clocks moving forward or back an hour, so some local times happen twice or never.',
    'pydantic': 'A Python library that checks data against a shape you declare and converts it to proper types.',
    'event loop': 'The part of async Python that switches between tasks while they wait.',
    'fixture': 'In pytest, shared setup (sample data, a fake client) handed to any test that asks for it by name.',
    'mock': 'A fake stand-in for a real system (like an API) that returns exactly what your test tells it to.',
  },
  sections: [
    {
      title: 'Python basics: values, lists and dictionaries',
      minutes: 6,
      body: [
        "**The problem.** In n8n the data shape is shown to you and you drag fields around. In Python you hold the data yourself and shape it with code. Good news: n8n items are JSON, and JSON maps almost one-to-one onto Python.",
        "A [[variable]] is a name pointing at a value: `email = \"ana@example.com\"`. Every value has a type:",
        "- `str`: text, in quotes.\n- `int` and `float`: whole and decimal numbers, `42` and `19.95`.\n- `bool`: `True` or `False` (capitalised, unlike JSON).\n- `None`: nothing. Python’s version of JSON `null`.",
        "Three containers do most of the work:",
        "- A [[list]] holds items in order: `tags = [\"vip\", \"au\"]`. `tags[0]` is the first; counting starts at 0.\n- A [[dict]] holds named fields, exactly like a JSON object: `lead[\"score\"]` reads one.\n- A **set** holds unique values only. `seen = set()` is the standard way to spot duplicates.",
        "**Missing fields.** `lead[\"phone\"]` crashes with `KeyError` if there’s no phone field. `lead.get(\"phone\")` returns `None` instead. Choose on purpose: crash on fields you require, use `.get` for optional ones.",
        "A [[comprehension]] builds a list in one line. `[l[\"email\"] for l in leads if l[\"score\"] > 50]` reads as “the email of every lead scoring over 50”. An **f-string** puts values into text: `f\"Lead {lead_id} synced\"`.",
        "[[Type hint|Type hints]] label what a value should be: `score: int = 80`. Python doesn’t enforce them while running, but your editor and checkers use them to catch mistakes before you run anything. Professional code uses them everywhere.",
      ],
      example: {
        caption: 'One n8n-style item, in Python',
        code: 'lead = {                                    # a dict, like one n8n item\n    "email": "  Ana@Example.com ",\n    "score": 80,\n    "tags": ["vip", "au"],                  # a list inside the dict\n    "phone": None,                          # JSON null becomes None\n}\nemail = lead["email"].strip().lower()       # "ana@example.com"\nis_vip = "vip" in lead["tags"]              # True\ncompany = lead.get("company", "unknown")    # missing field -> default\n\nleads = [lead, {"email": "bo@x.com", "score": 30, "tags": []}]\nhot = [l["email"] for l in leads if l["score"] > 50]\nprint(hot)                                  # [\'  Ana@Example.com \']',
      },
      interview: "I model integration data with Python’s core structures: dicts for records, lists for ordered results and sets for fast membership and deduplication. I’m deliberate about required versus optional fields, indexing for required keys and using .get with a default for optional ones, and I use type hints so tooling catches shape mistakes early.",
      check: [
        {
          id: 'm2-s0-1', kind: 'choice',
          prompt: 'What does this print?',
          code: 'tags = ["vip", "au", "new"]\nprint(tags[1])',
          options: [
            { text: 'au', why: 'Yes. Counting starts at 0, so index 1 is the second item.' },
            { text: 'vip', why: 'That’s tags[0]. Counting from 1 is the common mix-up; Python counts from 0.' },
            { text: 'new', why: 'That’s tags[2], the third item.' },
            { text: 'IndexError', why: 'Index 1 exists: there are three items, at 0, 1 and 2.' },
          ],
          answer: 0,
          explain: 'Python counts from 0. The last item is also reachable as tags[-1].',
        },
        {
          id: 'm2-s0-2', kind: 'choice',
          prompt: 'Phone is optional on your leads. Your script crashes with `KeyError: \'phone\'` on a lead without one. What’s the right fix?',
          options: [
            { text: 'Use `lead.get("phone")`, which gives None if the field is absent', why: 'Right. .get is for optional fields: no crash, just None.' },
            { text: 'Use `lead["phone"] or None`, so a missing phone falls back to None', why: 'The `or` never runs: `lead["phone"]` raises KeyError before it gets the chance.' },
            { text: 'Check `if lead["phone"] is not None:` before using the phone', why: 'Reading `lead["phone"]` inside the check is what raises KeyError.' },
            { text: 'Use `lead.phone`, which returns None for fields the dict lacks', why: 'Dicts don’t expose keys as attributes; this raises AttributeError.' },
          ],
          answer: 0,
          explain: 'Required field → `lead["x"]` (fail loudly). Optional field → `lead.get("x")`.',
        },
        {
          id: 'm2-s0-3', kind: 'choice',
          prompt: 'You’re processing 10,000 webhook events and need to skip any event ID you’ve already seen in this batch. Which structure?',
          options: [
            { text: 'A set of seen IDs, checked with `in` per event', why: 'Yes. Sets hold unique values and membership checks are instant.' },
            { text: 'A list of seen IDs, checked with `in`', why: 'It works, but `in` on a list scans every item, so 10,000 checks get slow.' },
            { text: 'A tuple of seen IDs, since IDs never change', why: 'Tuples can’t be added to, so you can’t record new IDs as you go.' },
            { text: 'One long string of IDs joined by commas', why: 'Searching text is slow and error-prone: ID 12 matches inside 123.' },
          ],
          answer: 0,
          explain: '`if event_id in seen: continue`, then `seen.add(event_id)`. Lasting deduplication across runs belongs in a database, which comes later.',
        },
      ],
    },
    {
      title: 'Functions, loops, modules and files',
      minutes: 7,
      body: [
        "**The problem.** A script that’s one long list of instructions works once. Then you need the same clean-up in three places, or you want to test it. Functions fix that.",
        "A [[function]] is a named, reusable step with inputs and an output, like a mini n8n node. `def` defines it; `return` hands back the result. Indentation (4 spaces) shows what’s inside it.",
        "A `for` loop repeats for each item: `for lead in leads:`. `if` / `elif` / `else` pick a branch, like an IF node.",
        "**Keep functions small and single-purpose.** A function that cleans an email shouldn’t also call the CRM and write to a database. Separate fetch, validate, transform and save. The middle parts, with no network or database, are easy to test. A 40-line function mixing HTTP, business rules, database writes and LLM calls is very hard to test.",
        "**Modules.** Any `.py` file is a [[module]]. Put helpers in `transform.py` and use them elsewhere with `from transform import normalise_email`. Python’s built-in tools work the same way: `import json`.",
        "**Files.** `with open(\"leads.json\") as f:` opens a file and closes it automatically when the block ends, even if something fails. Inside, `json.load(f)` turns JSON text into dicts and lists; `json.dump(data, f)` writes them back. `json.loads` and `json.dumps` do the same with text instead of a file.",
        "**Running as a script.** Code under `if __name__ == \"__main__\":` runs only when you run the file directly (`python sync.py`), not when another file imports it. That keeps imports side-effect free.",
      ],
      example: {
        caption: 'sync.py: read leads, clean them, write them out',
        code: 'import json\n\ndef normalise_email(value: str) -> str:\n    """Basic clean-up, not full email validation."""\n    result = value.strip().lower()\n    if "@" not in result:\n        raise ValueError(f"Invalid email: {value!r}")   # stop on bad input\n    return result\n\ndef main() -> None:\n    with open("leads.json") as f:          # closes automatically\n        leads = json.load(f)               # JSON text -> list of dicts\n\n    for lead in leads:\n        lead["email"] = normalise_email(lead["email"])\n\n    with open("cleaned.json", "w") as f:   # "w" = write, replaces the file\n        json.dump(leads, f, indent=2)\n\nif __name__ == "__main__":                 # only when run directly\n    main()',
      },
      interview: "I structure scripts as small functions with clear inputs and outputs, separating I/O from pure transformation logic so the logic is trivially testable. Helpers live in modules, files are handled with context managers, and the entry point sits behind a main guard so importing has no side effects.",
      check: [
        {
          id: 'm2-s1-1', kind: 'choice',
          prompt: 'What does this print?',
          code: 'def add_gst(amount: float) -> float:\n    total = amount * 1.1\n\nprint(add_gst(100))',
          options: [
            { text: 'None, since the function never returns a value', why: 'Yes. Without `return`, a function gives back None.' },
            { text: '110.0, since total is the last value computed', why: 'Python doesn’t return the last value automatically (some languages do). No `return`, no value.' },
            { text: 'Nothing at all: print skips None values', why: 'print shows None literally; it doesn’t skip it.' },
            { text: 'A NameError, because total only exists inside', why: 'The print line never mentions total, so there’s no NameError; it just gets None.' },
          ],
          answer: 0,
          explain: 'A function’s output is whatever it `return`s. Forgetting `return` is a classic beginner bug.',
        },
        {
          id: 'm2-s1-2', kind: 'choice',
          prompt: 'Why keep `normalise_email` separate from the code that calls the CRM?',
          options: [
            { text: 'You can test it instantly with plain inputs, no network or CRM needed', why: 'Right. Pure functions are the easiest code to test and reuse.' },
            { text: 'Python runs separate functions in parallel, so the sync finishes sooner', why: 'Functions run one after another unless you add concurrency yourself.' },
            { text: 'Each function gets its own memory, so a CRM failure can’t crash it', why: 'An uncaught exception travels up through every caller regardless of how code is split.' },
            { text: 'Shorter functions run faster, because Python compiles them separately', why: 'Splitting code doesn’t meaningfully change speed; the benefit is testability.' },
          ],
          answer: 0,
          explain: 'Separate decisions (pure logic) from effects (HTTP, database). Test the logic directly; fake the effects.',
        },
      ],
    },
    {
      title: 'Calling APIs with httpx',
      minutes: 7,
      body: [
        "**The problem.** n8n’s HTTP Request node makes many choices for you. In Python you make the call yourself, so you choose the timeout, the headers and what counts as a failure.",
        "Two popular [[library|libraries]]: `requests` (the classic) and [[httpx]] (similar style, plus async support). Install into your virtual environment and pin the version in `requirements.txt`. A [[lock file]] (from uv or Poetry) pins every sub-dependency too, so the server installs exactly what you tested.",
        "**Always set a timeout.** A [[timeout]] is the longest you’ll wait for a reply. `requests` waits forever by default. `httpx` defaults to 5 seconds, but set it explicitly so the choice is visible. Remember: a timeout on a write means “unknown outcome”, not “failed”.",
        "The parts map straight onto the HTTP node: `params=` for [[query parameters]], `headers=` for auth and content type, `json=` for the body.",
        "**Check the status.** A 404 or 500 is *not* a Python error by itself; you did get a response. `response.raise_for_status()` turns 4xx/5xx into an exception, so you can’t carry on with an error body by accident.",
        "Use a **Client** for repeated calls. It reuses the connection and holds shared settings: base URL, auth header, timeout.",
        "[[Pagination]]: most APIs return one page plus a cursor for the next. Loop until there’s no cursor. If you save a [[checkpoint]], advance it only after that page’s records are stored safely.",
        "`response.json()` gives you whatever the server sent, unchecked. Lesson 5 turns it into validated, typed objects.",
      ],
      example: {
        caption: 'Fetching every contact, page by page',
        code: 'import os\nimport httpx\n\nclient = httpx.Client(\n    base_url="https://api.example-crm.com/v1",\n    headers={"Authorization": f"Bearer {os.environ[\'CRM_TOKEN\']}"},\n    timeout=10.0,                          # seconds; never wait forever\n)\n\ndef fetch_all_contacts() -> list[dict]:\n    contacts, cursor = [], None\n    while True:\n        params = {"limit": 100}\n        if cursor:\n            params["cursor"] = cursor\n        response = client.get("/contacts", params=params)\n        response.raise_for_status()        # 4xx/5xx -> exception\n        page = response.json()\n        contacts.extend(page["results"])\n        cursor = page.get("next_cursor")   # None on the last page\n        if not cursor:\n            return contacts',
      },
      interview: "I use a shared httpx client with a base URL, auth headers and explicit timeouts, and call raise_for_status so HTTP errors can’t pass silently. Pagination follows the provider’s cursor until exhausted, with checkpoints advanced only after records are persisted. Dependencies are pinned with a lock file for reproducible installs.",
      check: [
        {
          id: 'm2-s2-1', kind: 'choice',
          prompt: 'An overnight script using `requests.get(url)` sat frozen for six hours on one call. What was missing?',
          options: [
            { text: 'A timeout, e.g. `requests.get(url, timeout=10)`', why: 'Yes. requests has no default timeout, so it can wait forever.' },
            { text: '`raise_for_status()`, so the error stops the script', why: 'That checks a response’s status; this call never got a response to check.' },
            { text: 'A retry loop, so the stuck call gets tried again', why: 'A retry only happens after the call returns or fails, and this one never did.' },
            { text: 'A `try/except`, so the failing call is skipped', why: 'Nothing was raised, so there was nothing to catch; it just waited.' },
          ],
          answer: 0,
          explain: 'Every network call gets an explicit timeout. Always.',
        },
        {
          id: 'm2-s2-2', kind: 'choice',
          prompt: 'This crashes with `KeyError: \'results\'`. The API actually returned 401 with `{"error": "invalid token"}`. What would have made the real problem obvious?',
          code: 'r = client.get("/contacts")\ndata = r.json()["results"]',
          options: [
            { text: 'Calling `r.raise_for_status()` before reading the body', why: 'Yes. It would raise an HTTP 401 error instead of a confusing KeyError.' },
            { text: 'Using `r.json().get("results")` so a missing key is safe', why: 'You’d get None and carry on with no contacts, hiding the 401.' },
            { text: 'Wrapping it in `try/except KeyError` and logging the key', why: 'You’d still log “missing results”, not the real cause: an invalid token.' },
            { text: 'Checking `if r.json():` so empty bodies are skipped', why: 'The error body isn’t empty, so the check passes and the KeyError still happens.' },
          ],
          answer: 0,
          explain: 'Check the status before trusting the body. Error bodies don’t look like success bodies.',
        },
      ],
    },
    {
      title: 'When things go wrong: exceptions and logs',
      minutes: 7,
      body: [
        "**The problem.** APIs time out, records are malformed, tokens expire. Python signals failure with an [[exception]]. If nothing catches it, the script stops and prints a [[traceback]]. Read tracebacks **from the bottom**: the last line says what went wrong; the lines above show how you got there.",
        "`try` / `except` catches an exception so you can respond. The rule: **catch narrow**. Catch only errors you know how to handle, by name. `except Exception: pass` hides every bug, like an n8n node set to continue on fail with nothing checking the output. Let unexpected errors reach one top-level handler that logs them.",
        "Sort failures into two kinds:",
        "- **Retryable** (temporary): timeouts, connection errors, 429, 5xx. Retry a few times with [[exponential backoff]].\n- **Permanent**: 400 or 422 (bad data), 404, and 401/403 (needs a new token or permission). Retrying won’t help; reject the record or alert someone. Exhausted retries go to a [[dead-letter queue]].",
        "When you translate an error, keep the original: `raise SyncError(\"CRM write failed\") from e` keeps both in the traceback. `finally:` runs whether or not something failed, e.g. to close a connection.",
        "**Logging** is how you find out later what happened. Use Python’s `logging` module, not `print`: each line gets a time and a level (`DEBUG`, `INFO`, `WARNING`, `ERROR`), and production can hide the noisy levels. Inside an `except`, `log.exception(...)` also records the traceback.",
        "Make log lines **structured**: fixed field names like `event_id=evt_42`, or full JSON, so you can search them. Put the event or [[correlation id]] in every line. **Never log secrets**: no tokens, no full request headers, and as little personal data as possible.",
      ],
      example: {
        caption: 'Classifying failures, with useful logs',
        code: 'import logging\nimport httpx\n\nlogging.basicConfig(level=logging.INFO,\n                    format="%(asctime)s %(levelname)s %(message)s")\nlog = logging.getLogger(__name__)\n\nRETRYABLE = {429, 500, 502, 503, 504}\n\ndef sync_lead(client: httpx.Client, lead: dict, event_id: str) -> str:\n    try:\n        r = client.post("/contacts", json=lead)\n        r.raise_for_status()\n    except httpx.TimeoutException:\n        log.warning("crm timeout event_id=%s outcome=unknown", event_id)\n        return "retry"          # unknown: check before re-sending\n    except httpx.HTTPStatusError as e:\n        code = e.response.status_code\n        log.error("crm rejected event_id=%s status=%s", event_id, code)\n        return "retry" if code in RETRYABLE else "reject"\n    # anything else (a bug, a dropped connection) is not caught here:\n    # it reaches the top-level handler and is logged with its traceback\n    log.info("lead synced event_id=%s", event_id)\n    return "ok"',
      },
      interview: "I catch narrow, expected exceptions where I can recover and let unexpected ones reach a top-level handler, chaining with raise-from to preserve context. Failures are classified as retryable (timeouts, connection errors, 429, 5xx) or permanent (validation, auth, not found). Logs are structured, carry a correlation ID, and never include tokens or unnecessary personal data.",
      check: [
        {
          id: 'm2-s3-1', kind: 'choice',
          prompt: 'Which response should you **not** retry?',
          options: [
            { text: '422 Unprocessable Entity: the email field is invalid', why: 'Right. The same bad data will fail the same way every time.' },
            { text: '503 Service Unavailable: the CRM is down for maintenance', why: 'Maintenance ends. It’s temporary, so retry with backoff.' },
            { text: '429 Too Many Requests: you hit the rate limit', why: 'Slow down and retry later, honouring Retry-After if given.' },
            { text: 'A connection timeout: the CRM didn’t answer in 10s', why: 'Often temporary, though for writes check whether it already happened.' },
          ],
          answer: 0,
          explain: 'Permanent failures get rejected with a reason; temporary ones get bounded retries.',
        },
        {
          id: 'm2-s3-2', kind: 'choice',
          prompt: 'What’s wrong with this code?',
          code: 'try:\n    sync_all_leads()\nexcept Exception:\n    pass',
          options: [
            { text: 'Every failure, including real bugs, is silently swallowed', why: 'Yes. Leads could fail for weeks with no trace.' },
            { text: 'Nothing; it keeps the scheduled job from crashing overnight', why: 'Not crashing while doing nothing useful is worse than crashing loudly.' },
            { text: 'It should catch `BaseException` so nothing slips through', why: 'That swallows even more, including Ctrl+C. Catching too much is the problem.' },
            { text: '`pass` should be `continue` so the next lead gets synced', why: 'There’s no loop here, so `continue` is a SyntaxError; and it would still hide errors.' },
          ],
          answer: 0,
          explain: 'Catch specific errors you can handle. Log everything else loudly.',
        },
        {
          id: 'm2-s3-3', kind: 'choice',
          prompt: 'A teammate adds `log.info("calling CRM headers=%s", headers)`. What’s the problem?',
          options: [
            { text: 'The auth token inside those headers ends up in the logs', why: 'Yes. Logs are read by many people and tools; secrets don’t belong there.' },
            { text: 'INFO is too low; request details belong at ERROR level', why: 'The level isn’t the issue; the content is. Nothing has failed yet either.' },
            { text: 'It’s fine, since the log files only live on our own server', why: 'Logs get shipped, shared and kept for ages. A leaked token is still leaked.' },
            { text: 'Use an f-string; logging can’t fill in `%s` by itself', why: 'It can: logging fills %s in for you, and only when the line is actually emitted.' },
          ],
          answer: 0,
          explain: 'Log IDs and outcomes, never credentials.',
        },
      ],
    },
    {
      title: 'Trust nothing: dates, time zones and Pydantic',
      minutes: 7,
      body: [
        "**Dates first.** A client in Sydney books for 9am, your server runs in UTC and the CRM shows US time. A time without a time zone is a guess. The rules:",
        "- Store and compare times in [[UTC]]. Convert to local time only for display, or for rules like “9am in the client’s time zone”.\n- Exchange them as [[ISO 8601]] text: `2026-10-07T09:00:00+11:00`, or ending in `Z` for UTC.\n- Use **aware** datetimes, which carry their zone: `datetime.now(timezone.utc)`, not `datetime.now()`. Python refuses to compare aware and naive (zone-less) ones and raises a `TypeError`.",
        "[[DST|Daylight saving]] moves local clocks, so some local times happen twice or never. A job “every day at 2:30am Sydney time” has no 2:30am on the morning clocks go forward. Schedule in UTC, or handle those days on purpose. `ZoneInfo(\"Australia/Sydney\")` knows each zone’s rules.",
        "**Now validation.** `response.json()` returns plain dicts. Nothing stops a field being missing, misspelt or `\"N/A\"`, and you find out three steps later, somewhere confusing. [[Pydantic]] lets you declare the shape you expect as a class, then checks incoming data against it:",
        "- Fields are declared with type hints. A missing or wrong field raises a `ValidationError` naming the exact field and why.\n- It converts where safe: an ISO string becomes a real `datetime`, `\"80\"` becomes `80`.\n- `model_dump()` turns the object back into a dict.",
        "**Validate at the boundary**, the moment data enters. Then decide: does one bad record stop the batch, or go to a rejected list with the reason and enough context to replay it later? Never drop it silently.",
      ],
      example: {
        caption: 'Validate each record; keep the rejects with their reasons',
        code: 'from datetime import datetime, timezone\nfrom pydantic import BaseModel, ValidationError\n\nclass Lead(BaseModel):\n    id: str\n    email: str\n    score: int = 0             # optional, defaults to 0\n    created_at: datetime       # ISO text -> datetime\n\ngood, rejected = [], []\nfor raw in records:            # records = list of dicts from the API\n    try:\n        good.append(Lead.model_validate(raw))\n    except ValidationError as e:\n        rejected.append({"record": raw, "errors": e.errors()})\n\nlead = Lead.model_validate({"id": "L1", "email": "a@x.com",\n                            "created_at": "2026-10-07T09:00:00+11:00"})\nprint(lead.created_at.astimezone(timezone.utc))   # 2026-10-06 22:00:00+00:00',
      },
      interview: "I store timestamps as timezone-aware UTC, exchange them as ISO 8601, and convert to local zones only at the edges, with DST handled explicitly for scheduling. External input is validated at the boundary with Pydantic models, so bad records fail with field-level errors and are quarantined with context for replay, instead of propagating as untyped dicts.",
      check: [
        {
          id: 'm2-s4-1', kind: 'choice',
          prompt: 'This raises `TypeError: can\'t compare offset-naive and offset-aware datetimes`. What’s the fix?',
          code: 'if datetime.now() > lead.created_at:   # created_at is UTC-aware\n    ...',
          options: [
            { text: 'Use `datetime.now(timezone.utc)` so both are aware', why: 'Yes. Compare aware with aware, in UTC.' },
            { text: 'Use `datetime.utcnow()`, which returns the time in UTC', why: 'It gives UTC clock time but still naive (no tzinfo), so the TypeError stays.' },
            { text: 'Call `.replace(tzinfo=None)` on created_at to match', why: 'It runs, but compares UTC with your server’s local time: silently wrong.' },
            { text: 'Compare `.isoformat()` strings instead of datetimes', why: 'Text comparison breaks across different offsets and formats.' },
          ],
          answer: 0,
          explain: 'Naive datetimes are guesses. Use aware UTC everywhere inside your code.',
        },
        {
          id: 'm2-s4-2', kind: 'choice',
          prompt: 'In a batch of 500 leads, record 37 has `"score": "N/A"`. Your business rule says one bad lead must not block the rest. What do you do?',
          options: [
            { text: 'Put it in a rejected list with its error and raw data, then continue', why: 'Right. It’s visible, replayable and the other 499 go through.' },
            { text: 'Default its score to 0 so it validates, and log a warning with its ID', why: 'You’d be inventing data the source never said, and scoring rules would act on it.' },
            { text: 'Stop the batch, fix record 37 by hand, then rerun all 500 leads', why: 'That breaks the stated rule: one bad lead must not block the rest.' },
            { text: 'Catch the ValidationError and `continue` on to the next lead', why: 'The lead vanishes with no record of why. Never drop data silently.' },
          ],
          answer: 0,
          explain: 'Choose the policy deliberately (stop or quarantine), but always keep the reason and the record.',
        },
        {
          id: 'm2-s4-3', kind: 'choice',
          prompt: 'Using the `Lead` model above, what is `lead.score` after `Lead.model_validate({..., "score": "80"})`?',
          options: [
            { text: 'The number 80', why: 'Yes. By default Pydantic converts text that clearly represents a number.' },
            { text: 'The text "80", unchanged', why: 'The field is declared as int, so Pydantic converts it.' },
            { text: '0, the declared default', why: 'The default is only used when the field is missing.' },
            { text: 'A ValidationError for type', why: '"80" converts cleanly. "N/A" would fail.' },
          ],
          answer: 0,
          explain: 'Pydantic converts where it’s safe and rejects where it isn’t. (Strict mode turns conversion off.)',
        },
      ],
    },
    {
      title: 'Async: many API calls at once, and when not to bother',
      minutes: 6,
      body: [
        "**The problem.** You need to enrich 500 leads. Each API call takes about a second, almost all of it *waiting* for the other server. One after another, that’s over 8 minutes of your program mostly doing nothing.",
        "**Async** lets one program start a call and, while it waits, start others. **The analogy:** a waiter doesn’t stand at one table until the food arrives; they take other orders meanwhile.",
        "- `async def` defines a function that can pause.\n- `await` marks the pause: “wait for this, and let other work run meanwhile”.\n- The [[event loop]] is the waiter, switching between paused tasks. `asyncio.run(main())` starts it.\n- `asyncio.gather(...)` runs several tasks and waits for all of them.",
        "**Limit how many run at once.** That’s your [[concurrency]]. Firing 500 requests at once will hit the [[rate limit]]. `asyncio.Semaphore(5)` lets at most 5 run at a time.",
        "**The trap.** Async only helps while waiting on the network or disk. A blocking call inside an async function, like `time.sleep()` or `requests.get()`, freezes *every* task, because the waiter is stuck too. Use async versions: `await asyncio.sleep()` and `httpx.AsyncClient`. Heavy calculation doesn’t get faster with async either.",
        "**When plain code is better:** a script making a handful of calls, an API that only allows a few requests a second anyway, or a flow you’re still figuring out. Normal (sync) code is easier to read and debug. Reach for async when waiting is clearly the bottleneck. You’ll also need to read it: FastAPI, in the FastAPI module, is async.",
      ],
      example: {
        caption: 'Enrich many leads, at most 5 at a time',
        code: 'import asyncio\nimport httpx\n\nasync def enrich(client, sem, email: str) -> dict:\n    async with sem:                         # wait for a free slot (max 5)\n        r = await client.get("/enrich", params={"email": email})\n        r.raise_for_status()\n        return r.json()\n\nasync def main(emails: list[str]) -> list[dict]:\n    sem = asyncio.Semaphore(5)\n    async with httpx.AsyncClient(base_url="https://api.example.com",\n                                 timeout=10.0) as client:\n        return await asyncio.gather(*(enrich(client, sem, e) for e in emails))\n\nresults = asyncio.run(main(["a@x.com", "b@x.com"]))',
      },
      interview: "I use async for I/O-bound fan-out, like many independent API calls, with an async client and a semaphore to bound concurrency below the provider’s rate limit. I avoid blocking calls inside coroutines because they stall the event loop, and I keep CPU-heavy work out of it. For a few sequential calls, sync code is simpler and I prefer it.",
      check: [
        {
          id: 'm2-s5-1', kind: 'choice',
          prompt: 'Your async enrichment script is no faster than the old one. Inside `async def enrich`, it calls `requests.get(url, timeout=10)`. Why?',
          options: [
            { text: '`requests` blocks the event loop, so calls run one by one', why: 'Yes. Use httpx.AsyncClient and await the call.' },
            { text: 'The 10-second timeout makes each call wait its full length', why: 'A timeout is a maximum, not a fixed wait; it doesn’t stop calls overlapping.' },
            { text: 'asyncio runs on one CPU core, so calls can’t truly overlap', why: 'Async overlaps waiting on one core; that’s the point. Cores aren’t the limit here.' },
            { text: 'Async needs a newer Python; older versions run it in order', why: 'Any supported Python runs async properly. The blocking call is the problem.' },
          ],
          answer: 0,
          explain: 'In async code, every slow call must be awaitable. One blocking call stalls everything.',
        },
        {
          id: 'm2-s5-2', kind: 'choice',
          prompt: 'Which job benefits most from async?',
          options: [
            { text: 'Looking up 300 companies via an API allowing 10 calls at once', why: 'Right. Lots of waiting, and the API allows overlap.' },
            { text: 'Resizing 300 large product images stored on your laptop', why: 'That’s calculation, not waiting. Async won’t speed it up.' },
            { text: 'Pulling 300 records from an API that’s capped at 1 call per second', why: 'The limit forces one-at-a-time anyway, so there’s nothing to overlap.' },
            { text: 'Parsing a 2 GB CSV file of leads that is already downloaded', why: 'That’s mostly CPU work on local data; async doesn’t help.' },
          ],
          answer: 0,
          explain: 'Async pays off with many waits that are allowed to overlap.',
        },
      ],
    },
    {
      title: 'Testing with pytest, including the failures',
      minutes: 7,
      body: [
        "**The problem.** You change one line and something three functions away breaks. You find out when a client complains. Tests are small programs that check your code still does what you promised, in seconds, every time.",
        "[[pytest]] finds files named `test_*.py`, runs every function whose name starts with `test_`, and reports any `assert` that failed. Run `pytest` in the project folder.",
        "- `assert result == \"ana@example.com\"`: the check.\n- `with pytest.raises(ValueError):` checks that bad input fails the right way.\n- `@pytest.mark.parametrize` runs one test with many inputs.\n- A [[fixture]] is shared setup, like sample data or a fake client, that pytest passes to any test naming it as a parameter.",
        "**Never call the real API in unit tests.** It’s slow, can cost money, changes real data and fails for reasons that aren’t your bug. Instead, [[mock]] the boundary: replace the HTTP call with a fake that returns exactly the response you choose. That’s how you test the scary cases on demand: 429, 500, a timeout, a duplicate event, malformed data.",
        "httpx makes this easy if your function *receives* its client: in tests, pass one built with `httpx.MockTransport`, which answers with your fake response. Libraries like `respx` (for httpx) and `responses` (for requests) do the same job.",
        "**Test behaviour, not implementation.** Assert what the business cares about: how many records were written, the final status, how many retries happened, that a duplicate didn’t create a second contact.",
        "Separately, keep a small integration test against the provider’s sandbox where one exists. `pytest-cov` measures coverage (`pytest --cov`); aim for meaningful tests of your own code, not just a number.",
      ],
      example: {
        caption: 'test_sync.py: plain logic, then faked HTTP failures',
        code: 'import httpx\nimport pytest\nfrom sync import normalise_email, sync_lead\n\n@pytest.mark.parametrize("raw, expected", [\n    ("  Ana@Example.com ", "ana@example.com"),\n    ("BO@X.COM", "bo@x.com"),\n])\ndef test_normalise_email(raw, expected):\n    assert normalise_email(raw) == expected\n\ndef test_rejects_email_without_at():\n    with pytest.raises(ValueError):\n        normalise_email("not-an-email")\n\ndef fake_crm(status: int) -> httpx.Client:\n    def handler(request: httpx.Request) -> httpx.Response:\n        return httpx.Response(status, json={})     # the pretend reply\n    return httpx.Client(base_url="https://crm.test",\n                        transport=httpx.MockTransport(handler))\n\ndef test_429_is_retried():\n    assert sync_lead(fake_crm(429), {"email": "a@x.com"}, "evt_1") == "retry"\n\ndef test_422_is_rejected():\n    assert sync_lead(fake_crm(422), {"email": "a@x.com"}, "evt_2") == "reject"',
      },
      interview: "I unit-test pure logic directly with parametrised cases, and test integration code by injecting the HTTP client and mocking the transport, so I can reproduce 429s, 5xx, timeouts, duplicates and malformed payloads deterministically. Assertions target business outcomes like writes, final state and retry counts. A small integration suite runs separately against a sandbox.",
      check: [
        {
          id: 'm2-s6-1', kind: 'choice',
          prompt: 'This test always passes, even when `sync_lead` is broken. Why?',
          code: 'def test_sync_handles_500():\n    sync_lead(fake_crm(500), {"email": "a@x.com"}, "evt_1")',
          options: [
            { text: 'It never asserts anything about what the result is', why: 'Yes. Add `assert ... == "retry"`, or it only proves the code didn’t crash.' },
            { text: 'fake_crm ignores the status and always returns 200', why: 'The handler returns whatever status you pass, here 500.' },
            { text: 'MockTransport skips the handler unless a fixture is used', why: 'MockTransport calls the handler on every request; fixtures are optional.' },
            { text: 'The event ID "evt_1" was already used by another test', why: 'Tests don’t share state here; the ID is fine. The test just checks nothing.' },
          ],
          answer: 0,
          explain: 'A test without an assertion about behaviour is decoration.',
        },
        {
          id: 'm2-s6-2', kind: 'choice',
          prompt: 'How would you test what `sync_lead` does on a timeout, without waiting for a real one?',
          options: [
            { text: 'Have the mock handler raise `httpx.ReadTimeout`, assert "retry"', why: 'Right. The mock reproduces the failure instantly and every time.' },
            { text: 'Set `timeout=0.001` on the real CRM client so every call times out', why: 'It hits the real CRM, is flaky, and might still create data. Not repeatable in CI.' },
            { text: 'Mock a 504 Gateway Timeout response and assert "retry"', why: 'A 504 is a response, so it tests the HTTPStatusError path, not a client timeout.' },
            { text: 'Use `time.sleep(11)` in the handler to exceed the timeout', why: 'MockTransport doesn’t enforce timeouts, so the test just runs slowly and returns.' },
          ],
          answer: 0,
          explain: 'Mocks let you trigger rare failures on demand, so failure paths are tested like the happy path.',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'm2-q1', kind: 'choice',
      prompt: 'What does this print?',
      code: 'leads = [{"score": 10}, {"score": 70}, {"score": 90}]\nhot = [l for l in leads if l["score"] > 50]\nprint(len(hot))',
      options: [
        { text: '2', why: 'Yes. 70 and 90 are over 50.' },
        { text: '3', why: '10 doesn’t pass the filter.' },
        { text: '160', why: 'len counts items; it doesn’t add scores.' },
        { text: '[70, 90]', why: 'len returns a count, not the matching values.' },
      ],
      answer: 0,
      explain: 'A comprehension with `if` filters the list; `len` counts what’s left.',
    },
    {
      id: 'm2-q2', kind: 'choice',
      prompt: 'Read the traceback. What happened?',
      code: 'Traceback (most recent call last):\n  File "sync.py", line 30, in <module>\n    main()\n  File "sync.py", line 22, in main\n    lead["email"] = normalise_email(lead["email"])\nKeyError: \'email\'',
      options: [
        { text: 'A lead in the data is missing its "email" field', why: 'Yes. The last line names the missing key, and the line above shows where.' },
        { text: 'normalise_email raised it on a bad email address', why: 'The KeyError came from reading lead["email"], before normalise_email ran.' },
        { text: 'main() on line 30 was called with the wrong arguments', why: 'Line 30 is just the start of the chain. Read from the bottom.' },
        { text: 'The JSON file failed to load, so leads is empty', why: 'An empty list would skip the loop entirely, with no KeyError.' },
      ],
      answer: 0,
      explain: 'Read tracebacks bottom-up: error type and message first, then the line that triggered it.',
    },
    {
      id: 'm2-q3', kind: 'order',
      prompt: 'Order the steps of a safe sync script for one page of records.',
      items: ['Fetch the page from the API', 'Validate each record with a Pydantic model', 'Transform valid records into the destination’s format', 'Upsert them into the destination', 'Advance the saved checkpoint'],
      explain: 'Move the checkpoint last, so a crash mid-page means re-processing it, not losing it.',
    },
    {
      id: 'm2-q4', kind: 'choice',
      prompt: 'Your loop keeps retrying a CRM call that returns **401 Unauthorized**. What should it do instead?',
      options: [
        { text: 'Stop retrying and alert that the CRM token needs reconnecting', why: 'Yes. Auth failures need a new token, not more attempts.' },
        { text: 'Keep retrying with exponential backoff until the CRM accepts it', why: 'Waiting doesn’t fix an invalid token; it will 401 forever.' },
        { text: 'Retry three times, then move on to the next record quietly', why: 'Every following record fails the same way, unnoticed.' },
        { text: 'Ask the CRM admin to grant the integration more permissions', why: 'That’s the fix for 403 (forbidden). 401 means the token itself isn’t accepted.' },
      ],
      answer: 0,
      explain: 'Retry temporary failures; diagnose permanent ones. 401/403 are permanent until someone acts.',
    },
    {
      id: 'm2-q5', kind: 'choice',
      prompt: 'A POST to create an invoice times out. What do you know?',
      options: [
        { text: 'Nothing certain: the invoice may or may not exist now', why: 'Right. Check, or use an idempotency key, before sending it again.' },
        { text: 'The invoice was not created, so it’s safe to send again', why: 'The server may have created it; only the reply was lost. Resending risks a duplicate.' },
        { text: 'It was created; the server just took too long to reply', why: 'Maybe, but the request might also never have arrived. You don’t know.' },
        { text: 'The request never reached the server, so nothing happened', why: 'It may have arrived and been processed. A timeout doesn’t tell you which.' },
      ],
      answer: 0,
      explain: 'A timeout on a write is an unknown outcome. Blind retries can create duplicates.',
    },
    {
      id: 'm2-q6', kind: 'choice',
      prompt: 'Which log line is best?',
      options: [
        { text: '`lead sync failed event_id=evt_42 status=429 attempt=3`', why: 'Yes. Searchable fields, an ID to trace and no secrets.' },
        { text: '`lead sync failed for ana@example.com, will retry soon`', why: 'Personal data instead of an ID, and no status or attempt to search on.' },
        { text: '`ERROR: Something went wrong syncing the lead, retrying`', why: 'No way to tell what failed, or for which event.' },
        { text: '`lead sync failed event_id=evt_42 auth=Bearer eyJhbGci…`', why: 'It has the ID, but it leaks the token. Never log credentials.' },
      ],
      answer: 0,
      explain: 'Structured fields + correlation ID + no secrets.',
    },
    {
      id: 'm2-q7', kind: 'choice',
      prompt: 'An API sends `"created": "07/10/2026 09:00"`. Why is that risky to store as-is?',
      options: [
        { text: 'It could mean 7 Oct or 10 July, and it has no time zone', why: 'Yes. Convert to an aware UTC datetime and store ISO 8601.' },
        { text: 'Python can’t parse slashes, so it must be reformatted first', why: 'Python parses it fine with strptime; the meaning is the problem, not the slashes.' },
        { text: 'It’s fine; store it as text and parse it when you need it', why: 'The ambiguity is still there later, and now spread through your data.' },
        { text: 'It’s fine once you assume the server’s local time zone', why: 'The server’s zone isn’t the sender’s, and day/month order is still unknown.' },
      ],
      answer: 0,
      explain: 'Parse at the boundary with a known format and zone, then keep it as UTC.',
    },
    {
      id: 'm2-q8', kind: 'choice',
      prompt: 'What does Pydantic give you that a plain dict from `response.json()` doesn’t?',
      options: [
        { text: 'Checks required fields and types, with errors naming each field', why: 'Yes. Bad data fails at the boundary, clearly.' },
        { text: 'Faster parsing of big responses than `response.json()` gives', why: 'Speed isn’t the point; it adds checking on top of parsing.' },
        { text: 'A guarantee the values are accurate, not just well formed', why: 'It checks shape and type, not whether the values are true.' },
        { text: 'Automatic retries of the request whenever the API sends malformed data', why: 'It validates data; retries are your HTTP and error-handling code’s job.' },
      ],
      answer: 0,
      explain: 'Validate at the edge so the rest of your code works with typed, trusted objects.',
    },
    {
      id: 'm2-q9', kind: 'choice',
      prompt: 'Your async script fires 1,000 requests at once and most come back 429. What’s the fix?',
      options: [
        { text: 'Cap concurrency with a semaphore and back off on 429s', why: 'Yes. Overlap the waiting, but within the API’s rules.' },
        { text: 'Retry each 429 straight away until it finally succeeds', why: 'Immediate retries repeat the same overload.' },
        { text: 'Raise the timeout so the API has longer to answer each call', why: '429 is about too many requests, not slow replies.' },
        { text: 'Use more threads instead of async to spread the load', why: 'Threads still fire too many requests at once; the API counts requests, not threads.' },
      ],
      answer: 0,
      explain: 'Concurrency is a dial. Set it from the provider’s rate limit.',
    },
    {
      id: 'm2-q10', kind: 'choice',
      prompt: 'Why should `sync_lead` take the HTTP client as a parameter instead of creating it inside?',
      options: [
        { text: 'Tests can pass in a fake client that returns 429s or timeouts', why: 'Right. Injecting the boundary makes failure paths testable.' },
        { text: 'A client created inside the function can’t set a timeout', why: 'It can; any client accepts a timeout. The issue is testability.' },
        { text: 'Reusing one client is the only way to keep the token secret', why: 'Where the client is built doesn’t affect secrecy; the token comes from the environment either way.' },
        { text: 'Functions can’t read environment variables like CRM_TOKEN themselves', why: 'They can; os.environ works anywhere. That isn’t the reason.' },
      ],
      answer: 0,
      explain: 'Pass dependencies in; swap them out in tests.',
    },
    {
      id: 'm2-q11', kind: 'choice',
      prompt: 'Your script works locally but fails in CI with an error from a newer version of a library. What prevents this?',
      options: [
        { text: 'Pin exact versions in a lock file so CI installs what you tested', why: 'Yes. Same versions everywhere.' },
        { text: 'Commit your .venv folder so CI reuses exactly the packages you had', why: 'Virtual environments hold machine-specific paths and binaries; they don’t transfer reliably.' },
        { text: 'Use `>=` versions so CI always gets the latest bug fixes', why: 'That’s exactly what pulled in the breaking newer version.' },
        { text: 'Run `pip install --upgrade` locally so you match CI’s versions', why: 'You’d match today, then drift again on the next release. Pinning fixes it.' },
      ],
      answer: 0,
      explain: 'Reproducible installs: pin and lock.',
    },
    {
      id: 'm2-q12', kind: 'choice',
      prompt: 'Which test gives the most confidence that duplicate webhooks are handled?',
      options: [
        { text: 'Send one event twice to a mocked CRM; assert one contact exists', why: 'Yes. It checks the business outcome, not internal details.' },
        { text: 'Send the event twice and assert the second call doesn’t raise an error', why: 'No error doesn’t mean no duplicate: a second contact could be created silently.' },
        { text: 'Assert that `dedupe()` was called once per incoming event', why: 'That tests implementation, not the outcome. It could be called and still let duplicates through.' },
        { text: 'Send the event twice to the real CRM and check it by eye', why: 'Slow, manual and touches real data. Use the sandbox for integration tests.' },
      ],
      answer: 0,
      explain: 'Test the invariant the business cares about: “one event, one contact”.',
    },
  ],
  tasks: [
    { device: 'computer', plain: 'Learn the Python building blocks: functions, modules and imports, comprehensions, lists/dicts/sets, reading and writing files, and type hints.', done: 'A small script that reads leads.json, cleans each record with your own functions and writes cleaned.json, and you’ve passed the Lesson 1 and 2 checks.' },
    { device: 'computer', plain: 'Set up a virtual environment, pin your dependencies, and understand what a lock file is for.', done: 'Committed requirements.txt (or lock file) with exact versions, and one sentence on why pinning matters.' },
    { device: 'computer', plain: 'Call a real API with httpx or requests, using an explicit timeout, headers and query parameters, and parse the response.', done: 'A script that fetches data, checks the status, and fails clearly on a 401 or a timeout.' },
    { device: 'phone', plain: 'Learn how to design error handling: catch specific errors, keep the original cause, and tell retryable failures from permanent ones.', done: 'You can sort 400, 401, 404, 422, 429, 500 and a timeout into retryable or permanent, and you’ve passed the Lesson 4 check.' },
    { device: 'computer', plain: 'Add logging to your script that includes an event or correlation ID on every line and never prints tokens.', done: 'A sample log from one run where each line has the ID, and a search of it finds no secrets.' },
    { device: 'phone', plain: 'Learn how to handle dates: store UTC, use ISO 8601, parse safely, and watch out for daylight-saving changes.', done: 'You can explain why a 2:30am Sydney job can misfire on DST day, and you’ve passed the Lesson 5 date check.' },
    { device: 'computer', plain: 'Use Pydantic models to validate the data coming in and going out, instead of passing raw dictionaries around.', done: 'Your script rejects a malformed record with a clear, field-level error and keeps it in a rejected list.' },
    { device: 'phone', plain: 'Learn the async basics: the event loop, await, when running things at the same time helps, and when normal code is simpler.', done: 'You can explain when you’d choose async and when you wouldn’t, and you’ve passed the Lesson 6 check.' },
    { device: 'computer', plain: 'Build a command-line script that pulls all records page by page, validates them, transforms them and upserts them somewhere else.', done: 'Running it twice gives the same result with no duplicates, and the checkpoint resumes after you stop it mid-run.' },
    { device: 'computer', plain: 'Learn pytest: write unit tests, use fixtures and parametrize, and fake the external HTTP calls.', done: 'A test file that runs with `pytest`, with at least one fixture, one parametrized test and one mocked HTTP call.' },
    { device: 'computer', plain: 'Write tests for the hard cases: a duplicate input, malformed input, a timeout, a 429, a 500, and a normal success.', done: 'Six passing tests, each asserting the outcome (final status, writes made or retries), not just “no crash”.' },
    { device: 'computer', plain: 'Rebuild the core script from a blank file with AI closed, then explain every dependency and failure path.', done: 'A working script written without AI, and a recording or note walking through each library and what happens when each call fails.' },
  ],
};
