import type { Lesson } from './types';

export const m3: Lesson = {
  intro: "Most automations start with Google Sheets as their memory. That works until two runs write at once, someone types “ASAP” into a date column, or a repeated webhook adds the same lead twice. A real database refuses bad data, keeps related changes together and answers questions in milliseconds. This module teaches SQL and PostgreSQL from zero with one running example, leads, their replies and their bookings, and ends with the tables behind an automation you can safely re-run.",
  glossary: {
    'database': 'A program built to store data safely, enforce rules on it and answer questions about it quickly.',
    'postgresql': 'A free, open-source database (“Postgres”). The most common choice for automation back ends, and n8n can use it too.',
    'table': 'One kind of thing in a database, like one tab of a spreadsheet: leads, replies, bookings.',
    'data type': 'What kind of value a column holds (text, number, date and time, true/false). The database rejects anything else.',
    'sql': 'Structured Query Language: the language for creating tables and reading or changing data in a database.',
    'connection string': 'One line with everything needed to reach a database: user, password, host, port and database name.',
    'connection pool': 'A small set of database connections kept open and shared, so many workers don’t each open their own.',
    'primary key': 'The column (or columns) that uniquely identifies each row. Never empty, never repeated.',
    'foreign key': 'A column that points to another table’s primary key, e.g. replies.lead_id → leads.id.',
    'constraint': 'A rule the database checks on every write, e.g. NOT NULL, UNIQUE or CHECK.',
    'null': 'A database’s “no value here”. It isn’t zero or empty text, and you test for it with IS NULL.',
    'cte': 'Common Table Expression: a named step inside a query, written WITH name AS (...).',
    'window function': 'A calculation across related rows (rank, running total, row number) that keeps every row instead of collapsing them.',
    'transaction': 'A group of database changes that are saved together or not at all.',
    'atomic': 'All-or-nothing: either every part happens or none of it does.',
    'outbox': 'A pattern where you save “I need to call the API” in the database first, then a separate step does it and records the result.',
    'index': 'A sorted lookup structure on a column, like the index at the back of a book, so the database finds rows without reading all of them.',
    'query plan': 'The database’s step-by-step plan for running a query, shown by EXPLAIN.',
    'jsonb': 'A Postgres column type that stores JSON in a form you can search and index.',
    'audit log': 'An append-only record of who or what changed which data, and when.',
  },
  sections: [
    {
      title: 'What is a database, and why not just Google Sheets?',
      minutes: 6,
      body: [
        "**The problem.** Your lead automation writes every new lead to a Google Sheet. It works for a month. Then a colleague sorts one column and scrambles the rows, someone types “next Tuesday” into a date column, and two webhook runs land at the same moment and add the same lead twice. **A sheet accepts whatever you give it.**",
        "A [[database]] is a program built to store data safely and answer questions about it. It checks every write against rules you set, lets many workflows read and write at once without overwriting each other, and stays fast with millions of rows. [[PostgreSQL]] (“Postgres”) is the free one most automation teams use.",
        "**The analogy.** A sheet is a whiteboard: anyone can write anything anywhere. A database is a strict filing clerk who hands back any form with a missing or wrong field.",
        "The words you need:",
        "- **[[Table]]**: one kind of thing, like a sheet tab: `leads`, `replies`, `bookings`.\n- **Row**: one record, e.g. one lead.\n- **Column**: one fact about every row, with a fixed [[data type]]: `text`, `integer`, `boolean` (true/false), `timestamptz` (date and time with timezone), `numeric` (exact numbers, for money).\n- **[[SQL]]**: the language you use to create tables and ask questions. Nearly every database speaks it.",
        "**How n8n or Python reaches it.** Through a [[connection string]]: one line with user, password, host, port and database name. Keep it in an [[environment variable]] such as `DATABASE_URL`, with a different value for dev and production, never inside the workflow or code.",
        "**Production point.** Each open connection uses memory on the database server, and Postgres only allows a set number (the `max_connections` setting, 100 by default). Twenty workers each opening ten connections hit that wall. A [[connection pool]] keeps a few connections open and shares them; PgBouncer is the usual tool.",
      ],
      example: {
        caption: 'A connection string and your first table',
        code: "-- connection string, kept in DATABASE_URL:\n-- postgresql://app_user:secret@db.example.com:5432/leads_db\n--             user     password host           port database\n\nCREATE TABLE leads (\n  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- auto-numbered ID\n  email      text NOT NULL,                 -- must be filled in\n  full_name  text,                          -- may be left empty\n  source     text,                          -- e.g. 'webform', 'linkedin'\n  created_at timestamptz NOT NULL DEFAULT now()  -- set automatically\n);",
      },
      interview: "I use Postgres rather than a spreadsheet as the source of truth because it enforces types and constraints, handles concurrent writers safely, and supports transactions. Connection details come from an environment-specific DATABASE_URL, and with many workers I put a pooler like PgBouncer in front so we don’t exhaust max_connections.",
      check: [
        {
          id: 'm3-s0-1', kind: 'choice',
          prompt: 'Your workflow tries to save “ASAP” into the `follow_up_at` column, which has type `timestamptz`. What happens in Postgres?',
          options: [
            { text: 'The insert is rejected with an error, because “ASAP” isn’t a valid date and time', why: 'Right. The data type is a rule the database enforces on every write.' },
            { text: 'It’s saved as text, like in a sheet', why: 'That’s spreadsheet behaviour. A typed column refuses values of the wrong type.' },
            { text: 'Postgres converts it to today’s date', why: 'It doesn’t guess. It refuses the value.' },
            { text: 'The column is silently left empty', why: 'Postgres reports an error rather than quietly dropping your data.' },
          ],
          answer: 0,
          explain: 'Typed columns catch bad data at the door, instead of letting it break a report three weeks later.',
        },
        {
          id: 'm3-s0-2', kind: 'choice',
          prompt: 'Your workers start failing with `FATAL: sorry, too many clients already`. What’s the most likely fix?',
          options: [
            { text: 'Put a connection pool in front of Postgres so workers share a few connections', why: 'Yes. The server has hit its connection limit; pooling shares connections instead of opening more.' },
            { text: 'Add more workers', why: 'More workers would open even more connections.' },
            { text: 'Change the database password', why: 'This is a limit on the number of connections, not a login problem.' },
            { text: 'Move the data back into Google Sheets', why: 'That swaps a configuration problem for a reliability problem.' },
          ],
          answer: 0,
          explain: 'Every connection costs memory, and max_connections caps them. A pooler such as PgBouncer is the standard answer.',
        },
      ],
    },
    {
      title: 'Keys and constraints: rules the database enforces',
      minutes: 6,
      body: [
        "Tables get useful when they connect. One lead can send several replies and make a booking. You link them with keys.",
        "- **[[Primary key]]**: the column that uniquely identifies each row, like a lead’s `id`. Never empty, never repeated.\n- **[[Foreign key]]**: a column that points at another table’s primary key. `replies.lead_id` says “this reply belongs to lead 42”. Postgres refuses a reply for a lead that doesn’t exist.",
        "Then add [[constraint|constraints]], rules checked on every insert and update:",
        "- `NOT NULL`: this column must have a value.\n- `UNIQUE`: no two rows may share this value, e.g. one lead per email. That’s a [[unique constraint]].\n- `CHECK`: a custom rule, e.g. status must be one of `new`, `contacted`, `booked`.",
        "**Why bother, if your n8n workflow already checks?** Because a workflow check can race. Two webhook runs arrive together. Both ask “does ana@example.com exist?”, both hear “no”, both insert. That’s a [[race condition]], and now you have a duplicate lead. A `UNIQUE` constraint can’t race: Postgres lets the first insert in and rejects the second.",
        "**Constraints are your last line of defence.** Whatever bug sits upstream, in n8n, Python or a human import, the database still refuses duplicates and broken links.",
        "**Production point.** Clean values before you compare them. `Ana@Example.com ` and `ana@example.com` are different text, so a plain `UNIQUE` lets both in. Store emails trimmed and lowercased, or enforce it with a unique index on `lower(email)`.",
      ],
      example: {
        caption: 'The running example: leads, replies, bookings',
        code: "CREATE TABLE leads (\n  id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  email     text NOT NULL UNIQUE,              -- one row per email\n  full_name text,\n  source    text,\n  status    text NOT NULL DEFAULT 'new'\n            CHECK (status IN ('new', 'contacted', 'booked'))\n);\n\nCREATE TABLE replies (\n  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  lead_id    bigint NOT NULL REFERENCES leads(id),  -- foreign key\n  body       text NOT NULL,\n  replied_at timestamptz NOT NULL\n);\n\nCREATE TABLE bookings (\n  id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  lead_id   bigint NOT NULL REFERENCES leads(id),\n  starts_at timestamptz NOT NULL\n);",
      },
      interview: "I put business invariants in the schema: primary keys for identity, foreign keys for relationships, and UNIQUE, CHECK and NOT NULL for rules. An application-level “check then insert” can race under concurrency, so the unique constraint is the authoritative guard against duplicates.",
      check: [
        {
          id: 'm3-s1-1', kind: 'choice',
          prompt: 'Your workflow searches for the lead’s email and only inserts if nothing is found. You still get occasional duplicates. What’s the real fix?',
          options: [
            { text: 'Add a UNIQUE constraint on email, so the database rejects the second insert', why: 'Yes. Two simultaneous runs can both find nothing; the constraint can’t be raced.' },
            { text: 'Add a second search node before the insert', why: 'Two checks can race just like one.' },
            { text: 'Add a Wait node before the search', why: 'Waiting changes the timing but doesn’t remove the race.' },
            { text: 'Delete duplicates with a weekly clean-up job', why: 'That hides the problem after it has already caused double emails.' },
          ],
          answer: 0,
          explain: 'A check in the workflow is a courtesy. A constraint in the database is a guarantee.',
        },
        {
          id: 'm3-s1-2', kind: 'choice',
          prompt: 'You insert a reply with `lead_id = 999`, but no lead 999 exists. What happens?',
          options: [
            { text: 'Postgres rejects it with a foreign key violation', why: 'Right. The foreign key guarantees every reply belongs to a real lead.' },
            { text: 'Postgres creates an empty lead 999 automatically', why: 'It never invents rows for you.' },
            { text: 'The reply is saved and linked later', why: 'The link is checked at insert time.' },
            { text: 'The reply is saved with lead_id set to NULL', why: 'The column is NOT NULL, and Postgres doesn’t rewrite your values anyway.' },
          ],
          answer: 0,
          explain: 'Foreign keys stop “orphan” rows that point at nothing.',
        },
        {
          id: 'm3-s1-3', kind: 'choice',
          prompt: 'A typo saves a lead with status `bookd`. Which constraint would have stopped it?',
          options: [
            { text: 'A CHECK constraint listing the allowed statuses', why: 'Yes. CHECK enforces custom rules like an allowed list.' },
            { text: 'NOT NULL', why: '“bookd” isn’t empty, so NOT NULL is satisfied.' },
            { text: 'UNIQUE', why: 'Many leads share a status, so UNIQUE would be wrong here.' },
            { text: 'A foreign key on email', why: 'Foreign keys link tables; they don’t validate status words.' },
          ],
          answer: 0,
          explain: 'NOT NULL = must exist, UNIQUE = no repeats, CHECK = must follow this rule.',
        },
      ],
    },
    {
      title: 'Asking questions: SELECT, WHERE and JOIN',
      minutes: 7,
      body: [
        "Reading data is one statement, `SELECT`. You say which columns, from which table, which rows and in what order:",
        "- `SELECT email, status` picks columns (`*` means all).\n- `FROM leads` picks the table.\n- `WHERE status = 'new'` keeps only matching rows.\n- `ORDER BY created_at DESC` sorts, newest first.\n- `LIMIT 10` returns at most 10 rows.",
        "**JOIN combines tables** using the keys from the last lesson. Look at the three tiny tables in the example: Ana replied and booked, Ben replied only, Cat did neither.",
        "- An inner `JOIN` keeps only rows that match on both sides. Leads joined to replies gives Ana and Ben.\n- A `LEFT JOIN` keeps **every** row from the left table and fills the right side with [[null|NULL]] where nothing matches. Leads left-joined to replies gives Ana, Ben, and Cat with an empty reply.",
        "That empty side is useful: it means “nothing there”. **The classic interview query** is “leads who replied but never booked”: join leads to replies, `LEFT JOIN` bookings, keep rows where the booking is `NULL`. The answer is Ben.",
        "Two traps:",
        "- `NULL` isn’t equal to anything, not even another `NULL`. Test it with `IS NULL`; `= NULL` never matches.\n- Joins multiply. If Ben replied three times, joining gives three Ben rows. Add `DISTINCT`, or use `WHERE EXISTS (...)`, when you want each lead once.",
      ],
      example: {
        caption: 'Leads who replied but never booked',
        code: "-- leads           replies             bookings\n-- id | email      lead_id | body      lead_id | starts_at\n-- 1  | ana@…      1       | 'Yes!'    1       | Tue 10am\n-- 2  | ben@…      2       | 'Info?'\n-- 3  | cat@…\n\nSELECT DISTINCT l.id, l.email\nFROM leads l                            -- l is a short nickname\nJOIN replies r ON r.lead_id = l.id      -- only leads who replied\nLEFT JOIN bookings b ON b.lead_id = l.id  -- booking if there is one\nWHERE b.lead_id IS NULL                 -- …but there isn’t\nORDER BY l.id;\n-- result: 2 | ben@…",
      },
      interview: "For “replied but never booked” I inner-join leads to replies and left-join bookings, filtering where the booking key IS NULL; NOT EXISTS is an equivalent anti-join that avoids duplicate rows. I watch for row multiplication on one-to-many joins and NULL semantics in filters.",
      check: [
        {
          id: 'm3-s2-1', kind: 'choice',
          prompt: 'Using the example tables (each lead has at most one reply), how many rows does this return?',
          code: 'SELECT l.email, r.body\nFROM leads l\nLEFT JOIN replies r ON r.lead_id = l.id;',
          options: [
            { text: '3: Ana, Ben, and Cat with an empty body', why: 'Yes. LEFT JOIN keeps every lead, with NULL where there’s no reply.' },
            { text: '2: Ana and Ben', why: 'That’s what an inner JOIN would return.' },
            { text: '1: only Ana', why: 'Ana is the only one who booked, but bookings aren’t in this query.' },
            { text: '0, because Cat has no reply', why: 'A missing match removes nothing in a LEFT JOIN.' },
          ],
          answer: 0,
          explain: 'Inner JOIN = matches only. LEFT JOIN = everything on the left, matched or not.',
        },
        {
          id: 'm3-s2-2', kind: 'choice',
          prompt: 'This query returns no rows, even though Ben clearly has no booking. What’s wrong?',
          code: '... LEFT JOIN bookings b ON b.lead_id = l.id\nWHERE b.lead_id = NULL;',
          options: [
            { text: 'It should be `IS NULL`; `= NULL` never matches anything', why: 'Right. NULL means unknown, so comparing with = is never true.' },
            { text: 'LEFT JOIN should be JOIN', why: 'An inner JOIN would drop Ben entirely.' },
            { text: 'You need ORDER BY', why: 'Sorting doesn’t change which rows match.' },
            { text: 'The bookings table is empty', why: 'Ana has a booking, and the bug is in the comparison.' },
          ],
          answer: 0,
          explain: 'Always IS NULL / IS NOT NULL. A very common interview gotcha.',
        },
      ],
    },
    {
      title: 'Summaries: GROUP BY, CTEs and window functions',
      minutes: 7,
      body: [
        "Clients ask “how many leads came from each source last week?” That’s **GROUP BY**: it squashes rows into groups and calculates one result per group with `count(*)`, `sum()`, `avg()`, `min()` or `max()`. Grouping by `date_trunc('week', created_at)` puts leads into weekly cohorts.",
        "`WHERE` filters rows **before** grouping. `HAVING` filters groups **after**: “only sources with more than 20 leads”.",
        "**Breaking a big query into steps.** A query can contain another query (a subquery), but nesting gets hard to read. A [[CTE]], written `WITH name AS (...)`, gives each step a name, like a helper column in a sheet. You read it top to bottom.",
        "**A taste of [[window function|window functions]].** `GROUP BY` collapses many rows into one per group. A window function calculates across related rows but **keeps every row**. Three everyday uses:",
        "- `row_number() OVER (PARTITION BY lead_id ORDER BY replied_at)`: number each lead’s replies 1, 2, 3, so you can pick the first.\n- `rank() OVER (ORDER BY total DESC)`: rank sources by volume.\n- `sum(bookings) OVER (ORDER BY day)`: a running total of bookings by day.",
        "`PARTITION BY` means “restart for each lead”. The `ORDER BY` inside `OVER` sets the sequence. That’s enough for ranking, running-total and cohort questions.",
        "**Production point.** You can’t filter on a window function in the same query’s `WHERE`, because `WHERE` runs first. Calculate it in a CTE, then filter in the next step, as in the example.",
      ],
      example: {
        caption: 'First reply per lead, counted by source',
        code: "WITH first_replies AS (            -- step 1: number each lead's replies\n  SELECT lead_id,\n         row_number() OVER (PARTITION BY lead_id\n                            ORDER BY replied_at) AS n\n  FROM replies\n)\nSELECT l.source, count(*) AS replied_leads   -- step 2: summarise\nFROM first_replies f\nJOIN leads l ON l.id = f.lead_id\nWHERE f.n = 1                      -- first reply only, so one per lead\nGROUP BY l.source\nHAVING count(*) > 20               -- filters groups, not rows\nORDER BY replied_leads DESC;",
      },
      interview: "I use GROUP BY with HAVING for aggregates, CTEs to stage complex queries readably, and window functions like row_number, rank and running sums when I need per-row results with group context, such as the latest event per entity. Window results are filtered in an outer query, since WHERE is evaluated before them.",
      check: [
        {
          id: 'm3-s3-1', kind: 'choice',
          prompt: 'This query errors. What’s the fix?',
          code: 'SELECT source, count(*)\nFROM leads\nWHERE count(*) > 20\nGROUP BY source;',
          options: [
            { text: 'Move the condition to `HAVING count(*) > 20` after GROUP BY', why: 'Yes. Conditions on group results belong in HAVING.' },
            { text: 'Remove GROUP BY', why: 'Then you can’t count per source at all.' },
            { text: 'Replace count(*) with sum(*)', why: 'The function isn’t the problem; WHERE can’t see group totals.' },
            { text: 'Add ORDER BY count(*)', why: 'Sorting doesn’t fix filtering in the wrong place.' },
          ],
          answer: 0,
          explain: 'WHERE filters rows before grouping; HAVING filters groups after.',
        },
        {
          id: 'm3-s3-2', kind: 'choice',
          prompt: 'The `replies` table has 10 rows from 4 leads. How many rows does `SELECT lead_id, row_number() OVER (PARTITION BY lead_id ORDER BY replied_at) FROM replies` return?',
          options: [
            { text: '10, because a window function keeps every row', why: 'Right. It adds a number to each row instead of collapsing them.' },
            { text: '4, one per lead', why: 'That’s what GROUP BY lead_id would give.' },
            { text: '1', why: 'Nothing here reduces the result to one row.' },
            { text: '40', why: 'Window functions don’t multiply rows.' },
          ],
          answer: 0,
          explain: 'GROUP BY collapses; window functions annotate.',
        },
      ],
    },
    {
      title: 'Transactions and upserts: all-or-nothing writes',
      minutes: 7,
      body: [
        "**The problem.** A booking arrives. Your workflow inserts the booking, then sets the lead’s status to `booked`. The server restarts between the two. Now there’s a booking for a lead still marked `new`, and tomorrow’s follow-up emails someone who already booked. **A half-finished write is worse than none**, because nothing looks broken.",
        "A [[transaction]] groups statements so they succeed or fail together ([[atomic]]). `BEGIN` starts it, `COMMIT` saves everything, `ROLLBACK` undoes everything. If the connection drops before `COMMIT`, Postgres throws the whole lot away.",
        "**The limit.** A transaction only covers the database. If you call the CRM inside one and then roll back, the CRM contact still exists. For outside effects, save what you *intend* to do in the database, do it in a separate step, then record the result. That’s the [[outbox]] pattern; checking the provider afterwards to confirm is called reconciliation.",
        "**Upserts fix the check-then-create race.** An [[upsert]] (`INSERT ... ON CONFLICT`) tries the insert. If it hits a unique constraint, it does nothing or updates the existing row instead, decided atomically by Postgres. Two simultaneous runs can’t both create the lead.",
        "- `ON CONFLICT (email) DO NOTHING`: keep the first, ignore repeats. Ideal for storing webhook events.\n- `ON CONFLICT (email) DO UPDATE SET ...`: update the existing row. `EXCLUDED` means “the row you tried to insert”.\n- `RETURNING id`: hand back the row’s ID for the next n8n node.",
        "**Production points.** `ON CONFLICT` needs a unique constraint or index on that column, or Postgres raises an error. And a transaction alone doesn’t stop duplicates: under the default isolation level, two transactions can both read “not found”. The unique constraint is what stops the second insert.",
      ],
      example: {
        caption: 'A transaction, then an upsert',
        code: "BEGIN;\n  INSERT INTO bookings (lead_id, starts_at)\n  VALUES (42, '2026-10-14 10:00+10');\n  UPDATE leads SET status = 'booked' WHERE id = 42;\nCOMMIT;  -- both saved; on an error or crash, neither\n\n-- create the lead, or refresh its name if the email exists\nINSERT INTO leads (email, full_name)\nVALUES ('ana@example.com', 'Ana Lopez')\nON CONFLICT (email)\nDO UPDATE SET full_name = EXCLUDED.full_name\nRETURNING id;",
      },
      interview: "Related writes go in one transaction so a crash can’t leave partial state. Transactions don’t cover external side effects, so for API calls I record intent, dispatch separately and reconcile. For create-or-update I use INSERT … ON CONFLICT against a unique constraint instead of check-then-insert, which races under Read Committed.",
      check: [
        {
          id: 'm3-s4-1', kind: 'choice',
          prompt: 'Inside `BEGIN ... COMMIT`, the booking insert succeeds, then the server crashes before the status update. What’s in the database afterwards?',
          options: [
            { text: 'Neither change: no booking, status unchanged', why: 'Right. Nothing was committed, so Postgres discards the partial work.' },
            { text: 'The booking, but the old status', why: 'That’s what happens without a transaction.' },
            { text: 'Both changes, because Postgres finishes them on restart', why: 'Uncommitted work is rolled back, not completed.' },
            { text: 'A corrupted table', why: 'Transactions exist precisely to prevent that.' },
          ],
          answer: 0,
          explain: 'All or nothing. That’s what makes multi-table writes safe.',
        },
        {
          id: 'm3-s4-2', kind: 'choice',
          prompt: 'A transaction inserts a booking, calls an SMS API to confirm it, then hits an error and rolls back. What happened?',
          options: [
            { text: 'The booking is undone, but the SMS was still sent', why: 'Yes. A rollback can’t un-send a message at another company.' },
            { text: 'Both the booking and the SMS are undone', why: 'Rollback only affects your database.' },
            { text: 'The SMS provider is told to cancel', why: 'Postgres has no idea the SMS exists.' },
            { text: 'Nothing; rollbacks only work for updates', why: 'Rollback undoes inserts, updates and deletes.' },
          ],
          answer: 0,
          explain: 'Keep external calls out of transactions: record intent, send separately, record the outcome.',
        },
        {
          id: 'm3-s4-3', kind: 'choice',
          prompt: 'Your upsert fails with: `there is no unique or exclusion constraint matching the ON CONFLICT specification`. Why?',
          options: [
            { text: 'The column in ON CONFLICT (...) has no unique constraint or index', why: 'Right. ON CONFLICT needs one to know what counts as a conflict.' },
            { text: 'The table is empty', why: 'Upserts work fine on empty tables.' },
            { text: 'You forgot BEGIN', why: 'A single statement is already atomic on its own.' },
            { text: 'RETURNING isn’t allowed with upserts', why: 'RETURNING works with ON CONFLICT.' },
          ],
          answer: 0,
          explain: 'Add the UNIQUE constraint first; the upsert relies on it.',
        },
      ],
    },
    {
      title: 'Indexes and EXPLAIN: making queries fast',
      minutes: 6,
      body: [
        "With 200 leads every query feels instant. With 2 million, “find this lead’s replies” can take seconds, because Postgres reads **every row** to check it. That’s a sequential scan.",
        "An [[index]] is like the index at the back of a book: a sorted list of values with a pointer to each row, so Postgres jumps straight to the match. `CREATE INDEX ON replies (lead_id);`",
        "**Indexes aren’t free.** Every insert and update must also update each index, and they use disk space. On a table receiving thousands of webhook events a minute, ten unused indexes slow every write. So **index the columns your real queries filter, join or sort on**, not every column.",
        "A primary key and a `UNIQUE` constraint already create an index. **A foreign key does not**, so index columns like `lead_id` yourself if you join on them.",
        "**How to know.** Put `EXPLAIN` in front of a query and Postgres shows its [[query plan]]: how it intends to run it. `EXPLAIN ANALYZE` actually runs it and adds real timings and row counts. Look for:",
        "- `Seq Scan` on a big table when you expected a few rows: probably a missing index.\n- `Index Scan`: the index is being used.\n- `Rows Removed by Filter`: rows read and thrown away.\n- `Execution Time`: total milliseconds.",
        "**Production points.** On a small table Postgres may choose a `Seq Scan` even with an index, because reading a few pages is cheaper. That’s fine. And `EXPLAIN ANALYZE` really executes the statement, so on an `UPDATE` or `DELETE` it changes data: wrap it in `BEGIN` ... `ROLLBACK`. The habit is: write the query, measure, add one index, measure again.",
      ],
      example: {
        caption: 'EXPLAIN ANALYZE before and after CREATE INDEX ON replies (lead_id)',
        code: "-- before: reads all 2 million rows to find 3\nSeq Scan on replies  (actual time=0.1..182.4 rows=3 loops=1)\n  Filter: (lead_id = 42)\n  Rows Removed by Filter: 1999997\nExecution Time: 182.5 ms\n\n-- after: jumps straight to them\nIndex Scan using replies_lead_id_idx on replies\n    (actual time=0.03..0.04 rows=3 loops=1)\n  Index Cond: (lead_id = 42)\nExecution Time: 0.06 ms",
      },
      interview: "I let query patterns drive indexing: I write the query, check the plan with EXPLAIN ANALYZE, and add an index for frequent filters, joins and sorts, then re-measure. Indexes cost write throughput and storage, so on high-ingest tables I keep only the ones a real query uses. Postgres doesn’t index foreign key columns automatically.",
      check: [
        {
          id: 'm3-s5-1', kind: 'choice',
          prompt: 'Read the plan. What’s the best next step?',
          code: 'Seq Scan on bookings  (actual time=0.2..240.9 rows=1 loops=1)\n  Filter: (lead_id = 7)\n  Rows Removed by Filter: 3500000',
          options: [
            { text: 'Add an index on bookings.lead_id and re-run EXPLAIN ANALYZE', why: 'Yes. It read 3.5 million rows to find one, a clear sign of a missing index.' },
            { text: 'Index every column on bookings', why: 'That slows every write and most indexes would never be used.' },
            { text: 'Add LIMIT 1 and move on', why: 'That hides the symptom for this query only, and still scans when there’s no match.' },
            { text: 'Buy a bigger database server', why: 'Hardware won’t fix reading every row for a single match.' },
          ],
          answer: 0,
          explain: 'Seq Scan + huge “Rows Removed by Filter” on a selective query = index candidate.',
        },
        {
          id: 'm3-s5-2', kind: 'choice',
          prompt: 'After a colleague adds 12 indexes to the `events` table, webhook inserts get noticeably slower. Why?',
          options: [
            { text: 'Every insert now has to update all 12 indexes as well', why: 'Right. Indexes speed up reads but add work to every write.' },
            { text: 'Indexes lock the table for reading', why: 'Normal indexes don’t block reads.' },
            { text: 'Postgres has a limit of 5 indexes', why: 'There’s no such limit.' },
            { text: 'Indexes delete old rows', why: 'They don’t remove any data.' },
          ],
          answer: 0,
          explain: 'Index what your real queries need, and drop indexes nothing uses.',
        },
      ],
    },
    {
      title: 'Designing tables for an automation',
      minutes: 7,
      body: [
        "A reliable automation needs the database to remember **what happened**, not just the final result. A typical set of tables:",
        "- **events**: every inbound webhook, stored raw before any processing.\n- **executions** (or attempts): each try at processing an event: when, outcome, error.\n- **external_records**: your ID mapped to the CRM’s ID, so a replay updates the same contact instead of creating another.\n- **[[Audit log]]**: who or what changed which data, and when. Rows are only ever added.",
        "**The events table matters most.** Its primary key is the client account (tenant) plus the provider’s own event ID, so a repeated delivery hits the constraint and `ON CONFLICT DO NOTHING` ignores it. A random ID generated on arrival would defeat this, because every repeat would look new. The table also holds **retry state**: `status`, `attempts`, `next_attempt_at` and `last_error`. A worker picks rows that are `pending` and due.",
        "Keep two timestamps: `occurred_at` (when it happened at the provider) and `received_at` (when you stored it). Webhooks arrive late and out of order.",
        "[[JSONB]] stores the raw payload in one column that you can still query: `payload->>'email'` returns the email as text. That’s ideal for raw events whose shape you don’t control. It becomes a **dumping ground** when the fields you filter, join or enforce rules on exist only inside the JSON: no types, no constraints. Keep the raw JSON, and copy the fields you depend on into real columns.",
        "**Changing tables later.** Never edit production tables by hand. Each change is a [[migration]]: a small numbered SQL file in Git, run in order against dev, staging and production, each with its own connection string.",
      ],
      example: {
        caption: 'An events table you can safely replay from',
        code: "CREATE TABLE events (\n  tenant_id       text NOT NULL,         -- which client account\n  event_id        text NOT NULL,         -- the provider's own ID\n  event_type      text NOT NULL,         -- e.g. 'lead.created'\n  payload         jsonb NOT NULL,        -- raw body, untouched\n  occurred_at     timestamptz,\n  received_at     timestamptz NOT NULL DEFAULT now(),\n  status          text NOT NULL DEFAULT 'pending'\n    CHECK (status IN ('pending', 'processing', 'done', 'failed')),\n  attempts        int NOT NULL DEFAULT 0,\n  next_attempt_at timestamptz,\n  last_error      text,\n  PRIMARY KEY (tenant_id, event_id)      -- a repeat can't duplicate\n);\nCREATE INDEX ON events (status, next_attempt_at);  -- the worker's query\n\nINSERT INTO events (tenant_id, event_id, event_type, payload)\nVALUES ('acme', 'evt_123', 'lead.created', '{\"email\": \"ana@example.com\"}')\nON CONFLICT DO NOTHING;               -- second delivery is ignored",
      },
      interview: "I model inbound work as an event store keyed on tenant plus provider event ID, with the raw payload in JSONB, occurred_at separate from received_at, and explicit retry state. External IDs live in a mapping table so replays update rather than create, and schema changes ship as versioned migrations.",
      check: [
        {
          id: 'm3-s6-1', kind: 'choice',
          prompt: 'Your events table uses `gen_random_uuid()` as its primary key. The provider sends the same webhook twice. What happens?',
          options: [
            { text: 'Both are stored as separate events, because each got a new random ID', why: 'Right. A fresh random key makes every repeat look new, so deduplication never triggers.' },
            { text: 'The second is rejected as a duplicate', why: 'Only if the key came from the provider’s event ID.' },
            { text: 'Postgres merges them', why: 'It has nothing telling it they’re the same.' },
            { text: 'The webhook fails', why: 'Both inserts succeed. That’s the problem.' },
          ],
          answer: 0,
          explain: 'Deduplicate on a stable key from the source (tenant + provider event ID), not one you invent on arrival.',
        },
        {
          id: 'm3-s6-2', kind: 'choice',
          prompt: 'Every query in your app filters on `payload->>\'tenant\'` and `payload->>\'status\'`, and someone stored “Done ” with a trailing space. What’s the design fix?',
          options: [
            { text: 'Copy tenant and status into real columns with types and a CHECK constraint, and keep the raw JSON too', why: 'Yes. Fields you filter and enforce rules on deserve real columns.' },
            { text: 'Put the whole row in JSONB to keep it flexible', why: 'That’s the dumping ground the lesson warns about.' },
            { text: 'Move it to Google Sheets', why: 'That loses even more rules.' },
            { text: 'Fix the bad value by hand and carry on', why: 'Nothing stops it happening again.' },
          ],
          answer: 0,
          explain: 'JSONB for the raw payload; columns and constraints for what you depend on.',
        },
        {
          id: 'm3-s6-3', kind: 'order',
          prompt: 'Order a replay-safe flow for an incoming webhook.',
          items: ['Store the raw event with ON CONFLICT DO NOTHING', 'Reply 200 to the provider', 'A worker picks up the pending event', 'Process it and record the outcome and status'],
          explain: 'Save first, acknowledge, then do the slow work. If processing fails, the raw event is still there to replay.',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'm3-q1', kind: 'choice',
      prompt: 'A client’s Sheet-based lead tracker keeps getting duplicate rows when two forms arrive together. What does moving to Postgres give you that fixes this?',
      options: [
        { text: 'A UNIQUE constraint that rejects the second row, however the two runs are timed', why: 'Yes. The database enforces it atomically.' },
        { text: 'Faster inserts, so the two runs don’t overlap', why: 'Speed narrows the window but never closes it.' },
        { text: 'Automatic merging of similar rows', why: 'Postgres doesn’t merge rows unless you tell it how.' },
        { text: 'Nothing; duplicates are an n8n problem', why: 'The database is exactly the place to enforce “no duplicates”.' },
      ],
      answer: 0,
      explain: 'Constraints are the last line of defence against duplicates.',
    },
    {
      id: 'm3-q2', kind: 'choice',
      prompt: 'Your production n8n is writing test leads into the live database. The Postgres credential was copied from dev. What’s the lasting fix?',
      options: [
        { text: 'Give each environment its own connection string, set through its own environment variables', why: 'Right. Same workflow, different DATABASE_URL per environment.' },
        { text: 'Add a WHERE clause to skip test leads', why: 'That patches one symptom; dev and prod still share a database.' },
        { text: 'Delete the dev database', why: 'You still need somewhere safe to test.' },
        { text: 'Hard-code the production URL in every node', why: 'Then dev would write to production instead.' },
      ],
      answer: 0,
      explain: 'Environment-specific connection strings keep dev and production apart.',
    },
    {
      id: 'm3-q3', kind: 'choice',
      prompt: 'Which query finds leads who have **never replied**?',
      options: [
        { text: 'SELECT l.email FROM leads l LEFT JOIN replies r ON r.lead_id = l.id WHERE r.lead_id IS NULL;', why: 'Yes. LEFT JOIN keeps every lead; NULL on the reply side means none matched.' },
        { text: 'SELECT l.email FROM leads l JOIN replies r ON r.lead_id = l.id;', why: 'An inner join returns only leads who did reply.' },
        { text: 'SELECT l.email FROM leads l LEFT JOIN replies r ON r.lead_id = l.id WHERE r.lead_id = NULL;', why: '= NULL never matches. You need IS NULL.' },
        { text: 'SELECT email FROM replies;', why: 'Replies only contain leads who replied, and this table has no email column.' },
      ],
      answer: 0,
      explain: 'LEFT JOIN + IS NULL is the standard “has no matching row” pattern (NOT EXISTS also works).',
    },
    {
      id: 'm3-q4', kind: 'choice',
      prompt: 'You want each lead’s **latest** reply only. Which approach fits best?',
      options: [
        { text: 'row_number() OVER (PARTITION BY lead_id ORDER BY replied_at DESC) in a CTE, then keep n = 1', why: 'Yes. Number each lead’s replies newest-first, then filter in the outer query.' },
        { text: 'GROUP BY lead_id and SELECT body', why: 'Postgres won’t let you select body without aggregating it.' },
        { text: 'ORDER BY replied_at DESC LIMIT 1', why: 'That gives one reply in total, not one per lead.' },
        { text: 'WHERE row_number() = 1 in the same query', why: 'WHERE runs before window functions, so this errors.' },
      ],
      answer: 0,
      explain: 'The “latest per group” pattern: window function in a CTE, filter outside.',
    },
    {
      id: 'm3-q5', kind: 'choice',
      prompt: 'Predict the result. `leads` has 3 rows with source `web` and 1 with source `ads`.',
      code: "SELECT source, count(*) AS n\nFROM leads\nGROUP BY source\nHAVING count(*) > 1;",
      options: [
        { text: 'One row: web | 3', why: 'Right. HAVING drops the ads group, which has only 1 lead.' },
        { text: 'Two rows: web | 3 and ads | 1', why: 'HAVING filters out groups with a count of 1 or less.' },
        { text: 'Four rows, one per lead', why: 'GROUP BY collapses rows into one per source.' },
        { text: 'An error, because HAVING needs WHERE', why: 'HAVING works without WHERE.' },
      ],
      answer: 0,
      explain: 'GROUP BY makes groups; HAVING keeps only the groups that pass.',
    },
    {
      id: 'm3-q6', kind: 'choice',
      prompt: 'An n8n workflow writes a deal row, then its line items, as two separate Postgres steps. Sometimes deals appear with no line items. What should you change?',
      options: [
        { text: 'Write both in one transaction so they commit together or not at all', why: 'Yes. A crash between steps can no longer leave half a deal.' },
        { text: 'Add Retry On Fail to the second step', why: 'Retries don’t help if the process died between the steps.' },
        { text: 'Write the line items first', why: 'You’d just get line items without a deal instead.' },
        { text: 'Add a nightly job to delete empty deals', why: 'That cleans up after the damage instead of preventing it.' },
      ],
      answer: 0,
      explain: 'Related writes belong in one atomic transaction.',
    },
    {
      id: 'm3-q7', kind: 'choice',
      prompt: 'Why is `INSERT ... ON CONFLICT (email) DO UPDATE` safer than “SELECT to check, then INSERT”?',
      options: [
        { text: 'Postgres decides insert-or-update atomically, so two simultaneous runs can’t both insert', why: 'Right. Check-then-insert leaves a gap where both runs see “not found”.' },
        { text: 'It’s shorter to type', why: 'True, but safety is the point.' },
        { text: 'It skips constraint checks', why: 'It depends on the unique constraint; it doesn’t skip it.' },
        { text: 'SELECT queries are unreliable', why: 'The SELECT is accurate; the problem is the gap between reading and writing.' },
      ],
      answer: 0,
      explain: 'Upserts close the race that check-then-create leaves open.',
    },
    {
      id: 'm3-q8', kind: 'choice',
      prompt: 'Read the plan for a query on a 40-row `settings` table, which has an index on `key`. What do you conclude?',
      code: 'Seq Scan on settings  (actual time=0.01..0.02 rows=1 loops=1)\n  Filter: (key = \'timezone\')\n  Rows Removed by Filter: 39\nExecution Time: 0.03 ms',
      options: [
        { text: 'Nothing to fix: for a tiny table a sequential scan is cheaper than the index', why: 'Yes. 0.03 ms is fine, and Postgres chose the cheaper plan.' },
        { text: 'The index is broken; rebuild it', why: 'Postgres simply decided not to use it for so few rows.' },
        { text: 'Add a second index', why: 'Another index won’t change the choice and costs writes.' },
        { text: 'Rewrite it with a JOIN', why: 'There’s nothing to join, and nothing is slow.' },
      ],
      answer: 0,
      explain: 'Read the timings, not just the node type. Seq Scan is only a problem on big tables.',
    },
    {
      id: 'm3-q9', kind: 'choice',
      prompt: 'You’re testing `EXPLAIN ANALYZE DELETE FROM events WHERE status = \'done\';` on production. What’s the danger?',
      options: [
        { text: 'EXPLAIN ANALYZE actually runs the DELETE, so the rows are really deleted', why: 'Right. Wrap it in BEGIN ... ROLLBACK if you must test a write.' },
        { text: 'None; EXPLAIN never changes data', why: 'Plain EXPLAIN doesn’t. EXPLAIN ANALYZE executes the statement.' },
        { text: 'It locks the whole database for an hour', why: 'It runs the statement once, no more.' },
        { text: 'It drops the index', why: 'It doesn’t touch indexes.' },
      ],
      answer: 0,
      explain: 'ANALYZE = really run it and measure.',
    },
    {
      id: 'm3-q10', kind: 'choice',
      prompt: 'Your query joins `replies` to `leads` on `replies.lead_id`, which is a foreign key. It’s slow on a big table. What might be missing?',
      options: [
        { text: 'An index on replies.lead_id; Postgres doesn’t create one for foreign keys', why: 'Yes. Primary keys and UNIQUE get indexes automatically; foreign keys don’t.' },
        { text: 'A second foreign key', why: 'One link is enough; speed needs an index.' },
        { text: 'A CHECK constraint', why: 'CHECK validates data; it doesn’t speed up lookups.' },
        { text: 'A larger LIMIT', why: 'LIMIT reduces output, not the work to find matches.' },
      ],
      answer: 0,
      explain: 'Index the columns you join on, and confirm with EXPLAIN ANALYZE.',
    },
    {
      id: 'm3-q11', kind: 'choice',
      prompt: 'When is storing data in a JSONB column a good idea?',
      options: [
        { text: 'For a raw webhook payload whose shape you don’t control, kept alongside real columns for key fields', why: 'Yes. You keep the original exactly, and still enforce rules on what matters.' },
        { text: 'For every field, so you never need migrations', why: 'You lose types, constraints and easy indexing. That’s the dumping ground.' },
        { text: 'For the primary key', why: 'Keys should be simple typed columns.' },
        { text: 'Never; JSON doesn’t belong in a database', why: 'JSONB is very useful for semi-structured data.' },
      ],
      answer: 0,
      explain: 'Raw payload in JSONB; fields you filter, join or validate in columns.',
    },
    {
      id: 'm3-q12', kind: 'order',
      prompt: 'Order the steps for adding a `phone` column to `leads` safely.',
      items: ['Write a numbered migration file and commit it to Git', 'Run it against dev and test the workflow', 'Run it against staging', 'Run it against production using that environment’s connection string'],
      explain: 'The same versioned migration runs everywhere, in order. No hand edits in production.',
    },
  ],
  tasks: [
    { device: 'phone', plain: 'Learn tables, data types, primary and foreign keys, and the NOT NULL, UNIQUE and CHECK constraints.', done: 'You can explain what each constraint prevents, and you’ve passed the checks for Lessons 1 and 2.' },
    { device: 'phone', plain: 'Learn to read and write SELECT queries with WHERE, ORDER BY, JOINs, GROUP BY/HAVING, subqueries and CTEs.', done: 'You’ve passed the Lesson 3 and 4 checks and can write “leads who never replied” from memory.' },
    { device: 'phone', plain: 'Learn enough window functions to answer ranking, running-total and “first or latest per lead” questions.', done: 'You can write a row_number() query that keeps each lead’s latest reply, and explain PARTITION BY.' },
    { device: 'phone', plain: 'Learn transactions (BEGIN, COMMIT, ROLLBACK) and why a half-finished write is dangerous.', done: 'You can explain what happens on a crash before COMMIT, and why an API call inside a transaction isn’t undone.' },
    { device: 'computer', plain: 'Replace a “search, then create” step with a real INSERT ... ON CONFLICT upsert.', done: 'Running the same insert twice, or at the same time, leaves exactly one row.' },
    { device: 'phone', plain: 'Learn what indexes speed up, what they cost, and how to read EXPLAIN and EXPLAIN ANALYZE output.', done: 'You can read a plan and say whether it needs an index, and you’ve passed the Lesson 6 check.' },
    { device: 'phone', plain: 'Learn when JSONB helps (raw payloads) and when it turns into a dumping ground.', done: 'You can name which fields of a webhook you’d keep as real columns, and why.' },
    { device: 'computer', plain: 'Create tables for events, executions, external record IDs, an audit log and retry state.', done: 'A SQL file that creates them in Postgres, with keys, constraints and at least three useful indexes.' },
    { device: 'computer', plain: 'Write the query “leads who replied but never booked”, then check it with EXPLAIN ANALYZE and add an index if needed.', done: 'The query, plus before-and-after plans showing whether the index helped.' },
    { device: 'phone', plain: 'Learn connection strings, connection pooling, migrations and separate database URLs per environment.', done: 'You can explain what a connection pool solves and how a migration reaches production.' },
    { device: 'computer', plain: 'Simulate a crash halfway through a two-table write, once without a transaction and once with one.', done: 'Screenshots showing half-written data without the transaction, and clean data with it.' },
    { device: 'phone', plain: 'Practise sketching the tables for an automation that receives webhooks and must be safe to replay.', done: 'A recorded 3-minute explanation covering the event key, raw payload, retry state and external ID mapping.' },
  ],
};
