import type { Lesson } from './types';

export const m3: Lesson = {
  intro: "Most automations start with Google Sheets as their memory. That works until two runs write at once, someone types “ASAP” into a date column, or a repeated webhook adds the same lead twice. A real database refuses bad data, keeps related changes together and answers questions in milliseconds. This module teaches SQL and PostgreSQL from zero with one running example, leads, their replies and their bookings, and ends with the tables behind an automation you can safely re-run.",
  glossary: {
    'database': 'A program built to store data safely, enforce rules on it and answer questions about it quickly.',
    'postgresql': 'A free, open-source database (“Postgres”). The most common choice for automation back ends, and n8n can use it too.',
    'table': 'One kind of thing in a database, like one tab of a spreadsheet: leads, replies, bookings.',
    'data type': 'What kind of value a column holds (text, number, date and time, true/false). The database rejects anything else.',
    'sql': 'Structured Query Language: the language for creating tables and reading or changing data in a database.',
    'connection string': 'One line with everything needed to reach a database: user, password, host, port and database name.',
    'connection pool': 'A small set of database connections kept open and shared, so many workers don’t each open their own.',
    'primary key': 'The column (or columns) that uniquely identifies each row. Never empty, never repeated.',
    'foreign key': 'A column that points to another table’s primary key, e.g. replies.lead_id → leads.id.',
    'constraint': 'A rule the database checks on every write, e.g. NOT NULL, UNIQUE or CHECK.',
    'null': 'A database’s “no value here”. It isn’t zero or empty text, and you test for it with IS NULL.',
    'cte': 'Common Table Expression: a named step inside a query, written WITH name AS (...).',
    'window function': 'A calculation across related rows (rank, running total, row number) that keeps every row instead of collapsing them.',
    'transaction': 'A group of database changes that are saved together or not at all.',
    'atomic': 'All-or-nothing: either every part happens or none of it does.',
    'outbox': 'A pattern where you save “I need to call the API” in the database first, then a separate step does it and records the result.',
    'index': 'A sorted lookup structure on a column, like the index at the back of a book, so the database finds rows without reading all of them.',
    'query plan': 'The database’s step-by-step plan for running a query, shown by EXPLAIN.',
    'jsonb': 'A Postgres column type that stores JSON in a form you can search and index.',
    'audit log': 'An append-only record of who or what changed which data, and when.',
  },
  sections: [
    {
      title: 'What is a database, and why not just Google Sheets?',
      minutes: 6,
      body: [
        "**The problem.** Your lead automation writes every new lead to a Google Sheet. It works for a month. Then a colleague sorts one column and scrambles the rows, someone types “next Tuesday” into a date column, and two webhook runs land at the same moment and add the same lead twice. **A sheet accepts whatever you give it.**",
        "A [[database]] is a program built to store data safely and answer questions about it. It checks every write against rules you set, lets many workflows read and write at once without overwriting each other, and stays fast with millions of rows. [[PostgreSQL]] (“Postgres”) is the free one most automation teams use.",
        "**The analogy.** A sheet is a whiteboard: anyone can write anything anywhere. A database is a strict filing clerk who hands back any form with a missing or wrong field.",
        "The words you need:",
        "- **[[Table]]**: one kind of thing, like a sheet tab: `leads`, `replies`, `bookings`.\n- **Row**: one record, e.g. one lead.\n- **Column**: one fact about every row, with a fixed [[data type]]: `text`, `integer`, `boolean` (true/false), `timestamptz` (date and time with timezone), `numeric` (exact numbers, for money).\n- **[[SQL]]**: the language you use to create tables and ask questions. Nearly every database speaks it.",
        "**How n8n or Python reaches it.** Through a [[connection string]]: one line with user, password, host, port and database name. Keep it in an [[environment variable]] such as `DATABASE_URL`, with a different value for dev and production, never inside the workflow or code.",
        "**Production point.** Each open connection uses memory on the database server, and Postgres only allows a set number (the `max_connections` setting, 100 by default). Twenty workers each opening ten connections hit that wall. A [[connection pool]] keeps a few connections open and shares them; PgBouncer is the usual tool.",
      ],
      example: {
        caption: 'A connection string and your first table',
        code: "-- connection string, kept in DATABASE_URL:\n-- postgresql://app_user:secret@db.example.com:5432/leads_db\n--             user     password host           port database\n\nCREATE TABLE leads (\n  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- auto-numbered ID\n  email      text NOT NULL,                 -- must be filled in\n  full_name  text,                          -- may be left empty\n  source     text,                          -- e.g. 'webform', 'linkedin'\n  created_at timestamptz NOT NULL DEFAULT now()  -- set automatically\n);",
      },
      interview: "I use Postgres rather than a spreadsheet as the source of truth because it enforces types and constraints, handles concurrent writers safely, and supports transactions. Connection details come from an environment-specific DATABASE_URL, and with many workers I put a pooler like PgBouncer in front so we don’t exhaust max_connections.",
      check: [
        {
          id: 'm3-s0-1', kind: 'choice',
          prompt: 'Your workflow tries to save “ASAP” into the `follow_up_at` column, which has type `timestamptz`. What happens in Postgres?',
          options: [
            { text: 'The insert fails with an invalid-input error for type timestamptz', why: 'Right. A typed column rejects any value it can’t parse, so the bad data never gets in.' },
            { text: 'Postgres stores NULL instead, since the value can’t be read as a date', why: 'Postgres doesn’t swap bad input for NULL. It raises an error and the whole insert fails.' },
            { text: 'It’s saved as plain text, because timestamptz columns accept strings', why: 'A typed column only accepts text it can convert to that type. Free text like “ASAP” is refused.' },
            { text: 'Postgres reads it like the special input ‘now’ and saves the current time', why: 'Postgres does accept a few special words such as ‘now’ and ‘today’, but “ASAP” isn’t one, so it errors.' },
          ],
          answer: 0,
          explain: 'Typed columns catch bad data at the door, instead of letting it break a report three weeks later.',
        },
        {
          id: 'm3-s0-2', kind: 'choice',
          prompt: 'Your workers start failing with `FATAL: sorry, too many clients already`. What’s the most likely fix?',
          options: [
            { text: 'Add a pooler like PgBouncer so workers share a few open connections', why: 'Yes. The server has hit its connection limit; pooling shares connections instead of opening more.' },
            { text: 'Raise max_connections to 2,000 so every worker gets its own connections', why: 'Each connection costs server memory. A cap that high trades this error for memory pressure, and it grows with every new worker.' },
            { text: 'Close idle sessions with a nightly job that runs pg_terminate_backend', why: 'The limit is hit at busy times. Killing sessions overnight does nothing for the daytime peak.' },
            { text: 'Increase the connect timeout in DATABASE_URL so workers wait longer', why: 'The server refuses the connection outright. Waiting longer on the client side doesn’t free a slot.' },
          ],
          answer: 0,
          explain: 'Every connection costs memory, and max_connections caps them. A pooler such as PgBouncer is the standard answer.',
        },
      ],
    },
    {
      title: 'Keys and constraints: rules the database enforces',
      minutes: 6,
      body: [
        "Tables get useful when they connect. One lead can send several replies and make a booking. You link them with keys.",
        "- **[[Primary key]]**: the column that uniquely identifies each row, like a lead’s `id`. Never empty, never repeated.\n- **[[Foreign key]]**: a column that points at another table’s primary key. `replies.lead_id` says “this reply belongs to lead 42”. Postgres refuses a reply for a lead that doesn’t exist.",
        "Then add [[constraint|constraints]], rules checked on every insert and update:",
        "- `NOT NULL`: this column must have a value.\n- `UNIQUE`: no two rows may share this value, e.g. one lead per email. That’s a [[unique constraint]].\n- `CHECK`: a custom rule, e.g. status must be one of `new`, `contacted`, `booked`.",
        "**Why bother, if your n8n workflow already checks?** Because a workflow check can race. Two webhook runs arrive together. Both ask “does ana@example.com exist?”, both hear “no”, both insert. That’s a [[race condition]], and now you have a duplicate lead. A `UNIQUE` constraint can’t race: Postgres lets the first insert in and rejects the second.",
        "**Constraints are your last line of defence.** Whatever bug sits upstream, in n8n, Python or a human import, the database still refuses duplicates and broken links.",
        "**Production point.** Clean values before you compare them. `Ana@Example.com ` and `ana@example.com` are different text, so a plain `UNIQUE` lets both in. Store emails trimmed and lowercased, or enforce it with a unique index on `lower(email)`.",
      ],
      example: {
        caption: 'The running example: leads, replies, bookings',
        code: "CREATE TABLE leads (\n  id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  email     text NOT NULL UNIQUE,              -- one row per email\n  full_name text,\n  source    text,\n  status    text NOT NULL DEFAULT 'new'\n            CHECK (status IN ('new', 'contacted', 'booked'))\n);\n\nCREATE TABLE replies (\n  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  lead_id    bigint NOT NULL REFERENCES leads(id),  -- foreign key\n  body       text NOT NULL,\n  replied_at timestamptz NOT NULL\n);\n\nCREATE TABLE bookings (\n  id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  lead_id   bigint NOT NULL REFERENCES leads(id),\n  starts_at timestamptz NOT NULL\n);",
      },
      interview: "I put business invariants in the schema: primary keys for identity, foreign keys for relationships, and UNIQUE, CHECK and NOT NULL for rules. An application-level “check then insert” can race under concurrency, so the unique constraint is the authoritative guard against duplicates.",
      check: [
        {
          id: 'm3-s1-1', kind: 'choice',
          prompt: 'Your workflow searches for the lead’s email and only inserts if nothing is found. You still get occasional duplicates. What’s the real fix?',
          options: [
            { text: 'Add a UNIQUE constraint on email so Postgres rejects the second insert', why: 'Yes. Two simultaneous runs can both find nothing; the constraint can’t be raced.' },
            { text: 'Wrap the search and the insert in a transaction so they run as one unit', why: 'Under the default isolation level, two transactions can still both read “not found” and both insert.' },
            { text: 'Search again right after inserting and delete the newer row if one exists', why: 'That second check races too: both runs may delete, or neither will.' },
            { text: 'Lowercase emails before searching, so the lookup matches reliably', why: 'That helps with “Ana@” vs “ana@”, but these duplicates come from simultaneous runs that both find nothing.' },
          ],
          answer: 0,
          explain: 'A check in the workflow is a courtesy. A constraint in the database is a guarantee.',
        },
        {
          id: 'm3-s1-2', kind: 'choice',
          prompt: 'You insert a reply with `lead_id = 999`, but no lead 999 exists. What happens?',
          options: [
            { text: 'Postgres rejects the insert with a foreign key violation', why: 'Right. The foreign key guarantees every reply belongs to a real lead.' },
            { text: 'It’s saved, and the link is only checked when you next join', why: 'The link is checked at insert time, not when you read.' },
            { text: 'Postgres saves it with lead_id set to NULL, as no lead matches', why: 'The column is NOT NULL, and Postgres doesn’t rewrite your values anyway.' },
            { text: 'The insert succeeds, since foreign keys only guard DELETEs', why: 'Foreign keys are checked on inserts and updates of the child row too, not just on deletes of the parent.' },
          ],
          answer: 0,
          explain: 'Foreign keys stop “orphan” rows that point at nothing.',
        },
        {
          id: 'm3-s1-3', kind: 'choice',
          prompt: 'A typo saves a lead with status `bookd`. Which constraint would have stopped it?',
          options: [
            { text: 'A CHECK constraint listing the allowed status words', why: 'Yes. CHECK enforces custom rules like an allowed list.' },
            { text: 'A NOT NULL constraint with DEFAULT ‘new’', why: '“bookd” isn’t empty, so NOT NULL is satisfied, and a default only applies when no value is given.' },
            { text: 'A UNIQUE constraint on the status column', why: 'Many leads share a status, so UNIQUE would wrongly block the second “booked” lead and still allow “bookd”.' },
            { text: 'Making status varchar(6) instead of text', why: 'A length limit only stops long values. “bookd” is five characters and fits.' },
          ],
          answer: 0,
          explain: 'NOT NULL = must exist, UNIQUE = no repeats, CHECK = must follow this rule.',
        },
      ],
    },
    {
      title: 'Asking questions: SELECT, WHERE and JOIN',
      minutes: 7,
      body: [
        "Reading data is one statement, `SELECT`. You say which columns, from which table, which rows and in what order:",
        "- `SELECT email, status` picks columns (`*` means all).\n- `FROM leads` picks the table.\n- `WHERE status = 'new'` keeps only matching rows.\n- `ORDER BY created_at DESC` sorts, newest first.\n- `LIMIT 10` returns at most 10 rows.",
        "**JOIN combines tables** using the keys from the last lesson. Look at the three tiny tables in the example: Ana replied and booked, Ben replied only, Cat did neither.",
        "- An inner `JOIN` keeps only rows that match on both sides. Leads joined to replies gives Ana and Ben.\n- A `LEFT JOIN` keeps **every** row from the left table and fills the right side with [[null|NULL]] where nothing matches. Leads left-joined to replies gives Ana, Ben, and Cat with an empty reply.",
        "That empty side is useful: it means “nothing there”. **The classic interview query** is “leads who replied but never booked”: join leads to replies, `LEFT JOIN` bookings, keep rows where the booking is `NULL`. The answer is Ben.",
        "Two traps:",
        "- `NULL` isn’t equal to anything, not even another `NULL`. Test it with `IS NULL`; `= NULL` never matches.\n- Joins multiply. If Ben replied three times, joining gives three Ben rows. Add `DISTINCT`, or use `WHERE EXISTS (...)`, when you want each lead once.",
      ],
      example: {
        caption: 'Leads who replied but never booked',
        code: "-- leads           replies             bookings\n-- id | email      lead_id | body      lead_id | starts_at\n-- 1  | ana@…      1       | 'Yes!'    1       | Tue 10am\n-- 2  | ben@…      2       | 'Info?'\n-- 3  | cat@…\n\nSELECT DISTINCT l.id, l.email\nFROM leads l                            -- l is a short nickname\nJOIN replies r ON r.lead_id = l.id      -- only leads who replied\nLEFT JOIN bookings b ON b.lead_id = l.id  -- booking if there is one\nWHERE b.lead_id IS NULL                 -- …but there isn’t\nORDER BY l.id;\n-- result: 2 | ben@…",
      },
      interview: "For “replied but never booked” I inner-join leads to replies and left-join bookings, filtering where the booking key IS NULL; NOT EXISTS is an equivalent anti-join that avoids duplicate rows. I watch for row multiplication on one-to-many joins and NULL semantics in filters.",
      check: [
        {
          id: 'm3-s2-1', kind: 'choice',
          prompt: 'Using the example tables (each lead has at most one reply), how many rows does this return?',
          code: 'SELECT l.email, r.body\nFROM leads l\nLEFT JOIN replies r ON r.lead_id = l.id;',
          options: [
            { text: '3: Ana and Ben, plus Cat with a NULL body', why: 'Yes. LEFT JOIN keeps every lead, with NULL where there’s no reply.' },
            { text: '2: Ana and Ben, the leads with a reply', why: 'That’s what an inner JOIN would return.' },
            { text: '3: Ana, Ben, Cat, but Cat’s email is NULL', why: 'The NULLs go on the right-hand side (replies). Cat’s own email comes from leads and is filled in.' },
            { text: '6: every lead paired with every reply', why: 'That’s a cross join. The ON condition only pairs replies with their own lead.' },
          ],
          answer: 0,
          explain: 'Inner JOIN = matches only. LEFT JOIN = everything on the left, matched or not.',
        },
        {
          id: 'm3-s2-2', kind: 'choice',
          prompt: 'This query returns no rows, even though Ben clearly has no booking. What’s wrong?',
          code: '... LEFT JOIN bookings b ON b.lead_id = l.id\nWHERE b.lead_id = NULL;',
          options: [
            { text: '`= NULL` never matches; it must be `IS NULL`', why: 'Right. NULL means unknown, so comparing with = is never true.' },
            { text: 'The LEFT JOIN should be an inner JOIN', why: 'An inner JOIN would drop Ben entirely, since he has no booking to match.' },
            { text: 'The filter belongs in the ON clause, not WHERE', why: 'Moving it doesn’t help: `= NULL` is never true wherever you put it.' },
            { text: 'NULL needs quotes, as in `= \'NULL\'`, to match', why: 'That compares with the four-letter text ‘NULL’, which is a different thing from a missing value.' },
          ],
          answer: 0,
          explain: 'Always IS NULL / IS NOT NULL. A very common interview gotcha.',
        },
      ],
    },
    {
      title: 'Summaries: GROUP BY, CTEs and window functions',
      minutes: 7,
      body: [
        "Clients ask “how many leads came from each source last week?” That’s **GROUP BY**: it squashes rows into groups and calculates one result per group with `count(*)`, `sum()`, `avg()`, `min()` or `max()`. Grouping by `date_trunc('week', created_at)` puts leads into weekly cohorts.",
        "`WHERE` filters rows **before** grouping. `HAVING` filters groups **after**: “only sources with more than 20 leads”.",
        "**Breaking a big query into steps.** A query can contain another query (a subquery), but nesting gets hard to read. A [[CTE]], written `WITH name AS (...)`, gives each step a name, like a helper column in a sheet. You read it top to bottom.",
        "**A taste of [[window function|window functions]].** `GROUP BY` collapses many rows into one per group. A window function calculates across related rows but **keeps every row**. Three everyday uses:",
        "- `row_number() OVER (PARTITION BY lead_id ORDER BY replied_at)`: number each lead’s replies 1, 2, 3, so you can pick the first.\n- `rank() OVER (ORDER BY total DESC)`: rank sources by volume.\n- `sum(bookings) OVER (ORDER BY day)`: a running total of bookings by day.",
        "`PARTITION BY` means “restart for each lead”. The `ORDER BY` inside `OVER` sets the sequence. That’s enough for ranking, running-total and cohort questions.",
        "**Production point.** You can’t filter on a window function in the same query’s `WHERE`, because `WHERE` runs first. Calculate it in a CTE, then filter in the next step, as in the example.",
      ],
      example: {
        caption: 'First reply per lead, counted by source',
        code: "WITH first_replies AS (            -- step 1: number each lead's replies\n  SELECT lead_id,\n         row_number() OVER (PARTITION BY lead_id\n                            ORDER BY replied_at) AS n\n  FROM replies\n)\nSELECT l.source, count(*) AS replied_leads   -- step 2: summarise\nFROM first_replies f\nJOIN leads l ON l.id = f.lead_id\nWHERE f.n = 1                      -- first reply only, so one per lead\nGROUP BY l.source\nHAVING count(*) > 20               -- filters groups, not rows\nORDER BY replied_leads DESC;",
      },
      interview: "I use GROUP BY with HAVING for aggregates, CTEs to stage complex queries readably, and window functions like row_number, rank and running sums when I need per-row results with group context, such as the latest event per entity. Window results are filtered in an outer query, since WHERE is evaluated before them.",
      check: [
        {
          id: 'm3-s3-1', kind: 'choice',
          prompt: 'This query errors. What’s the fix?',
          code: 'SELECT source, count(*)\nFROM leads\nWHERE count(*) > 20\nGROUP BY source;',
          options: [
            { text: 'Move it to `HAVING count(*) > 20` after GROUP BY', why: 'Yes. Conditions on group results belong in HAVING.' },
            { text: 'Move WHERE below GROUP BY so it runs after grouping', why: 'Clause order is fixed in SQL: WHERE must come before GROUP BY. Group filters use HAVING.' },
            { text: 'Give count(*) an alias and use the alias in WHERE', why: 'WHERE can’t see SELECT aliases, and it runs before any counting happens.' },
            { text: 'Replace count(*) with count(source) in WHERE', why: 'Any aggregate in WHERE fails, because WHERE filters single rows before groups exist.' },
          ],
          answer: 0,
          explain: 'WHERE filters rows before grouping; HAVING filters groups after.',
        },
        {
          id: 'm3-s3-2', kind: 'choice',
          prompt: 'The `replies` table has 10 rows from 4 leads. How many rows does `SELECT lead_id, row_number() OVER (PARTITION BY lead_id ORDER BY replied_at) FROM replies` return?',
          options: [
            { text: '10, one per reply, each with a number', why: 'Right. It adds a number to each row instead of collapsing them.' },
            { text: '4, one row per lead with its highest number', why: 'That’s what GROUP BY lead_id with max() would give. Window functions don’t collapse rows.' },
            { text: '1, the earliest reply across all leads', why: 'Nothing here filters to n = 1, and PARTITION BY restarts per lead anyway.' },
            { text: '40, each reply numbered against each lead', why: 'Window functions don’t multiply rows; PARTITION BY only groups the numbering.' },
          ],
          answer: 0,
          explain: 'GROUP BY collapses; window functions annotate.',
        },
      ],
    },
    {
      title: 'Transactions and upserts: all-or-nothing writes',
      minutes: 7,
      body: [
        "**The problem.** A booking arrives. Your workflow inserts the booking, then sets the lead’s status to `booked`. The server restarts between the two. Now there’s a booking for a lead still marked `new`, and tomorrow’s follow-up emails someone who already booked. **A half-finished write is worse than none**, because nothing looks broken.",
        "A [[transaction]] groups statements so they succeed or fail together ([[atomic]]). `BEGIN` starts it, `COMMIT` saves everything, `ROLLBACK` undoes everything. If the connection drops before `COMMIT`, Postgres throws the whole lot away.",
        "**The limit.** A transaction only covers the database. If you call the CRM inside one and then roll back, the CRM contact still exists. For outside effects, save what you *intend* to do in the database, do it in a separate step, then record the result. That’s the [[outbox]] pattern; checking the provider afterwards to confirm is called reconciliation.",
        "**Upserts fix the check-then-create race.** An [[upsert]] (`INSERT ... ON CONFLICT`) tries the insert. If it hits a unique constraint, it does nothing or updates the existing row instead, decided atomically by Postgres. Two simultaneous runs can’t both create the lead.",
        "- `ON CONFLICT (email) DO NOTHING`: keep the first, ignore repeats. Ideal for storing webhook events.\n- `ON CONFLICT (email) DO UPDATE SET ...`: update the existing row. `EXCLUDED` means “the row you tried to insert”.\n- `RETURNING id`: hand back the row’s ID for the next n8n node.",
        "**Production points.** `ON CONFLICT` needs a unique constraint or index on that column, or Postgres raises an error. And a transaction alone doesn’t stop duplicates: under the default isolation level, two transactions can both read “not found”. The unique constraint is what stops the second insert.",
      ],
      example: {
        caption: 'A transaction, then an upsert',
        code: "BEGIN;\n  INSERT INTO bookings (lead_id, starts_at)\n  VALUES (42, '2026-10-14 10:00+10');\n  UPDATE leads SET status = 'booked' WHERE id = 42;\nCOMMIT;  -- both saved; on an error or crash, neither\n\n-- create the lead, or refresh its name if the email exists\nINSERT INTO leads (email, full_name)\nVALUES ('ana@example.com', 'Ana Lopez')\nON CONFLICT (email)\nDO UPDATE SET full_name = EXCLUDED.full_name\nRETURNING id;",
      },
      interview: "Related writes go in one transaction so a crash can’t leave partial state. Transactions don’t cover external side effects, so for API calls I record intent, dispatch separately and reconcile. For create-or-update I use INSERT … ON CONFLICT against a unique constraint instead of check-then-insert, which races under Read Committed.",
      check: [
        {
          id: 'm3-s4-1', kind: 'choice',
          prompt: 'Inside `BEGIN ... COMMIT`, the booking insert succeeds, then the server crashes before the status update. What’s in the database afterwards?',
          options: [
            { text: 'Neither change: no booking, status unchanged', why: 'Right. Nothing was committed, so Postgres discards the partial work.' },
            { text: 'The booking, but the lead still marked new', why: 'That’s what happens without a transaction.' },
            { text: 'Both, as Postgres replays its log on restart', why: 'Recovery only replays committed work. Uncommitted changes are thrown away.' },
            { text: 'The booking, until someone runs ROLLBACK by hand', why: 'You don’t need to clean up: a dropped connection rolls back automatically.' },
          ],
          answer: 0,
          explain: 'All or nothing. That’s what makes multi-table writes safe.',
        },
        {
          id: 'm3-s4-2', kind: 'choice',
          prompt: 'A transaction inserts a booking, calls an SMS API to confirm it, then hits an error and rolls back. What happened?',
          options: [
            { text: 'The booking is undone; the SMS was still sent', why: 'Yes. A rollback can’t un-send a message at another company.' },
            { text: 'Both are undone, since the API call ran inside it', why: 'Rollback only affects your database. Postgres has no idea the SMS exists.' },
            { text: 'Neither is undone, as the API call committed it', why: 'Calling an API doesn’t commit anything in Postgres; the booking insert is rolled back.' },
            { text: 'The SMS is queued and only sent after COMMIT', why: 'The API call happened immediately. Postgres can’t hold back requests your code makes.' },
          ],
          answer: 0,
          explain: 'Keep external calls out of transactions: record intent, send separately, record the outcome.',
        },
        {
          id: 'm3-s4-3', kind: 'choice',
          prompt: 'Your upsert fails with: `there is no unique or exclusion constraint matching the ON CONFLICT specification`. Why?',
          options: [
            { text: 'The ON CONFLICT column has no unique index or constraint', why: 'Right. ON CONFLICT needs a unique constraint or index to know what counts as a conflict.' },
            { text: 'The table has no primary key for ON CONFLICT to use', why: 'A primary key wouldn’t help: the conflict target is the column you named, and that’s what needs to be unique.' },
            { text: 'ON CONFLICT must run inside BEGIN ... COMMIT', why: 'A single statement is already atomic on its own. The error is about a missing constraint.' },
            { text: 'RETURNING can’t be combined with ON CONFLICT', why: 'RETURNING works fine with ON CONFLICT; the lesson’s example uses both.' },
          ],
          answer: 0,
          explain: 'Add the UNIQUE constraint first; the upsert relies on it.',
        },
      ],
    },
    {
      title: 'Indexes and EXPLAIN: making queries fast',
      minutes: 6,
      body: [
        "With 200 leads every query feels instant. With 2 million, “find this lead’s replies” can take seconds, because Postgres reads **every row** to check it. That’s a sequential scan.",
        "An [[index]] is like the index at the back of a book: a sorted list of values with a pointer to each row, so Postgres jumps straight to the match. `CREATE INDEX ON replies (lead_id);`",
        "**Indexes aren’t free.** Every insert and update must also update each index, and they use disk space. On a table receiving thousands of webhook events a minute, ten unused indexes slow every write. So **index the columns your real queries filter, join or sort on**, not every column.",
        "A primary key and a `UNIQUE` constraint already create an index. **A foreign key does not**, so index columns like `lead_id` yourself if you join on them.",
        "**How to know.** Put `EXPLAIN` in front of a query and Postgres shows its [[query plan]]: how it intends to run it. `EXPLAIN ANALYZE` actually runs it and adds real timings and row counts. Look for:",
        "- `Seq Scan` on a big table when you expected a few rows: probably a missing index.\n- `Index Scan`: the index is being used.\n- `Rows Removed by Filter`: rows read and thrown away.\n- `Execution Time`: total milliseconds.",
        "**Production points.** On a small table Postgres may choose a `Seq Scan` even with an index, because reading a few pages is cheaper. That’s fine. And `EXPLAIN ANALYZE` really executes the statement, so on an `UPDATE` or `DELETE` it changes data: wrap it in `BEGIN` ... `ROLLBACK`. The habit is: write the query, measure, add one index, measure again.",
      ],
      example: {
        caption: 'EXPLAIN ANALYZE before and after CREATE INDEX ON replies (lead_id)',
        code: "-- before: reads all 2 million rows to find 3\nSeq Scan on replies  (actual time=0.1..182.4 rows=3 loops=1)\n  Filter: (lead_id = 42)\n  Rows Removed by Filter: 1999997\nExecution Time: 182.5 ms\n\n-- after: jumps straight to them\nIndex Scan using replies_lead_id_idx on replies\n    (actual time=0.03..0.04 rows=3 loops=1)\n  Index Cond: (lead_id = 42)\nExecution Time: 0.06 ms",
      },
      interview: "I let query patterns drive indexing: I write the query, check the plan with EXPLAIN ANALYZE, and add an index for frequent filters, joins and sorts, then re-measure. Indexes cost write throughput and storage, so on high-ingest tables I keep only the ones a real query uses. Postgres doesn’t index foreign key columns automatically.",
      check: [
        {
          id: 'm3-s5-1', kind: 'choice',
          prompt: '`bookings` has only its primary key index. Read the plan. What’s the best next step?',
          code: 'Seq Scan on bookings  (actual time=0.2..240.9 rows=1 loops=1)\n  Filter: (lead_id = 7)\n  Rows Removed by Filter: 3500000',
          options: [
            { text: 'Index bookings.lead_id and re-run EXPLAIN ANALYZE', why: 'Yes. It read 3.5 million rows to find one, a clear sign of a missing index.' },
            { text: 'Run VACUUM ANALYZE so the planner uses the right index', why: 'Fresh statistics can’t help when there’s no index on lead_id to choose.' },
            { text: 'Add LIMIT 1 so Postgres stops after the first match', why: 'It still scans until it finds the row, and reads everything when there’s no match.' },
            { text: 'Raise work_mem so the scan runs in memory, not on disk', why: 'work_mem is for sorts and hashes. The problem is reading every row, not where they’re read.' },
          ],
          answer: 0,
          explain: 'Seq Scan + huge “Rows Removed by Filter” on a selective query = index candidate.',
        },
        {
          id: 'm3-s5-2', kind: 'choice',
          prompt: 'After a colleague adds 12 indexes to the `events` table, webhook inserts get noticeably slower. Why?',
          options: [
            { text: 'Each insert must also update every one of the 12 indexes', why: 'Right. Indexes speed up reads but add work to every write.' },
            { text: 'New indexes need a VACUUM before inserts are fast', why: 'VACUUM cleans up dead rows; it doesn’t remove the cost of maintaining 12 indexes per insert.' },
            { text: 'Indexed tables block writes while a read is running', why: 'In Postgres, normal reads and writes don’t block each other, indexed or not.' },
            { text: 'The planner re-plans every insert across 12 indexes', why: 'Planning a simple insert is trivial. The cost is writing an entry into each index.' },
          ],
          answer: 0,
          explain: 'Index what your real queries need, and drop indexes nothing uses.',
        },
      ],
    },
    {
      title: 'Designing tables for an automation',
      minutes: 7,
      body: [
        "A reliable automation needs the database to remember **what happened**, not just the final result. A typical set of tables:",
        "- **events**: every inbound webhook, stored raw before any processing.\n- **executions** (or attempts): each try at processing an event: when, outcome, error.\n- **external_records**: your ID mapped to the CRM’s ID, so a replay updates the same contact instead of creating another.\n- **[[Audit log]]**: who or what changed which data, and when. Rows are only ever added.",
        "**The events table matters most.** Its primary key is the client account (tenant) plus the provider’s own event ID, so a repeated delivery hits the constraint and `ON CONFLICT DO NOTHING` ignores it. A random ID generated on arrival would defeat this, because every repeat would look new. The table also holds **retry state**: `status`, `attempts`, `next_attempt_at` and `last_error`. A worker picks rows that are `pending` and due.",
        "**Two workers, one job.** If two workers both ask for “the next pending event”, they can grab the same row and process it twice. Claim it inside a transaction with `SELECT ... FOR UPDATE SKIP LOCKED`: `FOR UPDATE` locks the row you picked, and `SKIP LOCKED` tells other workers to pass over locked rows instead of waiting. Set the row to `processing` in the same transaction and commit. Each worker now gets a different event.",
        "Keep two timestamps: `occurred_at` (when it happened at the provider) and `received_at` (when you stored it). Webhooks arrive late and out of order.",
        "[[JSONB]] stores the raw payload in one column that you can still query: `payload->>'email'` returns the email as text. That’s ideal for raw events whose shape you don’t control. It becomes a **dumping ground** when the fields you filter, join or enforce rules on exist only inside the JSON: no types, no constraints. Keep the raw JSON, and copy the fields you depend on into real columns.",
        "**Changing tables later.** Never edit production tables by hand. Each change is a [[migration]]: a small numbered SQL file in Git, run in order against dev, staging and production, each with its own connection string.",
      ],
      example: {
        caption: 'An events table you can safely replay from',
        code: "CREATE TABLE events (\n  tenant_id       text NOT NULL,         -- which client account\n  event_id        text NOT NULL,         -- the provider's own ID\n  event_type      text NOT NULL,         -- e.g. 'lead.created'\n  payload         jsonb NOT NULL,        -- raw body, untouched\n  occurred_at     timestamptz,\n  received_at     timestamptz NOT NULL DEFAULT now(),\n  status          text NOT NULL DEFAULT 'pending'\n    CHECK (status IN ('pending', 'processing', 'done', 'failed')),\n  attempts        int NOT NULL DEFAULT 0,\n  next_attempt_at timestamptz,\n  last_error      text,\n  PRIMARY KEY (tenant_id, event_id)      -- a repeat can't duplicate\n);\nCREATE INDEX ON events (status, next_attempt_at);  -- the worker's query\n\nINSERT INTO events (tenant_id, event_id, event_type, payload)\nVALUES ('acme', 'evt_123', 'lead.created', '{\"email\": \"ana@example.com\"}')\nON CONFLICT DO NOTHING;               -- second delivery is ignored\n\n-- a worker claims one due event; other workers skip it\nBEGIN;\nSELECT tenant_id, event_id FROM events\nWHERE status = 'pending'\n  AND (next_attempt_at IS NULL OR next_attempt_at <= now())\nORDER BY received_at\nLIMIT 1\nFOR UPDATE SKIP LOCKED;\n-- UPDATE that row SET status = 'processing', then:\nCOMMIT;",
      },
      interview: "I model inbound work as an event store keyed on tenant plus provider event ID, with the raw payload in JSONB, occurred_at separate from received_at, and explicit retry state; workers claim jobs with FOR UPDATE SKIP LOCKED. External IDs live in a mapping table so replays update rather than create, and schema changes ship as versioned migrations.",
      check: [
        {
          id: 'm3-s6-1', kind: 'choice',
          prompt: 'Your events table uses `gen_random_uuid()` as its primary key. The provider sends the same webhook twice. What happens?',
          options: [
            { text: 'Both are stored, each with its own new random ID', why: 'Right. A fresh random key makes every repeat look new, so deduplication never triggers.' },
            { text: 'The second is rejected by the primary key', why: 'Only if the key came from the provider’s event ID. Two random UUIDs never collide.' },
            { text: 'Postgres spots the identical payload and skips it', why: 'Postgres only compares what a constraint tells it to. Nothing here covers the payload.' },
            { text: 'The second replaces the first with the same payload', why: 'Nothing conflicts, so there’s nothing to replace. Both rows are inserted.' },
          ],
          answer: 0,
          explain: 'Deduplicate on a stable key from the source (tenant + provider event ID), not one you invent on arrival.',
        },
        {
          id: 'm3-s6-2', kind: 'choice',
          prompt: 'You run two copies of your worker. Each one does `SELECT ... FROM events WHERE status = \'pending\' LIMIT 1`, then processes the row. Some events get processed twice. What fixes it?',
          options: [
            { text: 'Claim rows with FOR UPDATE SKIP LOCKED in a transaction', why: 'Yes. The first worker locks its row; the second skips it and takes the next one.' },
            { text: 'Add ORDER BY received_at so the workers see a fixed order', why: 'A fixed order makes it worse: both workers now pick the very same first row.' },
            { text: 'Wrap the SELECT in a transaction at the default isolation', why: 'A plain SELECT takes no row lock, so both transactions can still read the same pending row.' },
            { text: 'Use LIMIT 10 so each worker takes its own batch of rows', why: 'Both workers would read the same ten rows. Nothing marks a row as taken.' },
          ],
          answer: 0,
          explain: 'FOR UPDATE locks the claimed row; SKIP LOCKED lets other workers move on instead of waiting or doubling up.',
        },
        {
          id: 'm3-s6-3', kind: 'order',
          prompt: 'Order a replay-safe flow for an incoming webhook.',
          items: ['Store the raw event with ON CONFLICT DO NOTHING', 'Reply 200 to the provider', 'A worker claims the pending event with SKIP LOCKED', 'Process it and record the outcome and status'],
          explain: 'Save first, acknowledge, then do the slow work. If processing fails, the raw event is still there to replay.',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'm3-q1', kind: 'choice',
      prompt: 'A client’s Sheet-based lead tracker keeps getting duplicate rows when two forms arrive together. What does moving to Postgres give you that fixes this?',
      options: [
        { text: 'A UNIQUE constraint that rejects the second row, whatever the timing', why: 'Yes. The database enforces it atomically.' },
        { text: 'Row-level locks, so the second insert waits until the first one commits', why: 'Locks protect rows that already exist. Two brand-new rows don’t lock each other, so both go in.' },
        { text: 'Transactions, so each form’s check and insert happen as one unit', why: 'Under the default isolation level both transactions can still read “not found” and insert.' },
        { text: 'Auto-increment IDs, so each row has a key the sheet never had', why: 'Each duplicate just gets its own new ID. A generated key never spots a repeat.' },
      ],
      answer: 0,
      explain: 'Constraints are the last line of defence against duplicates.',
    },
    {
      id: 'm3-q2', kind: 'choice',
      prompt: 'Your production n8n is writing test leads into the live database. The Postgres credential was copied from dev. What’s the lasting fix?',
      options: [
        { text: 'A separate DATABASE_URL per environment, set by env variables', why: 'Right. Same workflow, different connection string per environment.' },
        { text: 'A separate Postgres schema for test leads in the same database', why: 'Dev and production would still share one server and one credential, so one slip mixes them again.' },
        { text: 'An is_test column, and filter test rows out of reports', why: 'That hides the symptom; test traffic still lands in the live database.' },
        { text: 'Rename the credential “Production” so it’s clearly marked', why: 'A label doesn’t change where the connection string points.' },
      ],
      answer: 0,
      explain: 'Environment-specific connection strings keep dev and production apart.',
    },
    {
      id: 'm3-q3', kind: 'choice',
      prompt: 'Which query finds leads who have **never replied**?',
      options: [
        { text: 'SELECT email FROM leads l WHERE NOT EXISTS (SELECT 1 FROM replies r WHERE r.lead_id = l.id);', why: 'Yes. It keeps each lead for which no reply row exists.' },
        { text: 'SELECT r.lead_id FROM replies r GROUP BY r.lead_id HAVING count(r.id) = 0;', why: 'Every lead in replies has at least one reply, so no group has a count of 0. This returns nothing.' },
        { text: 'SELECT l.email FROM leads l LEFT JOIN replies r ON r.lead_id = l.id WHERE r.lead_id = NULL;', why: 'Close, but = NULL never matches. With IS NULL this would work.' },
        { text: 'SELECT DISTINCT l.email FROM leads l JOIN replies r ON r.lead_id <> l.id;', why: 'This pairs each lead with other leads’ replies, so nearly every lead appears.' },
      ],
      answer: 0,
      explain: 'NOT EXISTS, or LEFT JOIN + IS NULL, is the standard “has no matching row” pattern.',
    },
    {
      id: 'm3-q4', kind: 'choice',
      prompt: 'You want each lead’s **latest** reply only. Which approach fits best?',
      options: [
        { text: 'row_number() per lead, newest first, in a CTE; keep n = 1', why: 'Yes. Number each lead’s replies newest-first, then filter in the outer query.' },
        { text: 'GROUP BY lead_id and select max(replied_at) with body', why: 'Postgres won’t let you select body without aggregating it, and max() doesn’t bring its row along.' },
        { text: 'WHERE row_number() OVER (...) = 1 in the same query', why: 'WHERE runs before window functions, so this errors.' },
        { text: 'ORDER BY replied_at DESC with LIMIT 1 per lead_id', why: 'LIMIT applies to the whole result, not per group. You’d get one reply in total.' },
      ],
      answer: 0,
      explain: 'The “latest per group” pattern: window function in a CTE, filter outside.',
    },
    {
      id: 'm3-q5', kind: 'choice',
      prompt: 'Predict the result. `leads` has 3 rows with source `web` and 1 with source `ads`.',
      code: "SELECT source, count(*) AS n\nFROM leads\nGROUP BY source\nHAVING count(*) > 1;",
      options: [
        { text: 'One row: web | 3', why: 'Right. HAVING drops the ads group, which has only 1 lead.' },
        { text: 'Two rows: web | 3 and ads | 1', why: 'HAVING filters out groups with a count of 1 or less.' },
        { text: 'Four rows, one per lead', why: 'GROUP BY collapses rows into one per source.' },
        { text: 'An error, because HAVING needs WHERE', why: 'HAVING works without WHERE.' },
      ],
      answer: 0,
      explain: 'GROUP BY makes groups; HAVING keeps only the groups that pass.',
    },
    {
      id: 'm3-q6', kind: 'choice',
      prompt: 'An n8n workflow writes a deal row, then its line items, as two separate Postgres steps. Sometimes deals appear with no line items. What should you change?',
      options: [
        { text: 'Run both inserts in one transaction so they commit together', why: 'Yes. They commit together or not at all, so a crash can’t leave half a deal.' },
        { text: 'Turn on Retry On Fail for the line-items step', why: 'Retries don’t help if the whole process died between the steps.' },
        { text: 'Add a foreign key from line items to the deal', why: 'That stops line items without a deal, not a deal without line items.' },
        { text: 'Use ON CONFLICT DO NOTHING on the deal insert', why: 'That handles repeats of the same deal, not a crash between two writes.' },
      ],
      answer: 0,
      explain: 'Related writes belong in one atomic transaction.',
    },
    {
      id: 'm3-q7', kind: 'choice',
      prompt: 'Why is `INSERT ... ON CONFLICT (email) DO UPDATE` safer than “SELECT to check, then INSERT”?',
      options: [
        { text: 'The insert-or-update is atomic, so two runs can’t both insert', why: 'Right. Check-then-insert leaves a gap where both runs see “not found”.' },
        { text: 'It takes a table lock, so other runs queue behind it', why: 'It doesn’t lock the table. It relies on the unique index to detect the conflict.' },
        { text: 'It runs at Serializable isolation instead of Read Committed', why: 'It runs at whatever isolation level you’re using; the unique constraint does the work.' },
        { text: 'It’s one round trip, so the gap is too small to hit', why: 'A smaller gap still races under load. Atomicity, not speed, is what closes it.' },
      ],
      answer: 0,
      explain: 'Upserts close the race that check-then-create leaves open.',
    },
    {
      id: 'm3-q8', kind: 'choice',
      prompt: 'Read the plan for a query on a 40-row `settings` table, which has an index on `key`. What do you conclude?',
      code: 'Seq Scan on settings  (actual time=0.01..0.02 rows=1 loops=1)\n  Filter: (key = \'timezone\')\n  Rows Removed by Filter: 39\nExecution Time: 0.03 ms',
      options: [
        { text: 'Nothing: on 40 rows a Seq Scan is cheaper than the index', why: 'Yes. 0.03 ms is fine, and Postgres chose the cheaper plan.' },
        { text: 'The index is corrupt; run REINDEX and check again', why: 'Nothing suggests corruption. Postgres simply chose not to use the index for so few rows.' },
        { text: 'Planner statistics are stale; run ANALYZE settings', why: 'Even with fresh statistics, scanning one or two pages beats using an index here.' },
        { text: 'Force the index with SET enable_seqscan = off', why: 'That’s a debugging switch, not a fix, and the query is already fast.' },
      ],
      answer: 0,
      explain: 'Read the timings, not just the node type. Seq Scan is only a problem on big tables.',
    },
    {
      id: 'm3-q9', kind: 'choice',
      prompt: 'You’re testing `EXPLAIN ANALYZE DELETE FROM events WHERE status = \'done\';` on production. What’s the danger?',
      options: [
        { text: 'It really runs the DELETE, so those rows are gone', why: 'Right. Wrap it in BEGIN ... ROLLBACK if you must test a write.' },
        { text: 'None: EXPLAIN only estimates and never changes data', why: 'Plain EXPLAIN doesn’t. EXPLAIN ANALYZE executes the statement.' },
        { text: 'It runs the DELETE but rolls it back automatically', why: 'There’s no automatic rollback. Outside BEGIN, the delete commits straight away.' },
        { text: 'It recomputes statistics for every table, slowing prod', why: 'That’s the separate ANALYZE command. Here ANALYZE means “run it and time it”.' },
      ],
      answer: 0,
      explain: 'ANALYZE = really run it and measure.',
    },
    {
      id: 'm3-q10', kind: 'choice',
      prompt: 'Your query joins `replies` to `leads` on `replies.lead_id`, which is a foreign key. It’s slow on a big table. What might be missing?',
      options: [
        { text: 'An index on replies.lead_id; foreign keys don’t get one automatically', why: 'Yes. Primary keys and UNIQUE get indexes automatically; foreign keys don’t.' },
        { text: 'A composite (lead_id, replied_at) index; joins can’t use single-column ones', why: 'A single-column index on lead_id serves a join on lead_id perfectly well. The problem is that there’s no index at all.' },
        { text: 'VACUUM ANALYZE, since the planner’s stats on the foreign key are stale', why: 'Fresh statistics can’t make Postgres use an index that doesn’t exist.' },
        { text: 'An index on leads.id, because the join looks up each lead there', why: 'leads.id is the primary key, so it’s already indexed. The missing one is on replies.' },
      ],
      answer: 0,
      explain: 'Index the columns you join on, and confirm with EXPLAIN ANALYZE.',
    },
    {
      id: 'm3-q11', kind: 'choice',
      prompt: 'Every query in your app filters on `payload->>\'tenant\'` and `payload->>\'status\'`, and someone stored “Done ” with a trailing space. What’s the design fix?',
      options: [
        { text: 'Give tenant and status real columns plus a CHECK; keep the raw JSON', why: 'Yes. Fields you filter and enforce rules on deserve real columns, and you still keep the original payload.' },
        { text: 'Add a GIN index on payload so the filters are fast and consistent', why: 'An index speeds up lookups but doesn’t validate values. “Done ” would still get in.' },
        { text: 'Validate in n8n before inserting, and keep everything in JSONB', why: 'That only covers one workflow. Other writers, scripts and manual imports still bypass it.' },
        { text: 'Use payload->\'status\' instead of ->> so it’s compared as JSON', why: '-> returns JSON instead of text; neither operator stops a bad value being stored.' },
      ],
      answer: 0,
      explain: 'JSONB for the raw payload; real columns and constraints for the fields you depend on.',
    },
    {
      id: 'm3-q12', kind: 'order',
      prompt: 'Order the steps for adding a `phone` column to `leads` safely.',
      items: ['Write a numbered migration file and commit it to Git', 'Run it against dev and test the workflow', 'Run it against staging', 'Run it against production using that environment’s connection string'],
      explain: 'The same versioned migration runs everywhere, in order. No hand edits in production.',
    },
  ],
  tasks: [
    { device: 'phone', plain: 'Learn tables, data types, primary and foreign keys, and the NOT NULL, UNIQUE and CHECK constraints.', done: 'You can explain what each constraint prevents, and you’ve passed the checks for Lessons 1 and 2.' },
    { device: 'phone', plain: 'Learn to read and write SELECT queries with WHERE, ORDER BY, JOINs, GROUP BY/HAVING, subqueries and CTEs.', done: 'You’ve passed the Lesson 3 and 4 checks and can write “leads who never replied” from memory.' },
    { device: 'phone', plain: 'Learn enough window functions to answer ranking, running-total and “first or latest per lead” questions.', done: 'You can write a row_number() query that keeps each lead’s latest reply, and explain PARTITION BY.' },
    { device: 'phone', plain: 'Learn transactions (BEGIN, COMMIT, ROLLBACK) and why a half-finished write is dangerous.', done: 'You can explain what happens on a crash before COMMIT, and why an API call inside a transaction isn’t undone.' },
    { device: 'computer', plain: 'Replace a “search, then create” step with a real INSERT ... ON CONFLICT upsert.', done: 'Running the same insert twice, or at the same time, leaves exactly one row.' },
    { device: 'phone', plain: 'Learn what indexes speed up, what they cost, and how to read EXPLAIN and EXPLAIN ANALYZE output.', done: 'You can read a plan and say whether it needs an index, and you’ve passed the Lesson 6 check.' },
    { device: 'phone', plain: 'Learn when JSONB helps (raw payloads) and when it turns into a dumping ground.', done: 'You can name which fields of a webhook you’d keep as real columns, and why.' },
    { device: 'computer', plain: 'Create tables for events, executions, external record IDs, an audit log and retry state.', done: 'A SQL file that creates them in Postgres, with keys, constraints and at least three useful indexes.' },
    { device: 'computer', plain: 'Write the query “leads who replied but never booked”, then check it with EXPLAIN ANALYZE and add an index if needed.', done: 'The query, plus before-and-after plans showing whether the index helped.' },
    { device: 'phone', plain: 'Learn connection strings, connection pooling, migrations and separate database URLs per environment.', done: 'You can explain what a connection pool solves and how a migration reaches production.' },
    { device: 'computer', plain: 'Simulate a crash halfway through a two-table write, once without a transaction and once with one.', done: 'Screenshots showing half-written data without the transaction, and clean data with it.' },
    { device: 'phone', plain: 'Practise sketching the tables for an automation that receives webhooks and must be safe to replay.', done: 'A recorded 3-minute explanation covering the event key, raw payload, retry state and external ID mapping.' },
  ],
};
