import type { Lesson } from './types';

export const m4: Lesson = {
  intro: "You already build n8n workflows that work. This module covers the gap between “it works when I test it” and “I’d trust it with a client’s leads while I sleep”: knowing exactly how data moves, failing loudly, retrying only when it helps, never creating duplicates, recovering lost events, keeping secrets safe and running n8n on more than one machine. It leans on the Postgres skills from Module 4 for the things n8n shouldn’t have to remember on its own.",
  glossary: {
    'item': 'One record travelling through an n8n workflow, e.g. one lead. Each node receives and outputs a list of items.',
    'expression': 'A bit of code inside {{ }} in an n8n field that reads data from items, e.g. {{ $json.email }}.',
    'execution': 'One run of a workflow, from its trigger to the end. n8n can save each one so you can inspect it.',
    'binary data': 'Files (PDFs, images, spreadsheets) carried by an n8n item separately from its JSON fields.',
    'sub-workflow': 'A workflow called by another workflow, like a reusable function: data in, result out.',
    'runbook': 'Short written steps for what to do when something breaks, so anyone on call can follow them.',
    'error workflow': 'A workflow starting with the Error Trigger node that n8n runs automatically when another workflow fails.',
    'replay': 'Running a stored event through processing again, on purpose, after fixing whatever made it fail.',
    'encryption key': 'The secret n8n uses to encrypt saved credentials (N8N_ENCRYPTION_KEY). Without it, they can’t be read.',
    'execution retention': 'How long n8n keeps saved execution data before deleting it.',
    'queue mode': 'An n8n setup where a main instance puts executions on a Redis queue and separate worker processes run them.',
    'redis': 'A very fast in-memory data store. n8n’s queue mode uses it to hold the queue of executions.',
  },
  sections: [
    {
      title: 'How data really moves through n8n',
      minutes: 6,
      body: [
        "Most n8n bugs come from one misunderstanding: what a node actually receives. So start there.",
        "**Every node outputs a list of [[item|items]].** An item is one record: one lead, one row, one email. Each item has a `json` part (its fields) and can have a `binary` part ([[binary data]], a file such as a PDF). If a Google Sheets node returns 50 rows, the next node receives 50 items.",
        "**Most nodes run once per item.** A Gmail node after those 50 items sends 50 emails. Usually that’s what you want. It’s also the classic surprise: you add a Slack “summary” node and get 50 Slack messages. Fixes: an **Aggregate** node to combine items into one first, or the node setting **Execute Once**.",
        "**[[Expression|Expressions]]** read item data inside a field. `{{ $json.email }}` means “the email field of the item this node is processing right now”. To reach back to an earlier node, name it: `{{ $('Webhook').item.json.body.email }}`. n8n tracks which output item came from which input item, so `.item` finds the matching one.",
        "**An [[execution]]** is one run of a workflow, started by its trigger. n8n can save each execution, so you can open it and see what every node received and output. That’s your first debugging tool, but not a permanent record (Lesson 4 explains why).",
        "**Production points.**",
        "- Files take far more memory than JSON. Don’t pull hundreds of PDFs into one execution; process them in batches.\n- In a Code node, pick the mode on purpose. “Run Once for All Items” sees the whole list with `$input.all()`; “Run Once for Each Item” sees one item with `$json`.\n- Name nodes for what they do (`Find CRM contact`, not `HTTP Request3`). Error alerts and execution logs show node names.",
      ],
      example: {
        caption: 'What a Webhook node outputs, and two ways to read it',
        code: "// Webhook output: a list containing ONE item\n[\n  {\n    \"json\": {\n      \"headers\": { \"content-type\": \"application/json\" },\n      \"body\": { \"email\": \"ana@example.com\", \"source\": \"webform\" }\n    }\n  }\n]\n\n// In the node straight after the Webhook:\n{{ $json.body.email }}                  // → ana@example.com\n\n// Several nodes later, after a Set node changed the fields:\n{{ $('Webhook').item.json.body.email }} // → ana@example.com",
      },
      interview: "n8n passes arrays of items between nodes, each with JSON and optional binary data, and most nodes execute once per item. I use paired-item references like $('Node').item to reach upstream data, aggregate deliberately when I need a single action, and keep binary payloads small or batched because they’re memory-heavy.",
      check: [
        {
          id: 'm4-s0-1', kind: 'choice',
          prompt: 'A Postgres node returns 30 new leads. The next node posts “New leads today!” to Slack. The channel gets 30 messages. Best fix?',
          options: [
            { text: 'Add an Aggregate node before Slack (or turn on Execute Once), then post one summary', why: 'Yes. Slack ran once per item; combine them first, or tell it to run once.' },
            { text: 'Add a Wait node before Slack', why: 'It would still post 30 messages, just later.' },
            { text: 'Limit the Postgres query to 1 row', why: 'Then your summary would only know about one lead.' },
            { text: 'Mute the Slack channel', why: 'That hides the bug instead of fixing it.' },
          ],
          answer: 0,
          explain: 'Most nodes run once per item. Decide on purpose when you want one action instead.',
        },
        {
          id: 'm4-s0-2', kind: 'choice',
          prompt: 'After a Set node that keeps only `name`, your expression `{{ $json.body.email }}` comes out empty. Why?',
          options: [
            { text: '`$json` is the current item, which no longer has body; use `$(\'Webhook\').item.json.body.email`', why: 'Right. $json only sees what the previous node output.' },
            { text: 'Expressions can’t read emails', why: 'They can read any field that exists on the item.' },
            { text: 'The webhook didn’t send an email', why: 'It may well have; the Set node removed it from the current item.' },
            { text: 'You need a Code node to read it', why: 'A node reference in an expression is enough.' },
          ],
          answer: 0,
          explain: '$json = this item now. $(\'Node name\').item = the matching item from that earlier node.',
        },
      ],
    },
    {
      title: 'Workflows someone else can run: documentation and sub-workflows',
      minutes: 6,
      body: [
        "**The problem.** You’re on holiday. The client’s lead workflow fails, and a colleague opens a 60-node canvas called “My workflow 7”. They can’t tell what it does, which accounts it uses or whether re-running it will email everyone twice.",
        "**Give every workflow the same header.** A sticky note at the start of the canvas (and the same text in the workflow description) answering:",
        "- **Purpose**: the business outcome.\n- **Owner**: who gets called when it breaks.\n- **Inputs and outputs**: what triggers it, and what it writes where.\n- **Credentials**: which accounts it uses.\n- **Failure modes**: what can go wrong, and what happens then.\n- **[[Runbook]]**: how to recover, including whether a re-run is safe.",
        "**Split giant workflows into [[sub-workflow|sub-workflows]].** A sub-workflow is a normal workflow that starts with the trigger **When Executed by Another Workflow** (called Execute Workflow Trigger in older versions). A parent calls it with the **Execute Workflow** node (Execute Sub-workflow in newer versions). Think of it as a function: data goes in, a result comes out.",
        "Good candidates: “upsert contact in CRM”, “send alert”, “enrich lead”. Build each once, test it on its own, reuse it everywhere. A bug fix then lands in one place.",
        "**Give each one a contract.** List the input fields it expects (the trigger lets you define them) and say what it returns. Validate inputs at the top, so bad data fails there with a clear message instead of three nodes later. Use one consistent envelope for events everywhere, e.g. `event_id`, `tenant_id`, `type`, `payload`, `correlation_id`.",
        "**Production point.** By default the parent waits for the sub-workflow and receives its output. You can switch waiting off for fire-and-forget work, but then the parent can’t know whether it succeeded.",
      ],
      example: {
        caption: 'The sticky note at the top of a production workflow',
        code: "PURPOSE   Website leads → one deduped HubSpot contact + Slack alert\nOWNER     Sam (backup: ops@agency.com)\nTRIGGER   Webhook POST /lead from the website form\nWRITES    Postgres events table, HubSpot contacts, Slack #sales\nCREDS     HubSpot private app, Postgres n8n_app, Slack bot\nFAILS     HubSpot 429/5xx → retried later; bad email → failed + alert\nRUNBOOK   Safe to replay: the contact step is an upsert by email.\n          Run 'Replay failed events' with the event_id.",
      },
      interview: "Every production workflow carries the same metadata: purpose, owner, inputs, outputs, credentials, failure modes and a runbook. I factor shared steps into sub-workflows with explicit input contracts and validation at the boundary, so they’re testable on their own and a fix lands once.",
      check: [
        {
          id: 'm4-s1-1', kind: 'choice',
          prompt: 'The same “create or update HubSpot contact” logic is copied into six workflows. HubSpot changes a field name. What would have made this a one-place fix?',
          options: [
            { text: 'A single sub-workflow for the contact step, called by all six', why: 'Yes. Shared logic in one place means one fix.' },
            { text: 'More sticky notes in each workflow', why: 'Good documentation, but you’d still edit six copies.' },
            { text: 'Duplicating the workflow again as a backup', why: 'That makes seven copies to fix.' },
            { text: 'Turning on Retry On Fail', why: 'Retrying a wrong field name fails every time.' },
          ],
          answer: 0,
          explain: 'Sub-workflows are n8n’s functions: write once, call many times.',
        },
        {
          id: 'm4-s1-2', kind: 'choice',
          prompt: 'A sub-workflow receives a lead with no email and fails three nodes later with “Cannot read properties of undefined”. What’s the better design?',
          options: [
            { text: 'Validate required inputs at the top and fail there with a clear message', why: 'Right. Fail early, at the boundary, with an error a human can act on.' },
            { text: 'Wrap every node in a try/catch Code node', why: 'That spreads the problem around instead of checking once at the door.' },
            { text: 'Set the email to an empty string', why: 'That hides bad data and passes the problem downstream.' },
            { text: 'Make the parent wait longer', why: 'Timing has nothing to do with a missing field.' },
          ],
          answer: 0,
          explain: 'A contract means stating what you need and checking it first.',
        },
      ],
    },
    {
      title: 'When it fails: error workflows, alerts and retries',
      minutes: 7,
      body: [
        "By default a failed production execution just sits in the executions list, marked red. Nobody looks until the client asks where their leads went.",
        "**Error workflows.** Build one workflow that starts with the **Error Trigger** node and sends an alert. Then in each production workflow open **Settings → Error workflow** and choose it. When an automatic execution fails, n8n runs your [[error workflow]] with the workflow name, the last node that ran, the error message and a link to the execution. Manual test runs don’t trigger it. One central error workflow can serve all your workflows.",
        "**An actionable alert** says which workflow, which node, what error, which event (its [[correlation id]]), a short *safe* summary of the data (no full payloads, tokens or personal details) and the execution link. “Workflow failed” on its own gets ignored.",
        "**Retries.** In a node’s **Settings**, turn on **Retry On Fail** and set **Max Tries** and **Wait Between Tries**. Good for blips: timeouts, 5xx errors, dropped connections. The wait is fixed, so for longer outages, or a 429 with a `Retry-After` header, mark the event for a later attempt with [[exponential backoff]] instead (Lesson 4 shows the table that makes this easy).",
        "**When not to retry.** Retry On Fail retries **every** error. But a 400 (bad data), 401 (bad credentials) or 404 fails the same way each time, so retrying only delays the alert. Make these **fail fast**: set the node’s **On Error** to “Continue (using error output)”, then route on the status code. Retryable errors go round again; the rest go straight to failed-and-alerted.",
        "**The failure no error workflow catches** is a workflow that never starts: trigger switched off, webhook URL changed, server down. Add a heartbeat check that alerts when an expected run *doesn’t* happen.",
      ],
      example: {
        caption: 'Slack message in the central error workflow (after the Error Trigger)',
        code: "Workflow failed: {{ $json.workflow.name }}\nNode:  {{ $json.execution.lastNodeExecuted }}\nError: {{ $json.execution.error.message }}\nLink:  {{ $json.execution.url }}\n\n// The Error Trigger doesn't know your event ID. To include it, have the\n// main workflow save event_id with {{ $execution.id }} in your events table,\n// then look it up here by {{ $json.execution.id }}.",
      },
      interview: "Every production workflow points at a central error workflow built on the Error Trigger, which posts the workflow, failing node, error, correlation ID and execution link to an owned channel. I use node-level retries only for transient failures, route 4xx errors to a fail-fast branch via the error output, and add heartbeat checks because a workflow that never runs raises no error.",
      check: [
        {
          id: 'm4-s2-1', kind: 'choice',
          prompt: 'An HTTP Request node has Retry On Fail (5 tries, 5 s wait). The API key has expired. What happens?',
          options: [
            { text: 'It retries a 401 five times, waiting each time, then fails anyway; the alert just arrives later', why: 'Right. Retry On Fail doesn’t know a 401 can’t fix itself.' },
            { text: 'n8n refreshes the API key automatically', why: 'n8n can’t create a new API key for you.' },
            { text: 'It skips retries because it’s a 401', why: 'Retry On Fail retries any error.' },
            { text: 'It succeeds on the fifth try', why: 'An expired key stays expired.' },
          ],
          answer: 0,
          explain: 'Retry the temporary (timeouts, 5xx); fail fast on the permanent (400, 401, 403, 404).',
        },
        {
          id: 'm4-s2-2', kind: 'choice',
          prompt: 'You set up an error workflow, then click “Test workflow” on a broken workflow. No alert arrives. Why?',
          options: [
            { text: 'Error workflows only run for automatic (production) executions, not manual test runs', why: 'Yes. Test it with a real trigger, e.g. by calling the production webhook URL.' },
            { text: 'The Error Trigger node is broken', why: 'Its behaviour is expected.' },
            { text: 'You need one error workflow per workflow', why: 'One central error workflow can serve all of them.' },
            { text: 'Slack blocks automated messages', why: 'The error workflow never ran, so Slack wasn’t involved.' },
          ],
          answer: 0,
          explain: 'Trigger a real failure to prove your alerting works.',
        },
        {
          id: 'm4-s2-3', kind: 'choice',
          prompt: 'Which alert is most useful at 3am?',
          options: [
            { text: '“Lead intake → Create HubSpot contact: 429 rate limited. Event evt_88. Link: …”', why: 'Yes. Workflow, node, error, event and a link: you can act immediately.' },
            { text: '“Workflow failed.”', why: 'You don’t know which one, where or why.' },
            { text: 'The full webhook payload with the customer’s details', why: 'Too much, and it leaks personal data into Slack.' },
            { text: 'A daily email listing all executions', why: 'Too late and too noisy.' },
          ],
          answer: 0,
          explain: 'Actionable = what, where, which record, and how to look closer, with nothing sensitive.',
        },
      ],
    },
    {
      title: 'Safe to run twice: idempotency, raw events and replay',
      minutes: 7,
      body: [
        "**The problem.** A HubSpot node creates a contact, then the next node times out and the execution fails. You retry. Now there are two contacts. **A failed execution may already have done things**: created records, sent emails. Never treat “it failed” as proof that nothing happened.",
        "So every create or update step must be [[idempotent]]: running it twice leaves the same result as running it once. Three tools:",
        "- **Stable keys.** Identify each piece of work by something that doesn’t change between attempts: the provider’s event ID, the email, an order number. A random ID made fresh on every run defeats the purpose.\n- **Upserts, not search-then-create.** Use the CRM’s create-or-update operation keyed on email, or `INSERT ... ON CONFLICT` in Postgres. Search-then-create races when two runs overlap.\n- **Record outcomes.** Before sending an email or creating a deal, check your table: already done for this event? After success, store the provider’s ID. A replay reads that instead of repeating the action.",
        "**Log the raw event first.** Straight after the Webhook, insert the untouched body into your `events` table (Module 4) with `ON CONFLICT DO NOTHING` on the event ID. Then respond, then process. If your transformation has a bug, the original data is safe.",
        "**Build a [[replay]] path.** A small workflow that takes an event ID, or all events with `status = 'failed'`, loads the stored payload and sends it to the same processing sub-workflow. Because each step is idempotent, replaying is safe.",
        "**Why not just n8n’s Retry button?** It’s handy for a one-off. But executions are deleted after the retention period (or never saved), and the failed node itself may have half-succeeded, like a create that timed out. **Your events table is the durable record**; n8n’s execution list isn’t.",
      ],
      example: {
        caption: 'Intake, processing and replay as three workflows',
        code: "'Lead intake'\n  Webhook (POST /lead)\n  → Postgres: INSERT INTO events ... ON CONFLICT DO NOTHING RETURNING event_id\n      (setting Always Output Data, so a duplicate still continues)\n  → Respond to Webhook: 200\n  → IF event_id is empty → stop      // duplicate delivery, already stored\n  → Execute Workflow: 'Process lead'\n\n'Process lead' (sub-workflow)\n  → Postgres: load the event; stop if status = 'done'\n  → HubSpot: Create or Update contact (matched by email)\n  → Postgres: UPDATE events SET status = 'done', crm_id = ...\n\n'Replay failed events' (manual or scheduled)\n  → Postgres: SELECT event_id FROM events WHERE status = 'failed'\n  → Execute Workflow: 'Process lead'   // the same sub-workflow",
      },
      interview: "I persist the raw inbound event before transformation, keyed on the provider’s event ID, then process it through idempotent steps: upserts on stable keys and recorded provider outcomes. Recovery is a replay workflow over stored events, not re-running executions and hoping, because a failed execution can still have produced side effects.",
      check: [
        {
          id: 'm4-s3-1', kind: 'choice',
          prompt: 'Your workflow uses “HubSpot: search contact by email → IF not found → create contact”. Two form submissions arrive within a second, and you get two contacts. Best fix?',
          options: [
            { text: 'Use a create-or-update operation keyed on email instead of search-then-create', why: 'Yes. One atomic step on a stable key can’t race.' },
            { text: 'Add Retry On Fail to the create node', why: 'Nothing failed; both creates succeeded.' },
            { text: 'Add a 2-second Wait before the search', why: 'Both runs would wait and then race anyway.' },
            { text: 'Delete duplicates manually each week', why: 'Duplicates still trigger double emails in the meantime.' },
          ],
          answer: 0,
          explain: 'Search-then-create is a race. Upsert on a stable key.',
        },
        {
          id: 'm4-s3-2', kind: 'choice',
          prompt: 'A transformation bug corrupted 200 leads last week. Your executions from then have been pruned. What lets you recover?',
          options: [
            { text: 'The raw events you logged before transformation, replayed through the fixed workflow', why: 'Right. The original data is untouched, and idempotent steps make replay safe.' },
            { text: 'n8n’s Retry button on those executions', why: 'They’ve been pruned; there’s nothing to retry.' },
            { text: 'Asking the provider to resend everything', why: 'Many providers can’t or won’t resend old webhooks.' },
            { text: 'Fixing the 200 leads by hand in the CRM', why: 'Slow, error-prone, and you may not know the original values.' },
          ],
          answer: 0,
          explain: 'Store raw first, then transform. Your own log outlives n8n’s execution history.',
        },
      ],
    },
    {
      title: 'Big jobs: batching and rate limits',
      minutes: 6,
      body: [
        "**The problem.** A client uploads 5,000 contacts to enrich. Your workflow fires 5,000 API calls as fast as it can. After 100, the provider replies `429 Too Many Requests` and the rest fail. Or the execution runs out of memory holding everything at once.",
        "Every API has a [[rate limit]], e.g. 100 requests per 10 seconds. It’s in the provider’s docs; read it before you build. Limits are often per API key, so every workflow using that key shares the same allowance.",
        "**Batching in n8n:**",
        "- **Loop Over Items** (formerly Split In Batches) hands on a list in batches of, say, 50. Put the API call and a **Wait** node inside the loop, so each batch is followed by a pause.\n- The **HTTP Request** node has a **Batching** option (Items per Batch, Batch Interval) that spaces out its own requests without a loop.\n- Fetch big lists page by page ([[pagination]]) instead of all at once.",
        "**Do the maths.** Limit 100 per 10 seconds: batches of 50 with a 6-second wait send at most 50 every 6 seconds, comfortably under it, with room left for other workflows on the same key.",
        "**When you still get a 429, back off.** If the response has a `Retry-After` header, wait that long. Otherwise wait longer each time ([[exponential backoff]]) with a little random [[jitter]], so parallel runs don’t all retry at the same instant.",
        "**Production point.** Don’t hold 5,000 items in one execution. Write them to a table as `pending`, then let a scheduled workflow take the next 200 each run and mark each row `done`. If it crashes, it resumes where it stopped instead of starting over. And **more workers don’t raise the provider’s limit**; they just reach it faster.",
      ],
      example: {
        caption: 'A scheduled enrichment job that respects a rate limit',
        code: "Schedule Trigger (every 5 minutes)\n  → Postgres: SELECT * FROM enrich_jobs\n              WHERE status = 'pending' ORDER BY id LIMIT 200\n  → Loop Over Items (batch size 50)\n      → HTTP Request: enrich contact\n      → Postgres: UPDATE enrich_jobs SET status = 'done' WHERE id = ...\n      → Wait: 6 seconds\n      → back to Loop Over Items\n  → done branch: finished (the next run picks up the next 200)",
      },
      interview: "I size batches from the provider’s documented limit, leaving headroom for other consumers of the same key, using Loop Over Items with Wait or the HTTP node’s batching. On 429 I honour Retry-After, otherwise back off exponentially with jitter. Large jobs are persisted as pending rows and processed in checkpointed chunks, since adding workers doesn’t raise an external rate limit.",
      check: [
        {
          id: 'm4-s4-1', kind: 'choice',
          prompt: 'The API allows 60 requests per minute. Which setup stays safely under it?',
          options: [
            { text: 'Batches of 20, with a 30-second wait after each (about 40 a minute)', why: 'Yes. Under the limit, with headroom for other workflows.' },
            { text: 'Batches of 60, with no wait', why: 'That hits the limit immediately and then exceeds it.' },
            { text: 'Batches of 100, with a 1-minute wait', why: '100 at once is already over 60.' },
            { text: 'Batches of 30, with a 10-second wait (about 180 a minute)', why: 'Three times the limit.' },
          ],
          answer: 0,
          explain: 'Requests per batch ÷ time per batch must stay under the limit, ideally with room to spare.',
        },
        {
          id: 'm4-s4-2', kind: 'choice',
          prompt: 'Enrichment keeps hitting 429 errors, so a teammate adds two more n8n workers. What happens?',
          options: [
            { text: 'More 429s: the provider’s limit hasn’t changed, and now more requests arrive at once', why: 'Right. Workers add capacity on your side, not theirs.' },
            { text: 'The 429s stop, because the work is spread out', why: 'The provider counts requests per key, however many workers send them.' },
            { text: 'The provider raises your limit automatically', why: 'Limits come from your plan, not your traffic.' },
            { text: 'Nothing changes', why: 'More parallel sending usually makes rate limiting worse.' },
          ],
          answer: 0,
          explain: 'Rate limits are solved by pacing and backoff, not by scaling up.',
        },
      ],
    },
    {
      title: 'Secrets, settings and backups',
      minutes: 6,
      body: [
        "**Credentials** are the saved logins n8n uses: API keys, OAuth tokens, database passwords. n8n stores them in its database **encrypted** with an [[encryption key]]. If you don’t set one, n8n generates one and saves it in its data folder (`.n8n`). In production, set it yourself with `N8N_ENCRYPTION_KEY` and keep a copy somewhere safe, such as a password manager. Lose it and every saved credential is unreadable.",
        "**Configure n8n with [[environment variable|environment variables]]**, not by clicking around: database connection, `WEBHOOK_URL`, timezone (`GENERIC_TIMEZONE`), execution settings. Dev, staging and production then differ only by their `.env` file.",
        "**[[Execution retention]].** Saved executions hold the full data of every node: emails, phone numbers, sometimes tokens in API responses. They also fill the database. Turn on pruning (`EXECUTIONS_DATA_PRUNE=true`, with `EXECUTIONS_DATA_MAX_AGE` in hours), and consider not saving successful runs at all (`EXECUTIONS_DATA_SAVE_ON_SUCCESS=none`).",
        "**Secret rotation** means replacing a key on a schedule or after a leak: create the new key at the provider, update the n8n credential, test, then revoke the old key. Give each credential the smallest [[scopes]] it needs, so a leak does less damage.",
        "**A full n8n backup has three parts:**",
        "1. The database (`pg_dump` for Postgres): workflows, credentials, executions.\n2. The encryption key.\n3. Your config: the compose file and `.env`, stored securely and never in Git.",
        "Also export workflows as JSON into Git (`n8n export:workflow --all --output=workflows.json`) for version history. **Prove the backup works:** restore all three into a fresh server and run a workflow that uses a credential.",
      ],
      example: {
        caption: 'A production .env for n8n (never committed to Git)',
        code: "N8N_ENCRYPTION_KEY=<long random string, also in your password manager>\nDB_TYPE=postgresdb\nDB_POSTGRESDB_HOST=postgres\nDB_POSTGRESDB_DATABASE=n8n\nDB_POSTGRESDB_USER=n8n\nDB_POSTGRESDB_PASSWORD=<secret>\nWEBHOOK_URL=https://n8n.client.com/\nGENERIC_TIMEZONE=Australia/Sydney\nEXECUTIONS_DATA_PRUNE=true\nEXECUTIONS_DATA_MAX_AGE=168            # hours: keep 7 days\nEXECUTIONS_DATA_SAVE_ON_SUCCESS=none   # keep failures only",
      },
      interview: "Credentials are encrypted with N8N_ENCRYPTION_KEY, which I set explicitly and back up separately, because a database restore without it is useless. Configuration is environment-driven, execution data is pruned since it contains personal data, and secrets are least-privilege and rotated by creating, switching, testing and then revoking. I prove backups by restoring database, key and config into a clean environment.",
      check: [
        {
          id: 'm4-s5-1', kind: 'choice',
          prompt: 'You start a fresh n8n on a new server, pointed at a copy of the old database, without setting N8N_ENCRYPTION_KEY. Workflows load, but every credential fails. Why?',
          options: [
            { text: 'The new instance generated its own key, which can’t decrypt credentials encrypted with the old one', why: 'Right. Set the original key before starting it.' },
            { text: 'Credentials aren’t stored in the database', why: 'They are, encrypted.' },
            { text: 'Every API key expires when you move servers', why: 'The keys are fine; n8n just can’t decrypt them.' },
            { text: 'Postgres needs reindexing', why: 'This is a decryption problem, not a database one.' },
          ],
          answer: 0,
          explain: 'Database + encryption key + config. Miss one and the restore fails.',
        },
        {
          id: 'm4-s5-2', kind: 'order',
          prompt: 'An API key appeared in a screenshot you shared. Put the rotation steps in order.',
          items: ['Create a new key at the provider', 'Update the credential in n8n', 'Run a test execution that uses it', 'Revoke the old key'],
          explain: 'New first, revoke last, so nothing breaks in between.',
        },
        {
          id: 'm4-s5-3', kind: 'choice',
          prompt: 'A privacy review finds customer phone numbers in n8n executions from two years ago. What should you change?',
          options: [
            { text: 'Turn on execution pruning with a sensible max age, and stop saving successful runs if you don’t need them', why: 'Yes. Keep execution data only as long as it’s useful.' },
            { text: 'Delete the n8n database', why: 'That deletes your workflows and credentials too.' },
            { text: 'Rotate all API keys', why: 'Good hygiene, but it doesn’t remove stored personal data.' },
            { text: 'Make the workflows inactive', why: 'Old executions stay where they are.' },
          ],
          answer: 0,
          explain: 'Execution data is a liability as well as a debugging tool. Set retention on purpose.',
        },
      ],
    },
    {
      title: 'Scaling with queue mode, and when to use Python instead',
      minutes: 7,
      body: [
        "**The problem.** By default one n8n process does everything: serves the editor, receives webhooks and runs every execution. One heavy job slows everything else, and if that process dies, all running work stops with it.",
        "**[[Queue mode]]** splits the jobs up:",
        "- **Main instance**: the editor, triggers and webhooks. When a workflow should run, it puts the execution on a queue instead of running it.\n- **[[Redis]]**: holds that queue.\n- **Workers**: separate n8n processes started with `n8n worker`. They take executions off the queue and run them. More workers, more executions at once.\n- **Postgres**: the shared database. Workers load the workflow from it and save the results back. SQLite isn’t supported in queue mode.",
        "You turn it on with `EXECUTIONS_MODE=queue` plus the Redis connection settings (such as `QUEUE_BULL_REDIS_HOST`). **Every instance needs the same `N8N_ENCRYPTION_KEY`** and the same database, or workers can’t read credentials. Each worker runs several executions at once; set how many with `--concurrency`, e.g. `n8n worker --concurrency=5`.",
        "**What it doesn’t fix:** provider rate limits, non-idempotent steps and broken workflows. More workers make all three hit harder. So test the failures: kill a worker mid-execution, stop Redis, and check what your alerts and replay path do.",
        "**n8n or a Python service?** n8n is excellent at orchestration: triggers, routing, connecting APIs, alerts, and showing a non-developer what happens. Move work into a small Python service (Module 6) when the logic is complex, needs proper automated tests, is reused by several systems, or is heavy computation. The common answer is **both**: n8n runs the trigger and the flow, and calls your service over HTTP for the hard part.",
      ],
      example: {
        caption: 'compose.yaml sketch: main + 2 workers (volumes left out for brevity)',
        code: "# .env shared by main and workers:\n#   EXECUTIONS_MODE=queue\n#   QUEUE_BULL_REDIS_HOST=redis\n#   DB_TYPE=postgresdb   DB_POSTGRESDB_HOST=postgres  ...\n#   N8N_ENCRYPTION_KEY=<the same key everywhere>\n\nservices:\n  n8n-main:          # editor, triggers, webhooks → puts jobs on the queue\n    image: docker.n8n.io/n8nio/n8n\n    env_file: .env\n    ports: [\"5678:5678\"]\n  n8n-worker:        # takes jobs off the queue and runs them\n    image: docker.n8n.io/n8nio/n8n\n    command: worker --concurrency=5\n    env_file: .env\n    deploy:\n      replicas: 2    # two workers\n  redis:\n    image: redis:7\n  postgres:\n    image: postgres:16",
      },
      interview: "In queue mode the main instance handles the editor, triggers and webhooks and enqueues executions in Redis; workers pull and run them against the shared Postgres, all with the same encryption key. It adds throughput and isolation but doesn’t fix rate limits or non-idempotent steps. I keep n8n as the orchestrator and move complex, heavily tested or reused logic into a Python service it calls over HTTP.",
      check: [
        {
          id: 'm4-s6-1', kind: 'choice',
          prompt: 'In queue mode, a webhook arrives. Which component actually runs the workflow?',
          options: [
            { text: 'A worker, after the main instance puts the execution on the Redis queue', why: 'Right. Main receives and enqueues; workers execute.' },
            { text: 'Redis', why: 'Redis only holds the queue; it doesn’t run workflows.' },
            { text: 'Postgres', why: 'Postgres stores workflows and results; it doesn’t run them.' },
            { text: 'The main instance, always', why: 'In queue mode, execution is handed to workers.' },
          ],
          answer: 0,
          explain: 'Main = front desk. Redis = the queue. Workers = the people doing the work. Postgres = the filing cabinet.',
        },
        {
          id: 'm4-s6-2', kind: 'choice',
          prompt: 'A lead-scoring workflow has grown to 40 IF and Code nodes. The client wants every rule tested before each change. What’s a sensible move?',
          options: [
            { text: 'Move the scoring logic into a tested Python service, and call it from n8n over HTTP', why: 'Yes. n8n keeps orchestrating; the complex, test-heavy logic lives in code.' },
            { text: 'Add more sticky notes', why: 'Documentation doesn’t give you automated tests.' },
            { text: 'Switch to queue mode', why: 'Queue mode adds capacity, not testability.' },
            { text: 'Rebuild everything in Python, including triggers and alerts', why: 'Possible, but you lose what n8n is good at for no gain.' },
          ],
          answer: 0,
          explain: 'n8n for the flow, code for complex logic that needs tests. Often both.',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'm4-q1', kind: 'choice',
      prompt: 'A Google Sheets node returns 25 rows. The next node is an HTTP Request that posts each lead to a CRM. How many requests are sent?',
      options: [
        { text: '25, one per item', why: 'Yes. Most nodes run once for each incoming item.' },
        { text: '1, containing all 25', why: 'Only if you aggregate first or use Execute Once.' },
        { text: '0, until you add a Loop node', why: 'n8n loops over items automatically.' },
        { text: '50, because of request and response', why: 'One request per item.' },
      ],
      answer: 0,
      explain: 'Items in = runs of the node. Plan for that, especially before emails or paid APIs.',
    },
    {
      id: 'm4-q2', kind: 'order',
      prompt: 'Order the steps to set up central error alerts.',
      items: ['Create a workflow starting with the Error Trigger node', 'Add a Slack or email node with workflow, node, error and link', 'In each production workflow, choose it under Settings → Error workflow', 'Cause a real failure through the production trigger and check the alert'],
      explain: 'Build it, connect it, then prove it with a real (not manual) failure.',
    },
    {
      id: 'm4-q3', kind: 'choice',
      prompt: 'Which error should an HTTP node **retry**?',
      options: [
        { text: '503 Service Unavailable', why: 'Yes. A temporary server-side problem; a retry may well succeed.' },
        { text: '400 Bad Request', why: 'The data is wrong; it will fail the same way every time.' },
        { text: '401 Unauthorized', why: 'Credentials need fixing; retrying just delays the alert.' },
        { text: '404 Not Found', why: 'The thing doesn’t exist; retrying won’t create it.' },
      ],
      answer: 0,
      explain: 'Retry timeouts, 5xx and 429 (with backoff). Fail fast on other 4xx.',
    },
    {
      id: 'm4-q4', kind: 'choice',
      prompt: 'An execution failed at “Send welcome email”, after “Create contact” succeeded. You replay the event. What keeps this safe?',
      options: [
        { text: 'Create contact is an upsert on email, and the email step checks your table for “already sent”', why: 'Right. Idempotent steps make the replay harmless.' },
        { text: 'n8n remembers which nodes already ran in previous executions', why: 'A replay of a stored event starts fresh; your own records must hold that memory.' },
        { text: 'The CRM rejects duplicates automatically', why: 'Many CRMs happily create duplicates. Don’t rely on it.' },
        { text: 'Replaying at night when traffic is low', why: 'Timing doesn’t prevent duplicates.' },
      ],
      answer: 0,
      explain: 'Stable keys + upserts + recorded outcomes = safe to run twice.',
    },
    {
      id: 'm4-q5', kind: 'choice',
      prompt: 'The provider sends the same webhook twice, two seconds apart. Your intake inserts it with `ON CONFLICT (tenant_id, event_id) DO NOTHING`. What happens to the second one?',
      options: [
        { text: 'The insert is skipped, no row is returned, and the workflow stops before processing', why: 'Yes. The stored event key absorbs the duplicate.' },
        { text: 'It’s processed again, creating a second contact', why: 'Not if processing only continues when a new row was inserted.' },
        { text: 'The workflow crashes with a constraint error', why: 'DO NOTHING turns the conflict into a quiet skip.' },
        { text: 'The first event is overwritten', why: 'DO NOTHING keeps the first row as it is.' },
      ],
      answer: 0,
      explain: 'Deduplicate at intake on the provider’s event ID.',
    },
    {
      id: 'm4-q6', kind: 'choice',
      prompt: 'Why log the raw webhook body **before** transforming it?',
      options: [
        { text: 'If the transformation has a bug, you still have the original to fix and replay', why: 'Right. Transformed data can’t be un-transformed.' },
        { text: 'It makes the workflow faster', why: 'It adds a step; the value is recovery.' },
        { text: 'n8n requires it', why: 'n8n doesn’t; it’s a design choice.' },
        { text: 'It replaces the need for error alerts', why: 'You still need to know when something fails.' },
      ],
      answer: 0,
      explain: 'Store raw, then transform. That’s what makes replay possible.',
    },
    {
      id: 'm4-q7', kind: 'choice',
      prompt: 'Read the log. What’s the right fix?',
      code: '10:00:01 enrich batch 1: 100 requests → 100 OK\n10:00:02 enrich batch 2: 100 requests → 37 OK, 63 × 429\n          Retry-After: 30',
      options: [
        { text: 'Smaller batches with a Wait between them, and honour Retry-After when a 429 arrives', why: 'Yes. Pace under the limit, and wait as long as the provider asks.' },
        { text: 'Retry the 63 immediately', why: 'They’ll get 429 again; the provider asked for 30 seconds.' },
        { text: 'Add more workers', why: 'More parallel requests make rate limiting worse.' },
        { text: 'Ignore the 63 failures', why: 'Those are lost leads.' },
      ],
      answer: 0,
      explain: 'Rate limits need pacing and backoff, not force.',
    },
    {
      id: 'm4-q8', kind: 'choice',
      prompt: 'A client asks: “Why can’t we just use n8n’s execution history as our record of every lead?”',
      options: [
        { text: 'Executions get pruned (or may not be saved), so they aren’t a durable record; a database table is', why: 'Right. Execution data is for debugging, with a retention limit.' },
        { text: 'Execution history is encrypted and unreadable', why: 'You can open executions in the editor.' },
        { text: 'n8n only saves the first 10 executions', why: 'There’s no such fixed limit; retention is configured.' },
        { text: 'You can — it keeps everything forever', why: 'Not if pruning is on, which it should be for privacy and storage.' },
      ],
      answer: 0,
      explain: 'n8n executions = debugging. Your events table = system of record.',
    },
    {
      id: 'm4-q9', kind: 'choice',
      prompt: 'You restore an n8n backup to a new server. What must the backup include for credentials to work?',
      options: [
        { text: 'The database and the original N8N_ENCRYPTION_KEY', why: 'Yes. Credentials are encrypted in the database with that key.' },
        { text: 'Only the workflow JSON exports', why: 'Workflow exports don’t contain the credentials themselves.' },
        { text: 'Only the database', why: 'Without the key, the credentials in it can’t be decrypted.' },
        { text: 'Screenshots of each credential screen', why: 'n8n hides secret values on those screens, and you can’t restore from images.' },
      ],
      answer: 0,
      explain: 'Back up data, key and config together, and test the restore.',
    },
    {
      id: 'm4-q10', kind: 'choice',
      prompt: 'After switching to queue mode, workers log “credentials could not be decrypted” while the main instance works fine. Most likely cause?',
      options: [
        { text: 'The workers have a different N8N_ENCRYPTION_KEY from the main instance', why: 'Right. Every instance must share the same key.' },
        { text: 'Redis is full', why: 'A Redis problem would stop jobs being queued, not credential decryption.' },
        { text: 'Workers can’t use credentials', why: 'They can, as long as they share the key and database.' },
        { text: 'The workers need their own database', why: 'All instances share one Postgres database.' },
      ],
      answer: 0,
      explain: 'Same database, same Redis, same encryption key on main and every worker.',
    },
    {
      id: 'm4-q11', kind: 'choice',
      prompt: 'One record in a batch of 500 has a malformed email, and the whole run stops. What’s the production-grade behaviour?',
      options: [
        { text: 'Route that record to a failed state with an alert, and let the other 499 continue', why: 'Yes. One bad record shouldn’t block the rest, and it stays visible for fixing and replay.' },
        { text: 'Retry the whole batch until it works', why: 'The bad email will fail every time.' },
        { text: 'Silently skip the bad record', why: 'Then a lead disappears without anyone knowing.' },
        { text: 'Stop the workflow permanently', why: 'Good records shouldn’t wait for one bad one.' },
      ],
      answer: 0,
      explain: 'Isolate bad records: fail them visibly, keep the rest moving.',
    },
    {
      id: 'm4-q12', kind: 'choice',
      prompt: 'An interviewer asks when you’d use n8n versus a Python service. Which answer is strongest?',
      options: [
        { text: 'n8n for triggers, routing and integrations; Python for complex, heavily tested or reused logic; often both, with n8n calling the service', why: 'Yes. It shows you choose by what each tool is good at.' },
        { text: 'Always Python, because n8n isn’t real engineering', why: 'Dismissing a tool the team uses is a red flag, and it’s not true.' },
        { text: 'Always n8n, because you can build anything with Code nodes', why: 'Large logic in Code nodes is hard to test and review.' },
        { text: 'Whichever the client has heard of', why: 'That’s not a technical reason.' },
      ],
      answer: 0,
      explain: 'Orchestration in n8n, hard logic in code, clear contracts between them.',
    },
  ],
  tasks: [
    { device: 'phone', plain: 'Learn how n8n moves data: items, expressions, binary data, executions and sub-workflows.', done: 'You can predict how many times a node runs for a given input, and you’ve passed the Lesson 1 and 2 checks.' },
    { device: 'computer', plain: 'Add the standard header to every production workflow: purpose, owner, inputs, outputs, credentials, failure modes and runbook.', done: 'Each workflow has a sticky note and description following the same template.' },
    { device: 'computer', plain: 'Build one central error workflow that sends an alert with workflow, node, event ID, a safe data summary and the error.', done: 'A real (non-manual) failure produces an alert you could act on without opening n8n first.' },
    { device: 'computer', plain: 'Add limited retries with growing waits for temporary HTTP errors, and make permanent errors fail straight away.', done: 'A test where a 503 is retried and then succeeds, and a 400 goes to the failed branch on the first attempt.' },
    { device: 'computer', plain: 'Make every create or update step safe to run twice, using stable keys and database constraints.', done: 'Running the same event through the workflow twice leaves one contact and one row.' },
    { device: 'computer', plain: 'Store every incoming webhook raw before processing, and build a workflow that replays failed events.', done: 'You break a step, fix it, replay the failed events and get correct results with no duplicates.' },
    { device: 'computer', plain: 'Process a large job in batches that stay under the provider’s rate limit.', done: 'A run of 1,000+ items finishes with no 429 errors, and you can show the maths behind your batch size and wait.' },
    { device: 'phone', plain: 'Learn how n8n stores credentials, the encryption key, environment variables, execution retention and secret rotation.', done: 'You can explain why a restore without the encryption key fails, and you’ve passed the Lesson 6 check.' },
    { device: 'computer', plain: 'Split one large workflow into reusable sub-workflows with defined inputs and outputs.', done: 'The parent calls at least two sub-workflows, each validating its inputs and tested on its own.' },
    { device: 'phone', plain: 'Learn queue mode: main instance, workers, Redis, Postgres, concurrency and scaling.', done: 'You can draw the four parts and explain what each does, and you’ve passed the Lesson 7 check.' },
    { device: 'computer', plain: 'Run n8n in queue mode locally or on a test VPS with at least two workers.', done: 'Executions show up on both workers, and the same workflow keeps working when one worker is stopped.' },
    { device: 'computer', plain: 'Back up the n8n database, encryption key and config, then restore them into a fresh environment.', done: 'Written restore steps, plus a workflow using a credential running successfully on the restored copy.' },
    { device: 'computer', plain: 'Break things on purpose: a duplicate event, a provider 500, Redis down, an expired credential and one malformed record.', done: 'A short table of each test, what happened, and how the workflow detected and recovered from it.' },
    { device: 'phone', plain: 'Practise explaining when you’d choose n8n, a Python service, or both.', done: 'A recorded 2-minute answer with one concrete example of each choice.' },
  ],
};
