import type { Lesson } from './types';

export const m4: Lesson = {
  intro: "You already build n8n workflows that work. This module covers the gap between “it works when I test it” and “I’d trust it with a client’s leads while I sleep”: knowing exactly how data moves, failing loudly, retrying only when it helps, never creating duplicates, recovering lost events, keeping secrets safe, running n8n on more than one machine, and translating it all to Make, Zapier and Power Automate. It leans on the Postgres skills from the SQL module for the things n8n shouldn’t have to remember on its own.",
  glossary: {
    'item': 'One record travelling through an n8n workflow, e.g. one lead. Each node receives and outputs a list of items.',
    'expression': 'A bit of code inside {{ }} in an n8n field that reads data from items, e.g. {{ $json.email }}.',
    'execution': 'One run of a workflow, from its trigger to the end. n8n can save each one so you can inspect it.',
    'binary data': 'Files (PDFs, images, spreadsheets) carried by an n8n item separately from its JSON fields.',
    'sub-workflow': 'A workflow called by another workflow, like a reusable function: data in, result out.',
    'runbook': 'Short written steps for what to do when something breaks, so anyone on call can follow them.',
    'error workflow': 'A workflow starting with the Error Trigger node that n8n runs automatically when another workflow fails.',
    'replay': 'Running a stored event through processing again, on purpose, after fixing whatever made it fail.',
    'encryption key': 'The secret n8n uses to encrypt saved credentials (N8N_ENCRYPTION_KEY). Without it, they can’t be read.',
    'execution retention': 'How long n8n keeps saved execution data before deleting it.',
    'queue mode': 'An n8n setup where a main instance puts executions on a Redis queue and separate worker processes run them.',
    'redis': 'A very fast in-memory data store. n8n’s queue mode uses it to hold the queue of executions.',
  },
  sections: [
    {
      title: 'How data really moves through n8n',
      minutes: 6,
      body: [
        "Most n8n bugs come from one misunderstanding: what a node actually receives. So start there.",
        "**Every node outputs a list of [[item|items]].** An item is one record: one lead, one row, one email. Each item has a `json` part (its fields) and can have a `binary` part ([[binary data]], a file such as a PDF). If a Google Sheets node returns 50 rows, the next node receives 50 items.",
        "**Most nodes run once per item.** A Gmail node after those 50 items sends 50 emails. Usually that’s what you want. It’s also the classic surprise: you add a Slack “summary” node and get 50 Slack messages. Fixes: an **Aggregate** node to combine items into one first, or the node setting **Execute Once**.",
        "**[[Expression|Expressions]]** read item data inside a field. `{{ $json.email }}` means “the email field of the item this node is processing right now”. To reach back to an earlier node, name it: `{{ $('Webhook').item.json.body.email }}`. n8n tracks which output item came from which input item, so `.item` finds the matching one.",
        "**An [[execution]]** is one run of a workflow, started by its trigger. n8n can save each execution, so you can open it and see what every node received and output. That’s your first debugging tool, but not a permanent record (Lesson 4 explains why).",
        "**Production points.**",
        "- Files take far more memory than JSON. Don’t pull hundreds of PDFs into one execution; process them in batches.\n- In a Code node, pick the mode on purpose. “Run Once for All Items” sees the whole list with `$input.all()`; “Run Once for Each Item” sees one item with `$json`.\n- Name nodes for what they do (`Find CRM contact`, not `HTTP Request3`). Error alerts and execution logs show node names.",
      ],
      example: {
        caption: 'What a Webhook node outputs, and two ways to read it',
        code: "// Webhook output: a list containing ONE item\n[\n  {\n    \"json\": {\n      \"headers\": { \"content-type\": \"application/json\" },\n      \"body\": { \"email\": \"ana@example.com\", \"source\": \"webform\" }\n    }\n  }\n]\n\n// In the node straight after the Webhook:\n{{ $json.body.email }}                  // → ana@example.com\n\n// Several nodes later, after a Set node changed the fields:\n{{ $('Webhook').item.json.body.email }} // → ana@example.com",
      },
      interview: "n8n passes arrays of items between nodes, each with JSON and optional binary data, and most nodes execute once per item. I use paired-item references like $('Node').item to reach upstream data, aggregate deliberately when I need a single action, and keep binary payloads small or batched because they’re memory-heavy.",
      check: [
        {
          id: 'm4-s0-1', kind: 'choice',
          prompt: 'A Postgres node returns 30 new leads. The next node posts “New leads today!” to Slack. The channel gets 30 messages. Best fix?',
          options: [
            { text: 'Add an Aggregate node before Slack, or turn on Execute Once', why: 'Yes. Slack ran once per item; combine the items first, or tell the node to run once.' },
            { text: 'Turn on Always Output Data on the Postgres node so it outputs one item', why: 'That setting only outputs an empty item when there are no results. 30 rows are still 30 items.' },
            { text: 'Put Slack inside Loop Over Items with a batch size of 30', why: 'The loop hands Slack a batch of 30 items, and Slack still runs once for each of them.' },
            { text: 'Set the Postgres node to return its rows as a single JSON array', why: 'The Postgres node outputs one item per row; there’s no setting that changes that. Aggregate does the combining.' },
          ],
          answer: 0,
          explain: 'Most nodes run once per item. Decide on purpose when you want one action instead.',
        },
        {
          id: 'm4-s0-2', kind: 'choice',
          prompt: 'After a Set node that keeps only `name`, your expression `{{ $json.body.email }}` comes out empty. Why?',
          options: [
            { text: "`$json` is now the Set output; use `$('Webhook').item.json.body.email`", why: 'Right. $json only sees what the previous node output, and Set removed body.' },
            { text: 'Use `$json.email` instead, because the Set node flattens body fields', why: 'Set doesn’t flatten anything here. It kept only name, so email is gone from the current item.' },
            { text: 'Use `$input.first().json.body.email` to read the original input', why: '$input is still the Set node’s output, which has no body. You need to name the Webhook node.' },
            { text: 'Webhook data expires after one node, so save it to a variable first', why: 'Nothing expires. Earlier node data stays reachable with $(\'Node name\') for the whole execution.' },
          ],
          answer: 0,
          explain: '$json = this item now. $(\'Node name\').item = the matching item from that earlier node.',
        },
      ],
    },
    {
      title: 'Workflows someone else can run: documentation and sub-workflows',
      minutes: 6,
      body: [
        "**The problem.** You’re on holiday. The client’s lead workflow fails, and a colleague opens a 60-node canvas called “My workflow 7”. They can’t tell what it does, which accounts it uses or whether re-running it will email everyone twice.",
        "**Give every workflow the same header.** A sticky note at the start of the canvas (and the same text in the workflow description) answering:",
        "- **Purpose**: the business outcome.\n- **Owner**: who gets called when it breaks.\n- **Inputs and outputs**: what triggers it, and what it writes where.\n- **Credentials**: which accounts it uses.\n- **Failure modes**: what can go wrong, and what happens then.\n- **[[Runbook]]**: how to recover, including whether a re-run is safe.",
        "**Split giant workflows into [[sub-workflow|sub-workflows]].** A sub-workflow is a normal workflow that starts with the trigger **When Executed by Another Workflow** (called Execute Workflow Trigger in older versions). A parent calls it with the **Execute Workflow** node (Execute Sub-workflow in newer versions). Think of it as a function: data goes in, a result comes out.",
        "Good candidates: “upsert contact in CRM”, “send alert”, “enrich lead”. Build each once, test it on its own, reuse it everywhere. A bug fix then lands in one place.",
        "**Give each one a contract.** List the input fields it expects (the trigger lets you define them) and say what it returns. Validate inputs at the top, so bad data fails there with a clear message instead of three nodes later. Use one consistent envelope for events everywhere, e.g. `event_id`, `tenant_id`, `type`, `payload`, `correlation_id`.",
        "**Production point.** By default the parent waits for the sub-workflow and receives its output. You can switch waiting off for fire-and-forget work, but then the parent can’t know whether it succeeded.",
        "**Portfolio point.** The same header turns a workflow into evidence of your skill. Some employers ask applicants to submit their most complex workflow JSON. Before you share one, remove credentials: exports leave out secret values but keep credential names and IDs, plus any key pasted straight into a node. Sticky notes then explain it without you in the room.",
      ],
      example: {
        caption: 'The sticky note at the top of a production workflow',
        code: "PURPOSE   Website leads → one deduped HubSpot contact + Slack alert\nOWNER     Sam (backup: ops@agency.com)\nTRIGGER   Webhook POST /lead from the website form\nWRITES    Postgres events table, HubSpot contacts, Slack #sales\nCREDS     HubSpot private app, Postgres n8n_app, Slack bot\nFAILS     HubSpot 429/5xx → retried later; bad email → failed + alert\nRUNBOOK   Safe to replay: the contact step is an upsert by email.\n          Run 'Replay failed events' with the event_id.",
      },
      interview: "Every production workflow carries the same metadata: purpose, owner, inputs, outputs, credentials, failure modes and a runbook. I factor shared steps into sub-workflows with explicit input contracts and validation at the boundary, so they’re testable on their own and a fix lands once.",
      check: [
        {
          id: 'm4-s1-1', kind: 'choice',
          prompt: 'The same “create or update HubSpot contact” logic is copied into six workflows. HubSpot changes a field name. What would have made this a one-place fix?',
          options: [
            { text: 'One sub-workflow for the contact step, called by all six', why: 'Yes. Shared logic in one place means one fix.' },
            { text: 'A workflow template so every copy starts from the same version', why: 'Templates help you start, but each copy then lives on its own. You’d still edit six workflows.' },
            { text: 'Pinned data on each HubSpot node so the mapping is saved once', why: 'Pinned data is sample data for testing. It doesn’t share field mappings between workflows.' },
            { text: 'One shared HubSpot credential used by all six workflows', why: 'A credential holds the login, not the field names. Six mappings would still need changing.' },
          ],
          answer: 0,
          explain: 'Sub-workflows are n8n’s functions: write once, call many times.',
        },
        {
          id: 'm4-s1-2', kind: 'choice',
          prompt: 'A sub-workflow receives a lead with no email and fails three nodes later with “Cannot read properties of undefined”. What’s the better design?',
          options: [
            { text: 'Validate required inputs at the top and fail there clearly', why: 'Right. Fail early, at the boundary, with an error a human can act on.' },
            { text: 'Set On Error to Continue on every node so the run still finishes', why: 'The run “succeeds” with a lead that has no email. The bad data is hidden, not handled.' },
            { text: 'Default a missing email to an empty string in the parent', why: 'That passes bad data downstream, where it fails later or creates a useless record.' },
            { text: 'Turn on Retry On Fail for the node that throws the error', why: 'The email is still missing on every retry. Retries are for temporary failures.' },
          ],
          answer: 0,
          explain: 'A contract means stating what you need and checking it first.',
        },
      ],
    },
    {
      title: 'When it fails: error workflows, alerts and retries',
      minutes: 7,
      body: [
        "By default a failed production execution just sits in the executions list, marked red. Nobody looks until the client asks where their leads went.",
        "**Error workflows.** Build one workflow that starts with the **Error Trigger** node and sends an alert. Then in each production workflow open **Settings → Error workflow** and choose it. When an automatic execution fails, n8n runs your [[error workflow]] with the workflow name, the last node that ran, the error message and a link to the execution. Manual test runs don’t trigger it. One central error workflow can serve all your workflows.",
        "**An actionable alert** says which workflow, which node, what error, which event (its [[correlation id]]), a short *safe* summary of the data (no full payloads, tokens or personal details) and the execution link. “Workflow failed” on its own gets ignored.",
        "**Retries.** In a node’s **Settings**, turn on **Retry On Fail** and set **Max Tries** and **Wait Between Tries**. Good for blips: timeouts, 5xx errors, dropped connections. The wait is fixed, so for longer outages, or a 429 with a `Retry-After` header, mark the event for a later attempt with [[exponential backoff]] instead (Lesson 4 shows the table that makes this easy).",
        "**When not to retry.** Retry On Fail retries **every** error. But a 400 (bad data), 401 (bad credentials) or 404 fails the same way each time, so retrying only delays the alert. Make these **fail fast**: set the node’s **On Error** to “Continue (using error output)”, then route on the status code. Retryable errors go round again; the rest go straight to failed-and-alerted.",
        "**The failure no error workflow catches** is a workflow that never starts: trigger switched off, webhook URL changed, server down. Add a heartbeat check that alerts when an expected run *doesn’t* happen.",
      ],
      example: {
        caption: 'Slack message in the central error workflow (after the Error Trigger)',
        code: "Workflow failed: {{ $json.workflow.name }}\nNode:  {{ $json.execution.lastNodeExecuted }}\nError: {{ $json.execution.error.message }}\nLink:  {{ $json.execution.url }}\n\n// The Error Trigger doesn't know your event ID. To include it, have the\n// main workflow save event_id with {{ $execution.id }} in your events table,\n// then look it up here by {{ $json.execution.id }}.",
      },
      interview: "Every production workflow points at a central error workflow built on the Error Trigger, which posts the workflow, failing node, error, correlation ID and execution link to an owned channel. I use node-level retries only for transient failures, route 4xx errors to a fail-fast branch via the error output, and add heartbeat checks because a workflow that never runs raises no error.",
      check: [
        {
          id: 'm4-s2-1', kind: 'choice',
          prompt: 'An HTTP Request node has Retry On Fail (5 tries, 5 s wait). The API key has expired. What happens?',
          options: [
            { text: 'It retries the 401 five times, then fails; the alert just arrives later', why: 'Right. Retry On Fail doesn’t know a 401 can’t fix itself.' },
            { text: 'n8n refreshes the key after the first 401, so the next try succeeds', why: 'n8n can refresh OAuth tokens, but it can’t issue a new API key. That needs a human.' },
            { text: 'It skips the retries, because n8n treats any 4xx as permanent', why: 'Retry On Fail retries every error, 4xx included. That’s why you route 4xx yourself.' },
            { text: 'It fails once, then the error workflow retries it four more times', why: 'The error workflow sends alerts; it doesn’t retry. The node’s own retries happen first.' },
          ],
          answer: 0,
          explain: 'Retry the temporary (timeouts, 5xx); fail fast on the permanent (400, 401, 403, 404).',
        },
        {
          id: 'm4-s2-2', kind: 'choice',
          prompt: 'You set up an error workflow, then click “Test workflow” on a broken workflow. No alert arrives. Why?',
          options: [
            { text: 'Error workflows run for automatic executions, not manual tests', why: 'Yes. Test it with a real trigger, e.g. by calling the production webhook URL.' },
            { text: 'The error workflow must be set to Active before n8n will call it', why: 'A workflow that starts with the Error Trigger doesn’t need activating. The manual run is the issue.' },
            { text: 'Each workflow needs its own error workflow; one can’t serve several', why: 'One central error workflow can serve all of them.' },
            { text: 'The Error Trigger only fires for HTTP errors, not node failures', why: 'It fires for any failed automatic execution, whatever the error.' },
          ],
          answer: 0,
          explain: 'Trigger a real failure to prove your alerting works.',
        },
        {
          id: 'm4-s2-3', kind: 'choice',
          prompt: 'Which alert is most useful at 3am?',
          options: [
            { text: '“Lead intake → Create contact: 429. Event evt_88. Link: …”', why: 'Yes. Workflow, node, error, event and a link: you can act immediately.' },
            { text: '“Lead intake failed: Request failed with status code 429”', why: 'Better than nothing, but no node, no event and no link. You start by hunting.' },
            { text: 'The full webhook payload and error stack, so nothing is missing', why: 'Too much to read at 3am, and it leaks personal data into Slack.' },
            { text: '“Lead intake failed for ana@example.com. Please check n8n.”', why: 'It puts personal data in Slack and still doesn’t say which node, what error or where to look.' },
          ],
          answer: 0,
          explain: 'Actionable = what, where, which record, and how to look closer, with nothing sensitive.',
        },
      ],
    },
    {
      title: 'Safe to run twice: idempotency, raw events and replay',
      minutes: 7,
      body: [
        "**The problem.** A HubSpot node creates a contact, then the next node times out and the execution fails. You retry. Now there are two contacts. **A failed execution may already have done things**: created records, sent emails. Never treat “it failed” as proof that nothing happened.",
        "So every create or update step must be [[idempotent]]: running it twice leaves the same result as running it once. Three tools:",
        "- **Stable keys.** Identify each piece of work by something that doesn’t change between attempts: the provider’s event ID, the email, an order number. A random ID made fresh on every run defeats the purpose.\n- **Upserts, not search-then-create.** Use the CRM’s create-or-update operation keyed on email, or `INSERT ... ON CONFLICT` in Postgres. Search-then-create races when two runs overlap.\n- **Record outcomes.** Before sending an email or creating a deal, check your table: already done for this event? After success, store the provider’s ID. A replay reads that instead of repeating the action.",
        "**Log the raw event first.** Straight after the Webhook, insert the untouched body into your `events` table (the SQL module) with `ON CONFLICT DO NOTHING` on the event ID. Then respond, then process. If your transformation has a bug, the original data is safe.",
        "**Build a [[replay]] path.** A small workflow that takes an event ID, or all events with `status = 'failed'`, loads the stored payload and sends it to the same processing sub-workflow. Because each step is idempotent, replaying is safe.",
        "**Why not just n8n’s Retry button?** It’s handy for a one-off. But executions are deleted after the retention period (or never saved), and the failed node itself may have half-succeeded, like a create that timed out. **Your events table is the durable record**; n8n’s execution list isn’t.",
      ],
      example: {
        caption: 'Intake, processing and replay as three workflows',
        code: "'Lead intake'\n  Webhook (POST /lead)\n  → Postgres: INSERT INTO events ... ON CONFLICT DO NOTHING RETURNING event_id\n      (setting Always Output Data, so a duplicate still continues)\n  → Respond to Webhook: 200\n  → IF event_id is empty → stop      // duplicate delivery, already stored\n  → Execute Workflow: 'Process lead'\n\n'Process lead' (sub-workflow)\n  → Postgres: load the event; stop if status = 'done'\n  → HubSpot: Create or Update contact (matched by email)\n  → Postgres: UPDATE events SET status = 'done', crm_id = ...\n\n'Replay failed events' (manual or scheduled)\n  → Postgres: SELECT event_id FROM events WHERE status = 'failed'\n  → Execute Workflow: 'Process lead'   // the same sub-workflow",
      },
      interview: "I persist the raw inbound event before transformation, keyed on the provider’s event ID, then process it through idempotent steps: upserts on stable keys and recorded provider outcomes. Recovery is a replay workflow over stored events, not re-running executions and hoping, because a failed execution can still have produced side effects.",
      check: [
        {
          id: 'm4-s3-1', kind: 'choice',
          prompt: 'Your workflow uses “HubSpot: search contact by email → IF not found → create contact”. Two form submissions arrive within a second, and you get two contacts. Best fix?',
          options: [
            { text: 'Replace search-then-create with create-or-update keyed on email', why: 'Yes. One atomic step on a stable key can’t race.' },
            { text: 'Turn on Retry On Fail for the create node so the second run backs off', why: 'Nothing failed; both creates succeeded. Retries don’t change that.' },
            { text: 'Add a 2-second Wait before the search so the first contact exists', why: 'Both runs wait two seconds, then race exactly as before.' },
            { text: 'Search by name as well as email so the match is more precise', why: 'The search isn’t wrong. Both runs search before either has created the contact.' },
          ],
          answer: 0,
          explain: 'Search-then-create is a race. Upsert on a stable key.',
        },
        {
          id: 'm4-s3-2', kind: 'choice',
          prompt: 'A transformation bug corrupted 200 leads last week. Your executions from then have been pruned. What lets you recover?',
          options: [
            { text: 'Replaying the raw events you stored, through the fixed workflow', why: 'Right. The original data is untouched, and idempotent steps make replay safe.' },
            { text: 'n8n’s “Retry with currently saved workflow” on those executions', why: 'They’ve been pruned; there’s nothing left to retry.' },
            { text: 'Re-running the workflow using the leads now in the CRM as input', why: 'Those are the corrupted values. You need the originals.' },
            { text: 'Restoring last night’s n8n database backup to get the executions', why: 'Last night’s backup was taken after the pruning, so those executions aren’t in it either.' },
          ],
          answer: 0,
          explain: 'Store raw first, then transform. Your own log outlives n8n’s execution history.',
        },
      ],
    },
    {
      title: 'Big jobs: batching and rate limits',
      minutes: 6,
      body: [
        "**The problem.** A client uploads 5,000 contacts to enrich. Your workflow fires 5,000 API calls as fast as it can. After 100, the provider replies `429 Too Many Requests` and the rest fail. Or the execution runs out of memory holding everything at once.",
        "Every API has a [[rate limit]], e.g. 100 requests per 10 seconds. It’s in the provider’s docs; read it before you build. Limits are often per API key, so every workflow using that key shares the same allowance.",
        "**Batching in n8n:**",
        "- **Loop Over Items** (formerly Split In Batches) hands on a list in batches of, say, 50. Put the API call and a **Wait** node inside the loop, so each batch is followed by a pause.\n- The **HTTP Request** node has a **Batching** option (Items per Batch, Batch Interval) that spaces out its own requests without a loop.\n- Fetch big lists page by page ([[pagination]]) instead of all at once.",
        "**Do the maths.** Limit 100 per 10 seconds: batches of 50 with a 6-second wait send at most 50 every 6 seconds, comfortably under it, with room left for other workflows on the same key.",
        "**When you still get a 429, back off.** If the response has a `Retry-After` header, wait that long. Otherwise wait longer each time ([[exponential backoff]]) with a little random [[jitter]], so parallel runs don’t all retry at the same instant.",
        "**Production point.** Don’t hold 5,000 items in one execution. Write them to a table as `pending`, then let a scheduled workflow take the next 200 each run and mark each row `done`. If it crashes, it resumes where it stopped instead of starting over. And **more workers don’t raise the provider’s limit**; they just reach it faster.",
      ],
      example: {
        caption: 'A scheduled enrichment job that respects a rate limit',
        code: "Schedule Trigger (every 5 minutes)\n  → Postgres: SELECT * FROM enrich_jobs\n              WHERE status = 'pending' ORDER BY id LIMIT 200\n  → Loop Over Items (batch size 50)\n      → HTTP Request: enrich contact\n      → Postgres: UPDATE enrich_jobs SET status = 'done' WHERE id = ...\n      → Wait: 6 seconds\n      → back to Loop Over Items\n  → done branch: finished (the next run picks up the next 200)",
      },
      interview: "I size batches from the provider’s documented limit, leaving headroom for other consumers of the same key, using Loop Over Items with Wait or the HTTP node’s batching. On 429 I honour Retry-After, otherwise back off exponentially with jitter. Large jobs are persisted as pending rows and processed in checkpointed chunks, since adding workers doesn’t raise an external rate limit.",
      check: [
        {
          id: 'm4-s4-1', kind: 'choice',
          prompt: 'The API allows 60 requests per minute. Which setup stays safely under it?',
          options: [
            { text: 'Batches of 20, with a 30-second wait', why: 'Yes. About 40 a minute: under the limit, with headroom for other workflows.' },
            { text: 'Batches of 60, with a 1-minute wait', why: 'Exactly at the limit, with no headroom. Any other workflow on the key tips it over.' },
            { text: 'Batches of 5, with a 2-second wait', why: 'Small batches look safe, but that’s about 150 a minute, well over the limit.' },
            { text: 'Batches of 30, with a 10-second wait', why: 'That’s about 180 a minute, three times the limit.' },
          ],
          answer: 0,
          explain: 'Requests per batch ÷ time per batch must stay under the limit, ideally with room to spare.',
        },
        {
          id: 'm4-s4-2', kind: 'choice',
          prompt: 'Enrichment keeps hitting 429 errors, so a teammate adds two more n8n workers. What happens?',
          options: [
            { text: 'More 429s: the limit is per key, and more requests arrive at once', why: 'Right. Workers add capacity on your side, not theirs.' },
            { text: 'Fewer 429s, because each worker gets its own share of the limit', why: 'The provider counts requests per key, however many workers send them.' },
            { text: 'No change, because n8n paces requests per credential across workers', why: 'n8n doesn’t coordinate rate limits between workers. Pacing is up to your workflow.' },
            { text: 'Fewer 429s, because Redis spaces out executions between workers', why: 'Redis only holds the queue. Workers take jobs as fast as they can.' },
          ],
          answer: 0,
          explain: 'Rate limits are solved by pacing and backoff, not by scaling up.',
        },
      ],
    },
    {
      title: 'Secrets, settings and backups',
      minutes: 6,
      body: [
        "**Credentials** are the saved logins n8n uses: API keys, OAuth tokens, database passwords. n8n stores them in its database **encrypted** with an [[encryption key]]. If you don’t set one, n8n generates one and saves it in its data folder (`.n8n`). In production, set it yourself with `N8N_ENCRYPTION_KEY` and keep a copy somewhere safe, such as a password manager. Lose it and every saved credential is unreadable.",
        "**Configure n8n with [[environment variable|environment variables]]**, not by clicking around: database connection, `WEBHOOK_URL`, timezone (`GENERIC_TIMEZONE`), execution settings. Dev, staging and production then differ only by their `.env` file.",
        "**[[Execution retention]].** Saved executions hold the full data of every node: emails, phone numbers, sometimes tokens in API responses. They also fill the database. Turn on pruning (`EXECUTIONS_DATA_PRUNE=true`, with `EXECUTIONS_DATA_MAX_AGE` in hours), and consider not saving successful runs at all (`EXECUTIONS_DATA_SAVE_ON_SUCCESS=none`).",
        "**Secret rotation** means replacing a key on a schedule or after a leak: create the new key at the provider, update the n8n credential, test, then revoke the old key. Give each credential the smallest [[scopes]] it needs, so a leak does less damage.",
        "**A full n8n backup has three parts:**",
        "1. The database (`pg_dump` for Postgres): workflows, credentials, executions.\n2. The encryption key.\n3. Your config: the compose file and `.env`, stored securely and never in Git.",
        "Also export workflows as JSON into Git (`n8n export:workflow --all --output=workflows.json`) for version history. **Prove the backup works:** restore all three into a fresh server and run a workflow that uses a credential.",
      ],
      example: {
        caption: 'A production .env for n8n (never committed to Git)',
        code: "N8N_ENCRYPTION_KEY=<long random string, also in your password manager>\nDB_TYPE=postgresdb\nDB_POSTGRESDB_HOST=postgres\nDB_POSTGRESDB_DATABASE=n8n\nDB_POSTGRESDB_USER=n8n\nDB_POSTGRESDB_PASSWORD=<secret>\nWEBHOOK_URL=https://n8n.client.com/\nGENERIC_TIMEZONE=Australia/Sydney\nEXECUTIONS_DATA_PRUNE=true\nEXECUTIONS_DATA_MAX_AGE=168            # hours: keep 7 days\nEXECUTIONS_DATA_SAVE_ON_SUCCESS=none   # keep failures only",
      },
      interview: "Credentials are encrypted with N8N_ENCRYPTION_KEY, which I set explicitly and back up separately, because a database restore without it is useless. Configuration is environment-driven, execution data is pruned since it contains personal data, and secrets are least-privilege and rotated by creating, switching, testing and then revoking. I prove backups by restoring database, key and config into a clean environment.",
      check: [
        {
          id: 'm4-s5-1', kind: 'choice',
          prompt: 'You start a fresh n8n on a new server, pointed at a copy of the old database, without setting N8N_ENCRYPTION_KEY. Workflows load, but every credential fails. Why?',
          options: [
            { text: 'The new instance made its own key, which can’t decrypt the old ones', why: 'Right. Set the original key before starting it.' },
            { text: 'Credentials are tied to the old server’s hostname, so they’re rejected', why: 'n8n doesn’t tie credentials to a hostname. It just can’t decrypt them.' },
            { text: 'OAuth tokens expire on migration, so each one must be reconnected', why: 'Moving servers doesn’t expire tokens, and API-key credentials fail too.' },
            { text: 'The database copy skipped the credentials table; dump it separately', why: 'Credentials live in the same database and were copied. They’re there, but encrypted.' },
          ],
          answer: 0,
          explain: 'Database + encryption key + config. Miss one and the restore fails.',
        },
        {
          id: 'm4-s5-2', kind: 'order',
          prompt: 'An API key appeared in a screenshot you shared. Put the rotation steps in order.',
          items: ['Create a new key at the provider', 'Update the credential in n8n', 'Run a test execution that uses it', 'Revoke the old key'],
          explain: 'New first, revoke last, so nothing breaks in between.',
        },
        {
          id: 'm4-s5-3', kind: 'choice',
          prompt: 'A privacy review finds customer phone numbers in n8n executions from two years ago. What should you change?',
          options: [
            { text: 'Turn on pruning with a max age, and stop saving successful runs', why: 'Yes. Keep execution data only as long as it’s useful.' },
            { text: 'Rotate every API key and credential those workflows use', why: 'Good hygiene, but it doesn’t remove the stored personal data.' },
            { text: 'Encrypt the database disk so the stored executions are protected', why: 'The data is still kept for years. Privacy needs it gone, not just locked.' },
            { text: 'Deactivate the old workflows so their executions get archived', why: 'Deactivating stops new runs. Old executions stay exactly where they are.' },
          ],
          answer: 0,
          explain: 'Execution data is a liability as well as a debugging tool. Set retention on purpose.',
        },
      ],
    },
    {
      title: 'Scaling with queue mode, and when to use Python instead',
      minutes: 7,
      body: [
        "**The problem.** By default one n8n process does everything: serves the editor, receives webhooks and runs every execution. One heavy job slows everything else, and if that process dies, all running work stops with it.",
        "**[[Queue mode]]** splits the jobs up:",
        "- **Main instance**: the editor, triggers and webhooks. When a workflow should run, it puts the execution on a queue instead of running it.\n- **[[Redis]]**: holds that queue.\n- **Workers**: separate n8n processes started with `n8n worker`. They take executions off the queue and run them. More workers, more executions at once.\n- **Postgres**: the shared database. Workers load the workflow from it and save the results back. SQLite isn’t supported in queue mode.",
        "You turn it on with `EXECUTIONS_MODE=queue` plus the Redis connection settings (such as `QUEUE_BULL_REDIS_HOST`). **Every instance needs the same `N8N_ENCRYPTION_KEY`** and the same database, or workers can’t read credentials. Each worker runs several executions at once; set how many with `--concurrency`, e.g. `n8n worker --concurrency=5`.",
        "**What it doesn’t fix:** provider rate limits, non-idempotent steps and broken workflows. More workers make all three hit harder. So test the failures: kill a worker mid-execution, stop Redis, and check what your alerts and replay path do.",
        "**n8n or a Python service?** n8n is excellent at orchestration: triggers, routing, connecting APIs, alerts, and showing a non-developer what happens. Move work into a small Python service (the FastAPI module) when the logic is complex, needs proper automated tests, is reused by several systems, or is heavy computation. The common answer is **both**: n8n runs the trigger and the flow, and calls your service over HTTP for the hard part.",
      ],
      example: {
        caption: 'compose.yaml sketch: main + 2 workers (volumes left out for brevity)',
        code: "# .env shared by main and workers:\n#   EXECUTIONS_MODE=queue\n#   QUEUE_BULL_REDIS_HOST=redis\n#   DB_TYPE=postgresdb   DB_POSTGRESDB_HOST=postgres  ...\n#   N8N_ENCRYPTION_KEY=<the same key everywhere>\n\nservices:\n  n8n-main:          # editor, triggers, webhooks → puts jobs on the queue\n    image: docker.n8n.io/n8nio/n8n\n    env_file: .env\n    ports: [\"5678:5678\"]\n  n8n-worker:        # takes jobs off the queue and runs them\n    image: docker.n8n.io/n8nio/n8n\n    command: worker --concurrency=5\n    env_file: .env\n    deploy:\n      replicas: 2    # two workers\n  redis:\n    image: redis:7\n  postgres:\n    image: postgres:16",
      },
      interview: "In queue mode the main instance handles the editor, triggers and webhooks and enqueues executions in Redis; workers pull and run them against the shared Postgres, all with the same encryption key. It adds throughput and isolation but doesn’t fix rate limits or non-idempotent steps. I keep n8n as the orchestrator and move complex, heavily tested or reused logic into a Python service it calls over HTTP.",
      check: [
        {
          id: 'm4-s6-1', kind: 'choice',
          prompt: 'In queue mode, a webhook arrives. Which component actually runs the workflow?',
          options: [
            { text: 'A worker, after the main instance puts it on the Redis queue', why: 'Right. Main receives and enqueues; workers execute.' },
            { text: 'The main instance, since it’s the one that received the webhook', why: 'In queue mode, main hands execution to the workers.' },
            { text: 'Redis, which runs queued jobs in order as workers become free', why: 'Redis only holds the queue; it doesn’t run workflows.' },
            { text: 'Postgres, which loads the workflow and runs it for the worker', why: 'Postgres stores workflows and results; it doesn’t run them.' },
          ],
          answer: 0,
          explain: 'Main = front desk. Redis = the queue. Workers = the people doing the work. Postgres = the filing cabinet.',
        },
        {
          id: 'm4-s6-2', kind: 'choice',
          prompt: 'A lead-scoring workflow has grown to 40 IF and Code nodes. The client wants every rule tested before each change. What’s a sensible move?',
          options: [
            { text: 'Move the scoring into a tested Python service that n8n calls', why: 'Yes. n8n keeps orchestrating; the complex, test-heavy logic lives in code.' },
            { text: 'Switch to queue mode so each rule runs and is checked separately', why: 'Queue mode adds capacity, not testability.' },
            { text: 'Merge the rules into one big Code node so they’re in one place', why: 'One place, but still no automated tests, and a huge Code node is hard to review.' },
            { text: 'Rebuild it all in Python, including the triggers and alerts', why: 'Possible, but you throw away what n8n does well for no gain.' },
          ],
          answer: 0,
          explain: 'n8n for the flow, code for complex logic that needs tests. Often both.',
        },
      ],
    },
    {
      title: 'n8n, Make, Zapier and Power Automate: same ideas, different tools',
      minutes: 6,
      body: [
        "**The problem.** Job ads rarely ask for n8n alone. Most want n8n plus at least one other platform, and Australian enterprise and government roles often name **Microsoft Power Automate**. Everything in this module carries over; only the names and buttons change.",
        "**Same workflow, four vocabularies.** A trigger starts a run, steps do the work, branches route it, and something handles errors. Describe a workflow in those terms and you can rebuild it anywhere.",
        "**Where they really differ:**",
        "- **Hosting.** Only n8n can be self-hosted on the client’s own server. The others run in the vendor’s cloud (Power Automate’s desktop flows, its RPA side, run on Windows machines). Power Automate’s on-premises data gateway lets cloud flows reach internal systems, but the flows still run in Microsoft’s cloud.\n- **Pricing model.** n8n Cloud counts workflow executions. Make counts the module runs inside a scenario; Zapier counts tasks (successful action steps). Power Automate is licensed per user or per flow, and premium connectors, including plain HTTP, need a paid licence.\n- **Code.** n8n has the Code node (JavaScript or Python) and Zapier has Code by Zapier. Make and Power Automate lean mostly on built-in functions and expressions; for real code, a Power Automate flow usually calls an Azure Function or your own API.\n- **Governance.** Power Automate lives inside Microsoft 365: the same staff sign-in, admin centre, environments and data loss prevention (DLP) policies IT already manages.",
        "**Copilot Studio** is Microsoft’s low-code tool for building AI agents and chatbots. An agent can answer from company documents and call Power Automate flows as actions, so the two often appear together in job ads.",
        "**The client’s stack usually decides.** A flow their IT team can see and govern beats a better tool nobody there can support. Self-hosting for data reasons, or heavy custom logic, points to n8n.",
        "**“We’re a Microsoft shop.”** Don’t sell against it. Say you’d build in Power Automate, check which connectors are premium, put heavy logic behind an API the flow calls, and keep the same patterns: raw event log, idempotent steps, error handling with Scopes.",
      ],
      example: {
        caption: 'One idea, four names (PA = Power Automate)',
        code: "THE WHOLE THING\n  n8n workflow · Make scenario · Zapier Zap · PA flow\n\nEACH STEP\n  n8n node · Make module · Zapier action · PA action\n\nBRANCHING\n  n8n IF / Switch\n  Make Router + filters\n  Zapier Paths / Filter\n  PA Condition / Switch\n\nLOOPING\n  n8n: automatic, once per item\n  Make: Iterator + Aggregator\n  Zapier: Looping by Zapier\n  PA: Apply to each\n\nERRORS\n  n8n: error workflow + error output\n  Make: error handler routes\n  Zapier: error notifications, autoreplay\n  PA: Scope + Configure run after",
      },
      interview: "The concepts are portable: triggers, steps, branching, iteration and error handling map directly between n8n workflows, Make scenarios, Zaps and Power Automate flows. I choose by the client’s constraints: self-hosting and custom code favour n8n, while a Microsoft 365 estate with central IT governance favours Power Automate, with Copilot Studio for agent front ends. The reliability patterns, idempotency, raw event logs and alerting, stay the same whichever tool runs them.",
      check: [
        {
          id: 'm4-s7-1', kind: 'choice',
          prompt: 'A client must keep every workflow and its data on its own servers. Which tool fits?',
          options: [
            { text: 'n8n, self-hosted on their own server', why: 'Right. Of these four, only n8n can be fully self-hosted.' },
            { text: 'Zapier, using its on-premises agent', why: 'Zapier runs only in Zapier’s cloud.' },
            { text: 'Make, with a private hosting region', why: 'Make lets you pick a cloud region, but it’s still Make’s cloud, not the client’s servers.' },
            { text: 'Power Automate, via the data gateway', why: 'The gateway lets cloud flows reach internal systems. The flows still run in Microsoft’s cloud.' },
          ],
          answer: 0,
          explain: 'Self-hosting is n8n’s clearest difference from the other three.',
        },
        {
          id: 'm4-s7-2', kind: 'choice',
          prompt: 'You’re rebuilding an n8n workflow in Zapier. It has an IF node that sends hot leads one way and cold leads another. What’s the closest equivalent?',
          options: [
            { text: 'Paths, one for each branch', why: 'Yes. Paths are Zapier’s branching; a Filter alone just stops the Zap.' },
            { text: 'A Router with two routes', why: 'That’s Make’s name for branching, not Zapier’s.' },
            { text: 'A Condition inside a Scope', why: 'Those are Power Automate actions, not Zapier steps.' },
            { text: 'Looping by Zapier with a rule', why: 'Looping repeats steps over a list; it doesn’t branch.' },
          ],
          answer: 0,
          explain: 'Branching is IF/Switch in n8n, Router in Make, Paths in Zapier, Condition/Switch in Power Automate.',
        },
        {
          id: 'm4-s7-3', kind: 'choice',
          prompt: 'A government agency says, “We’re a Microsoft shop,” and wants approvals automated. What’s the strongest first response?',
          options: [
            { text: 'Plan it in Power Automate, using their existing sign-in and policies', why: 'Yes. Their IT team can govern and support it, and your design patterns carry over.' },
            { text: 'Propose self-hosted n8n, since it’s more flexible and cheaper to run', why: 'Maybe for some jobs, but leading against their stack ignores who has to support it.' },
            { text: 'Build it in Copilot Studio, which has replaced Power Automate flows', why: 'Copilot Studio builds agents and chatbots. It calls flows; it hasn’t replaced them.' },
            { text: 'Use Zapier, because it connects to more apps than Power Automate', why: 'App count isn’t the issue. Governance and fit with Microsoft 365 are.' },
          ],
          answer: 0,
          explain: 'The client’s existing stack usually decides the tool. Your patterns go with you.',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'm4-q1', kind: 'choice',
      prompt: 'A Google Sheets node returns 25 rows. The next node is an HTTP Request that posts each lead to a CRM. How many requests are sent?',
      options: [
        { text: '25, one request per row', why: 'Yes. Most nodes run once for each incoming item.' },
        { text: '1, with all rows in one body', why: 'Only if you aggregate first or turn on Execute Once.' },
        { text: '0 until you add Loop Over Items', why: 'n8n runs the node once per item automatically. Loop Over Items is for batching.' },
        { text: '26, counting the header row', why: 'The header row becomes field names, not an item.' },
      ],
      answer: 0,
      explain: 'Items in = runs of the node. Plan for that, especially before emails or paid APIs.',
    },
    {
      id: 'm4-q2', kind: 'order',
      prompt: 'Order the steps to set up central error alerts.',
      items: ['Create a workflow starting with the Error Trigger node', 'Add a Slack or email node with workflow, node, error and link', 'In each production workflow, choose it under Settings → Error workflow', 'Cause a real failure through the production trigger and check the alert'],
      explain: 'Build it, connect it, then prove it with a real (not manual) failure.',
    },
    {
      id: 'm4-q3', kind: 'choice',
      prompt: 'Which error should an HTTP node **retry**?',
      options: [
        { text: '503 Service Unavailable', why: 'Yes. A temporary server-side problem; a retry may well succeed.' },
        { text: '400 Bad Request', why: 'The data is wrong; it will fail the same way every time.' },
        { text: '401 Unauthorized', why: 'Credentials need fixing; retrying just delays the alert.' },
        { text: '422 Unprocessable Entity', why: 'The provider understood the request but rejected the data. Same result every time.' },
      ],
      answer: 0,
      explain: 'Retry timeouts, 5xx and 429 (with backoff). Fail fast on other 4xx.',
    },
    {
      id: 'm4-q4', kind: 'choice',
      prompt: 'An execution failed at “Send welcome email”, after “Create contact” succeeded. You replay the event. What keeps this safe?',
      options: [
        { text: 'Contact is an upsert on email; the email step checks “already sent”', why: 'Right. Idempotent steps make the replay harmless.' },
        { text: 'n8n skips nodes that succeeded in the earlier execution of this event', why: 'A replay of a stored event starts fresh; your own records must hold that memory.' },
        { text: 'The CRM rejects a second contact with the same email automatically', why: 'Many CRMs happily create duplicates. Don’t rely on it.' },
        { text: 'The replay runs with Retry On Fail off, so no step can repeat', why: 'Retries happen within one run. The replay itself repeats every step.' },
      ],
      answer: 0,
      explain: 'Stable keys + upserts + recorded outcomes = safe to run twice.',
    },
    {
      id: 'm4-q5', kind: 'choice',
      prompt: 'The provider sends the same webhook twice, two seconds apart. Your intake inserts it with `ON CONFLICT (tenant_id, event_id) DO NOTHING RETURNING event_id`, followed by the IF check from the lesson. What happens to the second one?',
      options: [
        { text: 'No event_id is returned, so the IF node stops it', why: 'Yes. RETURNING gives nothing for a skipped insert, and the IF node stops the duplicate before processing.' },
        { text: 'It updates the stored row, and processing runs again', why: 'That’s DO UPDATE. DO NOTHING leaves the first row as it is.' },
        { text: 'The insert throws a unique violation, so the run fails', why: 'DO NOTHING turns the conflict into a quiet skip, not an error.' },
        { text: 'Both rows are stored, and the IF node skips the newer one', why: 'The unique key on (tenant_id, event_id) stops the second row being stored at all.' },
      ],
      answer: 0,
      explain: 'Deduplicate at intake on the provider’s event ID, and only continue when a new row was inserted.',
    },
    {
      id: 'm4-q6', kind: 'choice',
      prompt: 'Why log the raw webhook body **before** transforming it?',
      options: [
        { text: 'If a transformation bug hits, the original is there to replay', why: 'Right. Transformed data can’t be un-transformed.' },
        { text: 'So Respond to Webhook has the original data to send back', why: 'Respond to Webhook can send anything; it doesn’t need a stored copy. The value is recovery.' },
        { text: 'It lets you skip validation, since the row proves the data arrived', why: 'Arriving isn’t the same as being valid. You still validate.' },
        { text: 'It keeps executions smaller, since the payload lives in Postgres', why: 'The payload still passes through the execution. The value is recovery, not size.' },
      ],
      answer: 0,
      explain: 'Store raw, then transform. That’s what makes replay possible.',
    },
    {
      id: 'm4-q7', kind: 'choice',
      prompt: 'Read the log. What’s the right fix?',
      code: '10:00:01 enrich batch 1: 100 requests → 100 OK\n10:00:02 enrich batch 2: 100 requests → 37 OK, 63 × 429\n          Retry-After: 30',
      options: [
        { text: 'Smaller batches with a Wait, and pause 30 s when a 429 arrives', why: 'Yes. Pace under the limit, and wait as long as the provider asks.' },
        { text: 'Retry the 63 failed requests straight away with Retry On Fail', why: 'They’ll get 429 again; the provider asked for 30 seconds.' },
        { text: 'Add two more workers so the 63 are spread across processes', why: 'Same API key, more parallel requests: rate limiting gets worse.' },
        { text: 'Raise the HTTP node’s timeout so slow requests don’t fail', why: '429 means too many requests, not too slow. A timeout won’t change it.' },
      ],
      answer: 0,
      explain: 'Rate limits need pacing and backoff, not force.',
    },
    {
      id: 'm4-q8', kind: 'choice',
      prompt: 'A client asks: “Why can’t we just use n8n’s execution history as our record of every lead?”',
      options: [
        { text: 'Executions get pruned or may not be saved, so they aren’t durable', why: 'Right. Execution data is for debugging, with a retention limit.' },
        { text: 'Execution data is encrypted, so you can’t query it for reports', why: 'Credentials are encrypted; execution data isn’t, and you can open it in the editor.' },
        { text: 'n8n keeps only the last 100 executions per workflow by default', why: 'There’s no 100 limit. Retention is set by age and count settings you choose.' },
        { text: 'You can, as long as Save Manual Executions is turned on too', why: 'Manual runs aren’t the issue. Production executions still get pruned.' },
      ],
      answer: 0,
      explain: 'n8n executions = debugging. Your events table = system of record.',
    },
    {
      id: 'm4-q9', kind: 'choice',
      prompt: 'You restore an n8n backup to a new server. What must the backup include for credentials to work?',
      options: [
        { text: 'The database and the original N8N_ENCRYPTION_KEY', why: 'Yes. Credentials are encrypted in the database with that key.' },
        { text: 'The database plus every workflow exported as JSON', why: 'Workflow exports don’t contain secrets, and without the key the database copy can’t be decrypted.' },
        { text: 'Workflow JSON plus the output of export:credentials', why: 'Exported credentials stay encrypted with the old key unless decrypted, so the new instance can’t read them.' },
        { text: 'The database, with a fresh key set in the new .env', why: 'A new key can’t decrypt credentials encrypted with the old one.' },
      ],
      answer: 0,
      explain: 'Back up data, key and config together, and test the restore.',
    },
    {
      id: 'm4-q10', kind: 'choice',
      prompt: 'After switching to queue mode, workers log “credentials could not be decrypted” while the main instance works fine. Most likely cause?',
      options: [
        { text: 'The workers have a different N8N_ENCRYPTION_KEY from main', why: 'Right. Every instance must share the same key.' },
        { text: 'Redis stores the credentials, and its memory was flushed', why: 'Redis holds the queue, not credentials. Those live in Postgres.' },
        { text: 'Credentials must be re-entered in each worker’s own editor', why: 'Workers have no editor. They read the shared database, which works with the same key.' },
        { text: 'The workers are missing the QUEUE_BULL_REDIS_HOST setting', why: 'Then they’d never receive jobs, so they’d never reach the credentials.' },
      ],
      answer: 0,
      explain: 'Same database, same Redis, same encryption key on main and every worker.',
    },
    {
      id: 'm4-q11', kind: 'choice',
      prompt: 'One record in a batch of 500 has a malformed email, and the whole run stops. What’s the production-grade behaviour?',
      options: [
        { text: 'Mark that record failed with an alert; the other 499 continue', why: 'Yes. One bad record shouldn’t block the rest, and it stays visible for fixing and replay.' },
        { text: 'Turn on Retry On Fail so the bad record gets a few more attempts', why: 'The bad email fails every time. Retries only delay things.' },
        { text: 'Set On Error to Continue so the run finishes and skips it', why: 'The run finishes, but the lead disappears without anyone knowing.' },
        { text: 'Validate the batch first and reject all 500 if any one fails', why: 'Strict, but 499 good leads now wait on one bad one.' },
      ],
      answer: 0,
      explain: 'Isolate bad records: fail them visibly, keep the rest moving.',
    },
    {
      id: 'm4-q12', kind: 'choice',
      prompt: 'An interviewer asks when you’d use n8n versus a Python service. Which answer is strongest?',
      options: [
        { text: 'n8n for the flow and integrations; Python for complex, tested logic', why: 'Yes. It shows you choose by what each tool is good at, and often use both.' },
        { text: 'n8n for prototypes, then rewrite everything in Python for production', why: 'Plenty of production work runs well in n8n. A rewrite throws that away.' },
        { text: 'Python once a workflow passes about 20 nodes; n8n below that', why: 'Node count is a poor rule. What matters is complexity, testing and reuse.' },
        { text: 'n8n with Code nodes for the logic, so it all stays in one tool', why: 'Large logic in Code nodes is hard to test and review.' },
      ],
      answer: 0,
      explain: 'Orchestration in n8n, hard logic in code, clear contracts between them.',
    },
    {
      id: 'm4-q13', kind: 'choice',
      prompt: 'A client’s Make scenario uses a Router with two filtered routes. You’re moving it to Power Automate. What replaces the Router?',
      options: [
        { text: 'A Condition or Switch action', why: 'Yes. Those are Power Automate’s branching actions.' },
        { text: 'An Apply to each with a filter', why: 'Apply to each loops over a list; it doesn’t choose between routes.' },
        { text: 'A Scope with Configure run after', why: 'That’s Power Automate’s error-handling pattern, not branching.' },
        { text: 'Parallel branches, no filters', why: 'Both branches would always run, ignoring the Router’s filters.' },
      ],
      answer: 0,
      explain: 'Same idea, different names: Router in Make, Condition/Switch in Power Automate.',
    },
    {
      id: 'm4-q14', kind: 'choice',
      prompt: 'A job application asks for your most complex n8n workflow as JSON. What should you do before sending it?',
      options: [
        { text: 'Strip credential names and pasted keys, and add sticky notes', why: 'Yes. Clean, documented JSON shows skill without leaking anything.' },
        { text: 'Nothing, since exported JSON already removes anything sensitive', why: 'Secret values aren’t exported, but credential names and keys pasted into nodes are.' },
        { text: 'Include the credentials exported with --decrypted so it runs', why: 'That sends live secrets to a stranger. They should use their own credentials.' },
        { text: 'Send a database dump instead, so they see real executions', why: 'Executions contain client data. Never share them.' },
      ],
      answer: 0,
      explain: 'Portfolio JSON should be clean, documented and free of anything secret.',
    },
  ],
  tasks: [
    { device: 'phone', plain: 'Learn how n8n moves data: items, expressions, binary data, executions and sub-workflows.', done: 'You can predict how many times a node runs for a given input, and you’ve passed the Lesson 1 and 2 checks.' },
    { device: 'computer', plain: 'Add the standard header to every production workflow: purpose, owner, inputs, outputs, credentials, failure modes and runbook.', done: 'Each workflow has a sticky note and description following the same template.' },
    { device: 'computer', plain: 'Build one central error workflow that sends an alert with workflow, node, event ID, a safe data summary and the error.', done: 'A real (non-manual) failure produces an alert you could act on without opening n8n first.' },
    { device: 'computer', plain: 'Add limited retries with growing waits for temporary HTTP errors, and make permanent errors fail straight away.', done: 'A test where a 503 is retried and then succeeds, and a 400 goes to the failed branch on the first attempt.' },
    { device: 'computer', plain: 'Make every create or update step safe to run twice, using stable keys and database constraints.', done: 'Running the same event through the workflow twice leaves one contact and one row.' },
    { device: 'computer', plain: 'Store every incoming webhook raw before processing, and build a workflow that replays failed events.', done: 'You break a step, fix it, replay the failed events and get correct results with no duplicates.' },
    { device: 'computer', plain: 'Process a large job in batches that stay under the provider’s rate limit.', done: 'A run of 1,000+ items finishes with no 429 errors, and you can show the maths behind your batch size and wait.' },
    { device: 'phone', plain: 'Learn how n8n stores credentials, the encryption key, environment variables, execution retention and secret rotation.', done: 'You can explain why a restore without the encryption key fails, and you’ve passed the Lesson 6 check.' },
    { device: 'computer', plain: 'Split one large workflow into reusable sub-workflows with defined inputs and outputs.', done: 'The parent calls at least two sub-workflows, each validating its inputs and tested on its own.' },
    { device: 'phone', plain: 'Learn queue mode: main instance, workers, Redis, Postgres, concurrency and scaling.', done: 'You can draw the four parts and explain what each does, and you’ve passed the Lesson 7 check.' },
    { device: 'computer', plain: 'Run n8n in queue mode locally or on a test VPS with at least two workers.', done: 'Executions show up on both workers, and the same workflow keeps working when one worker is stopped.' },
    { device: 'computer', plain: 'Back up the n8n database, encryption key and config, then restore them into a fresh environment.', done: 'Written restore steps, plus a workflow using a credential running successfully on the restored copy.' },
    { device: 'computer', plain: 'Break things on purpose: a duplicate event, a provider 500, Redis down, an expired credential and one malformed record.', done: 'A short table of each test, what happened, and how the workflow detected and recovered from it.' },
    { device: 'phone', plain: 'Practise explaining when you’d choose n8n, a Python service, or both.', done: 'A recorded 2-minute answer with one concrete example of each choice.' },
  ],
};
