import type { Lesson } from './types';

export const m6: Lesson = {
  intro: "Getting an automation working on your laptop is half the job; the other half is running it reliably somewhere else and knowing when it breaks. This module covers the tools for that: Docker to package your app, background queues for slow work, automatic testing and shipping on every change, and monitoring. Job ads list these as “Docker, CI/CD, cloud, observability”.",
  glossary: {
    'image': 'A frozen package of an app plus everything it needs to run. The recipe a container is made from.',
    'container': 'A running copy of an image: an isolated box running your app.',
    'dockerfile': 'A text file with step-by-step instructions for building an image.',
    'volume': 'Storage that lives outside a container, so data survives when the container is deleted or replaced.',
    'docker compose': 'A tool that starts several containers together from one file (compose.yaml).',
    'environment variable': 'A named setting passed to a program from outside its code, e.g. DATABASE_URL. Used for config and secrets.',
    'port': 'A numbered door on a computer that network traffic comes in through, e.g. 5678 for n8n.',
    'queue': 'A waiting line of jobs. Producers add jobs; workers take them off and process them.',
    'acknowledge': 'A worker telling the queue “I finished this job, you can delete it”.',
    'ci/cd': 'Continuous Integration / Continuous Delivery: robots that test your code on every change and ship it if the tests pass.',
    'vps': 'Virtual Private Server: a Linux computer you rent in a data centre, e.g. from Hetzner or DigitalOcean.',
    'reverse proxy': 'A program at the front door of your server that handles HTTPS and forwards each request to the right app.',
    'correlation id': 'One ID attached to a piece of work as it passes through every system, so you can trace it in the logs.',
    'migration': 'A versioned script that changes a database’s structure, e.g. adding a column.',
  },
  sections: [
    {
      title: 'What is Docker, and why does everyone use it?',
      minutes: 6,
      body: [
        "**The problem.** You build a Python automation on your laptop and it works. You put it on a server and it breaks: “Python 3.12 not found”, “module requests not installed”. Software depends on lots of things around it: the right language version, libraries and settings. Every computer has a slightly different mix. Developers call this “it works on my machine”.",
        "**The idea.** Docker packs your app **together with everything it needs** into one sealed box, a [[container]]. That box runs the same way on your laptop, a colleague’s laptop or a cloud server.",
        "**The analogy.** Shipping containers. Ships used to be loaded with loose cargo of every shape, which was slow and things broke. Then came the standard steel box: whatever is inside, every crane, ship and truck handles it the same way. Docker does that for software.",
        "Three words you need:",
        "- [[Image]]: the recipe. A frozen package of your app plus everything it needs.\n- [[Container]]: the cake. A running copy made from the image. One recipe can make many cakes.\n- [[Dockerfile]]: the text file where you write the recipe.",
        "To use Docker, install **Docker Desktop** (docker.com) and keep it open; it runs Docker’s engine in the background. Then, in your project folder, `docker build -t my-bot .` turns your Dockerfile into an image: `-t my-bot` names (*tags*) the image “my-bot”, and the `.` means “use this folder”, where the Dockerfile and your code are. `docker run my-bot` starts a container from it.",
        "**The catch.** Containers are disposable. When you delete or update one, anything saved *inside* it is gone. A [[volume]] is a folder that lives *outside* the container, so data survives. This is the most common way people lose their self-hosted n8n workflows.",
      ],
      example: {
        caption: 'A Dockerfile, line by line',
        code: '# start from a box that already has Python\nFROM python:3.12-slim\n# work inside a folder called /app\nWORKDIR /app\n# copy the list of libraries in, then install them\nCOPY requirements.txt .\nRUN pip install -r requirements.txt\n# copy the rest of my code in\nCOPY . .\n# what to run when the box starts\nCMD ["python", "main.py"]',
      },
      interview: "Docker gives me a reproducible runtime: the image pins the OS, language version and dependencies, so the same artifact runs in dev, CI and production. Containers are ephemeral, so anything stateful, like the database or n8n’s data folder, goes on a volume or an external service.",
      check: [
        {
          id: 'm6-s0-1', kind: 'choice',
          prompt: 'What is the difference between an **image** and a **container**?',
          options: [
            { text: 'The image is the packaged template; a container is a running copy made from it', why: 'Right. You build an image once, and one image can start many containers.' },
            { text: 'The container is the packaged template; the image is the running copy of it', why: 'Reversed: you build an image, then run containers from it.' },
            { text: 'They’re the same thing: “container” is just the newer name Docker uses for an image', why: 'They’re related but different: the template versus a running instance of it.' },
            { text: 'An image holds only your code; the container adds the OS and libraries when it starts', why: 'The image already includes the OS layer and libraries; the container just runs it.' },
        ],
          answer: 0,
          explain: 'Recipe (image) → cake (container). You build an image once and run it anywhere.',
        },
        {
          id: 'm6-s0-2', kind: 'choice',
          prompt: 'You update your self-hosted n8n container to a new version, and all your workflows have vanished. What was missing?',
          options: [
            { text: 'A volume, so n8n’s data folder lived outside the container', why: 'Yes. Without a volume, the data lived inside the old container and was deleted with it.' },
            { text: 'A pinned image tag, so the new version could read the old data format', why: 'Pinning versions avoids surprise upgrades, but the data still lived inside the deleted container.' },
            { text: 'A saved copy of the Dockerfile, so the old container could be rebuilt', why: 'Rebuilding from a Dockerfile gives a fresh, empty container; Dockerfiles don’t hold data.' },
            { text: 'A restart policy, so the old container came back instead of being replaced', why: 'Restart policies restart after crashes; an update replaces the container regardless.' },
        ],
          answer: 0,
          explain: 'Rule: containers are disposable, so anything you care about keeping goes on a volume or in a database outside the container.',
        },
      ],
    },
    {
      title: 'Running several pieces together: Docker Compose',
      minutes: 7,
      body: [
        "Real automations are rarely one program. A typical setup is n8n, plus a Postgres database to store its data, plus maybe your own Python service. Starting each with a long `docker run` command gets messy fast.",
        "[[Docker Compose]] lets you describe all the pieces in one file, `compose.yaml`, and start everything with **one command**: `docker compose up -d`. The `-d` means “run in the background”.",
        "Things to notice in the example below:",
        "- **Services talk to each other by name.** n8n reaches the database at host `postgres`, not `localhost`. Inside a container, `localhost` means *that container itself*.\n- **Ports** (`\"5678:5678\"`) open a door from your computer into the container, written as *your-computer:container*. That’s how your browser reaches n8n.\n- **Volumes** keep the data safe when containers are replaced. They’re written `name:/folder-inside-container`: `db_data:/var/lib/postgresql/data` keeps Postgres’s data folder in a volume called `db_data`.\n- **[[Environment variable|Environment variables]]** pass in settings and passwords without hard-coding them. `${DB_PASSWORD}` is filled in from a `.env` file next to `compose.yaml` containing a line like `DB_PASSWORD=pick-something`. Never commit that file to GitHub.\n- `depends_on` starts `postgres` before `n8n`.\n- `restart: unless-stopped` brings a container back automatically if it crashes or the server reboots.",
        "Everyday commands: `docker compose up -d` (start), `docker compose logs -f n8n` (watch a service’s logs), `docker compose down` (stop). Careful: `docker compose down -v` also **deletes the volumes**, and with them your data.",
      ],
      example: {
        caption: 'compose.yaml: n8n with a Postgres database',
        code: 'services:\n  postgres:\n    image: postgres:16\n    environment:\n      POSTGRES_USER: n8n\n      # read from the .env file\n      POSTGRES_PASSWORD: ${DB_PASSWORD}\n      POSTGRES_DB: n8n\n    volumes:\n      - db_data:/var/lib/postgresql/data\n    restart: unless-stopped\n\n  n8n:\n    image: docker.n8n.io/n8nio/n8n\n    ports:\n      - "5678:5678"\n    environment:\n      DB_TYPE: postgresdb\n      # the service name, not localhost\n      DB_POSTGRESDB_HOST: postgres\n      DB_POSTGRESDB_USER: n8n\n      DB_POSTGRESDB_PASSWORD: ${DB_PASSWORD}\n    volumes:\n      - n8n_data:/home/node/.n8n\n    depends_on:\n      - postgres\n    restart: unless-stopped\n\nvolumes:\n  db_data:\n  n8n_data:',
      },
      interview: "I define the stack declaratively in Compose: each service with its image, config from environment variables, named volumes for state, restart policies and health checks. Services discover each other by service name on the Compose network, and secrets come from an env file or secret store that never goes into Git.",
      check: [
        {
          id: 'm6-s1-1', kind: 'choice',
          prompt: 'Your Python container can’t connect to Postgres at `localhost:5432`, even though both are in the same compose file. Why?',
          options: [
            { text: 'Inside a container, localhost is that container itself; use the service name instead', why: 'Exactly. Each container has its own localhost, so use `postgres`, the service name.' },
            { text: 'Postgres only listens on its own localhost, so it needs listen_addresses set to *', why: 'The official Postgres image already listens on all interfaces; the problem is the address your app uses.' },
            { text: 'Port 5432 isn’t published under ports, so other containers aren’t allowed to reach it', why: 'Publishing ports only matters for your host; containers on the same network reach each other without it.' },
            { text: 'The two services need network_mode: host before they can see each other at all', why: 'Compose already puts services on a shared network; host mode is unnecessary and hides the real issue.' },
        ],
          answer: 0,
          explain: 'This is one of the most common Docker mistakes. Services on the same Compose network reach each other by service name.',
        },
        {
          id: 'm6-s1-2', kind: 'choice',
          prompt: 'Which command stops your stack **and deletes your data**?',
          options: [
            { text: '`docker compose down -v`', why: 'Yes. The -v flag removes the named volumes too, and your data with them.' },
            { text: '`docker compose down --rmi all`', why: 'This also removes the images, but named volumes (your data) are kept.' },
            { text: '`docker compose rm -f`', why: 'This removes stopped containers without asking, but volumes are kept.' },
            { text: '`docker compose stop`', why: 'This only stops the containers; they and their volumes stay.' },
        ],
          answer: 0,
          explain: 'Know this one before you need it. Losing a production volume is a very bad day.',
        },
      ],
    },
    {
      title: 'Queues and workers: doing slow work in the background',
      minutes: 6,
      body: [
        "Some jobs take a while: calling an LLM, enriching 500 leads, generating a PDF. If a webhook waits for all that before replying, it times out. The fix is a [[queue]], a waiting line for jobs.",
        "- A **producer** adds a job to the queue (“process lead 42”) and moves on immediately.\n- A **[[worker]]** takes jobs off the queue one at a time and does the slow part.\n- When it finishes, the worker [[acknowledge|acknowledges]] the job, and the queue deletes it.",
        "Common queue tools: Redis (n8n’s queue mode uses it), RabbitMQ, AWS SQS. The idea is the same in all of them.",
        "**What happens when a worker crashes mid-job?** It never acknowledges, so after a while the queue hands the job to another worker. That’s good, because nothing is lost. But the first worker might have *already* sent the email before it crashed. So queues deliver jobs **at least once**, not exactly once, and your jobs must be safe to run twice. That’s idempotency, from the APIs & webhooks module.",
        "**Jobs that keep failing** shouldn’t retry forever. After a few attempts, move them to a [[dead-letter queue]]: a holding area where a person can inspect them, fix the cause and replay them.",
      ],
      interview: "I put slow or unreliable work behind a queue: the request path enqueues and returns, and workers process asynchronously. Delivery is at-least-once, so handlers are idempotent with stable job keys. I bound retries, route poison messages to a dead-letter queue, and alert on queue depth and age so a backlog is visible.",
      check: [
        {
          id: 'm6-s2-1', kind: 'choice',
          prompt: 'A worker sends a customer email, then crashes before acknowledging the job. What happens next?',
          options: [
            { text: 'Another worker picks up the same job and may send the email a second time', why: 'Yes. Unacknowledged jobs are redelivered, which is why handlers must be idempotent.' },
            { text: 'The job is marked failed and dropped, since the worker never reported success', why: 'Unacknowledged jobs aren’t dropped; they become visible again for redelivery.' },
            { text: 'The queue sees that the email went out and marks the job done on its behalf', why: 'The queue only knows about acknowledgements; it can’t see what the worker did.' },
            { text: 'The job waits for that same worker to restart, so it can resume where it stopped', why: 'Jobs aren’t tied to one worker; any free worker gets it, and it starts from the beginning.' },
        ],
          answer: 0,
          explain: 'At-least-once delivery + idempotent jobs = effectively once. Record “email sent for job X” before acknowledging.',
        },
        {
          id: 'm6-s2-2', kind: 'choice',
          prompt: 'A job has failed 5 times because the lead data is malformed. What should happen to it?',
          options: [
            { text: 'Move it to a dead-letter queue so someone can inspect, fix and replay it', why: 'Right. It’s visible, not lost, and it stops blocking other work.' },
            { text: 'Keep retrying with exponential backoff so it eventually goes through', why: 'Backoff helps with temporary failures; malformed data fails the same way every time.' },
            { text: 'Drop it and log the error, so it stops holding up the rest of the queue', why: 'A log line is easy to miss and the lead is gone; a dead-letter queue keeps it replayable.' },
            { text: 'Put it back at the front of the queue so it’s retried before newer jobs', why: 'It will fail again and block newer, valid jobs behind it.' },
        ],
          answer: 0,
          explain: 'Bounded retries plus a dead-letter queue is the standard pattern.',
        },
      ],
    },
    {
      title: 'CI/CD: robots that test and ship your code',
      minutes: 5,
      body: [
        "Every time you change code, you could break something. [[CI/CD]] means a robot checks every change for you.",
        "- **CI (Continuous Integration):** every time you push code to GitHub, a fresh machine installs your app, runs the tests and builds the Docker image. If anything fails, you see a red ❌ on the commit, before it reaches production.\n- **CD (Continuous Delivery/Deployment):** if everything passes, the robot ships the new version for you.",
        "On GitHub this robot is **GitHub Actions**. You add a file at `.github/workflows/ci.yml` that lists the steps. You’ve already used CD without noticing: this dashboard redeploys on Vercel every time new code is pushed to GitHub.",
        "Why employers care: it’s the difference between “I tested it on my laptop” and “every change is tested automatically, and broken code can’t reach the client”.",
      ],
      example: {
        caption: '.github/workflows/ci.yml: test and build on every push',
        code: 'name: CI\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4          # get the code\n      - uses: actions/setup-python@v5\n        with:\n          python-version: "3.12"\n      - run: pip install -r requirements.txt\n      - run: pytest                         # fail here = red ❌, nothing ships\n      - run: docker build -t my-bot .',
      },
      interview: "Every push and pull request runs CI: install, lint, tests, and a Docker build, so a broken change is caught before merge. Deployment only happens from a green main branch, and secrets come from the CI platform’s secret store, never from the repository.",
      check: [
        {
          id: 'm6-s3-1', kind: 'choice',
          prompt: 'Your teammate pushes code that breaks a test. With CI set up, what happens?',
          options: [
            { text: 'The CI run fails and is marked red, so the problem is caught before it ships', why: 'Yes. That’s the whole point of CI.' },
            { text: 'CI skips the failing test, deploys the rest and flags the test as a warning', why: 'A failing test fails the whole run; CI doesn’t quietly ship around it.' },
            { text: 'Git rejects the push, so the broken commit never reaches the repository', why: 'The commit lands; CI runs after the push and reports the failure. Branch protection can then block merging.' },
            { text: 'Nothing until release day, because CI only runs tests on the main branch', why: 'CI normally runs on every push and pull request, not just on main.' },
        ],
          answer: 0,
          explain: 'CI turns “hope it works” into “proved it works on a clean machine”.',
        },
        {
          id: 'm6-s3-2', kind: 'choice',
          prompt: 'Where should the API key your CI tests need be stored?',
          options: [
            { text: 'In GitHub’s encrypted repository secrets, read by the workflow', why: 'Right. The workflow can read it, but it never appears in the code.' },
            { text: 'In ci.yml, since workflow files are only visible to the CI runner', why: 'ci.yml is a normal file in the repo; anyone who can read the repo can read it.' },
            { text: 'In a .env file committed to the repo so CI can load it at startup', why: 'Committing .env puts the key in Git history; secrets must never be committed.' },
            { text: 'On a separate private branch, so it stays out of the main code', why: 'Branches aren’t access-controlled separately; anyone with repo access can read them.' },
        ],
          answer: 0,
          explain: 'Secrets live in the platform’s secret store and are injected as environment variables.',
        },
      ],
    },
    {
      title: 'Putting it on a server: VPS, domain and HTTPS',
      minutes: 6,
      body: [
        "To run 24/7, your Compose stack needs a computer that’s always on. The usual choice for automation work is a [[VPS]]: a Linux machine you rent in a data centre (Hetzner, DigitalOcean) for €5–20 a month. You connect to it with `ssh`, copy your compose file over, and run `docker compose up -d`, the same as on your laptop.",
        "To reach it at a nice address like `n8n.yourname.com` with the padlock (HTTPS), you need two more pieces:",
        "1. **A domain** pointing to your server’s IP address (a DNS “A record”).\n2. **A [[reverse proxy]]**: a program at the front door of your server. It receives all web traffic on the standard HTTPS port, handles the security certificate, and forwards each request to the right container. **Caddy** is the easiest: it gets free HTTPS certificates automatically.",
        "Two things that bite people with n8n behind a proxy: set n8n’s `WEBHOOK_URL` to your public address, or webhook URLs will show `localhost`. And only expose the proxy to the internet, never the database port.",
        "**Separate environments.** Keep a *staging* copy for testing changes and a *production* copy for real clients. Same code, different [[environment variable|environment variables]] (different database, different API keys).",
      ],
      example: {
        caption: 'Caddyfile: HTTPS for n8n in three lines',
        code: 'n8n.yourname.com {\n    reverse_proxy localhost:5678\n}',
      },
      interview: "I deploy the Compose stack to a VPS with a reverse proxy like Caddy or Traefik terminating TLS, only ports 80 and 443 open, and the database on the internal network only. Config differs per environment through environment variables, so staging and production run the same image.",
      check: [
        {
          id: 'm6-s4-1', kind: 'choice',
          prompt: 'What does the **reverse proxy** do in this setup?',
          options: [
            { text: 'Receives web traffic, handles HTTPS and forwards each request to the right container', why: 'Yes. It’s the front door.' },
            { text: 'Hides your server and blocks attacks, acting as the firewall in front of the containers', why: 'Some proxies add protections, but its job here is HTTPS and routing; you still need a firewall.' },
            { text: 'Spreads load by sending each request to a different copy of the same app', why: 'Load balancing is possible, but here it routes by domain to different apps and handles HTTPS.' },
            { text: 'Lets your containers make outbound API calls through one shared address', why: 'That’s a forward proxy, for outgoing traffic. A reverse proxy handles incoming traffic.' },
        ],
          answer: 0,
          explain: 'Client → reverse proxy (HTTPS) → container. One front door, many apps behind it.',
        },
        {
          id: 'm6-s4-2', kind: 'choice',
          prompt: 'Your n8n is live at `https://n8n.yourname.com`, but webhook nodes show URLs starting with `http://localhost:5678`. What’s the fix?',
          options: [
            { text: 'Set n8n’s WEBHOOK_URL environment variable to the public https address', why: 'Right. n8n can’t know its public address behind a proxy unless you tell it.' },
            { text: 'Open port 5678 to the internet so the localhost URLs become reachable', why: 'localhost still points at the caller’s own machine, and this bypasses your proxy and HTTPS.' },
            { text: 'Add the domain to the reverse proxy so it rewrites the URLs n8n displays', why: 'The proxy forwards traffic; it doesn’t change the URLs n8n generates in its own editor.' },
            { text: 'Change N8N_PORT to 443 so n8n generates URLs on the standard HTTPS port', why: 'That changes the port n8n listens on, not the public hostname it reports.' },
        ],
          answer: 0,
          explain: 'Apps behind a proxy often need to be told their public URL.',
        },
      ],
    },
    {
      title: 'Knowing when it breaks: logs, metrics and alerts',
      minutes: 6,
      body: [
        "If an automation fails at 3am and nobody notices, the client finds out first. Monitoring means *you* find out first. It has three parts:",
        "- **Logs**: a diary of individual events. “Lead 42 failed: HubSpot returned 429.” Use them to answer *what happened to this one thing?*\n- **Metrics**: numbers over time. Success rate, failures per hour, how long jobs take, how many jobs are waiting in the queue. Use them to answer *is the system healthy overall?*\n- **Alerts**: a message (Slack, email) when a metric crosses a line. Every alert needs an owner and a clear next action, or people learn to ignore them.",
        "**Correlation IDs.** Give each piece of work one ID when it arrives, and include it in every log line across n8n, your service and the database. Then one search finds the whole story of that lead. That ID is a [[correlation id]].",
        "**The sneakiest failure is silence.** If your Monday report workflow never starts at all, there’s no error to alert on. Fix it with a check that expects a “success” signal by a certain time, and alerts if it doesn’t arrive. Free services like healthchecks.io do exactly this.",
      ],
      interview: "I log in structured JSON with a correlation ID that follows each event across services. I track a few metrics that reflect what the user cares about: success rate, end-to-end latency, queue depth and age, and failed jobs awaiting action. Alerts have owners and runbooks, and scheduled jobs get a heartbeat check, because a job that never runs produces no error.",
      check: [
        {
          id: 'm6-s5-1', kind: 'choice',
          prompt: 'A scheduled workflow silently stopped running a week ago. No error alert fired. What would have caught it?',
          options: [
            { text: 'A check that expects a success signal on schedule and alerts when it’s missing', why: 'Yes. You can only alert on missing success, because there’s no error to catch.' },
            { text: 'An alert on any error in the workflow’s execution logs, sent to Slack', why: 'A workflow that never runs produces no errors, so the alert never fires.' },
            { text: 'Retries on the schedule trigger, so a missed run is repeated automatically', why: 'Retries act on failed runs; there was no run to retry, and nobody is told.' },
            { text: 'An uptime monitor that pings the n8n server every minute and alerts if it’s down', why: 'The server was up; only the schedule stopped. Uptime doesn’t prove the job ran.' },
        ],
          answer: 0,
          explain: 'This “dead man’s switch” pattern is a favourite interview topic.',
        },
        {
          id: 'm6-s5-2', kind: 'choice',
          prompt: 'A client says lead `L-981` never reached their CRM. What lets you find what happened fastest?',
          options: [
            { text: 'Searching the logs for that lead’s correlation ID across every system', why: 'Yes. One search shows its whole journey and where it stopped.' },
            { text: 'Opening the error tracker, since a lost lead must have thrown an exception', why: 'Leads are often dropped silently (a filter, a skipped branch) with no exception at all.' },
            { text: 'Checking the failed-jobs metric around the time the lead came in', why: 'Metrics show totals, not which lead, and this lead may not have failed loudly.' },
            { text: 'Replaying the original webhook to watch where the lead stops this time', why: 'It may create duplicates and may not reproduce the original problem.' },
        ],
          answer: 0,
          explain: 'Logs answer “what happened to this one thing?”; metrics answer “is everything healthy?”.',
        },
      ],
    },
    {
      title: 'Backups, safe updates and incidents',
      minutes: 6,
      body: [
        "**Backups.** Schedule a database backup (for Postgres, `pg_dump`) and copy it *off* the server. Then actually **restore it** into a blank environment at least once. A backup you’ve never restored is a hope, not a backup.",
        "For n8n specifically, also back up the **encryption key** (`N8N_ENCRYPTION_KEY`). n8n encrypts saved credentials with it; restore the database without the key and every credential is unreadable.",
        "**Safe database changes.** Changing a table’s structure is done with a [[migration]]: a small versioned script, kept in Git, run as part of the release. Make changes backward-compatible: add the new column first, ship the code that uses it, and remove the old column in a later release. Then if the new version misbehaves, you can **roll back** to the old code and it still works with the database.",
        "**Incidents.** When something does break, fix it first, then write a short incident report: what happened, who was affected, how you noticed, the root cause, the fix, and what will prevent it next time. Keep it blameless; the point is to fix the system, not blame a person. A real incident report in your portfolio is strong evidence of production experience.",
      ],
      interview: "Backups are automated, stored off-site, and restore-tested on a schedule; for n8n that includes the encryption key. Schema changes go through versioned migrations using expand-then-contract, so the previous release still runs and rollback stays possible. After incidents I write a blameless report with detection, impact, root cause and prevention.",
      check: [
        {
          id: 'm6-s6-1', kind: 'choice',
          prompt: 'You restore your n8n database backup onto a new server. Workflows appear, but every credential fails to decrypt. What was missing?',
          options: [
            { text: 'The original N8N_ENCRYPTION_KEY from the old server', why: 'Yes. Credentials are encrypted with it, and without it they’re unreadable.' },
            { text: 'A credentials export, since database dumps skip encrypted fields', why: 'The encrypted credentials are in the dump; they just can’t be decrypted without the key.' },
            { text: 'The same Postgres version, so encrypted columns read back correctly', why: 'The data restored fine (the workflows appear); it’s the decryption that fails.' },
            { text: 'The old server’s HTTPS certificate, which n8n uses for encryption', why: 'TLS certificates protect traffic in transit; n8n encrypts credentials with its own key.' },
        ],
          answer: 0,
          explain: 'Back up the key alongside the data, stored securely. This is why restore tests matter.',
        },
        {
          id: 'm6-s6-2', kind: 'order',
          prompt: 'Order the steps for safely **renaming** a database column without breaking the running app.',
          items: ['Add the new column and copy the data into it', 'Deploy code that uses the new column', 'Confirm everything works', 'Remove the old column in a later release'],
          explain: 'Expand, then contract. At every step the running code still matches the database, so you can roll back.',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'm6-q1', kind: 'choice',
      prompt: 'A colleague says “it works on my machine” but it fails on the server. How does Docker help?',
      options: [
        { text: 'The image packages the app with its exact dependencies, so it runs the same everywhere', why: 'Yes. Same image, same behaviour.' },
        { text: 'Docker gives the app a full virtual machine that copies the server’s operating system', why: 'Containers share the host’s kernel and don’t copy the server; the point is packaged dependencies.' },
        { text: 'Docker copies the libraries installed on your laptop onto the server when you deploy', why: 'Docker builds from the Dockerfile, not from your laptop’s setup; that’s what makes it reproducible.' },
        { text: 'Docker detects missing dependencies at runtime and installs them on the server for you', why: 'Dependencies are installed when the image is built, not discovered on the server.' },
      ],
      answer: 0,
      explain: 'Reproducibility is Docker’s core value: build once, run anywhere.',
    },
    {
      id: 'm6-q2', kind: 'choice',
      prompt: 'What does `"8080:5678"` in a compose file’s `ports` mean?',
      options: [
        { text: 'Port 8080 on your computer forwards to port 5678 inside the container', why: 'Yes. Your computer’s port comes first, then the container’s.' },
        { text: 'Port 5678 on your computer forwards to port 8080 inside the container', why: 'It’s the other way round: host port first, container port second.' },
        { text: 'The container listens on both 8080 and 5678, and either one reaches the app', why: 'It’s a one-way mapping from one host port to one container port.' },
        { text: 'Other containers must use port 8080 to reach the app instead of 5678', why: 'Other containers use the container port (5678) and the service name; the mapping is for your computer.' },
      ],
      answer: 0,
      explain: 'So you’d open http://localhost:8080 in your browser to reach the app listening on 5678 inside.',
    },
    {
      id: 'm6-q3', kind: 'choice',
      prompt: 'Read the log. What’s wrong?',
      code: 'api-1  | Connecting to postgresql://app@localhost:5432/app\napi-1  | ERROR: connection refused (localhost:5432)\ndb-1   | database system is ready to accept connections',
      options: [
        { text: 'The API connects to localhost instead of the database service name, db', why: 'Yes. The database is running; the API is looking in the wrong place.' },
        { text: 'Postgres hasn’t published port 5432, so other containers can’t reach it', why: 'Published ports are for your computer; other containers reach db on 5432 without them.' },
        { text: 'The password is wrong, so Postgres refused the connection from the API', why: 'A wrong password gives an authentication error, not “connection refused”.' },
        { text: 'The database is still starting and isn’t accepting connections yet', why: 'The db log says it’s ready, and localhost would be the wrong address anyway.' },
      ],
      answer: 0,
      explain: 'Change the host to `db`, the service name from the compose file.',
    },
    {
      id: 'm6-q4', kind: 'choice',
      prompt: 'Where should the database password for your compose stack live?',
      options: [
        { text: 'In a .env file on the server that’s listed in .gitignore', why: 'Yes. Compose reads it; Git never sees it.' },
        { text: 'In the environment section of compose.yaml, committed with the stack', why: 'Then anyone with repo access has your password.' },
        { text: 'In the Dockerfile as an ENV line, so the image always has it', why: 'It gets baked into the image, readable by anyone who has the image.' },
        { text: 'In .env.example, committed so teammates know where to find it', why: 'That file is for placeholder values; a real password there ends up in Git.' },
      ],
      answer: 0,
      explain: 'Config and secrets come from the environment, never from the code or image.',
    },
    {
      id: 'm6-q5', kind: 'choice',
      prompt: 'Your webhook handler calls an LLM (20 seconds) before replying. Which design fixes timeouts?',
      options: [
        { text: 'Save the event, queue a job, reply right away, and let a worker call the LLM', why: 'Yes. Fast reply, slow work in the background.' },
        { text: 'Switch to a smaller, faster model so the reply fits inside the timeout', why: 'It helps on average, but slow responses and spikes will still time out.' },
        { text: 'Raise your server’s request timeout so the handler has time to finish', why: 'The timeout belongs to the sender; your server waiting longer doesn’t stop them giving up.' },
        { text: 'Retry the LLM call inside the handler whenever it takes too long', why: 'That makes the handler even slower.' },
      ],
      answer: 0,
      explain: 'Separate intake from processing. This pattern appears in nearly every automation system design interview.',
    },
    {
      id: 'm6-q6', kind: 'choice',
      prompt: 'Queues usually deliver “at least once”. What must be true of your worker’s job code?',
      options: [
        { text: 'Running the same job twice must not cause a duplicate effect', why: 'Yes. Idempotent jobs make redelivery harmless.' },
        { text: 'It must acknowledge the job first, before doing any of the work', why: 'Acking first means a crash loses the job entirely; that trades duplicates for lost work.' },
        { text: 'It must finish quickly, so the queue never hands it to another worker', why: 'Speed reduces timeouts, but crashes still cause redelivery.' },
        { text: 'It must run on a single worker, so two copies can’t process it', why: 'One worker can still crash and receive the same job again.' },
      ],
      answer: 0,
      explain: 'At-least-once delivery + idempotent jobs = effectively-once results.',
    },
    {
      id: 'm6-q7', kind: 'choice',
      prompt: 'Which change belongs in CI?',
      options: [
        { text: 'Run the tests and build the Docker image on every push', why: 'Yes. Catch problems before they reach production.' },
        { text: 'Run the tests once a week on the lead developer’s laptop', why: 'CI runs automatically on a clean machine for every change, not weekly on one laptop.' },
        { text: 'Deploy every push to production first, then run the tests', why: 'Tests must run before shipping; otherwise broken code reaches users first.' },
        { text: 'Copy the production database into the repo on every push', why: 'Backups don’t belong in Git, and it isn’t a quality check.' },
      ],
      answer: 0,
      explain: 'CI = automated checks on every change. CD = automated shipping when the checks pass.',
    },
    {
      id: 'm6-q8', kind: 'choice',
      prompt: 'On your VPS, which ports should be open to the internet?',
      options: [
        { text: '80 and 443 for the reverse proxy, plus SSH, and nothing else', why: 'Yes. One front door; everything else stays internal.' },
        { text: '80, 443 and 5678, so webhooks can reach n8n directly', why: 'Go through the proxy for HTTPS instead of exposing n8n’s own port.' },
        { text: '80, 443 and 5432, so you can query the database from home', why: 'An internet-facing database is a common cause of breaches. Use an SSH tunnel instead.' },
        { text: 'Only 443, because HTTPS covers everything you’ll ever need', why: 'Port 80 is needed for redirects and certificate issuance, and SSH to manage the server.' },
      ],
      answer: 0,
      explain: 'Smallest possible attack surface: the proxy faces the world; services stay on the internal network.',
    },
    {
      id: 'm6-q9', kind: 'choice',
      prompt: 'Which is a **metric** rather than a log?',
      options: [
        { text: 'Failed jobs per hour, charted over the last week', why: 'Yes. A number tracked over time.' },
        { text: '“Lead 42 failed: HubSpot returned 429” at 2:14pm', why: 'That’s one event: a log line.' },
        { text: 'A stack trace from the 3am crash, with line numbers', why: 'That’s detail about one event: a log.' },
        { text: 'The error tracker’s entry for one failed webhook', why: 'That’s the record of a single event, not a number over time.' },
      ],
      answer: 0,
      explain: 'Metrics show patterns (“failures jumped at 2pm”); logs explain individual cases.',
    },
    {
      id: 'm6-q10', kind: 'choice',
      prompt: 'Your team has nightly backups but has never restored one. What’s the risk?',
      options: [
        { text: 'You don’t know whether the backups work until you need one', why: 'Yes. Untested backups often turn out to be incomplete or unusable.' },
        { text: 'None, as long as the backup job reports success each night', why: 'A successful job can still produce an incomplete dump or miss the encryption key; only a restore proves it.' },
        { text: 'Old backups pile up and fill the disk, since restores clear them', why: 'Restoring doesn’t delete backups; retention is a separate setting.' },
        { text: 'Restoring is the risk, because it overwrites the production data', why: 'You restore into a separate, blank environment, not over production.' },
      ],
      answer: 0,
      explain: '“A backup you haven’t restored is a hope.” Schedule restore tests.',
    },
    {
      id: 'm6-q11', kind: 'choice',
      prompt: 'You need to rename the column `phone` to `phone_number`. What’s the safest approach?',
      options: [
        { text: 'Add phone_number, copy data, deploy code using it, drop phone later', why: 'Yes. Expand then contract, so rollback is always possible.' },
        { text: 'Rename the column in a migration, then deploy the new code right after', why: 'Between the two steps the running code still asks for phone and breaks, and rollback breaks too.' },
        { text: 'Deploy code that uses phone_number first, then rename the column', why: 'The new code fails until the rename runs.' },
        { text: 'Rename it by hand in production during a quiet hour, then deploy', why: 'Untracked and unrepeatable, and the running code still breaks in between.' },
      ],
      answer: 0,
      explain: 'Migrations in Git + backward-compatible steps = safe releases you can undo.',
    },
    {
      id: 'm6-q12', kind: 'order',
      prompt: 'Put a short incident report in the usual order.',
      items: ['What happened and who was affected', 'How it was detected', 'Root cause', 'Fix applied', 'What will prevent it next time'],
      explain: 'Impact → detection → cause → fix → prevention. Keep it blameless and specific.',
    },
  ],
  tasks: [
    { device: 'phone', plain: 'Learn the Docker basics: image, container, Dockerfile, Compose, volumes, ports and restart policies.', done: 'You can explain each one in a sentence, and you’ve passed the checks for Lessons 1 and 2.' },
    { device: 'computer', plain: 'Run the same app with different settings for “dev” and “production”, without changing any code.', done: 'Two .env files (with fake values) and a note showing the app uses a different database in each.' },
    { device: 'computer', plain: 'Write a compose.yaml that starts your API, Postgres, Redis, a worker and n8n together with one command.', done: '`docker compose up -d` starts everything, and data survives `docker compose down` followed by `up` again.' },
    { device: 'phone', plain: 'Learn how queues work: producers, workers, acknowledgement, retries and dead-letter queues.', done: 'You can explain what happens when a worker crashes mid-job, and you’ve passed the Lesson 3 check.' },
    { device: 'computer', plain: 'Add a correlation ID that travels from the webhook through n8n and your service into the database, and appears in every log line.', done: 'One search for a single ID shows that event’s full journey.' },
    { device: 'phone', plain: 'Learn which numbers show whether a system is healthy: error rate, latency, throughput, queue depth and failed jobs.', done: 'You can say which metric you’d alert on for a lead-processing system, and why.' },
    { device: 'computer', plain: 'Set up error tracking: either a tool (Sentry, Better Stack) or a simple errors table you can query.', done: 'Cause a failure on purpose and show it appearing with useful details.' },
    { device: 'computer', plain: 'Add a GitHub Actions workflow that installs, tests and builds your Docker image on every push.', done: 'A screenshot of a red ❌ run for a broken test, then a green ✅ after the fix.' },
    { device: 'computer', plain: 'Deploy your stack to a VPS behind Caddy (or another reverse proxy) with HTTPS on your own domain.', done: 'Your app loads at https://your-domain with a padlock, and only ports 80, 443 and SSH are open.' },
    { device: 'computer', plain: 'Back up your database (and n8n encryption key), then restore it into a fresh, empty environment.', done: 'Written restore steps, plus proof that the restored copy works.' },
    { device: 'phone', plain: 'Learn how to change a database safely: migrations, backward-compatible changes and rollback.', done: 'You can explain “expand then contract” and order the steps in the Lesson 7 check.' },
    { device: 'computer', plain: 'Break something on purpose (stop the database, fill a queue), fix it, and write a one-page incident report.', done: 'The report covers what happened, impact, detection, root cause, fix and prevention.' },
  ],
};
