import type { Lesson } from './types';

export const m6: Lesson = {
  intro: "Building an automation that works on your laptop is half the job. The other half is getting it to run somewhere else, reliably, and knowing when it breaks. This module covers the tools for that: Docker to package it, queues to run slow work in the background, CI/CD to ship it safely, and monitoring to spot problems before your client does. Job ads list these as “Docker, CI/CD, cloud, observability”.",
  glossary: {
    'image': 'A frozen package of an app plus everything it needs to run. The recipe a container is made from.',
    'container': 'A running copy of an image: an isolated box running your app.',
    'dockerfile': 'A text file with step-by-step instructions for building an image.',
    'volume': 'Storage that lives outside a container, so data survives when the container is deleted or replaced.',
    'docker compose': 'A tool that starts several containers together from one file (compose.yaml).',
    'environment variable': 'A named setting passed to a program from outside its code, e.g. DATABASE_URL. Used for config and secrets.',
    'port': 'A numbered door on a computer that network traffic comes in through, e.g. 5678 for n8n.',
    'queue': 'A waiting line of jobs. Producers add jobs; workers take them off and process them.',
    'acknowledge': 'A worker telling the queue “I finished this job, you can delete it”.',
    'ci/cd': 'Continuous Integration / Continuous Delivery: robots that test your code on every change and ship it if the tests pass.',
    'vps': 'Virtual Private Server: a Linux computer you rent in a data centre, e.g. from Hetzner or DigitalOcean.',
    'reverse proxy': 'A program at the front door of your server that handles HTTPS and forwards each request to the right app.',
    'correlation id': 'One ID attached to a piece of work as it passes through every system, so you can trace it in the logs.',
    'migration': 'A versioned script that changes a database’s structure, e.g. adding a column.',
  },
  sections: [
    {
      title: 'What is Docker, and why does everyone use it?',
      minutes: 6,
      body: [
        "**The problem.** You build a Python automation on your laptop and it works. You put it on a server and it breaks: “Python 3.12 not found”, “module requests not installed”. Software depends on lots of things around it: the right language version, libraries and settings. Every computer has a slightly different mix. Developers call this “it works on my machine”.",
        "**The idea.** Docker packs your app **together with everything it needs** into one sealed box, a [[container]]. That box runs the same way on your laptop, a colleague’s laptop or a cloud server.",
        "**The analogy.** Shipping containers. Ships used to be loaded with loose cargo of every shape, which was slow and things broke. Then came the standard steel box: whatever is inside, every crane, ship and truck handles it the same way. Docker does that for software.",
        "Three words you need:",
        "- [[Image]]: the recipe. A frozen package of your app plus everything it needs.\n- [[Container]]: the cake. A running copy made from the image. One recipe can make many cakes.\n- [[Dockerfile]]: the text file where you write the recipe.",
        "`docker build -t my-bot .` turns your Dockerfile into an image. `docker run my-bot` starts a container from it.",
        "**The catch.** Containers are disposable. When you delete or update one, anything saved *inside* it is gone. A [[volume]] is a folder that lives *outside* the container, so data survives. This is the most common way people lose their self-hosted n8n workflows.",
      ],
      example: {
        caption: 'A Dockerfile, line by line',
        code: 'FROM python:3.12-slim                 # start from a box that already has Python\nWORKDIR /app                          # work inside a folder called /app\nCOPY requirements.txt .\nRUN pip install -r requirements.txt   # install libraries inside the box\nCOPY . .                              # copy the rest of my code in\nCMD ["python", "main.py"]             # what to run when the box starts',
      },
      interview: "Docker gives me a reproducible runtime: the image pins the OS, language version and dependencies, so the same artifact runs in dev, CI and production. Containers are ephemeral, so anything stateful, like the database or n8n’s data folder, goes on a volume or an external service.",
      check: [
        {
          id: 'm6-s0-1', kind: 'choice',
          prompt: 'What is the difference between an **image** and a **container**?',
          options: [
            { text: 'The image is the packaged recipe; a container is a running copy of it', why: 'Right. One image can start many containers.' },
            { text: 'They’re two names for the same thing', why: 'They’re related but different: the template versus the running instance.' },
            { text: 'A container is the recipe; the image is what runs', why: 'It’s the other way round.' },
            { text: 'An image is a screenshot of a running app', why: 'An image is a package of files and settings, not a picture.' },
          ],
          answer: 0,
          explain: 'Recipe (image) → cake (container). You build an image once and run it anywhere.',
        },
        {
          id: 'm6-s0-2', kind: 'choice',
          prompt: 'You update your self-hosted n8n container to a new version, and all your workflows have vanished. What was missing?',
          options: [
            { text: 'A volume, so n8n’s data was stored outside the container', why: 'Yes. Without a volume, the data lived inside the old container and was deleted with it.' },
            { text: 'A newer Dockerfile', why: 'The Dockerfile only describes how to build the app; it doesn’t store your data.' },
            { text: 'More memory for the container', why: 'Memory doesn’t affect whether data survives a replacement.' },
            { text: 'A faster internet connection', why: 'This is about where data is stored, not the network.' },
          ],
          answer: 0,
          explain: 'Rule: containers are disposable, so anything you care about keeping goes on a volume or in a database outside the container.',
        },
      ],
    },
    {
      title: 'Running several pieces together: Docker Compose',
      minutes: 7,
      body: [
        "Real automations are rarely one program. A typical setup is n8n, plus a Postgres database to store its data, plus maybe your own Python service. Starting each with a long `docker run` command gets messy fast.",
        "[[Docker Compose]] lets you describe all the pieces in one file, `compose.yaml`, and start everything with **one command**: `docker compose up -d`. The `-d` means “run in the background”.",
        "Things to notice in the example below:",
        "- **Services talk to each other by name.** n8n reaches the database at host `postgres`, not `localhost`. Inside a container, `localhost` means *that container itself*.\n- **Ports** (`\"5678:5678\"`) open a door from your computer into the container, written as *your-computer:container*. That’s how your browser reaches n8n.\n- **Volumes** keep the data safe when containers are replaced.\n- **[[Environment variable|Environment variables]]** pass in settings and passwords without hard-coding them. Keep real passwords in a `.env` file that you never commit to GitHub.\n- `restart: unless-stopped` brings a container back automatically if it crashes or the server reboots.",
        "Everyday commands: `docker compose up -d` (start), `docker compose logs -f n8n` (watch a service’s logs), `docker compose down` (stop). Careful: `docker compose down -v` also **deletes the volumes**, and with them your data.",
      ],
      example: {
        caption: 'compose.yaml: n8n with a Postgres database',
        code: 'services:\n  postgres:\n    image: postgres:16\n    environment:\n      POSTGRES_USER: n8n\n      POSTGRES_PASSWORD: ${DB_PASSWORD}   # read from the .env file\n      POSTGRES_DB: n8n\n    volumes:\n      - db_data:/var/lib/postgresql/data\n    restart: unless-stopped\n\n  n8n:\n    image: docker.n8n.io/n8nio/n8n\n    ports:\n      - "5678:5678"\n    environment:\n      DB_TYPE: postgresdb\n      DB_POSTGRESDB_HOST: postgres          # the service name, not localhost\n      DB_POSTGRESDB_USER: n8n\n      DB_POSTGRESDB_PASSWORD: ${DB_PASSWORD}\n    volumes:\n      - n8n_data:/home/node/.n8n\n    depends_on:\n      - postgres\n    restart: unless-stopped\n\nvolumes:\n  db_data:\n  n8n_data:',
      },
      interview: "I define the stack declaratively in Compose: each service with its image, config from environment variables, named volumes for state, restart policies and health checks. Services discover each other by service name on the Compose network, and secrets come from an env file or secret store that never goes into Git.",
      check: [
        {
          id: 'm6-s1-1', kind: 'choice',
          prompt: 'Your Python container can’t connect to Postgres at `localhost:5432`, even though both are in the same compose file. Why?',
          options: [
            { text: 'Inside a container, localhost means that container itself; use the service name `postgres`', why: 'Exactly. Each container has its own localhost.' },
            { text: 'Postgres doesn’t work in Docker', why: 'It works fine. This is an addressing problem.' },
            { text: 'Port 5432 is blocked by the firewall', why: 'Containers on the same Compose network can reach each other directly.' },
            { text: 'You need to restart your computer', why: 'Restarting won’t change what localhost means inside a container.' },
          ],
          answer: 0,
          explain: 'This is one of the most common Docker mistakes. Services on the same Compose network reach each other by service name.',
        },
        {
          id: 'm6-s1-2', kind: 'choice',
          prompt: 'Which command stops your stack **and deletes your data**?',
          options: [
            { text: '`docker compose down -v`', why: 'Yes. The -v flag removes the named volumes too.' },
            { text: '`docker compose down`', why: 'This stops and removes containers, but keeps named volumes.' },
            { text: '`docker compose logs -f`', why: 'This only shows logs.' },
            { text: '`docker compose up -d`', why: 'This starts the stack.' },
          ],
          answer: 0,
          explain: 'Know this one before you need it. Losing a production volume is a very bad day.',
        },
      ],
    },
    {
      title: 'Queues and workers: doing slow work in the background',
      minutes: 6,
      body: [
        "Some jobs take a while: calling an LLM, enriching 500 leads, generating a PDF. If a webhook waits for all that before replying, it times out. The fix is a [[queue]], a waiting line for jobs.",
        "- A **producer** adds a job to the queue (“process lead 42”) and moves on immediately.\n- A **[[worker]]** takes jobs off the queue one at a time and does the slow part.\n- When it finishes, the worker [[acknowledge|acknowledges]] the job, and the queue deletes it.",
        "Common queue tools: Redis (n8n’s queue mode uses it), RabbitMQ, AWS SQS. The idea is the same in all of them.",
        "**What happens when a worker crashes mid-job?** It never acknowledges, so after a while the queue hands the job to another worker. That’s good, because nothing is lost. But the first worker might have *already* sent the email before it crashed. So queues deliver jobs **at least once**, not exactly once, and your jobs must be safe to run twice. That’s idempotency, from the APIs module.",
        "**Jobs that keep failing** shouldn’t retry forever. After a few attempts, move them to a [[dead-letter queue]]: a holding area where a person can inspect them, fix the cause and replay them.",
      ],
      interview: "I put slow or unreliable work behind a queue: the request path enqueues and returns, and workers process asynchronously. Delivery is at-least-once, so handlers are idempotent with stable job keys. I bound retries, route poison messages to a dead-letter queue, and alert on queue depth and age so a backlog is visible.",
      check: [
        {
          id: 'm6-s2-1', kind: 'choice',
          prompt: 'A worker sends a customer email, then crashes before acknowledging the job. What happens next?',
          options: [
            { text: 'Another worker gets the same job and may send the email again', why: 'Yes. Unacknowledged jobs are redelivered, which is why handlers must be idempotent.' },
            { text: 'The job is lost forever', why: 'Unacknowledged jobs are kept and redelivered; that’s the point of acknowledgement.' },
            { text: 'The queue knows the email was sent and skips it', why: 'The queue only knows whether the job was acknowledged, not what the worker did.' },
            { text: 'The customer’s email provider blocks duplicates', why: 'You can’t rely on that. Prevent duplicates in your own code.' },
          ],
          answer: 0,
          explain: 'At-least-once delivery + idempotent jobs = effectively once. Record “email sent for job X” before acknowledging.',
        },
        {
          id: 'm6-s2-2', kind: 'choice',
          prompt: 'A job has failed 5 times because the lead data is malformed. What should happen to it?',
          options: [
            { text: 'Move it to a dead-letter queue for someone to inspect and replay', why: 'Right. It’s visible, not lost, and it stops blocking other work.' },
            { text: 'Keep retrying until it works', why: 'Malformed data won’t fix itself. You’d retry forever.' },
            { text: 'Delete it', why: 'Silently losing a lead is worse than failing loudly.' },
            { text: 'Restart the server', why: 'The problem is the data, not the server.' },
          ],
          answer: 0,
          explain: 'Bounded retries plus a dead-letter queue is the standard pattern.',
        },
      ],
    },
    {
      title: 'CI/CD: robots that test and ship your code',
      minutes: 5,
      body: [
        "Every time you change code, you could break something. [[CI/CD]] means a robot checks every change for you.",
        "- **CI (Continuous Integration):** every time you push code to GitHub, a fresh machine installs your app, runs the tests and builds the Docker image. If anything fails, you see a red ❌ on the commit, before it reaches production.\n- **CD (Continuous Delivery/Deployment):** if everything passes, the robot ships the new version for you.",
        "On GitHub this robot is **GitHub Actions**. You add a file at `.github/workflows/ci.yml` that lists the steps. You’ve already used CD without noticing: this dashboard redeploys on Vercel every time new code is pushed to GitHub.",
        "Why employers care: it’s the difference between “I tested it on my laptop” and “every change is tested automatically, and broken code can’t reach the client”.",
      ],
      example: {
        caption: '.github/workflows/ci.yml: test and build on every push',
        code: 'name: CI\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4          # get the code\n      - uses: actions/setup-python@v5\n        with:\n          python-version: "3.12"\n      - run: pip install -r requirements.txt\n      - run: pytest                         # fail here = red ❌, nothing ships\n      - run: docker build -t my-bot .',
      },
      interview: "Every push and pull request runs CI: install, lint, tests, and a Docker build, so a broken change is caught before merge. Deployment only happens from a green main branch, and secrets come from the CI platform’s secret store, never from the repository.",
      check: [
        {
          id: 'm6-s3-1', kind: 'choice',
          prompt: 'Your teammate pushes code that breaks a test. With CI set up, what happens?',
          options: [
            { text: 'The CI run fails and shows a red ❌, so the change is caught before it ships', why: 'Yes. That’s the whole point of CI.' },
            { text: 'GitHub automatically fixes the test', why: 'CI reports problems; it doesn’t fix them.' },
            { text: 'Nothing, until a customer complains', why: 'That’s what happens without CI.' },
            { text: 'The repository is deleted', why: 'No. It just marks the run as failed.' },
          ],
          answer: 0,
          explain: 'CI turns “hope it works” into “proved it works on a clean machine”.',
        },
        {
          id: 'm6-s3-2', kind: 'choice',
          prompt: 'Where should the API key your CI tests need be stored?',
          options: [
            { text: 'In GitHub’s encrypted repository secrets', why: 'Right. The workflow can read it, but it never appears in the code.' },
            { text: 'Hard-coded in ci.yml', why: 'Anyone who can read the repo can read it.' },
            { text: 'In the README', why: 'Never put secrets in documentation.' },
            { text: 'In a commit message', why: 'Commit history is permanent and public on public repos.' },
          ],
          answer: 0,
          explain: 'Secrets live in the platform’s secret store and are injected as environment variables.',
        },
      ],
    },
    {
      title: 'Putting it on a server: VPS, domain and HTTPS',
      minutes: 6,
      body: [
        "To run 24/7, your Compose stack needs a computer that’s always on. The usual choice for automation work is a [[VPS]]: a Linux machine you rent in a data centre (Hetzner, DigitalOcean) for €5–20 a month. You connect to it with `ssh`, copy your compose file over, and run `docker compose up -d`, the same as on your laptop.",
        "To reach it at a nice address like `n8n.yourname.com` with the padlock (HTTPS), you need two more pieces:",
        "1. **A domain** pointing to your server’s IP address (a DNS “A record”).\n2. **A [[reverse proxy]]**: a program at the front door of your server. It receives all web traffic on the standard HTTPS port, handles the security certificate, and forwards each request to the right container. **Caddy** is the easiest: it gets free HTTPS certificates automatically.",
        "Two things that bite people with n8n behind a proxy: set n8n’s `WEBHOOK_URL` to your public address, or webhook URLs will show `localhost`. And only expose the proxy to the internet, never the database port.",
        "**Separate environments.** Keep a *staging* copy for testing changes and a *production* copy for real clients. Same code, different [[environment variable|environment variables]] (different database, different API keys).",
      ],
      example: {
        caption: 'Caddyfile: HTTPS for n8n in three lines',
        code: 'n8n.yourname.com {\n    reverse_proxy localhost:5678\n}',
      },
      interview: "I deploy the Compose stack to a VPS with a reverse proxy like Caddy or Traefik terminating TLS, only ports 80 and 443 open, and the database on the internal network only. Config differs per environment through environment variables, so staging and production run the same image.",
      check: [
        {
          id: 'm6-s4-1', kind: 'choice',
          prompt: 'What does the **reverse proxy** do in this setup?',
          options: [
            { text: 'Receives web traffic, handles HTTPS and forwards requests to the right container', why: 'Yes. It’s the front door.' },
            { text: 'Stores the database backups', why: 'Backups are a separate job.' },
            { text: 'Runs your Python code', why: 'Your containers run the code; the proxy forwards traffic to them.' },
            { text: 'Speeds up your internet', why: 'It routes traffic; it doesn’t make your connection faster.' },
          ],
          answer: 0,
          explain: 'Client → reverse proxy (HTTPS) → container. One front door, many apps behind it.',
        },
        {
          id: 'm6-s4-2', kind: 'choice',
          prompt: 'Your n8n is live at `https://n8n.yourname.com`, but webhook nodes show URLs starting with `http://localhost:5678`. What’s the fix?',
          options: [
            { text: 'Set n8n’s WEBHOOK_URL environment variable to the public address', why: 'Right. n8n can’t know its public address behind a proxy unless you tell it.' },
            { text: 'Reinstall n8n', why: 'This is configuration, not a broken install.' },
            { text: 'Open port 5678 to the internet', why: 'That bypasses your proxy and HTTPS, and is less secure.' },
            { text: 'Use a different browser', why: 'The URL is generated by n8n, not the browser.' },
          ],
          answer: 0,
          explain: 'Apps behind a proxy often need to be told their public URL.',
        },
      ],
    },
    {
      title: 'Knowing when it breaks: logs, metrics and alerts',
      minutes: 6,
      body: [
        "If an automation fails at 3am and nobody notices, the client finds out first. Monitoring means *you* find out first. It has three parts:",
        "- **Logs**: a diary of individual events. “Lead 42 failed: HubSpot returned 429.” Use them to answer *what happened to this one thing?*\n- **Metrics**: numbers over time. Success rate, failures per hour, how long jobs take, how many jobs are waiting in the queue. Use them to answer *is the system healthy overall?*\n- **Alerts**: a message (Slack, email) when a metric crosses a line. Every alert needs an owner and a clear next action, or people learn to ignore them.",
        "**Correlation IDs.** Give each piece of work one ID when it arrives, and include it in every log line across n8n, your service and the database. Then one search finds the whole story of that lead. That ID is a [[correlation id]].",
        "**The sneakiest failure is silence.** If your Monday report workflow never starts at all, there’s no error to alert on. Fix it with a check that expects a “success” signal by a certain time, and alerts if it doesn’t arrive. Free services like healthchecks.io do exactly this.",
      ],
      interview: "I log in structured JSON with a correlation ID that follows each event across services. I track a few metrics that reflect what the user cares about: success rate, end-to-end latency, queue depth and age, and failed jobs awaiting action. Alerts have owners and runbooks, and scheduled jobs get a heartbeat check, because a job that never runs produces no error.",
      check: [
        {
          id: 'm6-s5-1', kind: 'choice',
          prompt: 'A scheduled workflow silently stopped running a week ago. No error alert fired. What would have caught it?',
          options: [
            { text: 'A check that expects a success signal on schedule and alerts when it’s missing', why: 'Yes. You can only alert on missing success, because there’s no error to catch.' },
            { text: 'More detailed error logs', why: 'A workflow that never runs writes no logs at all.' },
            { text: 'A faster server', why: 'Speed doesn’t help if the job isn’t running.' },
            { text: 'Retrying failed executions', why: 'There was no failed execution to retry.' },
          ],
          answer: 0,
          explain: 'This “dead man’s switch” pattern is a favourite interview topic.',
        },
        {
          id: 'm6-s5-2', kind: 'choice',
          prompt: 'A client says lead `L-981` never reached their CRM. What lets you find what happened fastest?',
          options: [
            { text: 'Searching the logs for that lead’s correlation ID across every system', why: 'Yes. One search shows its whole journey and where it stopped.' },
            { text: 'Checking the server’s CPU usage graph', why: 'That tells you about overall load, not one lead.' },
            { text: 'Re-running the whole workflow', why: 'That might create duplicates and still not tell you what went wrong.' },
            { text: 'Asking the client to resend it', why: 'You need to find the cause, or it will happen again.' },
          ],
          answer: 0,
          explain: 'Logs answer “what happened to this one thing?”; metrics answer “is everything healthy?”.',
        },
      ],
    },
    {
      title: 'Backups, safe updates and incidents',
      minutes: 6,
      body: [
        "**Backups.** Schedule a database backup (for Postgres, `pg_dump`) and copy it *off* the server. Then actually **restore it** into a blank environment at least once. A backup you’ve never restored is a hope, not a backup.",
        "For n8n specifically, also back up the **encryption key** (`N8N_ENCRYPTION_KEY`). n8n encrypts saved credentials with it; restore the database without the key and every credential is unreadable.",
        "**Safe database changes.** Changing a table’s structure is done with a [[migration]]: a small versioned script, kept in Git, run as part of the release. Make changes backward-compatible: add the new column first, ship the code that uses it, and remove the old column in a later release. Then if the new version misbehaves, you can **roll back** to the old code and it still works with the database.",
        "**Incidents.** When something does break, fix it first, then write a short incident report: what happened, who was affected, how you noticed, the root cause, the fix, and what will prevent it next time. Keep it blameless; the point is to fix the system, not blame a person. A real incident report in your portfolio is strong evidence of production experience.",
      ],
      interview: "Backups are automated, stored off-site, and restore-tested on a schedule; for n8n that includes the encryption key. Schema changes go through versioned migrations using expand-then-contract, so the previous release still runs and rollback stays possible. After incidents I write a blameless report with detection, impact, root cause and prevention.",
      check: [
        {
          id: 'm6-s6-1', kind: 'choice',
          prompt: 'You restore your n8n database backup onto a new server. Workflows appear, but every credential fails to decrypt. What was missing?',
          options: [
            { text: 'The original N8N_ENCRYPTION_KEY', why: 'Yes. Credentials are encrypted with it, and without it they’re unreadable.' },
            { text: 'A newer version of Postgres', why: 'The data restored fine; it’s the decryption that fails.' },
            { text: 'The Dockerfile', why: 'The Dockerfile builds the app; it doesn’t hold secrets.' },
            { text: 'More disk space', why: 'Disk space wouldn’t cause decryption errors.' },
          ],
          answer: 0,
          explain: 'Back up the key alongside the data, stored securely. This is why restore tests matter.',
        },
        {
          id: 'm6-s6-2', kind: 'order',
          prompt: 'Order the steps for safely **renaming** a database column without breaking the running app.',
          items: ['Add the new column and copy the data into it', 'Deploy code that uses the new column', 'Confirm everything works', 'Remove the old column in a later release'],
          explain: 'Expand, then contract. At every step the running code still matches the database, so you can roll back.',
        },
      ],
    },
  ],
  quiz: [
    {
      id: 'm6-q1', kind: 'choice',
      prompt: 'A colleague says “it works on my machine” but it fails on the server. How does Docker help?',
      options: [
        { text: 'The image packages the app with its exact dependencies, so it runs the same everywhere', why: 'Yes. Same image, same behaviour.' },
        { text: 'Docker makes the server faster', why: 'Speed isn’t the point. Consistency is.' },
        { text: 'Docker automatically fixes bugs', why: 'It packages code; it doesn’t change it.' },
        { text: 'Docker replaces the need for a server', why: 'Containers still need a machine to run on.' },
      ],
      answer: 0,
      explain: 'Reproducibility is Docker’s core value: build once, run anywhere.',
    },
    {
      id: 'm6-q2', kind: 'choice',
      prompt: 'What does `"8080:5678"` in a compose file’s `ports` mean?',
      options: [
        { text: 'Port 8080 on your computer forwards to port 5678 inside the container', why: 'Yes. Your computer’s port comes first, then the container’s.' },
        { text: 'Port 5678 on your computer forwards to 8080 inside', why: 'It’s the other way round.' },
        { text: 'The container uses both ports at random', why: 'The mapping is fixed and explicit.' },
        { text: 'It limits the container to 8080 MB of memory', why: 'That’s a port mapping, not a memory limit.' },
      ],
      answer: 0,
      explain: 'So you’d open http://localhost:8080 in your browser to reach the app listening on 5678 inside.',
    },
    {
      id: 'm6-q3', kind: 'choice',
      prompt: 'Read the log. What’s wrong?',
      code: 'api-1  | Connecting to postgresql://app@localhost:5432/app\napi-1  | ERROR: connection refused (localhost:5432)\ndb-1   | database system is ready to accept connections',
      options: [
        { text: 'The API uses localhost instead of the database service name (db)', why: 'Yes. The database is running; the API is looking in the wrong place.' },
        { text: 'The database crashed', why: 'The db log says it’s ready.' },
        { text: 'The password is wrong', why: 'A wrong password gives an authentication error, not “connection refused”.' },
        { text: 'Postgres needs a newer version', why: 'Nothing here points to a version problem.' },
      ],
      answer: 0,
      explain: 'Change the host to `db`, the service name from the compose file.',
    },
    {
      id: 'm6-q4', kind: 'choice',
      prompt: 'Where should the database password for your compose stack live?',
      options: [
        { text: 'In a .env file on the server that’s listed in .gitignore', why: 'Yes. Compose reads it; Git never sees it.' },
        { text: 'Directly in compose.yaml, committed to GitHub', why: 'Then anyone with repo access has your password.' },
        { text: 'Inside the Dockerfile', why: 'It would be baked into the image, and visible to anyone who has the image.' },
        { text: 'In a code comment', why: 'Comments are code. Same problem as hard-coding it.' },
      ],
      answer: 0,
      explain: 'Config and secrets come from the environment, never from the code or image.',
    },
    {
      id: 'm6-q5', kind: 'choice',
      prompt: 'Your webhook handler calls an LLM (20 seconds) before replying. Which design fixes timeouts?',
      options: [
        { text: 'Save the event, put a job on a queue, reply immediately, and let a worker call the LLM', why: 'Yes. Fast reply, slow work in the background.' },
        { text: 'Use a faster LLM', why: 'It might help a bit, but slow responses or spikes will still time out.' },
        { text: 'Ask the provider to wait longer', why: 'You can’t usually change the provider’s timeout.' },
        { text: 'Retry the LLM call in the handler', why: 'That makes the handler even slower.' },
      ],
      answer: 0,
      explain: 'Separate intake from processing. This pattern appears in nearly every automation system design interview.',
    },
    {
      id: 'm6-q6', kind: 'choice',
      prompt: 'Queues usually deliver “at least once”. What must be true of your worker’s job code?',
      options: [
        { text: 'Running the same job twice must not cause a duplicate effect', why: 'Yes. Idempotent jobs make redelivery harmless.' },
        { text: 'It must run very fast', why: 'Speed doesn’t prevent duplicates.' },
        { text: 'It must never crash', why: 'Crashes will happen; design for them.' },
        { text: 'It must run on only one server', why: 'One server can still crash and retry.' },
      ],
      answer: 0,
      explain: 'At-least-once delivery + idempotent jobs = effectively-once results.',
    },
    {
      id: 'm6-q7', kind: 'choice',
      prompt: 'Which change belongs in CI?',
      options: [
        { text: 'Run the tests and build the Docker image on every push', why: 'Yes. Catch problems before they reach production.' },
        { text: 'Email the client every time you commit', why: 'That’s noise, not a quality check.' },
        { text: 'Delete old branches automatically', why: 'Possible housekeeping, but not what CI is for.' },
        { text: 'Store production backups in the repository', why: 'Backups don’t belong in Git.' },
      ],
      answer: 0,
      explain: 'CI = automated checks on every change. CD = automated shipping when the checks pass.',
    },
    {
      id: 'm6-q8', kind: 'choice',
      prompt: 'On your VPS, which ports should be open to the internet?',
      options: [
        { text: '80 and 443 for the reverse proxy (plus SSH for you), not the database or app ports', why: 'Yes. One front door; everything else stays internal.' },
        { text: 'All ports, so everything works', why: 'Every open port is something attackers can probe.' },
        { text: '5432, so you can connect to the database from home', why: 'An internet-facing database is a common cause of breaches. Use an SSH tunnel instead.' },
        { text: '5678, so n8n is reachable', why: 'Go through the proxy for HTTPS instead of exposing n8n directly.' },
      ],
      answer: 0,
      explain: 'Smallest possible attack surface: the proxy faces the world; services stay on the internal network.',
    },
    {
      id: 'm6-q9', kind: 'choice',
      prompt: 'Which is a **metric** rather than a log?',
      options: [
        { text: 'Failed jobs per hour', why: 'Yes. A number tracked over time.' },
        { text: '“Lead 42 failed: HubSpot returned 429”', why: 'That’s one event: a log line.' },
        { text: 'A stack trace from one crash', why: 'That’s detail about one event: a log.' },
        { text: 'The JSON body of one webhook', why: 'That’s the raw data of a single event.' },
      ],
      answer: 0,
      explain: 'Metrics show patterns (“failures jumped at 2pm”); logs explain individual cases.',
    },
    {
      id: 'm6-q10', kind: 'choice',
      prompt: 'Your team has nightly backups but has never restored one. What’s the risk?',
      options: [
        { text: 'You don’t know whether the backups actually work until you need them', why: 'Yes. Untested backups often turn out to be incomplete or unusable.' },
        { text: 'There’s no risk; backups are backups', why: 'Corrupt dumps, missing keys and missing files are common, and only a restore reveals them.' },
        { text: 'Restoring would delete production', why: 'You restore into a separate, blank environment.' },
        { text: 'Backups slow down the database', why: 'That’s a separate concern, and usually minor.' },
      ],
      answer: 0,
      explain: '“A backup you haven’t restored is a hope.” Schedule restore tests.',
    },
    {
      id: 'm6-q11', kind: 'choice',
      prompt: 'You need to rename the column `phone` to `phone_number`. What’s the safest approach?',
      options: [
        { text: 'Add phone_number, copy the data, deploy code using it, then drop phone in a later release', why: 'Yes. Expand then contract, so rollback is always possible.' },
        { text: 'Rename the column in production, then deploy the new code', why: 'Between those two steps, the running code breaks.' },
        { text: 'Edit the production database by hand when nobody is using it', why: 'Manual changes aren’t repeatable or tracked.' },
        { text: 'Delete the table and recreate it', why: 'You’d lose the data.' },
      ],
      answer: 0,
      explain: 'Migrations in Git + backward-compatible steps = safe releases you can undo.',
    },
    {
      id: 'm6-q12', kind: 'order',
      prompt: 'Put a short incident report in the usual order.',
      items: ['What happened and who was affected', 'How it was detected', 'Root cause', 'Fix applied', 'What will prevent it next time'],
      explain: 'Impact → detection → cause → fix → prevention. Keep it blameless and specific.',
    },
  ],
  tasks: [
    { device: 'phone', plain: 'Learn the Docker basics: image, container, Dockerfile, Compose, volumes, ports and restart policies.', done: 'You can explain each one in a sentence, and you’ve passed the checks for Lessons 1 and 2.' },
    { device: 'computer', plain: 'Run the same app with different settings for “dev” and “production”, without changing any code.', done: 'Two .env files (with fake values) and a note showing the app uses a different database in each.' },
    { device: 'computer', plain: 'Write a compose.yaml that starts your API, Postgres, Redis, a worker and n8n together with one command.', done: '`docker compose up -d` starts everything, and data survives `docker compose down` followed by `up` again.' },
    { device: 'phone', plain: 'Learn how queues work: producers, workers, acknowledgement, retries and dead-letter queues.', done: 'You can explain what happens when a worker crashes mid-job, and you’ve passed the Lesson 3 check.' },
    { device: 'computer', plain: 'Add a correlation ID that travels from the webhook through n8n and your service into the database, and appears in every log line.', done: 'One search for a single ID shows that event’s full journey.' },
    { device: 'phone', plain: 'Learn which numbers show whether a system is healthy: error rate, latency, throughput, queue depth and failed jobs.', done: 'You can say which metric you’d alert on for a lead-processing system, and why.' },
    { device: 'computer', plain: 'Set up error tracking: either a tool (Sentry, Better Stack) or a simple errors table you can query.', done: 'Cause a failure on purpose and show it appearing with useful details.' },
    { device: 'computer', plain: 'Add a GitHub Actions workflow that installs, tests and builds your Docker image on every push.', done: 'A screenshot of a red ❌ run for a broken test, then a green ✅ after the fix.' },
    { device: 'computer', plain: 'Deploy your stack to a VPS behind Caddy (or another reverse proxy) with HTTPS on your own domain.', done: 'Your app loads at https://your-domain with a padlock, and only ports 80, 443 and SSH are open.' },
    { device: 'computer', plain: 'Back up your database (and n8n encryption key), then restore it into a fresh, empty environment.', done: 'Written restore steps, plus proof that the restored copy works.' },
    { device: 'phone', plain: 'Learn how to change a database safely: migrations, backward-compatible changes and rollback.', done: 'You can explain “expand then contract” and order the steps in the Lesson 7 check.' },
    { device: 'computer', plain: 'Break something on purpose (stop the database, fill a queue), fix it, and write a one-page incident report.', done: 'The report covers what happened, impact, detection, root cause, fix and prevention.' },
  ],
};
