'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { BookOpen, Play, Check, CheckCircle2, Circle, Code2, Braces, Network, Database, Workflow, Server, Boxes, Sparkles, Search, Bot, ShieldCheck, Layers, GraduationCap, BriefcaseBusiness, Clock3, FileText, ExternalLink, Download, Upload, Settings2, MessageSquare, CloudCheck, LoaderCircle, RotateCw, PanelRightClose, PanelRightOpen, ListChecks, Target, Trophy, X, LogOut, KeyRound, CalendarCheck, Smartphone, Laptop } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger, useSidebar } from '@/components/ui/sidebar';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Progress } from '@/components/ui/progress';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import curriculum from '@/lib/curriculum.json';
import { handbook } from '@/lib/handbook';
import { normalizeImport, type Stored } from '@/lib/state';
import VideoPlayer from './video-player';
import { createClient } from '@/lib/supabase/client';
import { lessons, PASS_MARK, type Question } from '@/lib/lessons';
import { schedule } from '@/lib/srs';
import Today from './today';
import { LessonView, QuizPanel } from './lesson';
const modules = curriculum.modules;
const icons = [Code2,Network,Braces,Database,Workflow,Server,Boxes,Sparkles,Search,Bot,ShieldCheck,Workflow,BookOpen,Bot,MessageSquare,BriefcaseBusiness];
const clean = (t:string) => t.replace(/^\d+\. /,'');
const phases = ['All modules','Foundation','Production','AI engineering','Portfolio','Career'];
const phaseMap = ['','FOUNDATION','PRODUCTION AUTOMATION','AI ENGINEERING','PORTFOLIO','JOB CONVERSION'];
const total = modules.reduce((sum,m)=>sum+m.tasks.length,0);
const totalHours = modules.reduce((sum,m)=>sum+m.hours,0);
const videoTime = (seconds:number) => `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;
const shortTask = (s:string) => s.split(/: |\. /)[0].slice(0,105);
// These publishers send X-Frame-Options/frame-ancestors headers, so the embedded reading room would be blank.
const noFrame = /(^|\.)(github\.com|docker\.com|mozilla\.org|postgresql\.org|supabase\.com|anthropic\.com|openai\.com|linkedin\.com)$/;
const openDoc = (doc:string[], embed:(d:string[])=>void) => noFrame.test(new URL(doc[1]).hostname) ? window.open(doc[1],'_blank','noopener') : embed(doc);
function SideNav({view,go,email}:{view:string;go:(s:string)=>void;email:string}) {
  const {setOpenMobile} = useSidebar();
  return <><SidebarHeader className="brand"><span className="brand-mark">a<span>•</span></span><div>Automation<span>ACADEMY</span></div></SidebarHeader><SidebarContent className="nav-content"><p className="nav-label">YOUR WORKSPACE</p><SidebarMenu>{[[CalendarCheck,'Today','today'],[BookOpen,'My learning','home'],[MessageSquare,'Interview practice','interview'],[BriefcaseBusiness,'Career tracker','career']].map(([Icon,title,id]) => {const I=Icon as typeof BookOpen; return <SidebarMenuItem key={String(id)}><SidebarMenuButton className="nav-button" isActive={view===id || id==='home' && view==='learn'} onClick={()=>{go(String(id));setOpenMobile(false);}}><I/><span>{String(title)}</span></SidebarMenuButton></SidebarMenuItem>;})}</SidebarMenu><div className="nav-guide"><span className="small-icon"><Target size={20}/></span><b>Build. Prove. Apply.</b><p>Your next role starts with what you can demonstrate.</p></div></SidebarContent><SidebarFooter className="nav-footer"><SidebarMenuButton className="nav-button" isActive={view==='settings'} onClick={()=>{go('settings');setOpenMobile(false);}}><Settings2/>Progress & backups</SidebarMenuButton><div className="profile"><span>{email.slice(0,2).toUpperCase()}</span><div>Your learning space<small>{email}</small></div></div><form action="/auth/signout" method="post" onSubmit={()=>{void caches?.keys().then(keys=>keys.forEach(k=>caches.delete(k)));}}><SidebarMenuButton type="submit" className="nav-button signout-button"><LogOut/>Sign out</SidebarMenuButton></form></SidebarFooter></>;
}
export default function Academy({email}:{email:string}) {
  const [route,setRoute] = useState('home');
  const [values,setValues] = useState<Stored>({});
  const valuesRef = useRef<Stored>({});
  const pending = useRef<Stored>({});
  const busy = useRef(false);
  const [loaded,setLoaded] = useState(false);
  const [status,setStatus] = useState('Loading progress');
  const [error,setError] = useState('');
  const [unauth,setUnauth] = useState(false);
  const [phase,setPhase] = useState('All modules');
  const [search,setSearch] = useState('');
  const [outline,setOutline] = useState(true);
  const [compact,setCompact] = useState(false);
  const [openModule,setOpenModule] = useState('m0');
  const [resource,setResource] = useState<string[]|null>(null);
  const [question,setQuestion] = useState(0);
  const [answer,setAnswer] = useState(false);
  const [questionFilter,setQuestionFilter] = useState('All topics');
  const [importData,setImportData] = useState<Stored|null>(null);
  const input = useRef<HTMLInputElement>(null);
  const [notice,setNotice] = useState('');
  const [newPassword,setNewPassword] = useState('');
  const updatePassword=async(e:React.FormEvent)=>{e.preventDefault();const {error}=await createClient().auth.updateUser({password:newPassword});setNotice(error?error.message:'Password updated.');if(!error)setNewPassword('');};
  const go = useCallback((path:string) => { window.location.hash=path; if(window.innerWidth<1000)setOutline(false); },[]);
  const change = useCallback((key:string,value:Stored[string]) => {
    if (!loaded) return;
    pending.current[key]=value;
    valuesRef.current={...valuesRef.current,[key]:value};
    setValues(valuesRef.current);setStatus('Unsaved changes');
  },[loaded]);
  const load = useCallback(async () => {
    setError('');setStatus('Loading progress');
    try { const res=await fetch('/api/progress',{cache:'no-store'});const data=await res.json() as {error?:string;values:Stored};if(!res.ok){setUnauth(res.status===401);throw new Error(data.error);}
      valuesRef.current=data.values;setValues(data.values);setLoaded(true);setUnauth(false);setStatus('All changes saved');
    } catch(e) {setError(e instanceof Error?e.message:'Could not load progress.');setStatus('Progress unavailable');}
  },[]);
  const flush = useCallback(async () => {
    if (busy.current || !Object.keys(pending.current).length) return;
    busy.current=true; const snapshot={...pending.current};setStatus('Saving');
    try {const res=await fetch('/api/progress',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:snapshot})});const data=await res.json() as {error?:string;values:Stored};if(!res.ok) throw new Error(data.error);
      for(const [k,v] of Object.entries(snapshot)) if(pending.current[k]===v) delete pending.current[k];
      setError('');setStatus(Object.keys(pending.current).length?'Unsaved changes':'All changes saved');
    }catch(e){setError(e instanceof Error?e.message:'Could not save.');setStatus('Changes not saved');}
    busy.current=false;
  },[]);
  useEffect(()=>{setOutline(window.innerWidth>=1000);setCompact(window.innerWidth<1000);const resize=()=>setCompact(window.innerWidth<1000);window.addEventListener('resize',resize);load();const onHash=()=>{const path=decodeURIComponent(location.hash.slice(1));setRoute(/^(today|home|interview|career|settings|learn\/m(?:[0-9]|1[0-5])\/(read|watch|practice|quiz|gate|notes)(\/\d+)?)$/.test(path)?path:!path&&window.innerWidth<768?'today':'home');};onHash();window.addEventListener('hashchange',onHash);return()=>{window.removeEventListener('hashchange',onHash);window.removeEventListener('resize',resize);};},[load]);
  useEffect(()=>{const id=setInterval(()=>{if(!error) void flush();},1000);return()=>clearInterval(id);},[flush,error]);
  useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(Object.keys(pending.current).length){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[]);
  useEffect(()=>{if(route.startsWith('learn/')){if(!/\/read\/\d+$/.test(route))window.scrollTo({top:0,behavior:'instant'});setOpenModule(route.split('/')[1]); if(loaded)change('resume',route.replace('/notes','/read'));}else window.scrollTo({top:0,behavior:'instant'});},[route,loaded,change]);
  useEffect(()=>{
    const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>unknown}}).modelContext;
    if(!context?.registerTool) return;
    const lifecycle=new AbortController();
    Promise.resolve(context.registerTool({name:'open_course_module',title:'Open a course module',description:'Navigate to a module reading page. Does not mark any work complete.',inputSchema:{type:'object',properties:{moduleId:{type:'string',enum:modules.map(m=>m.id)}},required:['moduleId'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(i:{moduleId:string})=>{if(!modules.some(m=>m.id===i.moduleId))throw new Error('Unknown module');go(`learn/${i.moduleId}/read`);return {opened:i.moduleId};}},{signal:lifecycle.signal})).catch(()=>{});
    return()=>lifecycle.abort();
  },[go]);
  const [view,mid,section='read',index='0'] = route.split('/');
  const module=modules.find(m=>m.id===mid)||modules[0];
  const moduleIndex=modules.indexOf(module);
  const taskIndex=Math.min(Math.max(Number(index)||0,0),module.tasks.length-1);
  const task=module.tasks[taskIndex];
  const videoIndex=Math.min(Math.max(Number(index)||0,0),module.videos.length-1);
  const relatedVideos=module.videoDetails.map((detail,i)=>({detail,i})).filter(({detail})=>detail.taskIndices.includes(taskIndex));
  const doneCount=(m:typeof module)=>m.tasks.filter((_,i)=>values[`${m.id}-${i}`]===true).length;
  const done=modules.reduce((n,m)=>n+doneCount(m),0), percent=Math.round(done/total*100);
  const mastery=modules.filter(m=>doneCount(m)===m.tasks.length && values[`gate:${m.id}`]).length;
  const remaining=Math.ceil(modules.reduce((n,m)=>n+m.hours*(1-doneCount(m)/m.tasks.length),0));
  const next=modules.find(m=>doneCount(m)<m.tasks.length || !values[`gate:${m.id}`])||modules[15];
  const resume=typeof values.resume==='string'?values.resume:`learn/${next.id}/read`;
  const resumeModule=modules.find(m=>m.id===resume.split('/')[1])||next;
  const pace=Number(values.pace)||18;
  const lesson=lessons[mid];
  const recordAnswer=(q:Question,correct:boolean)=>change(`srs:${q.id}`,schedule(valuesRef.current[`srs:${q.id}`],correct));
  const evidence=String(values[`evidence:${mid}`]||'');
  const quizPassed=Number(values[`quiz:${mid}`]??0)>=PASS_MARK;
  const gateReady=doneCount(module)===module.tasks.length&&(!lesson||quizPassed&&/^https?:\/\/\S+$/.test(evidence));
  const exportProgress=()=>{const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),values:valuesRef.current},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='automation-academy-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);};
  const readImport=async(file?:File)=>{if(!file)return;try{if(file.size>500000)throw new Error('Choose a progress file smaller than 500 KB.');setImportData(normalizeImport(JSON.parse(await file.text())));}catch(e){setNotice(e instanceof Error?e.message:'Invalid progress file.');}if(input.current)input.current.value='';};
  const advance=()=>{if(taskIndex<module.tasks.length-1)go(`learn/${mid}/practice/${taskIndex+1}`);else go(`learn/${mid}/gate`);};
  const filteredQuestions=curriculum.questions.filter(q=>questionFilter==='All topics'||q[0]===questionFilter);
  const currentQuestion=filteredQuestions[question%filteredQuestions.length];
  const showSaved=loaded&&!error;
  const readFooter = <><div className="key-takeaways"><h3>Keep these in mind</h3><ul>{module.notes.map(note=><li key={note}>{note}</li>)}</ul></div><div className="reading-resources"><h3>Go deeper with the official docs</h3><p>Open a reference in the reading room. The lesson above stays available here.</p>{module.docs.map(doc=><button key={doc[1]} className="resource-row" onClick={()=>openDoc(doc,setResource)}><span><FileText size={18}/>{doc[0]}</span>{noFrame.test(new URL(doc[1]).hostname)?<ExternalLink size={16}/>:<BookOpen size={16}/>}</button>)}</div><div className="lesson-bottom"><span>{lesson?'Read it? Test yourself, then build it.':'Ready to put this into practice?'}</span><div className="button-row">{lesson&&<button className="primary" onClick={()=>go(`learn/${mid}/quiz`)}>Take the module quiz</button>}<button className={lesson?'secondary':'primary'} onClick={()=>go(`learn/${mid}/practice/0`)}>Open the exercises</button></div></div></>;
  const outlinePanel = <aside className="course-outline"><div className="outline-header"><div className="row space-between"><h2>Course content</h2><button className="icon-button" onClick={()=>setOutline(false)} aria-label="Close course outline"><X size={18}/></button></div><p>{done} / {total} exercises complete</p><Progress value={percent}/></div><Accordion type="single" collapsible value={openModule} onValueChange={setOpenModule}>{modules.map((m,i)=><AccordionItem value={m.id} key={m.id}><AccordionTrigger className="outline-module"><span><small>MODULE {String(i+1).padStart(2,'0')} · {doneCount(m)}/{m.tasks.length}</small><b>{clean(m.title)}</b></span></AccordionTrigger><AccordionContent><div className="outline-links">{[['read','Lesson & reading',BookOpen],['watch',`${m.videos.length} video ${m.videos.length===1?'lesson':'lessons'}`,Play],['practice',`${m.tasks.length} practical exercises`,Code2],...(lessons[m.id]?[['quiz',`Module quiz${values[`quiz:${m.id}`]!==undefined?` · best ${values[`quiz:${m.id}`]}%`:''}`,ListChecks]]:[]),['gate','Mastery check',ShieldCheck],['notes','My notes',FileText]].map(([s,label,Icon])=>{const I=Icon as typeof BookOpen;return <button key={String(s)} className={mid===m.id&&section===s?'active':''} onClick={()=>go(`learn/${m.id}/${s}`)}><I size={16}/>{String(label)}{s==='gate'&&values[`gate:${m.id}`]&&doneCount(m)===m.tasks.length?<Check size={15}/>:null}</button>;})}</div></AccordionContent></AccordionItem>)}</Accordion></aside>;
  return <SidebarProvider style={{'--sidebar-width':'238px'} as React.CSSProperties}><Sidebar><SideNav view={view} go={go} email={email}/></Sidebar><div className="app-body"><header className="topbar"><div className="breadcrumbs"><SidebarTrigger/><span>Workspace</span><span className="slash">/</span><b>{view==='today'?'Today':view==='learn'?'My learning':view==='career'?'Career tracker':view==='interview'?'Interview practice':view==='settings'?'Progress & backups':'My learning'}</b></div><div className="save-status" role="status">{status==='Saving'||!loaded&&!error?<LoaderCircle className="spin" size={15}/>:showSaved?<CloudCheck size={16}/>:<Circle size={14}/>}<span>{status}</span></div></header>
  {error&&<div className="error-banner" role="alert"><span>{error}</span>{unauth?<a href="/login">Sign in</a>:<button onClick={()=>loaded?flush():load()}><RotateCw size={15}/>Retry</button>}</div>}
  {notice&&<div className="notice" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
  {view==='today'&&<Today values={values} answer={recordAnswer} go={go} loaded={loaded}/>}
  {view==='home'&&<main className="home content"><div className="page-title"><div><p className="eyebrow">YOUR NEXT CHAPTER</p><h1>My learning</h1><p>One module at a time. Build the skills for your next role.</p></div><span className="course-label"><GraduationCap size={18}/> AI Automation Engineering</span></div>
    <div className="home-top"><section className="resume-card"><div><span className="overline">{done?'PICK UP WHERE YOU LEFT OFF':'YOUR STARTING POINT'}</span><h2>{clean(resumeModule.title)}</h2><p>{resumeModule.outcome}</p><button className="primary white-button" onClick={()=>go(resume)}><Play size={17} fill="currentColor"/>{done?'Continue learning':'Start learning'}</button><span className="resume-meta">Module {modules.indexOf(resumeModule)+1} of 16 · {resumeModule.hours}h estimated effort</span></div><div className="progress-dial" style={{'--progress':`${percent*3.6}deg`} as React.CSSProperties}><div><strong>{percent}<small>%</small></strong><span>completed</span></div></div></section><section className="pace-card"><div className="row"><Clock3 size={19}/><h3>Your weekly pace</h3></div><Select value={String(pace)} onValueChange={v=>change('pace',Number(v))} disabled={!loaded}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[12,18,24].map(p=><SelectItem key={p} value={String(p)}>{p} hours / week</SelectItem>)}</SelectContent></Select><strong>~{Math.ceil(remaining/pace)} weeks</strong><p>Estimated remaining at your pace. Skip familiar work by proving it.</p><span className="pace-foot">Start applying while you learn.</span></section></div>
    <div className="stats-strip"><div><BookOpen/><span><strong>{mastery} <em>/ 16</em></strong>Modules mastered</span></div><div><CheckCircle2/><span><strong>{done} <em>/ {total}</em></strong>Exercises completed</span></div><div><Layers/><span><strong>{modules.slice(11,14).filter(m=>values[`gate:${m.id}`]&&doneCount(m)===m.tasks.length).length} <em>/ 3</em></strong>Portfolio capstones</span></div><div><Clock3/><span><strong>{remaining}<em> hours</em></strong>Estimated work remaining</span></div></div>
    <section className="curriculum"><div className="section-head"><div><h2>Your curriculum</h2><p>16 focused modules, from integration reliability to your next offer.</p></div><label className="searchbox"><Search size={17}/><input aria-label="Search modules" placeholder="Find a module…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><Tabs value={phase} onValueChange={setPhase}><TabsList className="phase-tabs" variant="line">{phases.map(p=><TabsTrigger value={p} key={p}>{p}</TabsTrigger>)}</TabsList></Tabs><div className="module-grid">{modules.filter(m=>(phase==='All modules'||m.phase===phaseMap[phases.indexOf(phase)])&&`${m.title} ${m.outcome}`.toLowerCase().includes(search.toLowerCase())).map(m=>{const i=modules.indexOf(m),Icon=icons[i],count=doneCount(m),p=Math.round(count/m.tasks.length*100);return <button className="module-card" key={m.id} onClick={()=>go(`learn/${m.id}/read`)}><div className="module-card-top"><span className={`module-icon tone-${Math.floor(i/4)}`}><Icon size={23}/></span><span className="module-number">MODULE {String(i+1).padStart(2,'0')}</span>{values[`gate:${m.id}`]&&p===100?<span className="state-tag complete">Mastered</span>:count>0?<span className="state-tag">In progress</span>:<span className="state-tag quiet">Not started</span>}</div><h3>{clean(m.title)}</h3><p>{m.outcome}</p><div className="module-meta"><span><Clock3 size={14}/>{m.hours}h</span><span><ListChecks size={14}/>{m.tasks.length} exercises</span><span><Play size={13}/>{m.videos.length} {m.videos.length===1?'video':'videos'}</span></div><Progress value={p} aria-label={`${p}% of exercises complete`}/><div className="card-bottom"><span>{count} of {m.tasks.length} complete</span><b>{count?'Continue module':'Explore module'}</b></div></button>;})}</div>{!modules.some(m=>(phase==='All modules'||m.phase===phaseMap[phases.indexOf(phase)])&&`${m.title} ${m.outcome}`.toLowerCase().includes(search.toLowerCase()))&&<div className="empty"><Search/><h3>No matching modules</h3><p>Try a different skill or choose All modules.</p><button className="secondary" onClick={()=>{setSearch('');setPhase('All modules');}}>Clear filters</button></div>}</section><p className="bottom-note">Progress reflects work you mark complete. Mastery means you can demonstrate it without AI assistance.</p>
  </main>}
  {view==='learn'&&<main className={`learning ${outline?'':'no-outline'}`}><div className="lesson-column"><div className="lesson-toolbar"><button className="text-button" onClick={()=>go('home')}>All modules</button><span>Module {moduleIndex+1} / 16</span><button className="text-button" onClick={()=>setOutline(!outline)}>{outline?<PanelRightClose size={18}/>:<PanelRightOpen size={18}/>}Course content</button></div><div className="lesson-heading"><span className="eyebrow">{module.phase.replace('JOB CONVERSION','CAREER')}</span><h1>{clean(module.title)}</h1><p>{module.outcome}</p><div className="lesson-metadata"><span><Clock3 size={15}/>{module.hours} hours estimated effort</span><span><CheckCircle2 size={15}/>{doneCount(module)} / {module.tasks.length} exercises</span></div></div>
  <Tabs value={section} onValueChange={s=>go(`learn/${mid}/${s}`)} className="lesson-tabs"><TabsList variant="line" className="learning-tabs">{[['read','Learn',BookOpen],['watch','Watch',Play],['practice','Practice',Code2],...(lesson?[['quiz','Quiz',ListChecks]]:[]),['gate','Mastery',ShieldCheck],['notes','Notes',FileText]].map(([id,label,Icon])=>{const I=Icon as typeof BookOpen;return <TabsTrigger key={String(id)} value={String(id)}><I size={16}/>{String(label)}</TabsTrigger>;})}</TabsList>
  <TabsContent value="read">{lesson?<LessonView lesson={lesson} values={values} answer={recordAnswer} loaded={loaded} focus={section==='read'&&index!=='0'||route.endsWith('/read/0')?Number(index):null} why={module.why} footer={readFooter}/>:<article className="reading"><div className="reading-intro"><span className="small-icon"><BookOpen size={20}/></span><div><h2>The lesson</h2><p>{module.why}</p></div></div>{handbook[mid]?.map((part,i)=><section className="reading-section" key={part.title}><span className="chapter-number">{String(i+1).padStart(2,'0')}</span><div><h3>{part.title}</h3><p>{part.body}</p>{part.example&&<pre><code>{part.example}</code></pre>}</div></section>)}{readFooter}</article>}</TabsContent>
  <TabsContent value="watch"><div className="watch-area">
    <h2>Topic videos</h2><p className="muted">Choose the topic you need. Chapter clips start and stop at the relevant section.</p>
    <Tabs value={String(videoIndex)} onValueChange={v=>go(`learn/${mid}/watch/${v}`)} key={mid}>
      <TabsList className="topic-choices" aria-label="Choose a video topic">{module.videos.map((v,i)=><TabsTrigger value={String(i)} key={i}><Play size={15}/><span><b>{v[0]}</b><small>{module.videoDetails[i].creator} · {Number(v[3])>0?`${videoTime(Number(v[3])-Number(v[2]))} chapter`:'Focused video'}</small></span></TabsTrigger>)}</TabsList>
      {module.videos.map((v,i)=><TabsContent key={i} value={String(i)}><h3>{v[0]}</h3><p className="video-focus">{module.videoDetails[i].focus}</p><p className="video-attribution">{module.videoDetails[i].creator}{Number(v[3])>0&&<> · Selected chapter {videoTime(Number(v[2]))}–{videoTime(Number(v[3]))}</>}</p><VideoPlayer video={v}/>{Number(v[3])>0&&<p className="muted clip-note">The embedded lesson stops at the end of this chapter. The YouTube link opens the full source video at the same starting point.</p>}</TabsContent>)}
    </Tabs><div className="watch-prompt"><h3>Put this topic into practice</h3><p>Pause and reproduce one example independently. Save what you built and what broke in My notes.</p><button className="secondary" onClick={()=>go(`learn/${mid}/practice/${module.videoDetails[videoIndex].taskIndices[0]??0}`)}>Open a related exercise</button></div>
  </div></TabsContent>
  <TabsContent value="practice"><div className="exercise-area"><div className="row space-between"><span className="eyebrow">EXERCISE {taskIndex+1} OF {module.tasks.length}</span><span className="task-type">{lesson&&(lesson.tasks[taskIndex].device==='phone'?<><Smartphone size={13}/>Phone-friendly · </>:<><Laptop size={13}/>Computer · </>)}{task[0]==='prove'?'Demonstrate':task[0]}</span></div>{lesson?<><h2>{lesson.tasks[taskIndex].plain}</h2><div className="done-looks-like"><b>Done looks like</b><p>{lesson.tasks[taskIndex].done}</p></div><details className="interview-version"><summary><FileText size={16}/>Technical brief</summary><p>{task[1]}</p></details></>:<h2>{task[1]}</h2>}{relatedVideos.length>0&&<section className="related-videos"><h3>Videos for this exercise</h3><div>{relatedVideos.map(({i})=><button className="secondary" key={i} onClick={()=>go(`learn/${mid}/watch/${i}`)}><Play size={14}/>{module.videos[i][0]}</button>)}</div></section>}<div className="exercise-brief"><h3>Your evidence</h3><p>{task[0]==='interview'?'Record your answer without notes. Explain the decision, the alternative you rejected, and what would change your answer.':task[0]==='learn'?'Explain the concept in your own words, then create a small working example. Record one edge case and show what happens.':task[0]==='prove'?'Run this without AI assistance. Capture the expected result, the actual result, and the failure or boundary condition you tested.':'Build it from a clean starting point. Save the code or workflow, demonstrate the happy path, and capture a failure plus the recovery.'}</p><div className="evidence-steps"><span><span>1</span>Build or explain it</span><span><span>2</span>Test a failure</span><span><span>3</span>Save your evidence</span></div></div><label className={`completion-row ${values[`${mid}-${taskIndex}`]?'checked':''}`}><Checkbox disabled={!loaded} checked={values[`${mid}-${taskIndex}`]===true} onCheckedChange={v=>{change(`${mid}-${taskIndex}`,v===true);if(v!==true)change(`gate:${mid}`,false);}}/><span><b>I can demonstrate this independently</b><small>Mark complete when you have evidence, not just familiarity.</small></span></label><div className="exercise-actions"><button className="secondary" disabled={taskIndex===0} onClick={()=>go(`learn/${mid}/practice/${taskIndex-1}`)}>Previous exercise</button><button className="primary" onClick={advance}>{taskIndex===module.tasks.length-1?'Open mastery check':'Next exercise'}</button></div><section className="exercise-list"><h3>All module exercises</h3>{module.tasks.map((t,i)=><button className={i===taskIndex?'active':''} key={i} onClick={()=>go(`learn/${mid}/practice/${i}`)}>{values[`${mid}-${i}`]?<CheckCircle2 size={17}/>:<Circle size={17}/>}<span><small>{String(i+1).padStart(2,'0')} · {t[0]}{lesson&&(lesson.tasks[i].device==='phone'?' · 📱 phone':' · 💻 computer')}</small>{lesson?lesson.tasks[i].plain:shortTask(t[1])}</span></button>)}</section></div></TabsContent>
  {lesson&&<TabsContent value="quiz"><QuizPanel mid={mid} values={values} answer={recordAnswer} change={change} loaded={loaded}/></TabsContent>}<TabsContent value="gate"><div className="mastery-area"><span className="mastery-icon"><ShieldCheck size={34}/></span><span className="eyebrow">AI-CLOSED MASTERY CHECK</span><h2>Can you own this independently?</h2><p className="gate-prompt">{module.gate}</p><div className="mastery-rules"><h3>What passing looks like</h3><p>Close the AI assistant. Use documentation, explain your trade-offs, and demonstrate a failure and recovery. Add a link to your evidence in My notes.</p><div className="row"><Progress value={doneCount(module)/module.tasks.length*100}/><span>{doneCount(module)}/{module.tasks.length}</span></div>{lesson&&<ul className="gate-checklist"><li className={doneCount(module)===module.tasks.length?'met':''}>{doneCount(module)===module.tasks.length?<CheckCircle2 size={17}/>:<Circle size={17}/>}All {module.tasks.length} exercises complete</li><li className={quizPassed?'met':''}>{quizPassed?<CheckCircle2 size={17}/>:<Circle size={17}/>}<span>Module quiz {PASS_MARK}%+ {values[`quiz:${mid}`]!==undefined&&`(best ${values[`quiz:${mid}`]}%)`} <button className="text-button" onClick={()=>go(`learn/${mid}/quiz`)}>Open quiz</button></span></li><li className={/^https?:\/\/\S+$/.test(evidence)?'met':''}>{/^https?:\/\/\S+$/.test(evidence)?<CheckCircle2 size={17}/>:<Circle size={17}/>}<span>Link to your evidence (GitHub repo, Loom video…)<input type="url" disabled={!loaded} placeholder="https://github.com/…" value={evidence} maxLength={2000} onChange={e=>change(`evidence:${mid}`,e.target.value)}/></span></li></ul>}</div><label className="completion-row"><Checkbox disabled={!loaded||!gateReady} checked={values[`gate:${mid}`]===true&&gateReady} onCheckedChange={v=>change(`gate:${mid}`,v===true)}/><span><b>I passed this mastery check</b><small>{gateReady?'Self-assessed against the criteria above.':lesson?'Complete the checklist above to unlock this.':'Complete the module exercises to unlock this check.'}</small></span></label>{values[`gate:${mid}`]&&gateReady&&<div className="success-note"><Trophy size={20}/>Module mastered. Your evidence is the achievement.</div>}<button className="primary" onClick={()=>moduleIndex<15?go(`learn/${modules[moduleIndex+1].id}/read`):go('career')}>{moduleIndex<15?'Open next module':'Open career tracker'}</button></div></TabsContent>
  <TabsContent value="notes"><div className="notes-area"><h2>Your module notebook</h2><p className="muted">Keep evidence links, debugging notes, and questions to revisit. Changes save automatically.</p><label className="field-label" htmlFor="module-notes">Notes for {clean(module.title)}</label><textarea id="module-notes" disabled={!loaded} maxLength={20000} value={String(values[`note:${mid}`]||'')} onChange={e=>change(`note:${mid}`,e.target.value)} placeholder={'What I built\n\nEvidence / repository link\n\nWhat failed and how I fixed it\n\nWhat I need to revisit'} rows={17}/><p className="muted">{String(values[`note:${mid}`]||'').length.toLocaleString()} / 20,000 characters · {status}</p></div></TabsContent>
  </Tabs></div>{outline&&(compact?<Sheet open={outline} onOpenChange={setOutline}><SheetContent className="outline-sheet"><SheetHeader><SheetTitle>Course content</SheetTitle><SheetDescription>Choose a module and learning activity.</SheetDescription></SheetHeader>{outlinePanel}</SheetContent></Sheet>:outlinePanel)}</main>}
  {view==='interview'&&<main className="content narrow"><p className="eyebrow">PRACTICE OUT LOUD</p><h1>Interview practice</h1><p className="page-subtitle">Explain how you think, then compare your answer with the key points.</p><div className="interview-filter"><Select value={questionFilter} onValueChange={v=>{setQuestionFilter(v);setQuestion(0);setAnswer(false);}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['All topics',...new Set(curriculum.questions.map(q=>q[0]))].map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select><span>{question%filteredQuestions.length+1} of {filteredQuestions.length} questions</span></div><div className="question-card"><span className="task-type">{currentQuestion[0]}</span><h2>{currentQuestion[1]}</h2><p className="muted">Take 2–3 minutes. Clarify assumptions and discuss failure cases.</p>{answer?<div className="answer"><h3>A strong answer covers</h3><p>{currentQuestion[2]}</p></div>:<button className="primary" onClick={()=>setAnswer(true)}>Reveal answer guide</button>}<div className="exercise-actions"><button className="secondary" disabled={question===0} onClick={()=>{setQuestion(q=>q-1);setAnswer(false);}}>Previous question</button><button className="secondary" onClick={()=>{setQuestion(q=>q+1);setAnswer(false);}}>Next question</button></div></div><section className="surface"><h3>Your interview feedback</h3><p className="muted">What did you miss? Which module will you revisit?</p><textarea aria-label="Interview feedback" disabled={!loaded} maxLength={20000} rows={6} value={String(values['career:interviewLog']||'')} onChange={e=>change('career:interviewLog',e.target.value)} placeholder="Question → gap in my answer → module to revisit → retest date"/></section><section className="surface"><h3>Skills to explain confidently</h3><div className="skills-table">{curriculum.market_skills.map((s,i)=><div key={i}><b>{s[0]}</b><p>{s[1]}</p></div>)}</div></section></main>}
  {view==='career'&&<main className="content"><p className="eyebrow">LEARNING AND APPLYING, TOGETHER</p><h1>Career tracker</h1><p className="page-subtitle">Build evidence. Apply to relevant roles. Let interview feedback shape what you learn next.</p><div className="career-metrics">{[['apps','Applications sent',BriefcaseBusiness],['outreach','Targeted outreach',MessageSquare],['screens','Screening calls',Search],['mocks','Mock interviews',GraduationCap]].map(([id,label,Icon])=>{const I=Icon as typeof BookOpen;return <label className="metric-edit" key={String(id)}><I size={23}/><span>{String(label)}</span><input type="number" min={0} max={100000} disabled={!loaded} aria-label={String(label)} value={Number(values[`career:${id}`])||0} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=0&&n<=100000)change(`career:${id}`,n);}}/></label>;})}</div><div className="career-columns"><section className="surface"><h2>Your portfolio</h2><p className="muted">Link to each project’s repository or demo.</p>{modules.slice(11,14).map((m,i)=><div className="portfolio-field" key={m.id}><label htmlFor={`portfolio${i}`}><span>0{i+1}</span>{clean(m.title).replace(/Capstone #\d — /,'')}</label><input id={`portfolio${i}`} disabled={!loaded} type="url" maxLength={20000} value={String(values[`career:portfolio${i+1}`]||'')} onChange={e=>change(`career:portfolio${i+1}`,e.target.value)} placeholder="https://github.com/…"/><button className="text-button" onClick={()=>go(`learn/${m.id}/read`)}>Open project brief</button></div>)}</section><section className="surface"><span className="small-icon"><Target size={21}/></span><h2>A weekly rhythm</h2><p className="muted">Suggested targets, not quotas. Prioritise roles where you can show relevant evidence.</p><div className="weekly-item"><strong>10</strong><span>Tailored applications</span></div><div className="weekly-item"><strong>15</strong><span>Relevant outreach messages</span></div><div className="weekly-item"><strong>1</strong><span>Mock interview with a failure log</span></div><button className="secondary" onClick={()=>go('interview')}>Practice an interview</button></section></div><section className="surface"><h3>Interview & application feedback</h3><textarea aria-label="Career feedback" disabled={!loaded} maxLength={20000} rows={6} value={String(values['career:feedback']||'')} onChange={e=>change('career:feedback',e.target.value)} placeholder="Company / role, result, what I learned, next action"/></section><p className="bottom-note">A roadmap can build your capability and evidence. Hiring outcomes also depend on fit, applications, interviews, and the market.</p></main>}
  {view==='settings'&&<main className="content narrow"><p className="eyebrow">YOUR WORK, SAVED</p><h1>Progress & backups</h1><p className="page-subtitle">Your exercises, notes, and career progress save to your signed-in account.</p><section className="surface"><h2>Learning preferences</h2><div className="settings-row"><label>Weekly study time</label><Select disabled={!loaded} value={String(pace)} onValueChange={v=>change('pace',Number(v))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[12,18,24].map(p=><SelectItem value={String(p)} key={p}>{p} hours / week</SelectItem>)}</SelectContent></Select></div><div className="settings-row"><label htmlFor="start-date">Start date</label><input id="start-date" disabled={!loaded} type="date" value={String(values.startDate||'')} onChange={e=>change('startDate',e.target.value)}/></div><p className="muted">The full roadmap estimates {totalHours} hours. Your remaining estimate adjusts as you complete exercises.</p></section><section className="surface"><h2>Keep a copy of your progress</h2><p className="muted">Export a JSON backup, or bring your progress from the previous dashboard. Imports merge supplied fields and leave other work in place.</p><div className="button-row"><button className="primary" disabled={!loaded} onClick={exportProgress}><Download size={17}/>Export progress</button><button className="secondary" disabled={!loaded} onClick={()=>input.current?.click()}><Upload size={17}/>Import progress</button></div><input hidden ref={input} type="file" accept="application/json,.json" onChange={e=>readImport(e.target.files?.[0])}/></section><section className="surface"><h2>Account</h2><p className="muted">Signed in as {email}.</p><form className="settings-row" onSubmit={updatePassword}><label htmlFor="new-password">New password</label><input id="new-password" type="password" autoComplete="new-password" minLength={8} required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><button className="secondary"><KeyRound size={16}/>Update password</button></form></section><section className="surface"><h3>About video playback</h3><p className="muted">Video lessons use YouTube’s hosted player. If a creator disables embedding, the player reports an error and you can open the same lesson on YouTube. Browser privacy extensions or network restrictions can also affect playback.</p><a className="text-button" href="https://developers.google.com/youtube/iframe_api_reference#onError" target="_blank" rel="noopener">YouTube playback documentation <ExternalLink size={15}/></a></section></main>}
  <nav className="mobile-tabbar" aria-label="Main">{[[CalendarCheck,'Today','today'],[BookOpen,'Learn','home'],[MessageSquare,'Interview','interview'],[BriefcaseBusiness,'Career','career'],[Settings2,'More','settings']].map(([Icon,label,id])=>{const I=Icon as typeof BookOpen;const active=view===id||id==='home'&&view==='learn';return <button key={String(id)} className={active?'active':''} aria-current={active?'page':undefined} onClick={()=>go(String(id))}><I size={20}/><span>{String(label)}</span></button>;})}</nav></div><Sheet open={!!resource} onOpenChange={v=>!v&&setResource(null)}><SheetContent className="reading-room" side="right"><SheetHeader><SheetTitle>{resource?.[0]}</SheetTitle><SheetDescription>Official reference. Some publishers prevent embedded viewing; use the original link if this page is blank.</SheetDescription></SheetHeader>{resource&&<><a className="secondary doc-external" href={resource[1]} target="_blank" rel="noopener">Open original reference <ExternalLink size={15}/></a><iframe src={resource[1]} title={resource[0]} referrerPolicy="strict-origin-when-cross-origin" className="docs-frame"/></>}</SheetContent></Sheet><AlertDialog open={!!importData} onOpenChange={v=>!v&&setImportData(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Import your previous progress?</AlertDialogTitle><AlertDialogDescription>This will merge {Object.keys(importData||{}).length} fields. Matching exercise statuses, notes and career fields will be replaced by the imported values. Export your current progress first if you want a backup.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={()=>{if(importData){for(const[k,v]of Object.entries(importData))change(k,v);setNotice('Progress imported. Saving your changes…');setImportData(null);}}}>Import progress</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></SidebarProvider>;
}
