// Plain-English definitions for terms marked [[like this]] in lessons. Keys are lowercase.
export const glossary: Record<string, string> = {
  'endpoint': 'A specific URL an API offers for one job, e.g. /v1/contacts for contacts.',
  'query parameters': 'Extra options added to the end of a URL after a ?, like ?page=2&limit=100.',
  'json': 'JavaScript Object Notation: the text format almost every API uses for data, e.g. {"name": "Ana"}.',
  'status code': 'The three-digit number in every HTTP response that says what happened (200 OK, 404 Not Found…).',
  'timeout': 'The maximum time you’ll wait for a reply before giving up. A timeout means “unknown outcome”, not “failed”.',
  'pagination': 'Getting a big list one page at a time instead of all at once.',
  'checkpoint': 'A saved bookmark of how far a job got, so it can resume after a crash instead of starting over.',
  'oauth': 'A standard way for a user to let your app act inside their account without giving you their password.',
  'scopes': 'The specific permissions you ask for in OAuth, e.g. “read contacts” but not “delete contacts”.',
  'access token': 'A short-lived key (often about 1 hour) sent with each API call to prove you’re allowed in.',
  'refresh token': 'A long-lived token used only to get new access tokens without asking the user to log in again.',
  'pkce': 'Proof Key for Code Exchange (“pixie”). An extra secret that makes a stolen OAuth authorization code useless.',
  'webhook': 'An HTTP call a provider makes to your URL when something happens, instead of you repeatedly asking.',
  'signature': 'A fingerprint sent with a webhook that proves it came from the provider and wasn’t changed.',
  'hmac': 'Hash-based Message Authentication Code: a fingerprint of a message made with a shared secret.',
  'replay attack': 'Capturing a genuine request and sending it again later to trigger the same action.',
  'worker': 'A background process that picks up saved jobs and does the slow work outside the request.',
  'unique constraint': 'A database rule that refuses to store two rows with the same value, e.g. the same event ID.',
  'rate limit': 'The maximum number of requests an API allows in a time window, e.g. 100 per minute.',
  'dead-letter queue': 'A holding area for jobs that failed permanently, so a person can inspect and replay them.',
  'exponential backoff': 'Waiting longer after each failed attempt: 1s, 2s, 4s, 8s…',
  'jitter': 'Random variation added to retry delays so many clients don’t retry at the same instant.',
  'thundering herd': 'Many clients retrying at exactly the same moment and overwhelming a recovering server.',
  'concurrency': 'How many things run at the same time, e.g. 5 requests in flight at once.',
  'idempotent': 'Doing it twice has the same effect as doing it once.',
  'upsert': 'Update if it exists, insert if it doesn’t, in one atomic step.',
  'idempotency key': 'A unique ID you send with a request so the server can recognise a retry and not repeat the action.',
  'race condition': 'A bug where the result depends on which of two simultaneous operations finishes first.',
};
