export const handbook: Record<string, {title:string;body:string;example?:string}[]> = {
m0:[
{title:'Start with evidence, not a blank checklist',body:'Choose one automation you already run. Draw the trigger, data transformations, external calls and writes. For each boundary, say what can fail and how you would detect it. An existing project is useful evidence only if you can explain its decisions without asking an AI assistant.'},
{title:'Use the diagnostic to skip familiar work',body:'Attempt each exercise before studying. If you can demonstrate the result and explain the trade-off, mark it complete. If you can only recognise the terminology, leave it open. Spend your time on gaps that prevent you from independently building or debugging a system.'},
{title:'Create a repeatable working environment',body:'Keep service code, exported workflows, infrastructure, tests and documentation in one repository. Use a virtual environment for Python and environment variables for secrets. Commit an example environment file containing names and harmless placeholders, never working tokens.',example:'automation-portfolio/\n  services/     # Python APIs and workers\n  workflows/    # exported n8n JSON\n  infra/        # Compose and deployment config\n  tests/        # fixtures and failure cases\n  docs/         # decisions and runbooks'},
{title:'Make your evidence easy to review',body:'For each completed exercise, save a command, test result, screenshot or short explanation. Record the failure you induced and what happened. Your module notes should link to this evidence so you can use it during interviews.'}],
m1:[
{title:'An integration is a contract',body:'Read the authentication, pagination, rate-limit and error sections before building. Record the source identifier and destination identifier. Distinguish a rejected request from a request whose result is unknown because your connection timed out. Retrying an unknown write can duplicate a side effect.'},
{title:'Design for repeated events',body:'Use the provider event ID together with its account or tenant identifier as a unique key. Verify the webhook signature against the original request bytes, check any signed timestamp, persist the event, then acknowledge it. Do expensive processing in a worker. A database constraint protects against two workers accepting the same event.'},
{title:'Checkpoint and retry deliberately',body:'Advance a pagination checkpoint only after the corresponding records have been stored safely. Respect Retry-After when supplied. Use bounded exponential backoff with jitter for transient errors and a terminal failure state for exhausted attempts. Authentication errors need diagnosis or reauthorisation, not an endless retry loop.',example:'receive → verify → persist → acknowledge\nworker  → claim → process → record outcome\nretry   → same event key → no duplicate effect'},
{title:'OAuth is a lifecycle',body:'Understand scopes, authorisation-code exchange, PKCE, access-token expiry and refresh-token revocation. Store credentials on the server. Coordinate refreshes so concurrent jobs do not race to rotate the same token. When consent is revoked, stop affected jobs and surface a reconnect action.'}],
m2:[
{title:'Move from scripts to small components',body:'Separate API access, validation, transformation and persistence. Write functions whose inputs and outputs are easy to test. A pure transformation function should not also send an email or mutate a database. Keep integration configuration outside the source code.'},
{title:'Treat external input as untrusted',body:'Validate required fields before acting. Use explicit types at boundaries and report which record is invalid. Choose whether one bad row should stop a batch or go to a rejected-records file; do not silently discard it. Preserve enough context to replay the row later.'},
{title:'Handle exceptions at the right boundary',body:'Give network requests a timeout. Distinguish connection failures, authentication failures, invalid input and provider errors. Catch expected exceptions where you can recover; let unexpected failures reach a top-level handler that logs a useful error without exposing secrets.'},
{title:'Test behaviour, including failures',body:'Use fixtures and mocked HTTP responses to test duplicates, pagination and rate limits. Assert observable outcomes such as number of writes, final status and retry count. A test that repeats the implementation is weaker than a test that states the business invariant.',example:'def normalise_email(value: str) -> str:\n    result = value.strip().lower()\n    if "@" not in result:\n        raise ValueError("Invalid email")\n    return result\n\n# This is basic normalisation, not full email validation.'}],
m3:[
{title:'Put invariants in the database',body:'Start with entities and their identifiers. Use primary keys for identity, foreign keys for relationships and unique constraints for business rules. Checking for a row before inserting is not enough: two concurrent requests can both see it missing. A uniqueness constraint remains authoritative.'},
{title:'Use transactions for related writes',body:'A transaction makes a group of database operations commit or roll back together. It does not automatically include external HTTP calls. For external effects, record durable intent, dispatch it separately and reconcile the outcome. Understand which reads can race under your chosen isolation level.'},
{title:'Model an event before processing it',body:'Store the tenant, provider event ID, received time, status, attempts and a reference to its payload. Keep occurred_at separate from recorded_at. A stable event key supports deduplication and replay; a new random key on every retry defeats it.',example:'CREATE TABLE events (\n  tenant_id text NOT NULL,\n  event_id text NOT NULL,\n  payload jsonb NOT NULL,\n  status text NOT NULL DEFAULT \'pending\',\n  PRIMARY KEY (tenant_id, event_id)\n);'},
{title:'Let query patterns guide indexes',body:'Write the query first, then inspect its plan with EXPLAIN. Index columns used in frequent filtering and joins. Measure query latency and row counts rather than adding an index to every column. Practice LEFT JOIN, grouping, CTEs and window functions on your actual event data.'}],
m4:[
{title:'Let n8n coordinate the system',body:'Use n8n for triggers, routing and integration steps. Move complex validation, reusable business logic or heavily tested algorithms into a service when that makes ownership clearer. Keep node names descriptive and establish a consistent event envelope.'},
{title:'Design the failure branch first',body:'For every external call, define timeouts, retries, terminal failures and the person or process responsible for resolution. An error workflow is useful, but a workflow that never starts needs a separate expected-completion check. Include correlation IDs in logs and alerts.'},
{title:'Retries require safe effects',body:'A failed execution can have already created a CRM contact or sent a message. Store stable operation keys and provider results. On replay, query recorded outcomes or provider state before repeating the action. Do not use the absence of a successful n8n execution as proof that nothing happened.'},
{title:'Scale only after correctness',body:'Queue mode separates the main process from execution workers. Plan shared credentials, the database, Redis, concurrency and execution retention together. Worker count does not remove provider rate limits. Test graceful shutdown, a crashed worker and recovery with your actual workflow.'}],
m5:[
{title:'Make the API boundary explicit',body:'Define request and response schemas with Pydantic. Return errors that callers can act on and keep internal stack traces out of responses. Validate input before any expensive operation. Authentication establishes identity; authorisation decides what that identity may do.'},
{title:'Keep business logic independent of HTTP',body:'Route handlers should orchestrate validation and call application functions. Keep provider adapters and database access separate enough to substitute in tests. Avoid building a large abstraction framework before you have a second concrete use case.'},
{title:'Async does not make every operation non-blocking',body:'Use async-compatible clients for network I/O in async handlers. Blocking calls can stall the event loop. CPU-heavy work and long-running jobs belong outside the request path. Return a durable job ID when the caller needs to check progress later.'},
{title:'Document a usable contract',body:'Include sample requests, error responses, authentication setup and an end-to-end example. Test valid and invalid payloads, unauthorised requests and provider failures. A health check should help operators understand whether the service is alive and whether it can accept work.'}],
m6:[
{title:'Containers package the process; volumes hold state',body:'Pin dependencies, keep runtime images small and run with only the permissions needed. Know which paths persist across a container replacement. A database stored only inside an ephemeral container filesystem will disappear with that container.'},
{title:'Queues usually deliver at least once',body:'A worker can finish an external call and crash before acknowledging the job. The next worker may receive the same job. Use stable operation keys and durable result records. Where the provider cannot deduplicate, reconcile ambiguous outcomes rather than promising exactly-once delivery.'},
{title:'Make deployment reversible',body:'Run validation and tests in CI, separate environments and keep secrets out of logs. Treat schema migrations as part of the release. Know how the old application behaves with the new schema before choosing a rollback strategy. Practice restoring a real backup to an isolated environment.'},
{title:'Measure the outcome users care about',body:'Start with successful job rate, end-to-end latency, queue age and failed jobs awaiting attention. Logs explain individual events, metrics expose patterns and traces connect work across services. An alert should have an owner and a useful action, not just announce a stack trace.'}],
m7:[
{title:'Structured output is only the first check',body:'A schema can ensure a label is one of the allowed strings. It cannot establish that the label is correct. Validate shape deterministically, then evaluate meaning against labelled examples. Route ambiguous or high-impact decisions to a human using rules informed by measured performance.'},
{title:'Build an evaluation set before tuning',body:'Collect representative cases, edge cases and known failures. Keep a held-out set separate from examples used to improve the prompt. Record prompt version, model configuration, latency and cost for each run. Compare candidates on the same data.'},
{title:'Understand the cost of each error',body:'Precision asks how many predicted positives were correct; recall asks how many true positives were found. A false-positive outbound action may be much more costly than a missed classification. Choose thresholds and review policies from these costs, not a model-reported confidence score.'},
{title:'Control cost and failure',body:'Set token and request budgets, use bounded retries and record the reason for fallbacks. Do not retry a semantic mistake with the identical prompt indefinitely. Evaluate a cheaper model or a rules-first path before introducing a more complex agent.'}],
m8:[
{title:'Separate retrieval from generation',body:'First ask whether the relevant evidence entered the context. If it did not, changing the answer prompt cannot fix the retrieval failure. Track retrieval metrics separately from answer correctness, citation support and appropriate abstention.'},
{title:'Chunk for useful evidence',body:'Preserve section boundaries, source identifiers and permission metadata. Tiny chunks can lose context; large chunks can bury useful passages. Compare chunk sizes and overlap on a fixed query set. Re-index when your embedding configuration or chunking changes.'},
{title:'Compare search methods fairly',body:'Vector search captures semantic similarity; lexical search is useful for exact names and identifiers. Hybrid retrieval combines signals, and a reranker reorders a smaller candidate set. Compare vector-only, hybrid and reranked retrieval on the same labelled queries and include latency.'},
{title:'Access control belongs before the answer',body:'Filter documents according to the authenticated user and tenant. Do not rely on the language model to hide unauthorised text once it is in context. Track source versions and deletion so removed documents stop being retrieved. Test instructions hidden inside retrieved documents as untrusted data.'}],
m9:[
{title:'Use an agent only when decisions need it',body:'If the steps are predictable, a deterministic workflow is easier to debug and cheaper to run. An agent is appropriate when the next useful action depends on intermediate observations. Define the tools, allowed transitions and stop conditions before prompting.'},
{title:'State is a durable contract',body:'Represent state explicitly: request, observations, decisions, pending action and outcome. Checkpoint before risky boundaries. Resume from stored state after a crash without repeating completed effects. Keep conversation memory separate from authoritative business records.'},
{title:'Approve the actual operation',body:'A human approval should bind to the exact tool, parameters and target. If the proposed action changes, obtain approval again. Enforce permissions in server-side tool code, independently of what the model says. Bound step count, elapsed time, tokens and spend.'},
{title:'MCP standardises an interface, not trust',body:'An MCP server exposes tools and resources. Its existence does not make every tool appropriate for every user or task. Validate tool inputs and returned data, apply least privilege and log consequential actions. Test unavailable tools, malformed results and repeated calls.'}],
m10:[
{title:'Draw the trust boundaries',body:'Identify which input comes from users, providers, retrieved documents and models. Validate data at each boundary. Keep credentials on the server and minimise their scopes. Redact tokens and unnecessary personal data from logs and exported examples.'},
{title:'Prompt injection is a permissions problem too',body:'Treat instructions inside email, PDFs and tool results as untrusted content. A prompt alone cannot guarantee safety. Restrict tool capabilities, enforce tenant and user access outside the model, and require explicit approval for high-impact actions.'},
{title:'Make destructive actions hard to trigger accidentally',body:'Use allowlisted operations, validated targets, bounded result sizes and confirmation tied to specific parameters. Give tools only the data and privileges required. Prefer drafts and previews when a mistaken action would be expensive to reverse.'},
{title:'Test containment, not just refusals',body:'Create cases that try to cross tenant boundaries, expose credentials or induce unexpected tool calls. Verify server-side denial and audit records. A polite model response is not proof that the underlying operation was blocked.'}],
m11:[
{title:'Define the lead system’s invariants',body:'An event is accepted once into durable storage; a contact is not duplicated during replay; no outbound message is sent without the required approval. Write these rules before selecting nodes or libraries. Use synthetic leads for your public demonstration.'},
{title:'Separate intake from execution',body:'Verify and persist the webhook quickly. Enrich and classify in a worker, then apply deterministic rules before CRM sync. Record each state transition and provider reference. Keep failed jobs visible with a documented replay action.'},
{title:'Prove recovery under uncertainty',body:'Crash the worker after the CRM acknowledges a write but before your job is marked complete. Demonstrate how replay finds the existing contact. Simulate rate limits, revoked tokens and two workers claiming the same event.'},
{title:'Package the result for an interviewer',body:'Show a normal lead, a failed lead and a recovered lead in a short demo. Include a system diagram, data model, setup steps, tests and a runbook. Report measured timings and error behaviour instead of claims such as production-ready without evidence.'}],
m12:[
{title:'Choose a bounded support domain',body:'Use documents you are allowed to publish or synthetic policies. Define supported questions, permission groups and examples that should be refused. Keep a labelled evaluation set with the relevant source passages for each answerable question.'},
{title:'Build a baseline before adding components',body:'Start with vector retrieval and record results. Add lexical retrieval and then reranking as separate experiments. Keep the documents and query set constant. Measure retrieval quality, answer grounding, abstention, latency and cost.'},
{title:'Show the evidence behind the answer',body:'Return source references that can be traced to the actual retrieved passages. Verify that the cited passage supports the specific claim. Include a no-answer path when evidence is missing and ensure that permission filters apply before generation.'},
{title:'Make your evaluation reproducible',body:'Save dataset versions, settings and results so another developer can repeat the comparison. Explain a case where the more complex pipeline did not help. Include document deletion, updates and prompt-injection tests in the demonstration.'}],
m13:[
{title:'Choose a narrow operations task',body:'A copilot that prepares a specific operational change is easier to evaluate than a general assistant. Define the tools it may use and what success looks like. Use deterministic code for steps that do not require model judgement.'},
{title:'Persist at consequential boundaries',body:'Store the proposed action, approval state and provider outcome. Resume a stopped run from this durable state. Approval is bound to the proposed parameters; a changed target or payload invalidates that approval.'},
{title:'Build a failure matrix',body:'Test tool outage, invalid arguments, duplicate results, exhausted budgets and crashes before and after external effects. Record the expected end state for each case. Verify that the agent can stop safely and explain what remains unresolved.'},
{title:'Demonstrate control, not autonomy theatre',body:'Show one successful task, one rejected request and one crash recovery. Explain why an agent helps this particular workflow. Include tool-selection evals and evidence that permission checks remain effective even when the model asks for a forbidden action.'}],
m14:[
{title:'Structure every design answer',body:'Clarify users, traffic, freshness, acceptable loss and consequential actions. Sketch the data flow and source of truth. Then cover failure recovery, security, observability and cost. State assumptions rather than inventing requirements.'},
{title:'Debug with hypotheses',body:'Start from the symptom and trace a correlation ID across boundaries. Check the last known successful state. Propose a hypothesis, the evidence that would support it and the smallest safe test. Avoid changing many settings at once.'},
{title:'Practice under realistic constraints',body:'Use a timer, close the AI assistant and explain your reasoning aloud. Solve a small parsing or SQL task without building an unnecessary framework. Test an edge case and discuss what you would improve with more time.'},
{title:'Turn a weak answer into a training item',body:'After each mock, record the question, what your answer missed, the relevant module and a retest date. Rehearse the corrected answer after a delay. Memorised phrasing is less useful than being able to handle a changed scenario.'}],
m15:[
{title:'Make your experience legible',body:'Describe the business problem, your responsibility, the implementation and an outcome you can support. If you have no measured improvement, describe scale, reliability or scope honestly. Do not invent revenue or time-savings figures.'},
{title:'Apply while you build',body:'Target roles close to your existing n8n, Make and integration experience while strengthening Python and production skills. Keep a weekly application and outreach rhythm. Use interview feedback to decide which gaps deserve the next study session.'},
{title:'Make the portfolio easy to inspect',body:'A recruiter should find the problem and demo quickly; an engineer should find architecture, setup, tests and trade-offs. Link three focused case studies. Remove secrets and client data before publishing repositories or recordings.'},
{title:'Track the conversion funnel',body:'Record applications, responses, interviews and outcomes. Low response rates suggest a targeting or positioning problem; repeated technical failures suggest a skill or explanation gap. Review the pattern weekly and change one thing you can measure.'}]
};
